### PR TITLE
azurerm_kusto_cluster  - Add new `public_ip_address` property 

### PR DESCRIPTION
**Pull request by liuwuliuyun**
Update 'public_ip_address' property to resource kusto cluster.

### CODE REVIEW

**Comment by liuwuliuyun** [comment]
Testing evidence will be provided shortly.

**Comment by liuwuliuyun** [comment]
Test on TestAccKustoCluster_update locally, result is as follows: 

GOROOT=D:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"D:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoCluster_update_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"D:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoCluster_update_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoCluster_update\E$ #gosetup
=== RUN   TestAccKustoCluster_update
=== PAUSE TestAccKustoCluster_update
=== CONT  TestAccKustoCluster_update
--- PASS: TestAccKustoCluster_update (4279.44s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
TestAccKustoCluster_complete results:

========================== Starting Command Output ===========================
##[debug]which '/usr/bin/bash'
##[debug]found: '/usr/bin/bash'
##[debug]/usr/bin/bash arg: /home/vsts/work/_temp/264e6dcd-23f8-49dc-8942-6b719799d2f0.sh
##[debug]exec tool: /usr/bin/bash
##[debug]arguments:
##[debug]   /home/vsts/work/_temp/264e6dcd-23f8-49dc-8942-6b719799d2f0.sh
/usr/bin/bash /home/vsts/work/_temp/264e6dcd-23f8-49dc-8942-6b719799d2f0.sh
=== RUN   TestAccKustoCluster_complete
=== PAUSE TestAccKustoCluster_complete
=== CONT  TestAccKustoCluster_complete
--- PASS: TestAccKustoCluster_complete (1182.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto	1182.237s
##[debug]Exit code 0 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;done=true;]
Finishing: Run test in parallel

**Review by katbyte — APPROVED** [review]
LGTM 🎩

**Pull request merged**
