### PR TITLE
`azurerm_application_gateway` - fix error when `firewall_policy_id` is removed

### PR DESCRIPTION
**Pull request by teowa**
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/23656
 my local test with config provided in the issue can work:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_application_gateway.network3 will be updated in-place
  ~ resource "azurerm_application_gateway" "network3" {
      - firewall_policy_id                = "/subscriptions/x/resourceGroups/wt-example-resources/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/examplewafpolicy" -> null
      - force_firewall_policy_association = true -> null
        id                                = "/subscriptions/x/resourceGroups/wt-example-resources/providers/Microsoft.Network/applicationGateways/example-appgateway"
        name                              = "example-appgateway"
        tags                              = {}
        # (6 unchanged attributes hidden)

      ~ sku {
          ~ name     = "WAF_v2" -> "Standard_v2"
          ~ tier     = "WAF_v2" -> "Standard_v2"
            # (1 unchanged attribute hidden)
        }

        # (8 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_application_gateway.network3: Modifying... [id=/subscriptions/x/resourceGroups/wt-example-resources/providers/Microsoft.Network/applicationGateways/example-appgateway]
azurerm_application_gateway.network3: Still modifying... [id=/subscriptions/x-...applicationGateways/example-appgateway, 10s elapsed]
azurerm_application_gateway.network3: Modifications complete after 12s [id=/subscriptions/x/resourceGroups/wt-example-resources/providers/Microsoft.Network/applicationGateways/example-appgateway]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
@teowa, can you please add an acceptance test for this case?

**Comment by teowa** [comment]
```
TF_ACC=1 go test -v ./internal/services/network -parallel 20 -run TestAccApplicationGateway_removeF -timeout 2h -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApplicationGateway_removeFirewallPolicy
=== PAUSE TestAccApplicationGateway_removeFirewallPolicy
=== CONT  TestAccApplicationGateway_removeFirewallPolicy
--- PASS: TestAccApplicationGateway_removeFirewallPolicy (1032.41s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       1032.418s
```

**Review by stephybun — COMMENTED** [review]
@teowa linting is failing

**Review by stephybun — APPROVED** [review]
Thanks @teowa LGTM 👍

**Pull request merged**
