### PR TITLE
new resource "azurerm_synapse_sql_pool_workload_group"

### PR DESCRIPTION
**Pull request by ms-henglu**
image

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]

**Comment by ms-henglu** [comment]
Thanks @katbyte for code review. I've added a commit according to your suggestion, please take another look, thanks!

**Review by katbyte — CHANGES_REQUESTED** [review]
Have some test failures now:
```
------- Stdout: -------
=== RUN   TestAccSynapseWorkloadGroup_update
=== PAUSE TestAccSynapseWorkloadGroup_update
=== CONT  TestAccSynapseWorkloadGroup_update
    testcase.go:110: Step 1/6 error: Error running pre-apply refresh: exit status 1
        
        Error: expected type of min_resource_percent_per_request to be integer
        
          with azurerm_synapse_sql_pool_workload_group.test,
          on terraform_plugin_test.tf line 48, in resource "azurerm_synapse_sql_pool_workload_group" "test":
          48:   min_resource_percent_per_request = 3
        
--- FAIL: TestAccSynapseWorkloadGroup_update (3.99s)
FAIL
```

**Comment by ms-henglu** [comment]
Hi @katbyte , I've updated. Please take another look. Thanks!

**Review by katbyte — APPROVED** [review]
Thanks @ms-henglu - LGTM now 🏗️

**Pull request merged**
