### PR TITLE
`azurerm_hdinsight_rserver_cluster` - add test for storage_account.storage_resource_id

### PR DESCRIPTION
**Pull request by heiazuo**
### create public version pull request for - `azurerm_hdinsight_rserver_cluster` add test for storage_account.storage_resource_id
**tesst result:**
image

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
have some test failures:
```
------- Stdout: -------
=== RUN   TestAccHDInsightRServerCluster_basic
=== PAUSE TestAccHDInsightRServerCluster_basic
=== CONT  TestAccHDInsightRServerCluster_basic
    testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement
        
        Terraform will perform the following actions:
        
          # azurerm_hdinsight_rserver_cluster.test must be replaced
        -/+ resource "azurerm_hdinsight_rserver_cluster" "test" {
              ~ cluster_version     = "3.6.1000.0" -> "3.6"
              ~ edge_ssh_endpoint   = "acctesthdi-220222235918509325-ed-ssh.azurehdinsight.net" -> (known after apply)
              ~ https_endpoint      = "acctesthdi-220222235918509325.azurehdinsight.net" -> (known after apply)
              ~ id                  = "/subscriptions/*******/resourceGroups/acctestRG-220222235918509325/providers/Microsoft.HDInsight/clusters/acctesthdi-220222235918509325" -> (known after apply)
                name                = "acctesthdi-220222235918509325"
              ~ ssh_endpoint        = "acctesthdi-220222235918509325-ssh.azurehdinsight.net" -> (known after apply)
              ~ tier                = "standard" -> "Standard" # forces replacement
              - tls_min_version     = "" -> null
                # (3 unchanged attributes hidden)
        
              ~ gateway {
                  ~ password = (sensitive value)
                    # (2 unchanged attributes hidden)
                }
        
              ~ roles {
                  ~ edge_node {
                        # (3 unchanged attributes hidden)
                    }
        
                  ~ head_node {
                        # (3 unchanged attributes hidden)
                    }
        
                  ~ worker_node {
                      ~ min_instance_count    = 0 -> (known after apply)
                        # (4 unchanged attributes hidden)
                    }
        
                  ~ zookeeper_node {
                        # (3 unchanged attributes hidden)
                    }
                }
        
              ~ storage_account {
                  - storage_resource_id  = "" -> null
                    # (3 unchanged attributes hidden)
                }
            }
        
        Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccHDInsightRServerCluster_basic (1678.60s)
FAIL
```

**Comment by heiazuo** [comment]
> have some test failures:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccHDInsightRServerCluster_basic
> === PAUSE TestAccHDInsightRServerCluster_basic
> === CONT  TestAccHDInsightRServerCluster_basic
>     testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
>         stdout:
>         
>         
>         Terraform used the selected providers to generate the following execution
>         plan. Resource actions are indicated with the following symbols:
>         -/+ destroy and then create replacement
>         
>         Terraform will perform the following actions:
>         
>           # azurerm_hdinsight_rserver_cluster.test must be replaced
>         -/+ resource "azurerm_hdinsight_rserver_cluster" "test" {
>               ~ cluster_version     = "3.6.1000.0" -> "3.6"
>               ~ edge_ssh_endpoint   = "acctesthdi-220222235918509325-ed-ssh.azurehdinsight.net" -> (known after apply)
>               ~ https_endpoint      = "acctesthdi-220222235918509325.azurehdinsight.net" -> (known after apply)
>               ~ id                  = "/subscriptions/*******/resourceGroups/acctestRG-220222235918509325/providers/Microsoft.HDInsight/clusters/acctesthdi-220222235918509325" -> (known after apply)
>                 name                = "acctesthdi-220222235918509325"
>               ~ ssh_endpoint        = "acctesthdi-220222235918509325-ssh.azurehdinsight.net" -> (known after apply)
>               ~ tier                = "standard" -> "Standard" # forces replacement
>               - tls_min_version     = "" -> null
>                 # (3 unchanged attributes hidden)
>         
>               ~ gateway {
>                   ~ password = (sensitive value)
>                     # (2 unchanged attributes hidden)
>                 }
>         
>               ~ roles {
>                   ~ edge_node {
>                         # (3 unchanged attributes hidden)
>                     }
>         
>                   ~ head_node {
>                         # (3 unchanged attributes hidden)
>                     }
>         
>                   ~ worker_node {
>                       ~ min_instance_count    = 0 -> (known after apply)
>                         # (4 unchanged attributes hidden)
>                     }
>         
>                   ~ zookeeper_node {
>                         # (3 unchanged attributes hidden)
>                     }
>                 }
>         
>               ~ storage_account {
>                   - storage_resource_id  = "" -> null
>                     # (3 unchanged attributes hidden)
>                 }
>             }
>         
>         Plan: 1 to add, 0 to change, 1 to destroy.
> --- FAIL: TestAccHDInsightRServerCluster_basic (1678.60s)
> FAIL
> ```

Thanks, I've reworked the code.

**Comment by stephybun** [comment]
@heiazuo could you resolve the merge conflict?

**Comment by heiazuo** [comment]
> 

@stephybun I resolved the conflict

**Pull request merged**
