### PR TITLE
`azurerm_cosmosdb_account`: Adding EnableMongoRetryableWrites EnableMongoRoleBasedAccessControl and EnableUniqueCompoundNestedDocs capabilities

### PR DESCRIPTION
**Pull request by CorrenSoft**
May solve #19192 

Started working on the mentioned issue, and decided to add the other 2 missing capabilities in the process. However, the 'desired' is failing (from Azure side), and that is why the PR is still in draft. If you think that is more appropriate to split the PR to add what is currently available, just let me know.

```
TF_ACC=1 go test -v ./internal/services/cosmos -run=TestAccCosmosDBAccount_mongoVersion40 -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccCosmosDBAccount_mongoVersion40
=== PAUSE TestAccCosmosDBAccount_mongoVersion40
=== CONT  TestAccCosmosDBAccount_mongoVersion40
--- PASS: TestAccCosmosDBAccount_mongoVersion40 (1059.63s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos        1059.855s
```

### CODE REVIEW

**Comment by catriona-m** [comment]
Hi @CorrenSoft, thanks for submitting this! If there are failures arising from an Azure bug it may be best to remove that part of the PR if possible and raise an issue here: https://github.com/Azure/azure-rest-api-specs . Then we can look at merging the rest. Thanks!

**Comment by katbyte** [comment]
@CorrenSoft - this PR looks fine and ready to merge given its just adding some capabilities? I'm not sure what you mean by "desired" is failing. is there any reason this is still in draft?

**Comment by CorrenSoft** [comment]
Hi, @catriona-m and @katbyte. 

You can find more details in the linked issue, but in short, this PR is adding a capability that wasn't available yet to the public (but included in the docs). It seems to be working now, so I will check (as soon as I can) for the conflicts, re-run the test and publish the PR to merge it.

**Comment by CorrenSoft** [comment]
I 've resolved the merge conflicts and re-executed the test.
We should be good to go now.

```
TF_ACC=1 go test -v ./internal/services/cosmos -run=TestAccCosmosDBAccount_mongoVersion40 -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccCosmosDBAccount_mongoVersion40
=== PAUSE TestAccCosmosDBAccount_mongoVersion40
=== CONT  TestAccCosmosDBAccount_mongoVersion40
--- PASS: TestAccCosmosDBAccount_mongoVersion40 (1248.90s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/cosmos        1249.095s
```

**Review by katbyte — APPROVED** [review]
Thanks @CorrenSoft! LGTM 💾

**Pull request merged**
