### PR TITLE
Upgrade Postgresql Flexible Server Firewall Rule API version from 2021-06-01 to 2022-12-01

### PR DESCRIPTION
**Pull request by neil-yechenwei**
image

### CODE REVIEW

**Comment by catriona-m** [comment]
Looks like this has some conflicts but once these are resolved this should be good to merge /wr

**Comment by neil-yechenwei** [comment]
@catriona-m , thanks for the comment. I've resolved conflict. Please take another look. Thanks.

**Comment by catriona-m** [comment]
Thanks @neil-yechenwei, merging the last postgres api update has caused more conflicts unfortunately, but we should be able to merge this once those are resolved again. /wr

**Comment by neil-yechenwei** [comment]
@catriona-m , thanks for the update. I've resolved the conflict. Please take another look. Thanks.

**Review by catriona-m — APPROVED** [review]
Thanks @neil-yechenwei LGTM!

**Pull request merged**
