### PR TITLE
`azurerm_sentinel_alert_rule_scheduled - support for `group_by_{alert|custom}_details`, `alert_details_override`, `entity_mapping`, `custom_details`

### LINKED ISSUE #11667: SecurityInsights - Sentinel Scheduled Rules: support for entityMappings
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm putting an issue here as a Todo and currently as blocked. See https://github.com/Azure/azure-rest-api-specs/issues/14078 as this has not yet been implemeneted within swagger. 
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview

Recently a new preview feature has come into the creation of Azure Sentinel Scheduled rules, whereby entities are now being defined in the alert Properties rather than in the query, whereby the traditional style was to include something in the query such as | extend AccountCustomEntity = AccountName is is now defined as:

```
entityMappings: [ {entityType: "Type", fieldMappings: [ {identifer: "Identifer", columnName: "columnName"} ] } 
]
```
in properties

The 2021-03-01-preview seems to currently be in heavy dev and does not have a single SecurityInsights.json full spec yet.

We may need a dedicated issue for the eventual 2021-03-01-preview migration if this is not backported. to 2019-01-01-preview, which is what current sentinel implementation is using. 
### New or Affected Resource(s)

- azurerm_sentinel_alert_rule_scheduled
- azurerm_sentinel_alert_rule_template_data_source (needs upgrade as a result for new property)

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  name                       = "example"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
  display_name               = "example"
  severity                   = "High"
  query                      = <<QUERY
AzureActivity |
  where OperationName == "Create or Update Virtual Machine" or OperationName =="Create Deployment" |
  where ActivityStatus == "Succeeded" |
  make-series dcount(ResourceId) default=0 on EventSubmissionTimestamp in range(ago(7d), now(), 1d) by Caller
QUERY

  entity_mapping {
    entity_type = "AzureResource" //Create a mapping for a resource id
    field_mappings {
      identifier="ResourceId" //Static options
      column_name="ResourceId" //This is the field from within the query
    }
  }

  entity_mapping {
    entity_type = "Account" //Create a mapping for an Account
    field_mappings {
      identifier="UPNSuffix" //Static options
      column_name="Caller" //This is the field from within the query
    }
    field_mappings {
      identifier="SID" //Static options
      column_name="userSID" //This is the field from within the query (Not applicable in AzureActivity but just an example)
    }
  }

}
```

### References
https://github.com/Azure/azure-rest-api-specs/issues/14078
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview

### LINKED ISSUE #14244: Support for alert_rule_template_version in the azurerm_sentinel_alert_rule_scheduled resource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is a missing field which can help indicate updates to template-based rules. Adding an `alert_rule_template_version` field would solve that. This relates to the existing `alert_rule_template_guid` field.

### New or Affected Resource(s)

* azurerm_sentinel_alert_rule_scheduled

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  name                       = "example"
  log_analytics_workspace_id = azurerm_log_analytics_solution.example.workspace_resource_id
  display_name               = "example"
  severity                   = "High"
  alert_rule_template_guid = aaaa-bbbb-cccc-dddd
  alert_rule_template_version = 1.0.0
  query                      = <<QUERY
AzureActivity |
  take 10
QUERY
}
```

### References

* #9712

### PR DESCRIPTION
**Pull request by magodo**
This PR adds a couple of new features for the sentinel scheduled alert rule, to make it 100% property covered.

Fixes #11667, fixes #14244

## Test

```shell
terraform-provider-azurerm on  main via 🐹 v1.18 took 6m17s
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/sentinel  -run='TestAccSentinelAlertRuleScheduled_'
=== RUN   TestAccSentinelAlertRuleScheduled_basic
=== PAUSE TestAccSentinelAlertRuleScheduled_basic
=== RUN   TestAccSentinelAlertRuleScheduled_complete
=== PAUSE TestAccSentinelAlertRuleScheduled_complete
=== RUN   TestAccSentinelAlertRuleScheduled_update
=== PAUSE TestAccSentinelAlertRuleScheduled_update
=== RUN   TestAccSentinelAlertRuleScheduled_requiresImport
=== PAUSE TestAccSentinelAlertRuleScheduled_requiresImport
=== RUN   TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid
=== PAUSE TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid
=== RUN   TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting
=== PAUSE TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting
=== CONT  TestAccSentinelAlertRuleScheduled_basic
=== CONT  TestAccSentinelAlertRuleScheduled_requiresImport
=== CONT  TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting
=== CONT  TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid
=== CONT  TestAccSentinelAlertRuleScheduled_update
=== CONT  TestAccSentinelAlertRuleScheduled_complete
--- PASS: TestAccSentinelAlertRuleScheduled_withAlertRuleTemplateGuid (169.39s)
--- PASS: TestAccSentinelAlertRuleScheduled_complete (172.72s)
--- PASS: TestAccSentinelAlertRuleScheduled_basic (176.35s)
--- PASS: TestAccSentinelAlertRuleScheduled_updateEventGroupingSetting (242.41s)
--- PASS: TestAccSentinelAlertRuleScheduled_update (278.09s)
--- PASS: TestAccSentinelAlertRuleScheduled_requiresImport (1456.46s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/sentinel      1456.478s
```

### CODE REVIEW

**Comment by magodo** [comment]
There are also some 3.0 TODO(s) for this resource, I'm wondering whether we can resolve them in this PR as well.

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
A few minor comments but this otherwise LGTM 👍

**Comment by magodo** [comment]
Thanks @tombuildsstuff! Besides these, do you mind I also:

1. Rename the `group_by` to `group_by_identities` to make it more clear
2. Fix the `TODO-3.0`(s) in this file, which mostly about mapping some enums which were changed in a previous API version

**Comment by tombuildsstuff** [comment]
@magodo I hope you don't mind but I've pushed a commit for 2 since I'm working through the rest of the codebase in a separate branch and wanted to ensure this PR contains it 👍 

For 1 it seems reasonable - I'll leave that for you 👍

**Comment by tombuildsstuff** [comment]
We'll also need to add these to the 3.0 upgrade guide fwiw - presumably something along the lines of

> `azurerm_sentinel_alert_rule_scheduled` - the field `entity_matching_method` can no longer be set to the legacy values `All`, `Custom` or `None` - use `AnyAlert`, `Selected` and `AllEntities` instead

**Comment by magodo** [comment]
Thanks @tombuildsstuff! I've made the change for 1 and update the upgrade document for this resource, please take another look!

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Pull request merged**
