### PR TITLE
New attribute `virtual_network_address_space` (azurerm_virtual_network_peering)

### PR DESCRIPTION
**Pull request by tiwood**
Its possible to re-sync local vnet address spaces to the peered virtual network without recreation. The required parameter is already set in the current implementation, we just need a way to force the in-place update:

```golang
future, err := vnetPeeringsClient.CreateOrUpdate(ctx, resGroup, vnetName, name, peer, network.SyncRemoteAddressSpaceTrue)
```

This PR adds a new attribute `virtual_network_address_space` that can be updated to force the resynchronization of the address_space by changing the list values.

It recommended to just use the address_space attribute of the local virtual network like so:

```hcl
resource "azurerm_virtual_network" "example-1" {
  name                = "peternetwork1"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.1.0/24"]
  location            = "West US"
}

resource "azurerm_virtual_network" "example-2" {
  name                = "peternetwork2"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.2.0/24"]
  location            = "West US"
}

resource "azurerm_virtual_network_peering" "example-1" {
  name                      = "peer1to2"
  resource_group_name       = azurerm_resource_group.example.name
  virtual_network_name      = azurerm_virtual_network.example-1.name
  virtual_network_address_space = azurerm_virtual_network.example-1.address_space
  remote_virtual_network_id = azurerm_virtual_network.example-2.id
}

resource "azurerm_virtual_network_peering" "example-2" {
  name                      = "peer2to1"
  resource_group_name       = azurerm_resource_group.example.name
  virtual_network_name      = azurerm_virtual_network.example-2.name
  virtual_network_address_space = azurerm_virtual_network.example-2.address_space
  remote_virtual_network_id = azurerm_virtual_network.example-1.id
}
```

The use-case and process is described here:
https://azure.microsoft.com/en-us/blog/how-to-resize-azure-virtual-networks-that-are-peered-now-in-preview/?cdn=disable

### CODE REVIEW

**Review by aristosvo — CHANGES_REQUESTED** [review]
Hi @tiwood! Thanks a lot for this PR.

With regard to the added code, it looks good and should do what is intended here. Would it be possible to add an Acceptance Test to validate the intended behaviour?

Thanks!

**Comment by tiwood** [comment]
I've added the new attribute to the existing tests.

image

**Comment by aristosvo** [comment]
Hi @tiwood!

After giving your AccTests a first look I've been thinking on this PR during the weekend a bit, being hesitant adding attributes which trigger functionality which is not direct and clear related to the attribute themselves. It might happen that people mix up what address space to fill in for `virtual_network_address_space`, the remote address space or that of the original VNet. To be honest, I'm not even sure if it's done right in your example above (it's still morning and haven't had no coffee yet ☕ 🤷🏽‍♂️ ).

One approach I was thinking of myself was to expose a `peering_sync_level` attribute which is both `Computed` and `Optional` based on`VirtualNetworkPeeringPropertiesFormat.PeeringSyncLevel`, which exposes the real sync level. When setting this attribute actively to `VirtualNetworkPeeringLevelFullyInSync`, any difference between the synchronisation level and wanted level will trigger a resync.

What do you think?

**Comment by tiwood** [comment]
> Hi @tiwood!
> 
> After giving your AccTests a first look I've been thinking on this PR during the weekend a bit, being hesitant adding attributes which trigger functionality which is not direct and clear related to the attribute themselves. It might happen that people mix up what address space to fill in for `virtual_network_address_space`, the remote address space or that of the original VNet. To be honest, I'm not even sure if it's done right in your example above (it's still morning and haven't had no coffee yet ☕ 🤷🏽‍♂️ ).
> 
> One approach I was thinking of myself was to expose a `peering_sync_level` attribute which is both `Computed` and `Optional` based on`VirtualNetworkPeeringPropertiesFormat.PeeringSyncLevel`, which exposes the real sync level. When setting this attribute actively to `VirtualNetworkPeeringLevelFullyInSync`, any difference between the synchronisation level and wanted level will trigger a resync.
> 
> What do you think?

The problem I see here is that the `PeeringSyncLevel` needs time to update, so if you change the `address_space` of the virtual network, the attribute will still be `FullySynchronized` during the plan and no change will be detected.

We can make the attribute more like an dummy attribute, this is implemented in other resources as well. Something like `trigger`, `changes_force_update`.

**Review by aristosvo — APPROVED** [review]
It makes sense, didn't think it through that well apparently! 😄

With this considerations in mind it seems to me the current solution is as good as it gets, the naming is in line with the solution from my point of view.

**Comment by tiwood** [comment]
@aristosvo, any chance this can be merged soon?
It seems it's possible to in-place update vnet address spaces now (while vnet peered) and this PR would allow us to also update the peering without manual steps.

**Comment by tombuildsstuff** [comment]
hey @tiwood 

Apologies for the delay with this one, we've been trying to work out a path forwards for it.

Chatting about this internally we believe we may need to take a different approach here - by leaving the `network.SyncRemoteAddress` argument as-is in the existing resource (as you have) and introducing a new virtual resource for managing the sync state (something along the lines of `azurerm_virtual_network_peering_sync`). This'd allow Terraform to both detect that these are out of sync and require being resynced - and allow users to force a resync (by tainting the resource).

Whilst we could look to add a fake property to this resource to trigger an update, it feels like the Peering itself and the Peering Sync Status are likely to have different lifecycles, and so are worth splitting out - WDYT?

Thanks!

**Comment by tiwood** [comment]
Hey @tombuildsstuff,

I can follow your thoughts, but I still see the same issue that I've explained above, but maybe I'm missing something crucial here.

Let's assume we use a virtual resource for a second.

```terraform
resource "azurerm_virtual_network" "example-1" {
  name                = "peternetwork1"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.1.0/24"]
  location            = "West US"
}

resource "azurerm_virtual_network" "example-2" {
  name                = "peternetwork2"
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.2.0/24"]
  location            = "West US"
}

resource "azurerm_virtual_network_peering" "example-1" {
  name                      = "peer1to2"
  resource_group_name       = azurerm_resource_group.example.name
  virtual_network_name      = azurerm_virtual_network.example-1.name
  remote_virtual_network_id = azurerm_virtual_network.example-2.id
}

resource "azurerm_virtual_network_peering" "example-2" {
  name                      = "peer2to1"
  resource_group_name       = azurerm_resource_group.example.name
  virtual_network_name      = azurerm_virtual_network.example-2.name
  remote_virtual_network_id = azurerm_virtual_network.example-1.id
}

resource "azurerm_virtual_network_peering_sync" "example-1" {
  virtual_network_peering_id = azurerm_virtual_network_peering.example-1.id
}

resource "azurerm_virtual_network_peering_sync" "example-2" {
  virtual_network_peering_id = azurerm_virtual_network_peering.example-2.id
}
```

How would we accomplish a re-sync without actually tainting the resource? Or do you suggest to still add a `trigger` property?

```terraform
resource "azurerm_virtual_network_peering_sync" "example-1" {
  virtual_network_peering_id = azurerm_virtual_network_peering.example-1.id
  trigger_sync_when_changed = {
    always = timestamp()
  }
}

resource "azurerm_virtual_network_peering_sync" "example-2" {
  virtual_network_peering_id = azurerm_virtual_network_peering.example-2.id
  trigger_sync_when_changed = {
    only_on_changes = azurerm_virtual_network.example-2.address_space
  }
}
```

But in this case I'm still  not sure if it would be better to just add this trigger to the actual peering resource, for visibility and maintainability.

**Comment by tombuildsstuff** [comment]
> How would we accomplish a re-sync without actually tainting the resource? Or do you suggest to still add a trigger property?

Since the `sync` resource would only manage the sync status, if we can detect that the peering is out of sync (which I'm assuming is determinable via the API) then we can mark the sync resource as requiring recreation - which (when re-created would force a sync. It's a bit of a weird scenario, but that means we don't need the trigger property at all, presuming that we can programatically determine the peering requires a resync.

**Comment by tiwood** [comment]
Yes, there is a [property](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/virtual-network-peerings/get#virtualnetworkpeeringlevel), but still, that would mean we need to run twice right? Because the sync status will only be in something else then `FullyInSync` AFTER the `address_spaces` where updated on one of the peers, which normally is done in the same Terraform configuration I assume (at least that's what we do)

**Comment by tombuildsstuff** [comment]
@tiwood ok that makes sense, apologies. I still think this is misplaced however, perhaps this should be forced as a part of the update of the Virtual Network, when the address space is resized and there's known pairing(s) present? In which case we'd do a GET and then Update of the peering setting the resync param, which would again remove the need for this Trigger here (since this is really related to with the Virtual Network address space being resized?

**Comment by tiwood** [comment]
I think we can do the following:

In `azurerm_virtual_network` we check for existing peerings, if any we force the sync on `adress_space` changes.

in `azurerm_virtual_network_peering` we can add a computed `peering_level` property. If the value is not `FullyInSync` we force and in-place upgrade.

Some thoughts
* Are in-place updates caused by computed values valid?

**Comment by tiwood** [comment]
It seems Microsoft is triggering a synchronisation automatically now if the `address_space` is updated.
I need to investigate this further, but this would make this obsolete.

**Comment by katbyte** [comment]
As its been some months now I'm going to assume this has been obsolete! thanks @tiwood  🙂

**Pull request closed without merging**
