### PR TITLE
New Data Source: `azurerm_private_dns_resolver_virtual_network_link`

### PR DESCRIPTION
**Pull request by pchanvallon**
``` txt
=== RUN   TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic
=== PAUSE TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic
=== CONT  TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic
--- PASS: TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic (475.71s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/privatednsresolver    476.885s

=== RUN   TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_complete
=== PAUSE TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_complete
=== CONT  TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_complete
--- PASS: TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_complete (502.64s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/privatednsresolver    503.902s
```

### CODE REVIEW

**Comment by pchanvallon** [comment]
Following PR #19947 review, I have implemented the same suggestions. 

Here is the updated test result :

``` txt
=== RUN   TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic
=== PAUSE TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic
=== CONT  TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic
--- PASS: TestAccPrivateDNSResolverVirtualNetworkLinkDataSource_basic (509.60s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/privatednsresolver    510.756s
```

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Oh you know the drill by now ;)

**Comment by pchanvallon** [comment]
Thanks again for you review, I've updated the documentation and tests following your comments.

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Pull request merged**
