### PR TITLE
Application gateway attribues are now sorted to avoid recreation.

### LINKED ISSUE #16136: Application Gateway request_routing_rule order change even with Azurerm 3.0.2
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
  dynamic request_routing_rule {
    for_each = var.application_gateway_request_routing_rule

    content  {
    http_listener_name = request_routing_rule.value["http_listener_name"]
    name = request_routing_rule.value["name"]
    redirect_configuration_name = request_routing_rule.value["redirect_configuration_name"]
    rule_type  = request_routing_rule.value["rule_type"]
    backend_address_pool_name = request_routing_rule.value["backend_address_pool_name"]
    backend_http_settings_name = request_routing_rule.value["backend_http_settings_name"]
    url_path_map_name = request_routing_rule.value["url_path_map_name"]
    }
  }

    {
      http_listener_name          = "HTTP-DEV-XXX-LISTENER"
      name                        = "XXX-DEV-HTTPS-REDIRECT-RULE"
      redirect_configuration_name = "XXXTP-DEV-HTTPS-REDIRECT"
      rule_type                   = "Basic"
      backend_address_pool_name   = null
      backend_http_settings_name  = null
      url_path_map_name           = null
    },
```

### Debug Output

      - request_routing_rule {
          - http_listener_id            = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/httpListeners/HTTP-DEV-XXX-LISTENER" -> null
          - http_listener_name          = "HTTP-DEV-XXX-LISTENER" -> null
          - id                          = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/requestRoutingRules/XXX-DEV-HTTPS-REDIRECT-RULE" -> null   
          - name                        = "XXX-DEV-HTTPS-REDIRECT-RULE" -> null
          - priority                    = 0 -> null
          - redirect_configuration_id   = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/redirectConfigurations/XXX-DEV-HTTPS-REDIRECT" -> null     
          - redirect_configuration_name = "XXX-DEV-HTTPS-REDIRECT" -> null
          - rule_type                   = "Basic" -> null
        }

      + request_routing_rule {
          + http_listener_id            = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/httpListeners/HTTP-DEV-XXX-LISTENER"
          + http_listener_name          = "HTTP-DEV-XXX-LISTENER"
          + id                          = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/requestRoutingRules/XXX-DEV-HTTPS-REDIRECT-RULE"
          + name                        = "XXX-DEV-HTTPS-REDIRECT-RULE"
          + redirect_configuration_id   = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/applicationGateways/xxx/redirectConfigurations/XXX-DEV-HTTPS-REDIRECT"
          + redirect_configuration_name = "XXX-DEV-HTTPS-REDIRECT"
          + rule_type                   = "Basic"
        }
### Expected Behaviour

No change detected, I also tried to run terraform apply, and it does somehow "modify" the application gateway, but if I run terraform plan again I still have the same issue.

### Actual Behaviour

Terraform tries to change the order of request_routing_rules only (and all of them, I only provided you one sample output since we have many of them on this app gateway). It keeps happening even after a terraform apply.

### Steps to Reproduce

1. Configure request_routing_rule using dynamic blocks as per the above code example in an application gateway
2. `terraform plan` - you will see the attempted change
3. `terraform apply` - terraform will apply the change even though there is no difference
4. `terraform plan` - terraform still tries to do the same changes

### Important Factoids

Some time ago when this issue was not known yet, I remember that I tried to create a new application gateway from scratch and the issue was not there, but after some months between various changes, the issue appeared again randomly and never went away. I don't know what is causing the issue but we have it on 3 different application gateways and can't get rid of it.

### References

* #6896 - marked as fixed but I still see this issue with the latest version of azurerm

### PR DESCRIPTION
**Pull request by michal-malec**
**The problem**
In Application Gateway order of listeners, routing rules, ssl settings, etc. changes between applies. This causes part of the configuration to be recreated.

**Current behaviour**
Current implementation in Terraform sorts configurations based on hash that is generated from most of the properties. It means that in most of the cases after adding new configuration block it is very likely that it will be added in the middle of the list and will cause removal and addition of settings.

**Proposed solution**
There is no ideal solution for this issue as in Azure API all AppGw configurations are kept in lists which don't have any argument that could be easily used to sort them (e.g. id). I propose to sort the lists by name (or priority in one case). This results in keeping old configuration while adding new settings if you name resources in alphabetical order.

The PR resolves #16136, #18422 (but only if names are set in alphabetical order)

### CODE REVIEW

**Review by mbfrahry — COMMENTED** [review]
Hi @michal-malec, I appreciate the effort put into this but as you mentioned, this will break people who don't have their configuration in alphabetical order. I know application gateways are already broken and needs fixing but that fix should be one that requires any work on the users part.

I'm not sure what the best solution is but I don't think it involves List or Sets. There is a new terraform framework that has some additional tools like a Map that we could use. It'll require some investigation on our part when we do move to it and I'm not sure when that will even be.

Unfortunately, I'm going to close this PR down and it's something we'll have to come back to at a later date when we've moved over to the new framework.

**Comment by EAaronHarris** [comment]
Extremely disappointing that this has been closed when a workable fix had been proposed.

We have a large/complex app gateway configuration, and we can re-sort our code to alphabetical order relatively easily - at this point, we would be thrilled to do that, in order to have a module that functions.

I do not understand the reasoning behind the decision to close this proposal. There is surely a large number of customers who would be happy with the proposed solution.

Asking everyone to wait for an indeterminate/indefinite period of time - when a solution is possible - does not seem like the right answer here.

**Comment by EAaronHarris** [comment]
@katbyte  It's possible that I am misunderstanding the scope of the issue and the fix.

If there are any customers for whom the module works already, then wouldn't that mean they are not using these unordered lists, and so wouldn't be impacted by any changes to the way they are handled?

On the flip side of the coin, for customers who are attempting to use the unordered lists (such as we are), changing the way/order in which they are handled will, in the worst case scenario, simply continue producing the exact same behavior we are already seeing each time we run a plan/apply today (i.e. re-ordering the elements) - but at the same time it would actually provide a path to resolving them.

This is the part that I'm not sure I understand. If it is truly a breaking change, then I agree. I just don't understand how it could break anything that isn't already... broken (for lack of a better word).

Would the change impact areas outside the unordered property/attribute lists?

Thank you for the response.

**Comment by mbfrahry** [comment]
Our big issue here is that we can't guarantee ordering and we're relying on users to get that ordering correct. Getting that ordering correct can be confusing too if you're not entirely sure why you're getting perpetual diffs. It's putting a lot of onus on users when we need a better solution that doesn't require constant upkeep on the config file. 

With all that said, I have thought of a solution that won't require waiting for the framework transition. It involves splitting out each of the block attributes into their own resources. This will still involve a config file rewrite but it should be a one time thing and we won't have to worry about ordering these settings in any particular way going forward. 

I'm going to start taking a crack at getting those resources written starting today.

**Comment by krknopp** [comment]
We were actually hoping this is where it would end up. We love the way the new Front Door CDN stuff was rewritten, which sounds very similar to what you're proposing.

**Comment by EAaronHarris** [comment]
Yes, that would be fantastic. This would not only address the issue (if it works as desired), but would also be a net overall improvement to the app gateway module as a whole. Thank you for considering this!

**Pull request closed without merging**
