### PR TITLE
`azurerm_cosmosdb_account` - update the nil check for `mongo_server_version`

### PR DESCRIPTION
**Pull request by neil-yechenwei**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description
Recently we received an issue ticket. User mentioned that updating CosmosDB Account would fail with below error after the kind property of CosmosDB Account is changed from "MongoDB" to "GlobalDocumentDB". After I investigated, I found this issue would happen at below scenario.

Error message:
```
azurerm_cosmosdb_account.test: Modifying... [id=/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-cosmos-test04/providers/Microsoft.DocumentDB/databaseAccounts/acctest-ca-test04]
╷
│ Error: updating Database Account (Subscription: "xx-xx-xx-xx"
│ Resource Group Name: "acctestRG-cosmos-test04"
│ Database Account Name: "acctest-ca-test04"): creating/updating CosmosDB Account "acctest-ca-test04" (Resource Group "acctestRG-cosmos-test04"): performing DatabaseAccountsCreateOrUpdate: unexpected status 400 (400 Bad Request) with response: {"code":"BadRequest","message":"ServerVersion is not allowed for this API type.\r\n, Microsoft.Azure.Documents.Common/2.14.0"}
│
│   with azurerm_cosmosdb_account.test,
│   on main.tf line 10, in resource "azurerm_cosmosdb_account" "test":
│   10: resource "azurerm_cosmosdb_account" "test" {
```

Scenario:
```
1. Create resource with kind = "MongoDB" and mongo_server_version = 4.0 in tfconfig1 using TF
2. Delete resource outside of TF
3. Create resource with kind = "GlobalDocumentDB" outside of TF
4. Update kind to "GlobalDocumentDB" and remove mongo_server_version = 4.0 and change the unrelated property like tags in tfconfig1
5. Run `tf apply`. At this time, TF would throw above error.
```

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

The failed test cases are also failed with same error on Teamcity Daily Run. So it's not related with this PR.
image
image
image
image
image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_cosmosdb_account` - update the nil check for `mongo_server_version`

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by Hemin-MSFT — COMMENTED** [review]
when will this PR be reviewed?

**Comment by neil-yechenwei** [comment]
@jackofallops , we may not update `O+C` to `Required` for `mongo_server_version`. Because `mongo_server_version` cannot be set when `kind` is not "MongoDB".

**Comment by jackofallops** [comment]
> @jackofallops , we may not update `O+C` to `Required` for `mongo_server_version`. Because service API doesn't allow to set `mongo_server_version` when `kind` is not `MongoDB`.

@neil-yechenwei - Do you know why this property is `Computed` at all then? Does it come back from the API with a value regardless of being set?

**Comment by neil-yechenwei** [comment]
@jackofallops ,
1. Sorry. I don't know why it's added "Computed" since this property isn't added by me. This [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/11486) introduced this property.
2. When "kind" is "MongoDB" and "mongo_server_version" isn't set, API would return default value "3.6".
3. When "kind" is "MongoDB" and "mongo_server_version" is "4.0", API would return corresponding value "4.0".
4. When "kind" is not "MongoDB" and "mongo_server_version" isn't set, API doesn't return default value.
Note: API doesn't allow to set "mongo_server_version" when "kind" is not "MongoDB".

**Review by katbyte — APPROVED** [review]
I think this is going to have to remain O+C for now, LGTM 🍅

**Pull request merged**
