### PR TITLE
azurerm_private_endpoint - support for the `custom_network_interface_name` property

### PR DESCRIPTION
**Pull request by alexwilcox9**
Hi All,

I'm looking to add the ability to specify a custom network interface name when creating a private endpoint. Without this the nic always contains a random GUID.

Proper tests and docs will be added before asking for review

### CODE REVIEW

**Comment by alexwilcox9** [comment]
`==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/network -run=TestAccPrivateEndpoint_updateNicName -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccPrivateEndpoint_updateNicName
=== PAUSE TestAccPrivateEndpoint_updateNicName
=== CONT  TestAccPrivateEndpoint_updateNicName
--- PASS: TestAccPrivateEndpoint_updateNicName (490.40s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       490.423s`

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @alexwilcox9 - overall this looks good but we have a test failure:
```
------- Stdout: -------
=== RUN   TestAccPrivateEndpoint_updateNicName
=== PAUSE TestAccPrivateEndpoint_updateNicName
=== CONT  TestAccPrivateEndpoint_updateNicName
    testcase.go:110: Step 3/6 error: Error running apply: exit status 1
        
        Error: waiting for creation of Private Endpoint "acctest-privatelink-220905154907967961" (Resource Group "zjhe-acctestRG-privatelink-220905154907967961"): Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'acctest-privatelink-220905154907967961' not found." Details=[]
        
          with azurerm_private_endpoint.test,
          on terraform_plugin_test.tf line 80, in resource "azurerm_private_endpoint" "test":
          80: resource "azurerm_private_endpoint" "test" {
        
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Subnet: (Name "acctestsnetendpoint-220905154907967961" / Virtual Network Name "acctestvnet-220905154907967961" / Resource Group "zjhe-acctestRG-privatelink-220905154907967961"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet acctestsnetendpoint-220905154907967961 is in use by /subscriptions/*******/resourceGroups/zjhe-acctestRG-privatelink-220905154907967961/providers/Microsoft.Network/networkInterfaces/acctest-privatelink-220905154907967961-nic/ipConfigurations/privateEndpointIpConfig.595c85a4-0a4e-42cc-b95f-bb0b7e0e183a and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
        
        
        Error: deleting Private Link Service: (Name "acctestPLS-220905154907967961" / Resource Group "zjhe-acctestRG-privatelink-220905154907967961"): network.PrivateLinkServicesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateLinkServiceWithPrivateEndpointConnectionsCannotBeDeleted" Message="Private link service /subscriptions/*******/resourceGroups/zjhe-acctestRG-privatelink-220905154907967961/providers/Microsoft.Network/privateLinkServices/acctestPLS-220905154907967961 cannot be deleted since it has 1 private endpoint connections. Please delete all private endpoint connections before deleting the private link service." Details=[]
        
--- FAIL: TestAccPrivateEndpoint_updateNicName (228.74s)
FAIL
```

**Comment by alexwilcox9** [comment]
Hi @katbyte - I'm struggling to recreate the error you recieved, this is the test command I'm running:
```make acctests SERVICE=network TESTARGS='-run=TestAccPrivateEndpoint_updateNicName' TESTTIMEOUT='60m'```
Is there something different I should be using? 

It looks like the test tried to delete the subnet before the private endpoints NIC but I don't know why that would happen as deleting the private endpoint deletes the NIC automatically

On an unrelated note whenever I test I get a warning that a lot of files I haven't touched need formatting. I do run make fmt but I don't include these files in the commit
```
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./internal/services/monitor/monitor_action_group_resource_test.go
./internal/services/legacy/virtual_machine_unmanaged_disks_resource_test.go
./internal/services/legacy/virtual_machine_resource.go
./internal/services/legacy/virtual_machine_scale_set_resource.go
./internal/services/synapse/sdk/2021-06-01-preview/artifacts/client.go
./internal/services/appconfiguration/sdk/1.0/appconfiguration/client.go
./internal/services/sql/validate/virtual_network_rule_name_test.go
./internal/services/sql/sql_virtual_network_rule_resource_test.go
./internal/services/serviceconnector/helper.go
./internal/services/blueprints/blueprint_published_version_data_source_test.go
./internal/services/blueprints/blueprint_definition_data_source_test.go
./internal/services/mssql/validate/mssql.go
./internal/sdk/resource_decode.go
./internal/tf/validation/pluginsdk.go
./helpers/validate/float.go
You can use the command: `make fmt` to reformat code.
make: *** [GNUmakefile:37: fmtcheck] Error 1
```

**Comment by katbyte** [comment]
It could be that in our environment things took longer due to the number of resources in it and the deletes returned too quick. There may be some sort of eventually consistency issue

as for the formatting are you running a older version of go? we use 1.18. thats the only thing that comes to mind

**Comment by alexwilcox9** [comment]
You were right on the go version thing, I was running 1.19.1. Falling back to 1.18 sorted it!

I was hoping that might be the cause of the test discrepancy too but it's still passing for me.

Does it fail consistently in your environment?

**Review by katbyte — APPROVED** [review]
i ran the test a half dozen times and it passed, i'll consider it a rare enough occurrence to not be from this change - LGTM 🚜

**Pull request merged**
