### PR TITLE
Restore `azurerm_nginx_configuration` resource and data source

### PR DESCRIPTION
**Pull request by puneetsarna**
Reverts hashicorp/terraform-provider-azurerm#24276

There are a couple of things here:
- The default configuration/import error issue was resolved. See [changelog from March 13, 2024](https://docs.nginx.com/nginxaas/azure/changelog/#march-13-2024)
- This is a breaking change from a product use-case perspective as it breaks our HTTPS use-case where in the workflow is:
  1. Create deployment.
  2. Create certificate.
  3. Create configuration.

With configuration now being inline, the use workflow breaks as `1` and `3` cannot be separated.

### CODE REVIEW

**Comment by puneetsarna** [comment]
@wuxu92

**Comment by puneetsarna** [comment]
Cross posting these from where the functionality was deprecated:

https://github.com/hashicorp/terraform-provider-azurerm/pull/24276#issuecomment-2019474958

https://github.com/hashicorp/terraform-provider-azurerm/pull/24276#issuecomment-2020538830

**Comment by puneetsarna** [comment]
Based on chats with @wuxu92, the below is a public facing example of a use-case for NGINXaaS that breaks if we retire the `azurerm_nginx_configuration` resource:

1. The user first creates `azurerm_nginx_deployment`.
2. The user proceeds to create the `azurerm_nginx_certificate` to add certificates to their deplyoment.
3. The user proceeds to create the `azurerm_nginx_configuration` referencing the certificate via file paths (and the added `depends_on` to ensure sequence of operations) to secure their deployment.

This is a very common use-case for our service and will break if we retire the configuration resource.

https://github.com/nginxinc/nginxaas-for-azure-snippets/blob/main/terraform/certificates/main.tf has these resources in action. Right now, I can create these resources in a single terraform run but if we embed the configuration inside the deployment, the user workflow breaks.

I hope the above helps explain why this PR has been staged.

**Comment by agazeley** [comment]
LGTM! 👍

**Comment by puneetsarna** [comment]
- Need to deprecate the new embedded fields.
- Add a test for certs and configs being used together to establish a workflow contract.

**Comment by puneetsarna** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/pull/25740 superseded this PR. closing it in favor of https://github.com/hashicorp/terraform-provider-azurerm/pull/25740.

**Pull request closed without merging**
