### PR TITLE
`data.azurerm_key_vault_access_policy` - Fix `azurerm_key_vault_access_policy` data source return values in lowercase issue

### PR DESCRIPTION
**Pull request by sinbai**
In the [Create keyvault API](https://github.com/Azure/azure-rest-api-specs/blob/01efd1f79d22d073b063554319562978c0bb1b9c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2021-10-01/keyvault.json#L18), when the value of the specified [accessPolicies](https://github.com/Azure/azure-rest-api-specs/blob/01efd1f79d22d073b063554319562978c0bb1b9c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2021-10-01/keyvault.json#L1092) permission is lowercase, the [Get API](https://github.com/Azure/azure-rest-api-specs/blob/01efd1f79d22d073b063554319562978c0bb1b9c/specification/keyvault/resource-manager/Microsoft.KeyVault/stable/2021-10-01/keyvault.json#L216) returns it in lowercase, and when it is specified as titlecase, the Get API returns it in titlecase. This means that the API return value depends on the setting value.

After terraform provider v3.0, the permission value is case sensitive and it is required for titlecase in terraform. So I assume that `data.azurerm_key_vault_access_policy` should return the values of permission in titlecase to fix issue #17086.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
This might be a breaking change for people using this as is? should we be putting it behind the 4.0 flag and doing the change then?

**Comment by sinbai** [comment]
> This might be a breaking change for people using this as is? should we be putting it behind the 4.0 flag and doing the change then?

@katbyte thanks for your feedback. I have added 4.0 flag for this fix. Could you take another look?

**Review by katbyte — APPROVED** [review]
Thanks @sinbai -LGTM ♻️

**Comment by magodo** [comment]
image

**Pull request merged**
