### PR TITLE
`azurerm_kubernetes_cluster` - mark `ebpf_data_plane` not force new

### PR DESCRIPTION
**Pull request by ms-henglu**
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/22918

image

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
@ms-henglu could you do a rebase please to fix the CI?

**Comment by ms-henglu** [comment]
Hi @stephybun ,

Thanks! I've rebased this PR, please take another look.

**Review by stephybun — CHANGES_REQUESTED** [review]

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @ms-henglu this is good to go after the merge conflict has been resolved.

**Review by stephybun — APPROVED** [review]
Thanks @ms-henglu LGTM 👍

**Pull request merged**
