### PR TITLE
SQL Managed Instance Premium Hardware Series

### LINKED ISSUE #14949: Support for Azure SQL Managed Instance Premium Hardware Series
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,
Azure SQL Managed Instance now has a new premium series hardware available under the General Purpose and Business Critical tiers. I wanted to raise a request for this and see about adding the support myself. 

* BC_Gen8IH - Business Critical Premium Series - Intel Ice Lake, 7 GB RAM/vCore
* BC_Gen8IM - Business Critical Premium Series - Memory Optimized - Intel Ice Lake, 13,6 GB RAM/vCore
* GP_Gen8IH - General Purpose Premium Series - Intel Ice Lake, 7 GB RAM/vCore
* GP_Gen8IM - General Purpose Premium Series - Memory Optimized - Intel Ice Lake, 13,6 GB RAM/vCore

image

### New or Affected Resource(s)

* azurerm_sql_managed_instance

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_managed_instance" "example" {
  name                         = "managedsqlinstance"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
  license_type                 = "BasePrice"
  subnet_id                    = azurerm_subnet.example.id
  sku_name                     = "BC_Gen8IH"
  vcores                       = 4
  storage_size_in_gb           = 32

  depends_on = [
    azurerm_subnet_network_security_group_association.example,
    azurerm_subnet_route_table_association.example,
  ]
}
```

### PR DESCRIPTION
**Pull request by codyja**
Wanted to see about adding support for the premium hardware series now available on Azure SQL Managed Instance. 

image

Resolves #14949

### CODE REVIEW

**Comment by codyja** [comment]
Resolves #14949

**Comment by codyja** [comment]
I wanted to see about some input on [this](https://github.com/hashicorp/terraform-provider-azurerm/blob/ef3c1e68a2c25f2ce5950bb459ef248ed4699171/internal/services/sql/sql_managed_instance_resource.go#L90-L98) validate func:
```
			"vcores": {
				Type:     schema.TypeInt,
				Required: true,
				ValidateFunc: validation.IntInSlice([]int{
					4,
					8,
					16,
					24,
					32,
					40,
					64,
					80,
				}),
			},
```
If you select the Premium Series Memory Optimized (_Gen8IM), you can only go up to 64 cores. Is there a recomendation on if I should add some logic here to handle that? Thank you

**Comment by aristosvo** [comment]
An example of how this could be handled is here: [elasticpool.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mssql/helper/elasticpool.go).

It has both pro's and con's, it would help users but would add some extra maintenance work on changes in that regard. Most of the different kind of DBs don't have it. It would also depend on the exception which is thrown by Azure itself, which may explain it (not) well enough for the user.

**Comment by codyja** [comment]
@aristosvo I'll test what happens when I assign 80 cores to the memory optimized hardware and check for errors. 

I realized I'm seeing an issue here though with the change. I believe it's showing a change on each terraform run and I'm not quite sure why yet:
```
  ~ resource "azurerm_sql_managed_instance" "primary" {
        id                           = "/xxxxxxx/x/x/x/x"
        name                         = "mi-eval-a7929232"
      ~ sku_name                     = "MIGP4G8IM" -> "GP_Gen8IM"
        tags                         = {
            "application"         = "managed_instance_eval"
        }
        # (15 unchanged attributes hidden)
    }
```

**Review by katbyte — APPROVED** [review]
Thanks @codyja - LGTM 🏗️

**Comment by aristosvo** [comment]
@codyja I believe this is an API inconsistency. You could try if using their advanced `sku_name` convention works better, but it is not as user friendly as the one you provided..

**Comment by codyja** [comment]
Ok luckily the Azure API returns a good error back. Here is a test I ran with *GP_Gen8IH* (Premium Memory Optimized) where the max vCores is 64 currently. I set it to 80, kicked off a run and got this error, which I think is good enough right?

`│ Error: sql.ManagedInstancesClient#CreateOrUpdate: Failure sending request: StatusCode=405 -- Original Error: Code="InvalidVcoreValue" Message="vCore value 80 is not valid. Please specify a valid vCore value."`

Looking into the Skus changing issue further now and will come back soon. Well, _soon_ being relative with Managed Instance deployments :) Thank you both!

**Comment by codyja** [comment]
Ok on the Skus changing issue, on each tf apply when doing a GET on an managed instance against the Azure API directly I see the following:

SKU in Terraform: GP_Gen8IH
```
"sku": {
    "name": "MIBC64G8IM",
    "tier": "BusinessCritical",
    "capacity": 64
  },
```

SKU in Terraform: GP_Gen5
```
"sku": {
    "name": "BC_Gen5",
    "tier": "BusinessCritical",
    "family": "Gen5",
    "capacity": 4
  },
```

Logs from a Terraform Run:
```
2022-01-14T08:47:24.245-0600 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for module.azurerm_managed_instance.azurerm_sql_managed_instance.primary during refresh.
      - .sku_name: was cty.StringVal("GP_Gen8IM"), but now cty.StringVal("MIGP4G8IM")
```  

Any recommendations on how to handle that response from the Azure API?

**Comment by katbyte** [comment]
🤣😭 such is azure life, they should probably return the same value so sounds like an API bug. could you open one on the rest specs (https://github.com/Azure/azure-rest-api-specs) and link it to above that code block? otherwise not much we can do aside from translate them upon read

**Comment by codyja** [comment]
Just a heads up that I opened the above issue as requested @katbyte. Thanks!

**Comment by katbyte** [comment]
Hey @codyja - we've included these changes in #15203, as such i'm going to close this out in favour of that PR.

**Pull request closed without merging**
