### PR TITLE
`data.azurerm_management_group` - Add new attributes: `management_group_ids`, `all_management_group_ids` and `all_subscription_ids`

### LINKED ISSUE #16168: Management Group Data Source does not Recursively Resolve Child Subscriptions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Provider versions 2.97.0, 2.99.0. Believe the code matches the current latest but have not tested with 3.x due to module compatibility issues. 

### Affected Resource(s)

* azurerm_management_group

### Terraform Configuration Files

```hcl
data "azurerm_management_group" "mgmt_group" {
  name = var.mgmt_group_id
}

output "subscriptions" {
  value = data.azurerm_management_group.mgmt_group.subscription_ids
}
```

### Expected Behaviour

In a situation with nested management groups, all recursive subscription Ids should be resolved and presented. 

### Actual Behaviour

No recursive lookup occurs. Only top-level subscription Ids are returned in a nested management group situation. 

### Steps to Reproduce

1. Ensure you have a management group nested within a management group. 
2. Ensure subscriptions are within the child management group. 
3. Use the parent management group as the data source. 
4. Validate an empty response as there is no recursive lookup.

### PR DESCRIPTION
**Pull request by magodo**
Fixes #16168 

## Test

```shell
💢  TF_ACC=1 go test -v -timeout=20h ./internal/services/managementgroup -run='TestAccManagementGroupDataSource_nestedManagmentGroup'
=== RUN   TestAccManagementGroupDataSource_nestedManagmentGroup
=== PAUSE TestAccManagementGroupDataSource_nestedManagmentGroup
=== CONT  TestAccManagementGroupDataSource_nestedManagmentGroup
--- PASS: TestAccManagementGroupDataSource_nestedManagmentGroup (190.92s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/managementgroup       190.928s
```

### CODE REVIEW

**Comment by marcosgm** [comment]
I'd love to vote +1 here! I'm eager to see this PR merged

**Review by katbyte — APPROVED** [review]
LGTM 🌵

**Comment by JustinGrote** [comment]
@magodo am I doing this wrong? I'm seeing the values as null in my testing
image

**Comment by JustinGrote** [comment]
It does work with a TF plan, not sure why it doesn't come up in console though.

**Pull request merged**
