### PR TITLE
New resource `azurerm_stream_analytics_stream_input_eventhub_v2`

### LINKED ISSUE #19039: `azurerm_stream_analytics_stream_input_eventhub` throws error on `terraform import`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.29

### Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_stream_input_eventhub

### Terraform Configuration Files

```hcl
resource "azurerm_stream_analytics_stream_input_eventhub" "evh" {
  name = "asa-evh-input"

  stream_analytics_job_name = "asa-job-example"
  resource_group_name       = "rg-eventhub"

  eventhub_consumer_group_name = "test"
  eventhub_name                = "evh-example"
  servicebus_namespace         = "evhns-example"
  authentication_mode          = "Msi"

  serialization {
    type     = "Json"
    encoding = "UTF8"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: converting Stream Input EventHub to an EventHub Stream Input: <nil>

TRACE output: (Refresh state)
{
  "id": "REDACTED",
  "name": "asa-evh-input",
  "type": "Microsoft.StreamAnalytics/streamingjobs/inputs",
  "properties": {
    "type": "Stream",
    "datasource": {
      "type": "Microsoft.EventHub/EventHub",
      "properties": {
        "consumerGroupName": "test",
        "eventHubName": "evh-example",
        "serviceBusNamespace": "evhns-example",
        "sharedAccessPolicyName": null,
        "authenticationMode": "Msi"
      }
    },
    "compression": {
      "type": "None"
    },
    "partitionKey": "partitionKeyExample",
    "serialization": {
      "type": "Json",
      "properties": {
        "encoding": "UTF8"
      }
    }
  }
}: timestamp=2022-10-28T12:00:53.597+0200
2022-10-28T12:00:53.598+0200 [ERROR] vertex "import azurerm_stream_analytics_stream_input_eventhub.evh result" error: converting Stream Input EventHub to an EventHub Stream Input: <nil>
```

### Expected Behaviour

`terraform import` succeeds

### Actual Behaviour

`terraform import` fails

### Steps to Reproduce

`terraform import azurerm_stream_analytics_stream_input_eventhub.evh <REDACTED ressource id>`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by stephybun**
Closes #19039

image

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🌵

**Comment by drdamour** [comment]
But how is it different than v1? Insee its got a diff type, but what does that mean

**Comment by magodo** [comment]
@drdamour Looks like it is mentioned here: https://github.com/hashicorp/terraform-provider-azurerm/pull/19150/files#diff-a2501c817c11563a007e8b1dcbb99c9502a25a03854711826bcf7bf6af2e63a3R11

**Comment by drdamour** [comment]
all that does is say it has a different type, but as i asked, what does that mean?

**Pull request merged**
