### PR TITLE
`containerapps`: updating to API Version `2023-05-01`

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR upgrades `containerapps` to use API Version `2023-05-01` rather than `2022-03-01` - which supersedes #22476 and will enable #21133 to be fixed

Dependent on #22803

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Looks like this API may not be fully rolled out just yet:

```
 Error: creating Managed Environment (Subscription: "*******"
        Resource Group Name: "acctestRG-CAEnv-230803102145526598"
        Managed Environment Name: "acctest-CAEnv230803102145526598"): performing CreateOrUpdate: managedenvironments.ManagedEnvironmentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'westeurope' and API version '2023-05-01' for type 'managedEnvironments'. The supported api-versions are '2022-01-01-preview, 2022-03-01, 2022-06-01-preview, 2022-10-01, 2022-11-01-preview, 2023-04-01-preview'
```

Whilst the Stable API Version has been merged into `main`, it's in neither [the Go SDK](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerapps/Azure.ResourceManager.AppContainers/src/autorest.md) or [the .net SDK](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerapps/Azure.ResourceManager.AppContainers/src/autorest.md) - so this is probably waiting on the API to be fully rolled out

**Comment by Joey40** [comment]
Can we reopen the other PR with the preview API?  Or do you think this will be resolved quickly?

**Comment by Phiph** [comment]
> Looks like this API may not be fully rolled out just yet:
> 
> ```
>  Error: creating Managed Environment (Subscription: "*******"
>         Resource Group Name: "acctestRG-CAEnv-230803102145526598"
>         Managed Environment Name: "acctest-CAEnv230803102145526598"): performing CreateOrUpdate: managedenvironments.ManagedEnvironmentsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'westeurope' and API version '2023-05-01' for type 'managedEnvironments'. The supported api-versions are '2022-01-01-preview, 2022-03-01, 2022-06-01-preview, 2022-10-01, 2022-11-01-preview, 2023-04-01-preview'
> ```
> 
> Whilst the Stable API Version has been merged into `main`, it's in neither [the Go SDK](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerapps/Azure.ResourceManager.AppContainers/src/autorest.md) or [the .net SDK](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/containerapps/Azure.ResourceManager.AppContainers/src/autorest.md) - so this is probably waiting on the API to be fully rolled out

Hey @tombuildsstuff  is there anything I can do to run this test to see when it's been made GA?

It looks as though MS haven't updated their changeling yet to include that API version. 

https://learn.microsoft.com/en-us/azure/templates/microsoft.app/change-log/managedenvironments

**Comment by Phiph** [comment]
There's a new Api revision that supports Multiple Ports which is very useful for many people under `2023-05-02-preview`


https://github.com/microsoft/azure-container-apps/issues/763#issuecomment-1668654775

**Comment by tombuildsstuff** [comment]
@Phiph looks like this Stable API Version is now available (per the docs site): https://learn.microsoft.com/en-us/azure/templates/microsoft.app/change-log/managedenvironments

Will run the tests to confirm that's been fully rolled out now..

**Comment by Phiph** [comment]
Legend! Thanks Tom

**Comment by Joey40** [comment]
FYI:

https://azure.microsoft.com/en-us/updates/retirement-azure-container-apps-preview-api-versions-20220601preview-and-20221101preview/

**Comment by tiwood** [comment]
@tombuildsstuff we too would like to deploy Container Apps with the latest API version. If I understood correctly this here could be merged now?

**Review by katbyte — APPROVED** [review]
LGTM 🍽️

**Comment by tombuildsstuff** [comment]
Tests look good 👍

**Comment by Joey40** [comment]
Just in time for a slew of other ACA updates that went GA yesterday. Thanks!

**Pull request merged**
