### PR TITLE
Upgrade `managedservices.registrationdefinitions` API version from `2019-06-01` to `2022-10-01`

### PR DESCRIPTION
**Pull request by neil-yechenwei**
This PR is to upgrade `managedservices.registrationdefinitions` API version from `2019-06-01` to `2022-10-01`.

Note: As the TCs related with Lighthouse Definition are skipped in Teamcity due to test data issue, so I ran them on my local and they passed.

--- PASS: TestAccLighthouseDefinition_basic (131.62s)
--- PASS: TestAccLighthouseDefinition_requiresImport (175.23s)
--- PASS: TestAccLighthouseDefinition_complete (161.23s)
--- PASS: TestAccLighthouseDefinition_update (559.91s)
--- PASS: TestAccLighthouseDefinition_emptyID (136.87s)
--- PASS: TestAccLighthouseDefinition_plan (127.90s)

### CODE REVIEW

**Review by manicminer — CHANGES_REQUESTED** [review]
@neil-yechenwei Thanks for the update. I've run the tests locally and the import check for `azurerm_lighthouse_assignment` doesn't seem to be working. I'm not sure if this is a regression but could you take a look at this? Other than that, this should be good to merge.

Screen Shot 2022-12-01 at 20 45 59

**Comment by neil-yechenwei** [comment]
@manicminer , if you can rollback to main branch, you would encounter the same issue. So I think there is some problem on this case not regression issue. As you can see, I didn't update the API version for LighthouseAssignment. I only update the API version for LighthouseDefinition. Hence, I think this failed issue isn't related with this PR.

**Comment by neil-yechenwei** [comment]
@manicminer , after investigated, I found the root cause is caused by that the logic of checking the existing resource is removed from this Lighthouse Assignment resource by [this PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/15839). So the test case failed. But per my understanding, it shouldn't be removed. So I updated this PR to add it back. Now all TCs passed.

--- PASS: TestAccLighthouseAssignment_basic (182.81s)
--- PASS: TestAccLighthouseAssignment_emptyID (190.43s)
--- PASS: TestAccLighthouseAssignment_requiresImport (223.70s)

**Review by manicminer — APPROVED** [review]
Great, thanks for spotting that and fixing @neil-yechenwei. Tests look good.

Screen Shot 2022-12-02 at 10 49 14

**Pull request merged**
