### PR TITLE
azurerm_healthcare_service - Add support of export storage account and identity (system Assigned)

### PR DESCRIPTION
**Pull request by Khayoann2**
I was unable to fully set up a new healthcare service project because some mandatory information needed to be provided. So I thought to myself, let’s try to contribute.

To be honest, i'm more a devops engineer than a developer so be aware to contribute and challenge me if i miss something...

### CODE REVIEW

**Comment by Khayoann2** [comment]
To be honest, i'm more a devops engineer than a developer so be aware to contribute and challenge me if i miss something...

**Comment by cedrox** [comment]
Thanks for tackling this. Do we have an ETA for the availability ?

**Comment by Khayoann2** [comment]
> Thanks for tackling this. Do we have an ETA for the availability ? 

Hope that a maintainer will take my PR soon 👌🤞

**Review by katbyte — CHANGES_REQUESTED** [review]
Looks like there is a test failure:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccHealthCareServiceDataSource_basic
=== PAUSE TestAccHealthCareServiceDataSource_basic
=== CONT  TestAccHealthCareServiceDataSource_basic

------- Stderr: -------
panic: identity: '': source data must be an array or slice, got struct

goroutine 412 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc00287f280, {0x8a58322, 0x8}, {0x8036140, 0xc003abf620})
	/opt/teamcity-agent/work/3337027aeff310bf/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:233 +0x2b5
github.com/hashicorp/terraform-provider-azurerm/internal/services/healthcare.resourceHealthcareServiceRead(0xc00287f280, {0x7a6be80?, 0xc004926480?})
```

**Comment by Khayoann2** [comment]
> Looks like there is a test failure:
> 
> ```
> Test ended in panic.
> 
> ------- Stdout: -------
> === RUN   TestAccHealthCareServiceDataSource_basic
> === PAUSE TestAccHealthCareServiceDataSource_basic
> === CONT  TestAccHealthCareServiceDataSource_basic
> 
> ------- Stderr: -------
> panic: identity: '': source data must be an array or slice, got struct
> 
> goroutine 412 [running]:
> github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc00287f280, {0x8a58322, 0x8}, {0x8036140, 0xc003abf620})
> 	/opt/teamcity-agent/work/3337027aeff310bf/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:233 +0x2b5
> github.com/hashicorp/terraform-provider-azurerm/internal/services/healthcare.resourceHealthcareServiceRead(0xc00287f280, {0x7a6be80?, 0xc004926480?})
> ```

Fix has been pushed and this issue is now solved

**Comment by Khayoann2** [comment]
I detected another issue. i will push another fix

**Comment by Khayoann2** [comment]
Now everything is green on my side
@katbyte

**Comment by Khayoann2** [comment]
@katbyte Could you take a look, please ? 👍

**Comment by Khayoann2** [comment]
I don't know what i can do to make it merged 😢 
Is there anything remaining on my side ? because i'm a little bit confused ...

**Review by katbyte — APPROVED** [review]
Thanks @Khayoann2 ! LGTM 🏥

**Pull request merged**
