### PR TITLE
`azurerm_signalr_service` - add `http_request_logs_enabled` property

### PR DESCRIPTION
**Pull request by xiaxyi**
Adding support for property `resource_logs` that was introduced in 2023-02-01 api version

### CODE REVIEW

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
Looks like we can remove the breaking change here by making the new field `http_request_logs_enabled` a top-level field like the other two are today?

**Comment by xiaxyi** [comment]
Thanks @tombuildsstuff for the comments, I was thinking about the same thing at the first place but turned to introduce the `resource_logs` block at the end as I would like to keep things the same as `Live_trace`. Anyway, I updated the code as suggested, feel free to let me know if there is anything needed.

**Comment by xiaxyi** [comment]
update acctest result:
--- PASS: TestAccSignalRService_resourceLogs (537.52s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/signalr       538.458s

**Review by katbyte — APPROVED** [review]
LGTM 🍨

**Pull request merged**
