### PR TITLE
Add SSL profile support to azurerm_application_gateway

### PR DESCRIPTION
**Pull request by koikonom**

### CODE REVIEW

**Comment by michal-malec** [comment]
Hi @koikonom, It seems I created a PR adding similar features ~2h ago: https://github.com/hashicorp/terraform-provider-azurerm/pull/13273.

**Comment by koikonom** [comment]
Hi @michal-malec ! Good job on the PR. It seems we followed the same method, so I'll just add a couple of things that are missing from this PR, close mine, and merge yours instead.

**Comment by michal-malec** [comment]
@koikonom, sounds fine for me. Feel free to add what's needed to my PR :)

**Comment by katbyte** [comment]
closing in favour of #13273

**Pull request closed without merging**
