### PR TITLE
azurerm_application_gateway - support for the Basic SKU 

### LINKED ISSUE #25739: azurerm_redhat_openshift_cluster - when deleting a cluster, if its already in the state of `deleting` it should wait and watch the delete to finish.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_redhat_openshift_cluster

### Terraform Configuration Files

```hcl
.
```

### Debug Output/Panic Output

```shell
.
```

### Expected Behaviour

when running an operation that would delete the cluster,  either deleting it or doing a version change,  if the cluster is already in a deleting state it should wait for the delete operation to finish and then update its state and move to the next resource.

### Actual Behaviour

```
To perform exactly these actions, run the following command to apply:
    terraform apply "aro.plan"
terraform apply aro.plan
azurerm_redhat_openshift_cluster.cluster: Destroying... [id=/subscriptions/c5545383-1a94-45fe-b501-7ebdf43e5d7a/resourceGroups/aro-xx-rg/providers/Microsoft.RedHatOpenShift/openShiftClusters/aro-pczarkow]
╷
│ Error: deleting Provider Open Shift Cluster (Subscription: "c5545383-1a94-45fe-b501-7ebdf43e5d7a"
│ Resource Group Name: "aro-xx-rg"
│ Open Shift Cluster Name: "aro-xx"): performing Delete: unexpected status 400 with error: RequestNotAllowed: Request is not allowed in provisioningState 'Deleting'.
│
│ deleting Provider Open Shift Cluster (Subscription: "c5545383-1a94-45fe-b501-7ebdf43e5d7a"
│ Resource Group Name: "aro-xx-rg"
│ Open Shift Cluster Name: "aro-xx"): performing Delete: unexpected status 400 with error: RequestNotAllowed:
│ Request is not allowed in provisioningState 'Deleting'.
╵
make: *** [Makefile:18: create] Error 1
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #25973: Support for `azurerm_application_gateway` Basic SKU (Preview)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

As per the announcement for the [Application Gateway Basic SKU](https://azure.microsoft.com/en-us/updates/public-preview-azure-application-gateway-v2-basic-sku/#:~:text=The%20Application%20Gateway%20Basic%20SKU,require%20advanced%20traffic%20management%20features.) (Preview) - implement `Basic` as an option for the `azurerm_application_gateway` property `sku.name` and `sku.tier`

Following feature will be required to be registered in the subscription:
`az feature register --name AllowApplicationGatewayBasicSku --namespace Microsoft.Network`

Some changes to the `sku.capacity` and `autoscale_configuration` logic/defaults may need to be made as well, since the `Basic` SKU doesn't support this

I'm happy to look at implementing this, is the process to update to [go-azure-sdk](https://github.com/hashicorp/go-azure-sdk) first, and then implement this in the provider?

### New or Affected Resource(s)/Data Source(s)

`azurerm_application_gateway`

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "this" {
  name                = "${var.prefix}-agw"
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location

  sku {
    name = "Basic"
    tier = "Basic"
  }
...
```

### References
https://azure.microsoft.com/en-us/updates/public-preview-azure-application-gateway-v2-basic-sku/#:~:text=The%20Application%20Gateway%20Basic%20SKU,require%20advanced%20traffic%20management%20features

### PR DESCRIPTION
**Pull request by tedsmitt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_application_gateway` - support for the `Basic` SKU tier

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #25973

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Looks like all the tests are failing with:
```
------- Stdout: -------
=== RUN   TestAccApplicationGateway_authCertificate
=== PAUSE TestAccApplicationGateway_authCertificate
=== CONT  TestAccApplicationGateway_authCertificate
    testcase.go:173: Step 1/6 error: Error running apply: exit status 1
        
        Error: creating Application Gateway (Subscription: "*******"
        Resource Group Name: "acctestRG-240920034903751201"
        Application Gateway Name: "acctestag-240920034903751201"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: AppGatewayV1SkuDeprecated: Application Gateway SKU tier Standard has been deprecated. Supported SKU tiers are Standard_v2,WAF_v2. Refer https://aka.ms/V1retirement.
        
          with azurerm_application_gateway.test,
          on terraform_plugin_test.tf line 72, in resource "azurerm_application_gateway" "test":
          72: resource "azurerm_application_gateway" "test" {
        
--- FAIL: TestAccApplicationGateway_authCertificate (181.02s)
FAIL
```

**Comment by tedsmitt** [comment]
As per https://learn.microsoft.com/en-us/azure/application-gateway/v1-retirement#retirement-timelines it looks like we can no longer deploy V1 SKUs of the application gateway since the 1st Sept.

At the very least we need to remove any acceptance tests that use any V1 SKUs e.g `Standard_Small`, but the provider should be updated to remove these as valid options. I believe that this is out of the scope of this PR though, so we should raise another to remove this capability. I'm not sure how much effort this will be, but I will start looking into it.

**Comment by katbyte** [comment]
@tedsmitt - could you swap the test SKUs to one that will allow them to pass? it's required to be able to test your changes properly for merge

**Comment by tedsmitt** [comment]
@katbyte I've removed the old SKUs from the acceptance tests

**Comment by tedsmitt** [comment]
@katbyte Any update on whether we can re-test this?

**Review by katbyte — CHANGES_REQUESTED** [review]
👋  ran the tests again and it appears to be a different error now :(

```
------- Stdout: -------
=== RUN   TestAccApplicationGateway_requiresImport
=== PAUSE TestAccApplicationGateway_requiresImport
=== CONT  TestAccApplicationGateway_requiresImport
    testcase.go:173: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Application Gateway (Subscription: "*******"
        Resource Group Name: "acctestRG-241016180010215836"
        Application Gateway Name: "acctestag-241016180010215836"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty: Priority for the request routing rule /subscriptions/*******/resourceGroups/acctestRG-241016180010215836/providers/Microsoft.Network/applicationGateways/acctestag-241016180010215836/requestRoutingRules/acctest-vnet-241016180010215836-rqrt cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01
        
          with azurerm_application_gateway.test,
          on terraform_plugin_test.tf line 71, in resource "azurerm_application_gateway" "test":
          71: resource "azurerm_application_gateway" "test" {
        
--- FAIL: TestAccApplicationGateway_requiresImport (202.42s)
FAIL
```

**Comment by tedsmitt** [comment]
@katbyte Have pushed some updates that fix the test case resources to be compatible with the v2 SKU. I have re-run some of the tests locally and they are looking better now.

P.S There is an opportunity here to do a bit of code tidy up as there are probably some duplicate tests since removing the old Standard SKU. However, I know this PR is already quite large so I'm hesitant to include those changes here, what do you think?

**Review by katbyte — APPROVED** [review]
Failing tests have gone from 30 to 7! and the remaining ones are failing one main. We would certainly welcome another pr cleaning up and fixing the remaining 7 but as this is enough for me to see your PR works + the remaining 7 are failing in main and seem unrelated to this change lets get this in for this weeks release LGTM 🍓

**Pull request merged**
