### PR TITLE
temp fix for synapse firewall resource

### PR DESCRIPTION
**Pull request by ms-henglu**
To address issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/13510

image

### CODE REVIEW

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @ms-henglu 

Thanks for this PR.

Unfortunately this isn't guaranteed to be available within a minute (even if it responds that way at the moment) - as such we can't ship this with a Sleep here - can we poll on something else?

Thanks!

**Comment by owenfarrell** [comment]
@tombuildsstuff - Sadly, I think the answer is "no". The existing implementation runs a `Get` immediately following the call to `CreateOrUpdate`.

But I **_think_** that means the 5-minute delay cited in the [Azure documentation](https://docs.microsoft.com/en-us/azure/azure-sql/database/firewall-configure#troubleshoot-the-database-firewall) is on Microsoft's side of the PaaS. 😔

Short of injecting a `Sleep` in the resource (which, I agree, doesn't feel right), I think chaining a `time_sleep` resource is the only safe bet here.

Of note, I ran in to this same issue when running some recent acceptance tests. So I think "mocking" up the delay as part of a `PreConfig` might be a need in some of the Synapse tests.

**Comment by ms-henglu** [comment]
Hi @tombuildsstuff , @owenfarrell , thanks for checking this PR.

> Unfortunately this isn't guaranteed to be available within a minute (even if it responds that way at the moment)
Actually I've checked with service team, the delay is 1 minute. But I agree that this is not a good way to fix it.

So here's another solution. When IP is added to the firewall ip range, we call GetWorkspace API to check whether firewall changes are taking effect. This is the recommended solution by service team.

**Comment by tombuildsstuff** [comment]
hi @ms-henglu 

Thanks for pushing those changes and checking with the service team - however this approach introduces a dependency on a third-party web service which we also can't ship here - instead whilst I'd like to thank you for this contribution I'm going to close this in favour of #13525 which fixes this in a different manner.

Thanks!

**Pull request closed without merging**
