### PR TITLE
new resource `azurerm_elastic_san_snapshot`

### PR DESCRIPTION
**Pull request by teowa**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

New resource `azurerm_elastic_san_snapshot`

ref:
1. https://learn.microsoft.com/en-us/azure/storage/elastic-san/elastic-san-snapshots?tabs=azure-cli
2. https://github.com/Azure/azure-rest-api-specs/blob/82f3d9571517966992eaf97b1db73f0a821cd06b/specification/elasticsan/resource-manager/Microsoft.ElasticSan/stable/2023-01-01/elasticsan.json#L1394

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

```
TF_ACC=1 go test -v ./internal/services/elasticsan -parallel 5 -run TestAccElasticSANSnapshot_ -timeout 2h -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccElasticSANSnapshot_basic
=== PAUSE TestAccElasticSANSnapshot_basic
=== RUN   TestAccElasticSANSnapshot_requiresImport
=== PAUSE TestAccElasticSANSnapshot_requiresImport
=== CONT  TestAccElasticSANSnapshot_basic
=== CONT  TestAccElasticSANSnapshot_requiresImport
--- PASS: TestAccElasticSANSnapshot_basic (304.64s)
--- PASS: TestAccElasticSANSnapshot_requiresImport (323.77s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/elasticsan    323.798s
```
- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* new resource `azurerm_elastic_san_snapshot` [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@teowa what's the use-case for this Resource? Snapshots are typically an interactive operation since they're time/context based - so this typically isn't a good fit for a Terraform Resource, therefore it'd be good to understand how this is likely to be used.

**Comment by teowa** [comment]
Hi @tombuildsstuff, Azure Elastic SAN volume snapshots are incremental point-in-time backups of volumes. The first snapshot occupies no space, and every subsequent snapshot consists only of the changes to the Elastic SAN volume since the last snapshot. 
The content of volume snapshot is time/context based, but the resource is closely related to other resources. We can create ElasticSAN volume (`azurerm_elastic_san_volume`) or Virtual Disk Snapshot(`azurerm_snapshot`) from the ElasticSAN volume snapshot.

**Comment by tombuildsstuff** [comment]
@teowa 

>  incremental point-in-time backups of volumes
> The content of volume snapshot is time/context based, but the resource is closely related to other resources. We can create ElasticSAN volume (azurerm_elastic_san_volume) or Virtual Disk Snapshot(azurerm_snapshot) from the ElasticSAN volume snapshot.

My point exactly, these aren't something you'd _create_ in Terraform, although you might use an existing one - so this would make sense as a Data Source but not as a Resource here?

**Comment by teowa** [comment]
Hi @tombuildsstuff , it makes sense that in many cases users might only use existing snapshots in an Terraform pipeline, but since the volume snapshot has regular PUT/DELETE API, should we also support it as a resource in case some users may need it? Like in some cases users may check the status with Portal or CLI but they want it be consistently managed through Terraform.

**Comment by tombuildsstuff** [comment]
@teowa we shouldn't add a resource just because an API is exposed, particularly if it's unlikely to be used or, as in this case, it's not well suited to Terraform.

A snapshot is taken at a given point-in-time, therefore it's not something you're likely to provision in Terraform because you likely wouldn't want to manage it's lifecycle long-term; instead you'd want to ensure it was triggered and then move on.

To give a more concrete example: let's I have an Elastic SAN and I need to take a daily/weekly/one-time snapshot of that. The vast majority of the time you're going to want that to be triggered on a schedule - and whilst you _could_ create those in Terraform, you'd need to define a resource for each backup type, which you'd likely do in some kind of cron job. Whilst you _could_ manage these backups in Terraform, to be honest it's the wrong tool for the job - and given that Terraform is managing the lifecycle of the resource (including deleting the snapshot) it's going to be _incredibly_ easy to foot-gun with that resource when it's used in the most non-trivial scenario.

Whilst I appreciate the desire to add a Resource for this purpose, in truth Terraform is likely the wrong tool to be creating Snapshots in (see also the `azurerm_snapshot` and `azurerm_image` resource, for which [Packer](https://packer.io) is far better suited to) - in this instance I don't think we need to expose a resource for this (or at least not without customer demand/a use-case) - but a Data Source would make sense.

Thanks!

**Comment by teowa** [comment]
Thanks @tombuildsstuff , I am going to implement a data source for this.

**Pull request closed without merging**
