### PR TITLE
`dependencies` - update `compute/gallery*` to `2022-03-03`

### PR DESCRIPTION
**Pull request by myc2h6o**
upgrading sdk to prepare for Community Gallery https://github.com/hashicorp/go-azure-sdk/blob/eb48fdabab6951dddff277f9efc7306098f8dd69/resource-manager/compute/2022-03-03/galleries/constants.go#L76

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
We have a test failure:
```
Error: updating Application Version (Subscription: "*******"
        Resource Group Name: "acctest-compute-230601154225989649"
        Gallery Name: "acctestsig230601154225989649"
        Application Name: "acctest-app-230601154225989649"
        Version Name: "0.0.1"): performing Update: galleryapplicationversions.GalleryApplicationVersionsClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Complete set of target locations not specified while updating gallery artifact '0.0.1' and type 'GalleryApplicationVersion'. Deletion of previously replicated locations is not allowed, and you need to specify a complete set of target locations in the update request or specify null or empty set for target regions in the update request or set allow deletion of replicated locations under safety profile property. To figure out complete set of target locations, you can perform a get first on gallery artifact"
        
          with azurerm_gallery_application_version.test,
          on terraform_plugin_test.tf line 60, in resource "azurerm_gallery_application_version" "test":
          60: resource "azurerm_gallery_application_version" "test" {
        
```

**Comment by myc2h6o** [comment]
Hi @katbyte thanks for reviewing! there is a new property in the new sdk `AllowDeletionOfReplicatedLocations` which needs to set to true to allow the count of `target_region` to be decreased.
This property is set to `true` on Azure Portal as well by default, however when missing in the sdk request, it is set to false, thus need to explicitly set it to true when using the new sdk

**Comment by myc2h6o** [comment]
Updated test result
image

**Review by katbyte — APPROVED** [review]
LGTM ☔

**Pull request merged**
