### PR TITLE
Container Registry API update: 2021-08-01-preview to 2023-06-01-preview

### PR DESCRIPTION
**Pull request by magodo**
This PR updates API version for ACR from 2021-08-01-preview to 2023-06-01-preview. Apart from the regular API update, it involves a breaking change (due to API change) that the `network_rule_set.virtual_network` is removed from `azurerm_container_registry`. We've got clarification from the service team that:

> We deliberatively deprecated this property since it is only used exclusively for service endpoints (which is a feature we are deprecating).  We are encouraging customers to use Private Endpoints instead.

### CODE REVIEW

**Comment by magodo** [comment]
image

The two failures are not related to this PR, which exist in the main branch already.

**Review by manicminer — CHANGES_REQUESTED** [review]
@magodo We can't just remove the `virtual_network` block as this is a breaking change. This will unfortunately have to wait until 4.0 - in the meantime we can deprecate the block in preparation.

**Comment by stephybun** [comment]
@magodo any updates here?

**Comment by magodo** [comment]
@stephybun I thought this PR is on hold until 4.0 release, as it contains breaking changes. I've merged against the main branch to resolve the conflicts. Please let me know if anything I've missed.

**Comment by stephybun** [comment]
@manicminer is suggesting to deprecate the block in preparation

**Comment by magodo** [comment]
@stephybun I've created another PR for the deprecation: https://github.com/hashicorp/terraform-provider-azurerm/pull/24140

**Comment by magodo** [comment]
@stephybun I've updated this PR, please take another look!

<details>
<summary>Test</summary>
<pre>
terraform-provider-azurerm on εéá acr_sdk_update_to_2023_06_01_preview via ≡ƒÉ╣ v1.22.1 took 6m23s
≡ƒÆñ  TF_ACC=1 go test -v -timeout=20h ./internal/services/containers -run='TestAccContainerRegistry_'
=== RUN   TestAccContainerRegistry_basic
=== PAUSE TestAccContainerRegistry_basic
=== RUN   TestAccContainerRegistry_requiresImport
=== PAUSE TestAccContainerRegistry_requiresImport
=== RUN   TestAccContainerRegistry_basicManagedStandard
=== PAUSE TestAccContainerRegistry_basicManagedStandard
=== RUN   TestAccContainerRegistry_basicManagedPremium
=== PAUSE TestAccContainerRegistry_basicManagedPremium
=== RUN   TestAccContainerRegistry_basic2Premium2basic
=== PAUSE TestAccContainerRegistry_basic2Premium2basic
=== RUN   TestAccContainerRegistry_complete
=== PAUSE TestAccContainerRegistry_complete
=== RUN   TestAccContainerRegistry_update
=== PAUSE TestAccContainerRegistry_update
=== RUN   TestAccContainerRegistry_geoReplicationLocation
=== PAUSE TestAccContainerRegistry_geoReplicationLocation
=== RUN   TestAccContainerRegistry_networkAccessProfileIp
=== PAUSE TestAccContainerRegistry_networkAccessProfileIp
=== RUN   TestAccContainerRegistry_networkAccessProfileUpdate
=== PAUSE TestAccContainerRegistry_networkAccessProfileUpdate
=== RUN   TestAccContainerRegistry_policies
=== PAUSE TestAccContainerRegistry_policies
=== RUN   TestAccContainerRegistry_zoneRedundancy
=== PAUSE TestAccContainerRegistry_zoneRedundancy
=== RUN   TestAccContainerRegistry_geoReplicationZoneRedundancy
=== PAUSE TestAccContainerRegistry_geoReplicationZoneRedundancy
=== RUN   TestAccContainerRegistry_geoReplicationRegionEndpoint
=== PAUSE TestAccContainerRegistry_geoReplicationRegionEndpoint
=== RUN   TestAccContainerRegistry_anonymousPull
=== PAUSE TestAccContainerRegistry_anonymousPull
=== RUN   TestAccContainerRegistry_dataEndpoint
=== PAUSE TestAccContainerRegistry_dataEndpoint
=== RUN   TestAccContainerRegistry_networkRuleBypassOption
=== PAUSE TestAccContainerRegistry_networkRuleBypassOption
=== RUN   TestAccContainerRegistry_encryption
=== PAUSE TestAccContainerRegistry_encryption
=== CONT  TestAccContainerRegistry_basic
=== CONT  TestAccContainerRegistry_networkAccessProfileUpdate
=== CONT  TestAccContainerRegistry_anonymousPull
=== CONT  TestAccContainerRegistry_complete
=== CONT  TestAccContainerRegistry_geoReplicationRegionEndpoint
=== CONT  TestAccContainerRegistry_zoneRedundancy
=== CONT  TestAccContainerRegistry_policies
=== CONT  TestAccContainerRegistry_geoReplicationLocation
=== CONT  TestAccContainerRegistry_networkAccessProfileIp
=== CONT  TestAccContainerRegistry_basicManagedPremium
=== CONT  TestAccContainerRegistry_basic2Premium2basic
=== CONT  TestAccContainerRegistry_basicManagedStandard
=== CONT  TestAccContainerRegistry_networkRuleBypassOption
=== CONT  TestAccContainerRegistry_encryption
=== CONT  TestAccContainerRegistry_requiresImport
=== CONT  TestAccContainerRegistry_dataEndpoint
=== CONT  TestAccContainerRegistry_update
=== CONT  TestAccContainerRegistry_geoReplicationZoneRedundancy
--- PASS: TestAccContainerRegistry_requiresImport (163.02s)
--- PASS: TestAccContainerRegistry_basicManagedPremium (201.13s)
--- PASS: TestAccContainerRegistry_basic (201.68s)
--- PASS: TestAccContainerRegistry_basicManagedStandard (202.25s)
--- PASS: TestAccContainerRegistry_networkRuleBypassOption (224.62s)
--- PASS: TestAccContainerRegistry_zoneRedundancy (230.84s)
--- PASS: TestAccContainerRegistry_complete (233.59s)
--- PASS: TestAccContainerRegistry_geoReplicationRegionEndpoint (238.57s)
--- PASS: TestAccContainerRegistry_geoReplicationZoneRedundancy (242.86s)
--- PASS: TestAccContainerRegistry_basic2Premium2basic (260.78s)
--- PASS: TestAccContainerRegistry_anonymousPull (286.65s)
--- PASS: TestAccContainerRegistry_dataEndpoint (288.89s)
--- PASS: TestAccContainerRegistry_networkAccessProfileIp (300.72s)
--- PASS: TestAccContainerRegistry_policies (333.30s)
--- PASS: TestAccContainerRegistry_update (366.42s)
--- PASS: TestAccContainerRegistry_networkAccessProfileUpdate (371.22s)
--- PASS: TestAccContainerRegistry_encryption (402.55s)
--- PASS: TestAccContainerRegistry_geoReplicationLocation (570.29s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    570.325s

</pre>
</details>

**Review by stephybun — APPROVED** [review]
Thanks @magodo! Tests look good, we'll merge this just before 4.0 goes out 👍

**Pull request merged**
