### PR TITLE
New resources `gallery_application` `gallery_application_version`

### PR DESCRIPTION
**Pull request by myc2h6o**
- Adding support for Gallery Application. It is similar to Shared Image in Shared Image Gallery (Azure Compute Gallery), which can be configured for a VM/VMSS. 
- Doc: https://docs.microsoft.com/en-us/azure/virtual-machines/vm-applications
- Swagger:
  - [Gallery Application](https://github.com/Azure/azure-rest-api-specs/blob/182d92fc16cc51247ffd4e863dee28c77c6484d2/specification/compute/resource-manager/Microsoft.Compute/stable/2021-10-01/gallery.json#L845)
  - [Gallery Application Version](https://github.com/Azure/azure-rest-api-specs/blob/182d92fc16cc51247ffd4e863dee28c77c6484d2/specification/compute/resource-manager/Microsoft.Compute/stable/2021-10-01/gallery.json#L1087)

### CODE REVIEW

**Comment by myc2h6o** [comment]
Test result
image

**Review by katbyte — CHANGES_REQUESTED** [review]
test failure:

```
------- Stdout: -------
=== RUN   TestAccGalleryApplicationVersion_targetRegion
=== PAUSE TestAccGalleryApplicationVersion_targetRegion
=== CONT  TestAccGalleryApplicationVersion_targetRegion
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Gallery Application: (Application Name "acctest-app-220627192519280007" / Gallery Name "acctestsig220627192519280007" / Resource Group "acctest-compute-220627192519280007"): compute.GalleryApplicationsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."
        
        deleting Gallery Application: (Application Name
        "acctest-app-220627192519280007" / Gallery Name
        "acctestsig220627192519280007" / Resource Group
        "acctest-compute-220627192519280007"):
        compute.GalleryApplicationsClient#Delete: Failure sending request:
        StatusCode=0 -- Original Error: autorest/azure: Service returned an error.
        Status=<nil> Code="CannotDeleteResource" Message="Can not delete resource
        before nested resources are deleted."
--- FAIL: TestAccGalleryApplicationVersion_targetRegion (1181.51s)
FAIL
```
- the delete might be happening to soon/something might need to wait

**Comment by myc2h6o** [comment]
Updated test result
image

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM 🌤️

**Pull request merged**
