### PR TITLE
signalr - regenerate embedded sdk

### PR DESCRIPTION
**Pull request by mbfrahry**

### CODE REVIEW

**Review by katbyte — APPROVED** [review]

**Review by tombuildsstuff — APPROVED** [review]
LGTM - @jackofallops mind a sanity check?

**Comment by tombuildsstuff** [comment]
Added & Tested the state migrations here

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2021-11-12 at 15 16 38

**Review by mbfrahry — COMMENTED** [review]
LGTM!

**Pull request merged**
