### PR TITLE
Update machine_learning_compute_instance_resource.go

### LINKED ISSUE #14817: azurerm_machine_learning_compute_instance : issue on policy instance name
terraform version : i test with 0.14.6 & 0.15.5
================================================
terraform {
  required_version = ">= 0.13.0"
  required_providers {
    azurerm = ">= 2.85.0"
  }
}
================================================

hello everyone 
I created a terraform module which creates both an aml workspace, as well as a compute cluster or / and compute instances, the problem I have is when creating compute instances, an error on terraform plan :

` Error: invalid value for name (It can include letters, digits and dashes. It must start with a letter, end with a letter or digit, and be between 2 and 16 characters in length.)`

whereas when I try to create the same computed instance with the same name on the Azure portal, the naming rule is not the same

`Compute instance name must be between 3 to 24 characters long.`

my ressource on the module  
======================

```terraform
#########################################   Instance Compute AML     ######################################

resource "azurerm_machine_learning_compute_instance" "compute_instance" {
  count                         = var.create_compute_instance ? 1 : 0
  **name                          = var.compute_instance_name**
  location                      = var.location
  machine_learning_workspace_id = var.create_aml_workspace ? azurerm_machine_learning_workspace.main[0].id : var.personal_aml_workspace_id
  virtual_machine_size          = var.compute_instance_size
  subnet_resource_id            = var.compute_instance_subnet_id
  authorization_type            = "personal" # only Possible values
  tags                          = var.tags

  ssh {
    #NOTE :  the user name is always : azureuser (obligated by azureML)
    public_key = var.create_compute_instance ? module.mod-tls-sshkey.public_key_openssh : null
  }

  identity {
    type         = var.create_compute_instance ? "SystemAssigned" : null #  Possible values are SystemAssigned, UserAssigned and SystemAssigned,UserAssigned
    identity_ids = var.create_compute_instance ? var.compute_instance_identity_ids : null

  }
  assign_to_user {
    object_id = var.create_compute_instance ? var.compute_instance_assign_to_user_id : null
    tenant_id = var.create_compute_instance ? var.tenant_id : null
  }
}
```

### PR DESCRIPTION
**Pull request by aziz-zaroual**
hello

I push this Pull request in order to correct the problem that I opened on the case :  #14817 

Fixes #14817

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
Thanks @aziz-zaroual - LGTM 🏗️

**Comment by katbyte** [comment]
@aziz-zaroual - could you please run `make fmt` and commit the fixes?

**Comment by aziz-zaroual** [comment]
hello @katbyte , make fmt ==> DONE

**Comment by katbyte** [comment]
@aziz-zaroual - are you on a older version of go? it seems like its updated way more files then should be for make fmt.

we are on 1.17.5

**Comment by aziz-zaroual** [comment]
@katbyte hello , i have the last version , i dont know what happened `go version go1.17.6 linux/amd64`

**Pull request merged**
