### PR TITLE
`azurerm_system_center_virtual_machine_manager_server` - add `StateRefreshFunc` for checking the sync status

### PR DESCRIPTION
**Pull request by neil-yechenwei**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description
Though azurerm_system_center_virtual_machine_manager_server is created successfully. But we can't use azurerm_system_center_virtual_machine_manager_inventory_items to get the list of Inventory Items immediately since Inventory Items are still in sync. Service team confirmed that it's expected since the backend operator creates CRD (Custom Resource Definitions) for all the existing resource from onPrem and create InventoryItem resources which takes some time after PUT VMM Server operation. So it's not a bug but it takes some while to populate the inventory item resource. Service team also confirmed that the sync would definitely be completed within ten minutes. So we just need to set a timeout of 10 minutes and check the inventory quantity continuously every minute for 10 times. If the quantity doesn't change, then we consider the sync to be complete.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

```
--- PASS: TestAccSystemCenterVirtualMachineManagerServerSequential/scvmmServer/basic (357.61s)
--- PASS: TestAccSystemCenterVirtualMachineManagerServerSequential/scvmmServer/requiresImport (295.43s)
--- PASS: TestAccSystemCenterVirtualMachineManagerServerSequential/scvmmServer/complete (352.76s)
--- PASS: TestAccSystemCenterVirtualMachineManagerServerSequential/scvmmServer/update (424.02s)
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_system_center_virtual_machine_manager_server` - add `StateRefreshFunc` for checking the sync status

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
reated: https://github.com/hashicorp/terraform-provider-azurerm/pull/25429#discussion_r1609551673

**Comment by catriona-m** [comment]
> Related: [#25429 (comment)](https://github.com/hashicorp/terraform-provider-azurerm/pull/25429#discussion_r1609551673)

Hi @neil-yechenwei - just checking in to see if there any updates about the concerns referenced in the above comment? Thanks

**Comment by neil-yechenwei** [comment]
@catriona-m , service team has replied that thread.

**Review by katbyte — APPROVED** [review]
LGTM 🔍

**Pull request merged**
