### PR TITLE
`azurerm_storage_share` - Add new enum `Premium` for `access_tier`

### LINKED ISSUE #16834: azurerm_storage_share_file : access_tier = "Premium" -> null
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

azurerm_storage_share_file

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "main" {
  name                     = var.storage_account_name
  resource_group_name      = var.storage_account_rg
  location                 = var.storage_account_location
  account_tier             = var.storage_account_tier
  account_replication_type = var.storage_account_replication_type
  account_kind             = var.storage_account_kind
  tags                     = var.storage_account_tags
  lifecycle {
    ignore_changes = [azure_files_authentication]
  }
}


resource "azurerm_storage_share" "main" {
  for_each             = var.shares
  name                 = each.value["share_name"]
  enabled_protocol     = "SMB"
  storage_account_name = azurerm_storage_account.main.name
  quota                = each.value["share_quota"]
}
```

### Debug Output/Panic Output

```shell
# module.test-storage-accounts-smb["test-recordings"].azurerm_storage_share.main["backup"] will be updated in-place
  ~ resource "azurerm_storage_share" "main" {
      - access_tier          = "Premium" -> null
        id                   = "https://xxxxxxxx.file.core.windows.net/backup"
        name                 = "backup"
        # (6 unchanged attributes hidden)
    }

  # module.test-storage-accounts-smb["test-recordings"].azurerm_storage_share.main["recordings"] will be updated in-place
  ~ resource "azurerm_storage_share" "main" {
      - access_tier          = "Premium" -> null
        id                   = "https://xxxxxxxx.file.core.windows.net/recordings"
        name                 = "recordings"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 2 to change, 0 to destroy
```

### Expected Behaviour

Over the last couple of days, Terraform has tried to change "access_tier" on the storage account share. As far as I can see from the Terraform docs, this isn't a parameter. 

However when try to add

``` hcl
resource "azurerm_storage_share" "main" {
  for_each             = var.shares
  name                 = each.value["share_name"]
  enabled_protocol     = "SMB"
  storage_account_name = azurerm_storage_account.main.name
  quota                = each.value["share_quota"]
  access_tier          = "Premium"
}
```

I get 'Error: expected access_tier to be one of [Hot Cool TransactionOptimized], got Premium'

So I changed to Hot 

``` hcl
resource "azurerm_storage_share" "main" {
  for_each             = var.shares
  name                 = each.value["share_name"]
  enabled_protocol     = "SMB"
  storage_account_name = azurerm_storage_account.main.name
  quota                = each.value["share_quota"]
  access_tier          = "Hot"
}
```

But this tries to change the access_tier to "Hot" rather than "Premium" which still doesn't feel right. 

```shell
module.test-storage-accounts-smb["test-recordings"].azurerm_storage_share.main["backup"] will be updated in-place
  ~ resource "azurerm_storage_share" "main" {
      ~ access_tier          = "Premium" -> "Hot"
        id                   = "[https://xxxxxxxxxxxxxxx.file.core.windows.net/backup"](https://xxxxxxxxxx.file.core.windows.net/backup%22)
        name                 = "backup"
        # (6 unchanged attributes hidden)
    }
```

### Actual Behaviour

As above

### Steps to Reproduce

terraform apply

### Important Factoids

None

### References

This has only started happening over the last couple of days.

### PR DESCRIPTION
**Pull request by magodo**
Fixes #16834.

Besides, making the `access_tier` computed so that it doesn't fail the existing tests (otherwise, should we change it to required instead?).

## Test

```shell
❯ TF_ACC=1 go test -timeout=60m -v -run='TestAccStorageShare_accessTier|TestAccStorageShare_basic' ./internal/services/storage
=== RUN   TestAccStorageShare_basic
=== PAUSE TestAccStorageShare_basic
=== RUN   TestAccStorageShare_accessTierStandard
=== PAUSE TestAccStorageShare_accessTierStandard
=== RUN   TestAccStorageShare_accessTierPremium
=== PAUSE TestAccStorageShare_accessTierPremium
=== CONT  TestAccStorageShare_basic
=== CONT  TestAccStorageShare_accessTierPremium
=== CONT  TestAccStorageShare_accessTierStandard
--- PASS: TestAccStorageShare_basic (148.42s)
--- PASS: TestAccStorageShare_accessTierPremium (154.99s)
--- PASS: TestAccStorageShare_accessTierStandard (194.76s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       194.770s
```

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@magodo what's the need for making this computed? that would indicate a bug we need to fix - does this field now always require/return a value?

**Comment by magodo** [comment]
@tombuildsstuff The `access_tier` can be absent in the request, but will be returned in the response. Instead, shall we just keep it optional and give it a default value?

**Comment by tombuildsstuff** [comment]
@magodo my guess is like everything else in Storage, the default value for this field changes depending on which SKU you're using for the Storage Account - so I don't think we can reasonably set a default value for this. In this case we should remove `Computed: true` here, since the users config should match whatever the default is for this field

**Comment by magodo** [comment]
@tombuildsstuff Then shall we also update the testcases to add the `access_tier` to at least pass the test? Arguably, I think we shall change it to required in this case.

**Comment by danielino** [comment]
hello, any news on this?

**Review by katbyte — APPROVED** [review]
LGTM 🥫

**Pull request merged**
