### PR TITLE
`azurerm_synapse_spark_pool` - set `node_count` in read if `auto_scale` is disabled

### PR DESCRIPTION
**Pull request by ms-henglu**
This PR only sets `node_count` in read func if the `auto_scale` is disabled. Because we have customer reported issues that the GET response of spark pool might have both `node_count` and `auto_scale` enabled, this is an API issue and we've asked the service team to investigate, but this PR will mitigate the issue.

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

```
=== RUN   TestAccSynapseSparkPool_complete
=== PAUSE TestAccSynapseSparkPool_complete
=== CONT  TestAccSynapseSparkPool_complete
--- PASS: TestAccSynapseSparkPool_complete (1537.79s)

```

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_resource` - support for the `thing1` property [GH-00000]

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
@ms-henglu could you elaborate on the issue that this is trying to solve?

**Comment by ms-henglu** [comment]
@stephybun - Sure. There's an issue on the API side that both `autoScale` and `nodeCount` are returned in the response. But in the config, only `node_count` is specified, then it causes plan-diff and couldn't resolve it.

**Comment by stephybun** [comment]
@ms-henglu what is the plan diff? The value of the `node_count` changes?

**Comment by ms-henglu** [comment]
> @ms-henglu what is the plan diff? The value of the `node_count` changes?

Yes, `- node_count = 3 -> null` and the auto_scale doesn't change.

**Review by stephybun — CHANGES_REQUESTED** [review]
Based on the behaviour of the property `node_count` should probably have `Computed` set on it instead of not setting it if auto scale is enabled. Can you please make that change?

**Comment by ms-henglu** [comment]
Hi @stephybun , I've confirmed with service team that:

1. When edit this resource from Synapse studio, a nodeCount will be added even it's not configured. So the resource might have both nodeCount and autoScale configured. But this is a bug and I'll ask the team to fix it.
2. The API will honor autoScale when both nodeCount and autoScale are configured.

So I think the node_count should not be marked as computed? I think we should ignore it when reading the resource, just like what it does in the create/update.

**Comment by stephybun** [comment]
@ms-henglu there are very few cases in the provider where we only conditionally set something into state based on the value of another property. The cases that come to mind are workarounds to prevent breaking changes.

If this is expected to be fixed in the API, then the workaround for the moment is for the user to apply `ignore_changes` to `node_count` or for us to set it to `Computed`.

**Comment by ms-henglu** [comment]
Thanks @stephybun ! I've marked this field as computed, please take another look, thanks!

**Review by stephybun — APPROVED** [review]
As an aside we're trying to keep track of remaining or introduced O+C properties in the provider using comments with the format `// NOTE: O+C because of reason xyz this property needs to be Computed` so I added that to your PR explaining the API behaviour.

LGTM 👍

**Pull request merged**
