### PR TITLE
azurerm_app_service_public_certificate - Fix "root resource absent" error ( #18164)

### LINKED ISSUE #18164: azurerm_app_service_public_certificate - Root resource was present, but now absent.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

3.20.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_public_certificate

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "= 3.20.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_windows_web_app" "this" {
  name                = "mytestapp01"
  resource_group_name = "testrg"
}

resource "azurerm_app_service_public_certificate" "this" {
  for_each  = fileset(path.module, "*.cer")
  resource_group_name   = data.azurerm_windows_web_app.this.resource_group_name
  app_service_name      = data.azurerm_windows_web_app.this.name
  certificate_name      = each.value
  certificate_location  = "CurrentUserMy" 
  blob                  = filebase64("${path.module}/${each.value}")
}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_app_service_public_certificate.this["testcertcer"], provider
│ "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

Public certs added to the web app with no error.

### Actual Behaviour

Public certs added to the web app with "Root resource was present, but now absent." error.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by lstemplinger**
The current version of the provider makes two API requests to create/update a certificate. After also running into the "Root resource was present, but now absent" reported in #18164, I noticed that sometimes the initial PUT request succeeds,  but the GET immediately after returns 404, triggering the removal logic in `resourceAppServicePublicCertificateRead`.

Removing the second request fixed the error for me. Since  the PUT response already contains all required info, the only downside I can see is some duplicate code between `Read` and `CreateUpdate`.

Fixes  #18164

### CODE REVIEW

**Comment by jackofallops** [comment]
Hi @lstemplinger - Thanks for this PR.
Unfortunately we need to set the state in the Read function, and not the Create. Setting the values from the Create (PUT) would bypass Terraform's ability to detect change. Setting the state in the Read allows us to compare the values configured to the values the resource actually has set in order to detect change, and ensure the Apply has succeeded or present the diff if not. 

Based on this, I'm going to close this PR for now, but I'll look into the issue myself as I suspect the API call is returning before the resource is actually created, so some form of wait/check that the `CreateOrUpdatePublicCertificate` call has actually completed successfully.

Thanks again for the contribution!

**Comment by lstemplinger** [comment]
Hi @jackofallops ,
thanks for looking into this. In case it helps with debugging: I consistently get the error when running terraform in our CI, which uses runners hosted in AKS, but could never reproduce it when running on my machine.

Do you know some piece of docs/code that I could look at to understand why Create vs Read makes a difference here? I don't see any comparison logic in Read that would be skipped, and as far as I understand PUT and GET return the same cert info. Not trying to argue since you know this stuff much better than me. I'd just like to understand what I missed.

**Comment by jackofallops** [comment]
Thanks for understanding @lstemplinger 

The [Developer Docs for provider development](https://developer.hashicorp.com/terraform/tutorials/providers) cover a lot of this detail, but the separation of create and read is fundamentally a check that what we send is accepted and applied correctly, so that during the apply we can react appropriately if something is not as we requested. By setting the state in the Create, and not running the Read we skip that validation and the state would just show our configuration values. If the request was not executed entirely correctly, the state and the resource would be out of sync. The best case scenario there is that a subsequent action (refresh / plan / apply) highlights this on Read. In other cases,  if the resource is part of a dependency for another item, that could have a knock on effect throughout the rest of the configuration potentially leading to broken resources or perhaps even data loss elsewhere in extreme cases.  Hope that helps!

Thanks again!

**Comment by lstemplinger** [comment]
Thank you, that explanation definitely helped.

**Pull request closed without merging**
