### PR TITLE
fix private link fast path in Express Route Connection settings

### LINKED ISSUE #26039: Express route connection - InvalidJson: Could not find member enablePrivateLinkFastPath
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.104.2

### Affected Resource(s)/Data Source(s)

azurerm_express_route_connection

### Terraform Configuration Files

```hcl
# plan output

# module.platform_foundation.azurerm_express_route_connection.vwan_express_route_connection["avs"] will be updated in-place
  ~ resource "azurerm_express_route_connection" "vwan_express_route_connection" {
      ~ enable_internet_security             = false -> true
        id                                   = "valid ID"
        name                                 = "sikg-cf-prod-exprc-avs"
        # (6 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }


# tf code

resource "azurerm_express_route_connection" "vwan_express_route_connection" {
  provider                         = azurerm.connectivity
  for_each                         = var.connectivity_express_route_connections
  express_route_circuit_peering_id = length(split("/", each.value.express_route_circuit)) > 1 ? "${each.value.express_route_circuit}/peerings/AzurePrivatePeering" : azurerm_express_route_circuit_peering.express_route_peering[each.key].id
  express_route_gateway_id         = azurerm_express_route_gateway.vwan_express_route_gateway[each.value.region].id
  name                             = "${var.customer}-${var.project}-${var.environment}-exprc-${each.key}"
  authorization_key                = length(split("/", each.value.express_route_circuit)) > 1 ? each.value.authorization_key : azurerm_express_route_circuit_authorization.authorization[each.key].authorization_key
  enable_internet_security         = each.value.enable_internet_security
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Express Route Connection: (Name "sikg-cf-prod-exprc-avs" / Express Route Gateway Name "sikg-cf-prod-ergw-euw" / Resource Group "sikg-cf-prod-rg-connectivity"): network.ExpressRouteConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJson","message":"Could not find member 'enablePrivateLinkFastPath' on object of type 'ExpressRouteConnectionProperties'. Path 'properties.enablePrivateLinkFastPath', line 1, position 163."}]
│ 
│   with module.platform_foundation.azurerm_express_route_connection.vwan_express_route_connection["avs"],
│   on .terraform/modules/platform_foundation/202_expressRoute.tf line 48, in resource "azurerm_express_route_connection" "vwan_express_route_connection":
│   48: resource "azurerm_express_route_connection" "vwan_express_route_connection" {
```

### Expected Behaviour

The express route connection should have internet security enabled when apply is finshed. 

### Actual Behaviour

Error as it is given in the error output is returned. For azurerm v3.99 it worked as expected.

### Steps to Reproduce

Take an existing express route connection, as given above and change the value for enable_internet_security to true. 

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by aochsner**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

Attempting to fix #26039

Unfortunately I'm not able to test this as I don't have an ExpressRoute connection configured in my personal Azure subscription and am not allowed to test inside my company's subscriptions where the ExpressRoutes live and we are having the same issues/workaround in the above issue.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_express_route_connection` - fix enablePrivateLinkFastPath json

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26039

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @aochsner, thanks for opening this PR but unfortunately, this isn't going to fix your issue. The issue is coming from what we are sending to Azure but this fix is changing something we're receiving from Azure.

**Comment by aochsner** [comment]
> Hey @aochsner, thanks for opening this PR but unfortunately, this isn't going to fix your issue. The issue is coming from what we are sending to Azure but this fix is changing something we're receiving from Azure.

duh sorry you're right...

**Comment by aochsner** [comment]
> Hey @aochsner, thanks for opening this PR but unfortunately, this isn't going to fix your issue. The issue is coming from what we are sending to Azure but this fix is changing something we're receiving from Azure.

But I'm also equally confused why it's broken...

**Comment by mbfrahry** [comment]
I am as well! It's going to take some time to dig into what is happening. Did you want to keep trying or should we close this until we can dig more into it?

**Comment by stephybun** [comment]
Thanks for having a go at fixing this @aochsner. A newer PR https://github.com/hashicorp/terraform-provider-azurerm/pull/26928 has been opened to address the same issue, since it's a more complete attempt I'm going to close this in favour of #26928.

**Pull request closed without merging**
