### PR TITLE
`azurerm_container_app:` updating to API Version 2022-11-01-preview

### PR DESCRIPTION
**Pull request by Phiph**
#21133 

In the Azure RM there is support for TCP connections. I'm no GO engineer, but I think I've done the right steps to reference the updated version allowing us to use the `tcp` type for `transport`. From what I can tell in the code, the schema references the azure-go-sdk schemas. 

I'll be upfront, I'm not too sure how to test using go, so any resources to help unit test this change would be great!

### CODE REVIEW

**Comment by Phiph** [comment]
I've noticed the build failures, thanks for triggering them.

I'll try and run the commands locally and learn a bit of GO as I go!

**Comment by Joey40** [comment]
Keeping an eye on this PR, it would fix the same issue for me.

**Comment by Phiph** [comment]
I've updated the api to 2022-11-01-preview, as I've found a Pandora PR that has been opened recently

https://github.com/hashicorp/pandora/pull/2734

**Comment by tombuildsstuff** [comment]
FYI, the SDK for `containerapps` @ `2022-11-01-preview` is now available within `hashicorp/go-azure-sdk`: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/containerapps/2022-11-01-preview

**Comment by Joey40** [comment]
> FYI, the SDK for `containerapps` @ `2022-11-01-preview` is now available within `hashicorp/go-azure-sdk`: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/containerapps/2022-11-01-preview

Did that make it into the latest provider? I don't see it in the release notes.

**Comment by tombuildsstuff** [comment]
hey @Phiph 

Since [there's now a new Stable version of this API available in `hashicorp/go-azure-sdk`](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/containerapps/2023-05-01) and this PR is targeting the earlier preview version, I've opened #22804 which updates the `containerapps` package to use this newer Stable API Version `2023-05-01`.

Once this has been merged, it should be possible to support the new functionality within this API version (which looks to be `identity`, `keyVaultUri` for secrets, in addition to TCP connections/#21133). However since #22804 updates `containerapps` to use the latest stable version of this API, whilst I'd like to thank you for this contribution, I'm going to close this PR in favour of #22804 - and once that's been merged it should be possible to support the new functionality in this API version.

Thanks!

**Comment by Phiph** [comment]
Hey @tombuildsstuff no problem, thanks for the update!

**Pull request closed without merging**
