### PR TITLE
`azurerm_kubernetes_cluster` - always set addon if enabled

### PR DESCRIPTION
**Pull request by ms-henglu**
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/17843

image

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@ms-henglu unfortunately setting these all of the time would breaks the use of `ignore_changes` for the addons - so we'd instead need to retrieve the current list of addons from the API and conditionally update these instead.

However, #17843 is ultimately an Azure Policy issue rather than a Terraform bug, the Azure Policy API should be passing through the (validly/previously configured) `AzurePolicy` addon to the Azure Policy being tested - so can you reach out to the Azure Policy team about that?

Thanks!

**Comment by piotrgwiazda** [comment]
@tombuildsstuff  @ms-henglu 
If a subsequent update on AKS will be missing the azure policy addon, isn't it going to be removed from the cluster?

Check this line:
https://github.com/hashicorp/terraform-provider-azurerm/blob/6fafede2c501208d64e4b0007442a0cabf3ac910/internal/services/containers/kubernetes_cluster_resource.go#L1344

If **any single** of the addons change then **the whole** section of addonProfiles is overwritten:
`existing.ManagedClusterProperties.AddonProfiles = *addonProfiles`

I think the maps should be merged or only the changed addon sections (map keys) should be updated.

**Comment by tombuildsstuff** [comment]
@piotrgwiazda the Update is done via a PATCH API, if the addon isn't specified then it won't be updated (or removed)

**Comment by piotrgwiazda** [comment]
@tombuildsstuff  the `collectKubernetesAddons` returns Terraform configuration to the `addOns` map. Then `expandKubernetesAddOns` creates JSON API representation based on the `addOns` map.
Then the whole section of JSON is overriden `existing.ManagedClusterProperties.AddonProfiles = *addonProfiles`
The existing `AddonProfiles` is not taken into account.

**Pull request closed without merging**
