### PR TITLE
`azurerm_mssql_managed_instance` : Fix acctests failure

### PR DESCRIPTION
**Pull request by sinbai**
The following acctests failed due to differences in routes settings after applying the test step and performing a `terraform refresh`. 

Failed test cases:

```
TestAccMsSqlManagedInstanceFailoverGroup_update,
TestAccMsSqlManagedInstance_premium,
TestAccMsSqlManagedInstance_dnsZonePartner,
TestAccMsSqlManagedInstance_multipleDnsZonePartners
```

Test cases fail in TC: https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MSSQLMANAGEDINSTANCE/133104?hideTestsFromDependencies=false&expandBuildDeploymentsSection=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false&expandBuildChangesSection=true

After comparing the routes configured by TF and returned by API, it was found that the routes returned by the API at the primary location (westeurope) and the secondary location (francecentral) are different. So, submit this PR to configure routes individually based on the location configuration to fix test case failure.

Test results in TC:
https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MSSQLMANAGEDINSTANCE/135862?buildTab=tests

Notes:
The reason why you explicitly specify the following "provider" block in testcases instead of specifying it in the [template ](https://github.com/hashicorp/terraform-provider-azurerm/blob/55f7fdd8696fbc80e3cfffba4fe736feb6244f80/internal/services/mssqlmanagedinstance/mssql_managed_instance_resource_test.go#L1655) is because the [template ](https://github.com/hashicorp/terraform-provider-azurerm/blob/55f7fdd8696fbc80e3cfffba4fe736feb6244f80/internal/services/mssqlmanagedinstance/mssql_managed_instance_transparent_data_encryption_resource_test.go#L365)method is also called in the test case `TestAccMsSqlManagedTransparentDataEncryption_keyVaultSystemAssignedIdentity`, which results in a  "Duplicate provider configuratio" error.
 

```
provider "azurerm" {
  features {}
}
```

### CODE REVIEW

**Comment by katbyte** [comment]
@sinbai - is this ready for review?

**Comment by sinbai** [comment]
> @sinbai - is this ready for review?

Yes.

**Review by katbyte — CHANGES_REQUESTED** [review]
Running this we are still getting failured:

```
------- Stdout: -------
=== RUN   TestAccMsSqlManagedInstance_identity
=== PAUSE TestAccMsSqlManagedInstance_identity
=== CONT  TestAccMsSqlManagedInstance_identity
    testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Resource Group "acctestRG1-sql-240506181806757163": the Resource Group still contains Resources.
        
        Terraform is configured to check for Resources within the Resource Group when deleting the Resource Group - and
        raise an error if nested Resources still exist to avoid unintentionally deleting these Resources.
        
        Terraform has detected that the following Resources still exist within the Resource Group:
        
        * `/subscriptions/*******/resourceGroups/acctestRG1-sql-240506181806757163/providers/Microsoft.Network/networkIntentPolicies/mi_default_15814648-afc9-4bef-89d9-3e41f6fdd11e_10-0-0-0-24_Update`
        
        This feature is intended to avoid the unintentional destruction of nested Resources provisioned through some
        other means (for example, an ARM Template Deployment) - as such you must either remove these Resources, or
        disable this behaviour using the feature flag `prevent_deletion_if_contains_resources` within the `features`
        block when configuring the Provider, for example:
        
        provider "azurerm" {
          features {
            resource_group {
              prevent_deletion_if_contains_resources = false
            }
          }
        }
        
        When that feature flag is set, Terraform will skip checking for any Resources within the Resource Group and
        delete this using the Azure API directly (which will clear up any nested resources).
        
        More information on the `features` block can be found in the documentation:
        https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block
        
        
--- FAIL: TestAccMsSqlManagedInstance_identity (5131.98s)
FAIL
```

**Comment by sinbai** [comment]
> Running this we are still getting failured:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccMsSqlManagedInstance_identity
> === PAUSE TestAccMsSqlManagedInstance_identity
> === CONT  TestAccMsSqlManagedInstance_identity
>     testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
>         
>         Error: deleting Resource Group "acctestRG1-sql-240506181806757163": the Resource Group still contains Resources.
>         
>         Terraform is configured to check for Resources within the Resource Group when deleting the Resource Group - and
>         raise an error if nested Resources still exist to avoid unintentionally deleting these Resources.
>         
>         Terraform has detected that the following Resources still exist within the Resource Group:
>         
>         * `/subscriptions/*******/resourceGroups/acctestRG1-sql-240506181806757163/providers/Microsoft.Network/networkIntentPolicies/mi_default_15814648-afc9-4bef-89d9-3e41f6fdd11e_10-0-0-0-24_Update`
>         
>         This feature is intended to avoid the unintentional destruction of nested Resources provisioned through some
>         other means (for example, an ARM Template Deployment) - as such you must either remove these Resources, or
>         disable this behaviour using the feature flag `prevent_deletion_if_contains_resources` within the `features`
>         block when configuring the Provider, for example:
>         
>         provider "azurerm" {
>           features {
>             resource_group {
>               prevent_deletion_if_contains_resources = false
>             }
>           }
>         }
>         
>         When that feature flag is set, Terraform will skip checking for any Resources within the Resource Group and
>         delete this using the Azure API directly (which will clear up any nested resources).
>         
>         More information on the `features` block can be found in the documentation:
>         https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block
>         
>         
> --- FAIL: TestAccMsSqlManagedInstance_identity (5131.98s)
> FAIL
> ```

Hi @katbyte the purpose of this PR is to fix the following failure in the [latest main branch test](https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MSSQLMANAGEDINSTANCE/143834?hideProblemsFromDependencies=false&expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true) of TC, taking test case `TestAccMsSqlManagedInstanceFailoverGroup_update` as an example:
image.

For the above test case `TestAccMsSqlManagedInstance_identity` failure, I have filed an [API issue](https://github.com/Azure/azure-rest-api-specs/issues/27991) to track it as it is an API issue.

We can see that in the [TC test](https://hashicorp.teamcity.com/buildConfiguration/TF_AzureRM_AZURERM_SERVICE_PUBLIC_MSSQLMANAGEDINSTANCE/144745?buildTab=tests&expandedTest=build%3A%28id%3A144745%29%2Cid%3A2000000005) containing this PR, the test results of `TestAccMsSqlManagedInstanceFailoverGroup_update` are the same as the above `TestAccMsSqlManagedInstance_identity`, which is caused by the API issue. I assume for this case TF should not add `prevent_deletion_if_contains_resources = false` but wait for RP team fix.

**Comment by katbyte** [comment]
current all tests are failing:
image

**Comment by stephybun** [comment]
Closing since there's been no activity for a while.

**Pull request closed without merging**
