### PR TITLE
Deprecate Resource: azurerm_cosmosdb_notebook_workspace

### PR DESCRIPTION
**Pull request by neil-yechenwei**
Service team confirmed that the CosmoDb Notebook Workspace has been deprecated and currently service API doesn't allow to create new resource anymore so that the existing TCs failed. And they also confirmed they’re not planning any other APIs to replace this feature as of now.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@neil-yechenwei is there a public deprecation message we can link to for this?

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , I will check with service team.

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , service team confirmed they haven't public deprecation message yet but they provided the justification, and they agree to mark this feature as deprecated right now in TF.

Justification:
```
1. Cosmos DB notebooks (the feature itself) is not deprecated and will return: https://learn.microsoft.com/en-us/azure/cosmos-db/notebooks-faq
2. However, Cosmos DB notebooks feature no longer uses the permanent notebooks workspace being referred to [here](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/notebook.json#L131) (have since moved to temporary notebooks workspaces which are short-lived <1 hour).
o	As a result, no longer need to have the public surface in the RP for such resources
o	It does plan to eventually deprecate the RP notebooks workspace surface area (not the notebooks overall feature, just the RP surface area), but don’t have a timeline for that yet.
```

**Comment by katbyte** [comment]
@neil-yechenwei - could we add this information to the deprecation message/docs for the resource? please include the https://learn.microsoft.com/en-us/azure/cosmos-db/notebooks-faq link so users have context

**Comment by neil-yechenwei** [comment]
@katbyte , thanks for your comment. I've added deprecation message in resource doc.

**Pull request merged**
