### PR TITLE
add length check to avoid panic

### PR DESCRIPTION
**Pull request by calebak404**
add length check to match linux_web_app to avoid potential panic in windows_web_app

linux change done in #21328

### CODE REVIEW

**Comment by calebak404** [comment]
Issue: #23739

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @calebak404.

There are some compilation failures showing up in the GitHub Actions - if you can fix those up we can take another look at this.

**Comment by calebak404** [comment]
I've amended to address those issues.

**Comment by calebak404** [comment]
Hi, are there any other changes I should be making to ensure this is a successful PR?

**Comment by calebak404** [comment]
Closing this since the fixes were applied in #23836 and #23812

**Pull request closed without merging**
