### PR TITLE
APIM : investigate random deletion failures in accTests

### PR DESCRIPTION
**Pull request by sinbai**
Note: Investigate random deletion failures in APIM accTest.

### CODE REVIEW

**Comment by stephybun** [comment]
@sinbai the APIM tests are looking quite unhealthy, making it difficult to review and merge APIM PRs, do you any updates here or is there another PR open with the changes needed to fix these?

**Comment by sinbai** [comment]
> the APIM tests are looking quite unhealthy, making it difficult to review and merge APIM PRs, do you any updates here or is there another PR open with the changes needed to fix these?

Hi @stephybun I'm very sorry that this issue has not been resolved yet, although I have been following up. So far, I have communicated with the Resource service and APIM service teams. At present, it seems that the problem may be on the APIM team's side, and the APIM service team is under investigation. I will always pay attention to the latest updates of the APIM service team and will let you know once the result are available.

**Comment by stephybun** [comment]
Thank you for the update @sinbai!

**Comment by sinbai** [comment]
Hi @stephybun I received a response from the APIM service team. The result of their investigation was that there was an APIM bug. The summary of this bug is that after sending a request to delete the APIM service, when APIM Get_API returns 404, the deletion may not actually be completed.

Because the long-running deletion operation of PandoraSDK determines whether the deletion is completed by calling Get_API to return 404, a large number of tests failed.

The service team will track fixing this bug ETA is March 2024. Before that, I have not thought of a suitable solution to mitigate the failure of test cases. What advice do you have on this?

**Comment by katbyte** [comment]
@sinbai - as this is a service bug and there is not much we can do i think we can close this and just wait for the service fix in a month

**Comment by sinbai** [comment]
> as this is a service bug and there is not much we can do i think we can close this and just wait for the service fix in a month

Thanks for your feedback @katbyte.

**Comment by katbyte** [comment]
@sinbai - is this ready for review?

**Comment by sinbai** [comment]
> @sinbai - is this ready for review?

The reason for reopening this PR is that I received feedback from the service team that this issue has been fixed on API v2023-05-01-preview. However, after testing, it was discovered that it was not actually fixed on this preview version. We are still in communicating. So, I would close this test PR.

**Pull request closed without merging**
