### PR TITLE
`azurerm_cognitive_deployment` - Add support for `VersionUpgradeOption`

### LINKED ISSUE #22501: azurerm_cognitive_deployment not able to deploy latest version(0613) of gpt3.5
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.0

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "uksouth"
}

resource "azurerm_cognitive_account" "example" {
  name                = "example-ca"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "OpenAI"
  sku_name            = "S0"
}

resource "azurerm_cognitive_deployment" "example" {
  name                 = "example-cd"
  cognitive_account_id = azurerm_cognitive_account.example.id
  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0613"
  }

  scale {
    type = "Standard"
  }
}
```

### Debug Output/Panic Output

When i used newer version 0613 on gpt-35-turbo it looks like below (perfect) but when i checked in the portal the version is pointing as old (0301). I believe somehow while creating it took the default version and not the newer version

```
+ model {
          + format  = "OpenAI"
          + name    = "gpt-35-turbo"
          + version = "0613"
        }

      + scale {
          + capacity = 120
          + type     = "Standard"
        }
```

I manually updated the version on the portal, and ran the terraform again now it shows like below

```
      ~ model {
            name    = "gpt-35-turbo"
          ~ version = "0301" -> "0613"
            # (1 unchanged attribute hidden)
        }
```

but I got the error like Error: doesn't support update (I can able to update the version from the portal successfully)

#References

https://github.com/hashicorp/terraform-provider-azurerm/issues/22198#issuecomment-1625004948

### PR DESCRIPTION
**Pull request by lonegunmanb**
Add support for VersionUpgradeOption so the users can set the model's version they like. This pr should fix #22501 .

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @lonegunmanb, this change is a good start but we should write a test for this as well. It also looks like the API defaults this value to `OnceNewDefaultVersionAvailable` so we'll want to account for that as well

**Comment by lonegunmanb** [comment]
Roger that, will do

**Comment by lonegunmanb** [comment]
Hi @mbfrahry I have to change the model used in e2e test since the original model is [deprecated](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/legacy-models#gpt-3) now. Would you please give this pr a review? Thanks!

**Comment by manicminer** [comment]
@lonegunmanb Thanks for updating the tests. It looks like the model got reverted to the older one when `main` got merged in, was this intentional?

**Comment by lonegunmanb** [comment]
> @lonegunmanb Thanks for updating the tests. It looks like the model got reverted to the older one when `main` got merged in, was this intentional?

Whoops... My bad, I must mess it up when I tried to merge the code, thanks for pointing out.

**Comment by lonegunmanb** [comment]
Hi @manicminer @mbfrahry I've rebased the pr to the latest main branch, and I've upgraded the model version in the e2e test so all acc tests could pass on my side. Would you please give this r another review? Thanks!

**Comment by manicminer** [comment]
Thanks @lonegunmanb. I'm getting a test failure with a 400 response.

Screenshot 2023-07-20 at 00 06 24

**Comment by lonegunmanb** [comment]
I'll see what I can do to solve this testing issue.

**Comment by lonegunmanb** [comment]
Hi @manicminer I've tried to switch the region but still got no luck. I've checked the team city's history, the same errors occurred before on the main branch. The tests got the green light on our testing subscription:

```text
=== RUN   TestAccCognitiveDeploymentSequential
--- PASS: TestAccCognitiveDeploymentSequential (784.22s)
=== RUN   TestAccCognitiveDeploymentSequential/deployment
    --- PASS: TestAccCognitiveDeploymentSequential/deployment (784.22s)
=== RUN   TestAccCognitiveDeploymentSequential/deployment/basic
        --- PASS: TestAccCognitiveDeploymentSequential/deployment/basic (262.07s)
=== RUN   TestAccCognitiveDeploymentSequential/deployment/requiresImport
        --- PASS: TestAccCognitiveDeploymentSequential/deployment/requiresImport (269.03s)
=== RUN   TestAccCognitiveDeploymentSequential/deployment/complete
        --- PASS: TestAccCognitiveDeploymentSequential/deployment/complete (253.12s)
PASS
```

Could we approve this pr for now? Or maybe we need to open a support ticket on your side I guess? Anyway, thanks for reading, waiting for your further instructions.

**Comment by manicminer** [comment]
@lonegunmanb It looks like we'll have to [submit an application](https://learn.microsoft.com/en-us/azure/ai-services/openai/overview#how-do-i-get-access-to-azure-openai) for access to the service

**Comment by jayendranarumugam** [comment]
Hello @manicminer , Is there any timeline for when this can be verified and merged? We are currently blocked with this. As there is no way for us to upgrade to a new version. Is there any way we can help ? Thanks!

**Comment by dkmiller** [comment]
@manicminer is there any way we could help with testing?

**Comment by MChorfa** [comment]
Is there a way to get this through? I can help with the testing as well

**Review by katbyte — APPROVED** [review]
LGTM ⚙️

**Comment by jayendranarumugam** [comment]
> It also looks like the API defaults this value to OnceNewDefaultVersionAvailable so we'll want to account for that as well
Hey @mbfrahry May I know from where this default is defined?

From [the doc](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/working-with-models?tabs=powershell#model-deployment-upgrade-configuration)

> null is equivalent to AutoUpgradeWhenExpired. If the Version update policy option is not present in the properties for a model that supports model upgrades this indicates the value is currently null. Once you explicitly modify this value the property will be visible in the studio properties page as well as via the REST API.


`AutoUpgradeWhenExpired` will be like `OnceCurrentVersionExpired`. So the default should be `OnceCurrentVersionExpired` is it ? Due to this change in the PR. My existing tfstate deployment are causing `forces replacement`

```
09    # azurerm_cognitive_deployment.generic_deployment["gpt-35-turbo"] must be replaced
16:51:09  -/+ resource "azurerm_cognitive_deployment" "generic_deployment" {
16:51:09        ~ id                     = "/subscriptions/xx/resourceGroups/ai-services-rg-01/providers/Microsoft.CognitiveServices/-cog-01/dex/gpt-35-txurbo-deployment-01" -> (known after apply)
16:51:09          name                   = "gpt-35-turbo-deployment-01"
16:51:09        ~ version_upgrade_option = "OnceCurrentVersionExpired" -> "OnceNewDefaultVersionAvailable" # forces replacement
16:51:09          # (2 unchanged attributes hidden)
16:51:09  
16:51:09        ~ scale {
16:51:09              # (2 unchanged attributes hidden)
16:51:09          }
16:51:09  
16:51:09          # (1 unchanged block hidden)
16:51:09      }
16:51:09  
```


I can raise a PR for a  quick fix. Do let me know thoughts  @katbyte

**Pull request merged**
