### PR TITLE
`azurerm_kusto_cluster` - add new skus to property `sku` on demand

### PR DESCRIPTION
**Pull request by liuwuliuyun**
**Background**

An important customer reach out to me for sku not supported issue urgently. After reviewing logs, I found that the skus required are not in the official document of kusto rest api yet. Therefore, we contact azure kusto team for assistance. 

Kusto team confirms that they have added support for below skus in the backend but not update swagger yet. As a result, our azure-go-sdk does not contain the newly added sku constants. They also confirm by email that these skus are already general avaliable.

**Protential Solutions**

I came up with two solutions for this, the first one is to wait for kusto team swagger release and generate new sdk based on that. But that would take a long time which our customer does not intend to wait for. 

The second is to add supported skus as constant string like in this PR. It is the most simple and quick solution I could think of for now. Although this would make the validation function looks a little weird, it does the trick and modifies the minimum lines of code. So I added comments to explain why we put these constants as string.

Plus, I updated the related doc and added a test case to verify the functionality of the newly added skus.

Any comments and suggestion is welcome on this problem :)

### CODE REVIEW

**Comment by liuwuliuyun** [comment]
GOROOT=D:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"D:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoCluster_newSkus_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"D:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoCluster_newSkus_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoCluster_newSkus\E$ #gosetup
=== RUN   TestAccKustoCluster_newSkus
=== PAUSE TestAccKustoCluster_newSkus
=== CONT  TestAccKustoCluster_newSkus
--- PASS: TestAccKustoCluster_newSkus (1383.60s)
PASS


Process finished with the exit code 0

**Review by katbyte — CHANGES_REQUESTED** [review]
can you open an issue on the rest API specs and link to it in code?

does the kusto team have an ETA for adding it to the swagger?

**Comment by liuwuliuyun** [comment]
> can you open an issue on the rest API specs and link to it in code?
> does the kusto team have an ETA for adding it to the swagger?
I could open an issue, but Kusto team are releasing the new API version and adding this to swagger in about 2 weeks. In this case, do we still need to open an issue on rest api specs?

**Comment by liuwuliuyun** [comment]
Link to issue in azure-rest-api-specs https://github.com/Azure/azure-rest-api-specs/issues/20468

**Comment by liuwuliuyun** [comment]
Hi @katbyte, MS Kusto team has made upgrade on their doc [here](https://docs.microsoft.com/en-us/rest/api/azurerekusto/clusters/create-or-update?tabs=HTTP#azuresku) about the supported skus. I think we could merge this PR to meet custom requirement in short term.

**Comment by liuwuliuyun** [comment]
And a long term solution is to upgrade to the latest API version 2022-07-01 with this [swagger link](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2022-07-07/kusto.json).

**Pull request closed without merging**
