### PR TITLE
app service - update sdk to 2022-09-01

### PR DESCRIPTION
**Pull request by xiaxyi**

### CODE REVIEW

**Comment by jackofallops** [comment]
HI @xiaxyi - Looks like all the tests on this service are now failing at the Service Plan creation:
```
=== CONT  TestAccLinuxFunctionApp_standardComplete
testcase.go:110: Step 1/2 error: Error running apply: exit status 1
Error: creating Service Plan: (Serverfarm Name "acctestASP-230413115942330585" / Resource Group "acctestRG-LFA-230413115942330585"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
with azurerm_service_plan.test,
on terraform_plugin_test.tf line 32, in resource "azurerm_service_plan" "test":
32: resource "azurerm_service_plan" "test" {
creating Service Plan: (Serverfarm Name "acctestASP-230413115942330585" /
Resource Group "acctestRG-LFA-230413115942330585"):
web.AppServicePlansClient#CreateOrUpdate: Failure sending request:
StatusCode=0 -- Original Error: autorest/azure: Service returned an error.
Status=<nil> <nil>
--- FAIL: TestAccLinuxFunctionApp_standardComplete (133.79s)
FAIL
```

Could you take a look?

**Comment by xiaxyi** [comment]
Thanks @jackofallops for the update. 

Seems all the service plan related tests were failed due to service plan, including logic app....

The issue has happened once earlier this week and it's due to sub's internal quota, can you help to have an internal confirmation? Thanks!

**Comment by xiaxyi** [comment]
Thanks @jackofallops for the comment, this is relating to the property `VnetRouteAllEnabled` existing in two places: siteConfig and siteProperty, the same issue happens in current api version 2021-03-01, not dedicated to the new api version. I will raise a seperate PR to fix it once the SDK gets updated.

**Comment by jackofallops** [comment]
> Thanks @jackofallops for the comment, this is relating to the property `VnetRouteAllEnabled` existing in two places: siteConfig and siteProperty, the same issue happens in current api version 2021-03-01, not dedicated to the new api version. I will raise a seperate PR to fix it once the SDK gets updated.

Hi @xiaxyi - I'm afraid we can't merge this with a known breakage in it. any user configs which have this property configured will fail leaving them stranded. I think we need to look to fix it here before this can be merged. Ideally, we might be able to do this in current API version and rebase this on top, which should mean this will then pass successfully, otherwise it will need to be addressed in this PR.

**Comment by xiaxyi** [comment]
Thanks @jackofallops , let me fix it in this pr.

**Comment by xiaxyi** [comment]
Hi @jackofallops , I updated the code, the issue is that the property `vnetRouteAllEnabled` is added under `SiteProperties` in 2022-09-01 api, so we need to make the value of this property the same under two places: `siteconfig` and `SiteProperties`

**Comment by jackofallops** [comment]
Hi @xiaxyi - Due to the conflicts introduced I've collected this change into another PR. (I've marked you as co-author on the commits).  I'm going to close this PR out in favour of the new one. Thanks again for your efforts on this service!

**Pull request closed without merging**
