### PR TITLE
`azurerm_monitor_activity_log_alert` - update - dynamic validation for `service_health`

### PR DESCRIPTION
**Pull request by HappyTobi**
Hi all,

just a small pr to add a better validation (based on Azure API) to validate the user / terraform input for "ServiceHealth" alerts.

Reason:
The API behind the Service Health feature was case sensitive, each input that was not 100% correct types will be pushed to the api (also shown in some views of the azure portal) but the action didn't work correct.
With the new dynamic validation each input will be validated with the service response that contains all possible input values. 
Also new Services can be handled in that way.

What I have changed / added

Add custom REST Client (api was not part of the azure sdk atm)
Add Validation errors
Add CustomDiff validation for `service_health` fields: `events` and `services`

resource "azurerm_monitor_activity_log_alert" "main" {
  name                = "example-activitylogalert"
  resource_group_name = azurerm_resource_group.main.name
  scopes              = [azurerm_resource_group.main.id]
  description         = "This alert will monitor a specific storage account updates."

  criteria {
    category = "ServiceHealth"    
    servicehealth {
      events   = ["Incident", "Maintenance"]
      regions  = ["Global", "West Europe"]
      services = ["App Service (Linux)", "Network Infrastructure"]
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
}

Please provide some feedback what you think about and if I have to change something

Regards,
Tobi

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Hi @HappyTobi,

Thank you for the PR, it looks like you've embedded a SDK into the provider, which is something we do not do. As I'm guessing this is not available in the Microsoft SDKs, we would look to generate it with Pandora, if you could provide us with a link to the swagger for it.

thanks!

**Comment by HappyTobi** [comment]
@katbyte when swagger was available we can also generate it into the offical go-sdk from ms.
I will try to ping the MS team when the swagger api is available

Regards

**Comment by katbyte** [comment]
@HappyTobi - any updates from the service team or should be just close this out until they get back to us?

**Comment by HappyTobi** [comment]
Hi @katbyte no feedback atm.
Let us close the pr I will reopen / recreate one if I get feedback

Regards

**Comment by katbyte** [comment]
will do, once there is swagger we can generate a new SDK ourselves FWIW

**Pull request closed without merging**
