### PR TITLE
[Documentation:] `azurerm_databricks_access_connector` - update private preview to public preview

### LINKED ISSUE #19287: Documentation of azurerm_databricks_access_connector Provider should be updated saying Public Preview rather than Private Preview
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_access_connector 

### Terraform Configuration Files

```hcl
This is not applicable
```

### Debug Output/Panic Output

```shell
This is not applicable
```

### Expected Behaviour

azurerm_databricks_access_connector provider should be documented as "Public Preview" as the service features are Public Preview from 06/30/2022 onwards. Currently the following page says it is "Private Preview". Also check any other places applicable and update there as well.

https://github.com/hashicorp/terraform-provider-azurerm/blob/54f23b882cc8abefc65766cd06bd19d808b45217/website/docs/r/databricks_access_connector.html.markdown#azurerm_databricks_access_connector

### Actual Behaviour

It is documented as Private Preview

### Steps to Reproduce

Refer the following page

https://github.com/hashicorp/terraform-provider-azurerm/blob/54f23b882cc8abefc65766cd06bd19d808b45217/website/docs/r/databricks_access_connector.html.markdown#azurerm_databricks_access_connector

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/blob/54f23b882cc8abefc65766cd06bd19d808b45217/website/docs/r/databricks_access_connector.html.markdown#azurerm_databricks_access_connector

### PR DESCRIPTION
**Pull request by WodansSon**
(fixes #19287)

### CODE REVIEW

**Comment by mvvsubbu** [comment]
Public Preview changes are not going to have breaking changes. So we shouldn't have this statement in PR **"and potentially subject to breaking change without notice."**

**Comment by WodansSon** [comment]
> Public Preview changes are not going to have breaking changes. So we shouldn't have this statement in PR **"and potentially subject to breaking change without notice."**

So are you saying I should just state that it is now in `public preview` and leave it at that? Or should I just remove the note completely?

**Comment by mvvsubbu** [comment]
You can remove it altogether if it is not mandatory to add note.

**Comment by WodansSon** [comment]
> You can remove it altogether if it is not mandatory to add note.

Oh, alright... I just removed the whole `NOTE` section and left the rest as it was.

**Comment by mvvsubbu** [comment]
Thanks, it looks good.

**Review by catriona-m — APPROVED** [review]
Thanks @WodansSon LGTM!

**Pull request merged**
