### PR TITLE
New DataSource: `azurerm_container_app`

### PR DESCRIPTION
**Pull request by jiaweitao001**
All tests passed.

```
=== RUN   TestAccContainerAppDataSource_basic
=== PAUSE TestAccContainerAppDataSource_basic
=== CONT  TestAccContainerAppDataSource_basic
--- PASS: TestAccContainerAppDataSource_basic (727.75s)
PASS
```

### CODE REVIEW

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for this @jiaweitao001

**Comment by GraemeMeyerGT** [comment]
@mbfrahry / @jiaweitao001 does a documentation page exist for this resource yet? I can't find it, but not sure if the `documentation` label means that's still to-do.

**Comment by jiaweitao001** [comment]
> 

Hi @GraemeMeyerGT , is [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/container_app) the doc page you're looking for?

**Comment by GraemeMeyerGT** [comment]
Yes it is! Thank you. I failed to scroll far enough in the sidebar after search 🤦‍♀️

**Pull request merged**
