### PR TITLE
azurerm_linux_function_app azurerm_linux_function_app_slot  - fixed wrong removal of WEBSITE_RUN_FROM_PACKAGE

### LINKED ISSUE #17081: `azurerm_linux_function_app` loses external `WEBSITE_RUN_FROM_PACKAGE` setting, causing the Function App to break
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "this" {
  name                       = "func-example-dev"
  resource_group_name        = var.resource_group_name
  location                   = var.location
  service_plan_id            = var.service_plan_id
  storage_account_name       = var.storage_account_name
  storage_account_access_key = var.storage_account_access_key
  https_only                 = true
  builtin_logging_enabled    = false
  tags                       = var.tags

  identity {
    type = "SystemAssigned"
  }

  site_config {
    application_insights_connection_string = var.application_insights_connection_string
    http2_enabled                          = true

    application_stack {
      node_version = 16
    }
  }

  app_settings = merge(
    { "WEBSITE_MOUNT_ENABLED" : "1" },
    var.app_settings
  )

  lifecycle {
    ignore_changes = [
      # We tried with and without ignoring changes here, but in both cases adding/removing entries to/from app_settings
      # causes WEBSITE_RUN_FROM_PACKAGE to be removed entirely
      app_settings["WEBSITE_RUN_FROM_PACKAGE"],
    ]
  }
}
```

### Debug Output/Panic Output

```shell
n/a (please let me know if I can provide any helpful output)
```

### Expected Behaviour

Making changes to `azurerm_linux_function_app.app_settings` has no effect on any external `WEBSITE_RUN_FROM_PACKAGE` entry.

### Actual Behaviour

Whenever there are changes to `app_settings` within the terraform configuration, the `WEBSITE_RUN_FROM_PACKAGE` setting gets removed on the next `terraform apply`. This renders the Function App broken, because the deployment package cannot be retrieved.

In particular this happens when deploying with the Azure Function Core Tools using `func azure functionapp publish`, since this will publish the package to a storage account and set the `WEBSITE_RUN_FROM_PACKAGE` in the Function App's `app_settings`. Upon the next changes in terraform, this setting will be removed and require another explicit deployment using the Azure Function Core Tools to be repaired. In between the Function App is broken.

Unlike mentioned in issue https://github.com/hashicorp/terraform-provider-azurerm/issues/16396 the `WEBSITE_RUN_FROM_PACKAGE` setting does not appear in the terraform plan or state at all, but it will be removed whenever there are any other changes in `app_settings`.

### Steps to Reproduce

1. Create the Function App `func-example-dev` using `terraform apply`
2. Deploy a function using `func azure functionapp publish func-example-dev` (here the `WEBSITE_RUN_FROM_PACKAGE` will be set on the Function App's settings)
3. Add an entry to the `app_settings` of the `azurerm_linux_function_app` resource in terraform
4. Run `terraform apply` to apply the changes to the `app_settings` (note that the plan will show no changes to `WEBSITE_RUN_FROM_PACKAGE`)
5. The Function App loses its `WEBSITE_RUN_FROM_PACKAGE` setting and becomes unusable

### Important Factoids

_No response_

### References

A similar issue has been reported here:
https://github.com/hashicorp/terraform-provider-azurerm/issues/16396

The issue was supposedly fixed in this pull request:
https://github.com/hashicorp/terraform-provider-azurerm/pull/16641

However, we are still running into the issue, although the behavior seems to have changed a bit (see `Actual Behavior`)

### PR DESCRIPTION
**Pull request by gioleppe**
As per the title, I fixed the case in which WEBSITE_RUN_FROM_PACKAGE gets removed if not set explicitly in the appsettings.

This was breaking deployments as the provider silently removed the setting even if it was explicitly ignored with ignore_settings, as documented on #17081 which this PR aims to fix

There was already a PR but it was closed due to [inactivity ](https://github.com/hashicorp/terraform-provider-azurerm/pull/21952)

With this PR, it's now sufficient to ignore the WEBSITE_RUN_FROM_PACKAGE setting, as ADO(/cli/whatever are using to do the runfrompackage deployment) is setting it up for the user.
Removal of locs fixing this issue was suggested by @jackofallops in the discussion under the original PR

fix #17081

### CODE REVIEW

**Comment by Sefriol** [comment]
I would double check that this still implements the original intent of @jackofallops 's commit: https://github.com/hashicorp/terraform-provider-azurerm/commit/0c56e1377d9cd0380e452f4e3939156467bd2431

I guess the problem persists with app slot as well.

**Comment by gioleppe** [comment]
Hi @Sefriol. Thank you for pointing this out.

I think that what @jackofallops was trying to achieve with that commit was to filter out the setting in the model if it was set by an external source like function app tools. This works as long as no other changes to the function app (or function app slot) are made.

As soon as you make other changes to the resource configuration, the API will be called on a model with that setting filtered out, thus breaking deployments.
This, as already discussed in #17081, subtly makes you think that you are not touching the WEBSITE_RUN_FROM_PACKAGE setting when you run terraform plan. Also, check [this](https://github.com/hashicorp/terraform-provider-azurerm/issues/17081#issuecomment-1147350779) comment for reference.

My take on this matter is that there should not be a special treatment for this setting: if you know how to use the lifecycle meta argument you would simply ignore it from the appsettings map, and that's it. 

Also, note that windows_function_app is working this way and no one ever complained about the behavior afaik.
On the other hand, I could bet this broke a lot of production deployments over the last two years (well, at least it broke mine, and the problem went undetected for a couple of days 😢)

**Comment by Sefriol** [comment]
Yeah, this broke our deployments as well. I am not disagreeing whether should be fixed. I was almost ready to make the same pull request myself. I just decided against it since I do not know the software well enough to know whether removing this could cause side effects that break current deployments.

.i.e is this a Breaking Change or not? Should there be a test that checks that it works in all situations?

(While I understand that this is a bug, it could still be a breaking change that needs to be notified to the end user. Otherwise they don't know whether they need to double check their deployments)

But as said, I am not an expert in this so maybe @jackofallops or somebody qualified should review this.

**Comment by gioleppe** [comment]
First of all thanks for the feedback on this which is very much appreciated.

My take on this is that this is the contrary to a breaking change, in the sense that this PR doesn't change behavior if the setting was already present on the resource. On the other hand, if not set on the resource and not ignored in the lifecycle meta argument, now the provider would correctly show the proposed removal, which I think is the whole point of using terraform in the first place.

Even though I tried to check all relevant code paths, I'm 100% with you in thinking someone more expert than me should double check this, let's just hope it doesn't take too long since this bug has been bothering us for months now!

**Comment by gioleppe** [comment]
For what concerns tests, removing those lines makes the WEBSITE_RUN_FROM_PACKAGE setting behave just like any other setting, i.e. the behavior should be covered by existing tests

**Comment by gioleppe** [comment]
@katbyte I think you've approved the tests on the latest merge, do you have any update on when this could be merged?
@jackofallops are you interested in merging this?

Thanks and have a great day!

**Review by stephybun — APPROVED** [review]
Thanks for picking this up @gioleppe! Although this is a breaking change for some users, after chatting through this internally we've decided to proceed with this PR given the nature and importance of this property for many valid deployment scenarios in App Service. We will make a point of calling this out in the Change Log. LGTM 👍

**Comment by gioleppe** [comment]
Thanks for closing this! 
Super proud of my microscopic change to the repo :)

**Pull request merged**
