### PR TITLE
Docs: Fix 'azurerm_mssql_database'

### PR DESCRIPTION
**Pull request by Tinear-PM**
This PR will improve the docs with the following:

- Add default value for `short_term_retention_policy retention_days`  according to the azure docs that is described [here](https://learn.microsoft.com/en-us/azure/azure-sql/database/automated-backups-overview?view=azuresql&tabs=single-database#short-term-retention)

### CODE REVIEW

**Review by mbfrahry — COMMENTED** [review]
Hey @Flo-PierreM, this value is Required by Terraform and must be specified in the config file. Because it needs to be specified, we don't allow for Default Values so I don't think we can accept this change. 

Are you seeing issues with this attribute that need to be further investigated?

**Comment by Flo-PierreM** [comment]
Hey @mbfrahry, 
I created this resource a couple days ago with only this attribute `account_replication_type` and by default, it created a `short_term_retention_policy` with a retention for 7 days.
It's not really a default configuration for this attribute. If you want, I can remove the default part and just let the change for the min days.

**Comment by mbfrahry** [comment]
So it looks like `short_term_retention_policy` is Computed as Azure will set that information for you if you don't set it. It looks like when `short_term_retention_policy` was first added `retention_days` was the only value you could set so we made `retention_days` Required while letting `short_term_retention_policy` be Computed. 

I think we could go back and make `retention_days` Optional and set the Default to `7` but that'll require some testing to make sure we're not going to inadvertently break anyone. In the meantime, let's remove the default section of the docs and just keep the min value change.

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for this @Tinear-PM!

**Pull request merged**
