### PR TITLE
[New Resource] `azurerm_confidential_ledger` - Add Azure Confidential Ledger Terraform Resource

### PR DESCRIPTION
**Pull request by lynshi**
This adds Terraform definitions for [Azure Confidential Ledger](https://azure.microsoft.com/en-us/services/azure-confidential-ledger/) based on our Public Preview API. We use the Hashicorp SDK generated from our [REST API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/confidentialledger/resource-manager/Microsoft.ConfidentialLedger/preview/2021-05-13-preview/confidentialledger.json) (as opposed to the Azure Go SDK).

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hi @lynshi

Thanks for this PR.

Since this is using an Embedded SDK I've pulled this down locally to check it matches what we're expecting and it appears there's a number of changes present - as such I hope you don't mind but I've ended up pushing a commit to update the Embedded SDK.

As I've pulled this down locally to update that, I ended up passing through the data sources/resources locally anyway - as such I hope you don't mind but I've pushed a couple of commits to this PR to update this so that we can get this merged.

Thanks!

**Comment by lynshi** [comment]
Hi @tombuildsstuff - appreciate the help and thank you! No worries at all. I had changed the auto-generated SDK slightly though I don't remember why.

I pulled the changes and ran it. Mostly looks good but I think one of the updates is disallowed (changes a property that can't be modified after creation), so the `certBased` test didn't pass. I'll push a fix sometime today.

**Comment by lynshi** [comment]
Sorry for the delay - I've verified that our resource tests pass and pushed the changes.

**Comment by koikonom** [comment]
Rebased to resolve conflicts.

**Comment by lynshi** [comment]
Hi, can I please get an update on this? The PR's been open for almost 3 months and I keep seeing milestones get added/removed, so just wanted to make sure we're on track as this is a requirement for General Availability of Azure Confidential Ledger.

**Review by koikonom — APPROVED** [review]

**Pull request merged**
