### PR TITLE
`azurerm_spring_cloud_app` - `public_endpoint_enabled`; `azurerm_spring_cloud_gateway_route_config`- support for the `open_api`;`azurerm_spring_cloud_service` - `log_stream_public_endpoint_enabled``read_timeout_seconds` properties

### PR DESCRIPTION
**Pull request by ms-henglu**
image
image
image

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🎩

**Review by katbyte — CHANGES_REQUESTED** [review]
test failing
```
------- Stdout: -------
=== RUN   TestAccSpringCloudGatewayRouteConfig_update
=== PAUSE TestAccSpringCloudGatewayRouteConfig_update
=== CONT  TestAccSpringCloudGatewayRouteConfig_update
    testcase.go:110: Step 1/6 error: Error running apply: exit status 1
        
        Error: updating config server for Spring Cloud Service: (Spring Name "acctest-sc-220802175417878955" / Resource Group "acctestRG-spring-220802175417878955"): appplatform.ConfigServersClient#UpdatePut: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Feature ConfigServer is not supported in Sku E0 for API version 2022-05-01-preview."
        
          with azurerm_spring_cloud_service.test,
          on terraform_plugin_test.tf line 12, in resource "azurerm_spring_cloud_service" "test":
          12: resource "azurerm_spring_cloud_service" "test" {
        
--- FAIL: TestAccSpringCloudGatewayRouteConfig_update (851.28s)
FAIL

```

**Comment by ms-henglu** [comment]
Hi @katbyte , thanks for code review, I've raised another PR to fix the failed tests in SpringCloud RP.

**Review by katbyte — APPROVED** [review]
Thanks @ms-henglu - all test pass now ♻️

**Pull request merged**
