### PR TITLE
r/`storage_queue`: fixing a bug where the Table URI was obtained rather than the Queue URI

### LINKED ISSUE #25261: Inconsistency in creating storage account and creating the subdomain as queue
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.7.1

### AzureRM Provider Version

v3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_queue

### Terraform Configuration Files

```hcl
resource "azurerm_storage_queue" "storage_queue" {
  name                 = "queue-${var.project}-${var.environment}"
  storage_account_name = azurerm_storage_account.storage_account.name
}
```

### Debug Output/Panic Output

```shell
Error: expected the subdomain type to be "queue" but got "table"
│ 
│   with azurerm_storage_queue.storage_queue,
│   on storage_account.tf line 45, in resource "azurerm_storage_queue" "storage_queue":
│   45: resource "azurerm_storage_queue" "storage_queue" {
```

### Expected Behaviour

azurerm_storage_queue.storage_queue: Creating...
azurerm_storage_queue.storage_queue: Creation complete after 1s [id=https://sttestpocqatest.queue.core.windows.net/testpoc-qatest-queue]

### Actual Behaviour

 Error: expected the subdomain type to be "queue" but got "table"
│ 
│   with azurerm_storage_queue.storage_queue,
│   on storage_account.tf line 45, in resource "azurerm_storage_queue" "storage_queue":
│   45: resource "azurerm_storage_queue" "storage_queue" {

### Steps to Reproduce

use azurerm provider 3.96.0 
try to create a storage account and create a queue

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by tombuildsstuff**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Fixes #25261

### CODE REVIEW

**Review by raguldevops — APPROVED** [review]

**Review by stephybun — APPROVED** [review]
Thanks @tombuildsstuff LGTM 👍

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2024-03-15 at 09 34 29

**Comment by raguldevops** [comment]
Thanks @tombuildsstuff for fixing the issue

**Comment by Mohamednourr** [comment]
I am hitting the same issue with a different error and it was fixed by pining the azurerm provider to v3.95.0

│ Error: expected the subdomain type to be "dfs" but got "blob"

**Pull request merged**
