### PR TITLE
`azurerm_managed_disk` - upgrade API from `2022-03-02` to `2023-04-02`

### PR DESCRIPTION
**Pull request by ms-zhenhua**
Upgrade API version to support newly added properties: (new properties will be in another PR)

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by tombuildsstuff** [comment]
@ms-zhenhua mind rebasing this PR/running `go mod tidy && go mod vendor`?

**Comment by ms-zhenhua** [comment]
> @ms-zhenhua mind rebasing this PR/running `go mod tidy && go mod vendor`?

@tombuildsstuff, thank you for your review. I am fixing the 2 failed checks. For `Check for new usages of deprecated functionality`, it's caused by the existing code. Do I need to change current logic of the `DELETE` function by removing the code of `d.Get` ? Or is there a way to skip the error caused by existing code?

**Comment by tombuildsstuff** [comment]
Rebased atop `main`

**Pull request merged**
