### PR TITLE
`azurerm_virtual_network_gateway` - support for new properties

### PR DESCRIPTION
**Pull request by neil-yechenwei**
This PR is to support new properties `bgp_route_translation_for_nat_enabled`, `dns_forwarding_enabled`, `ip_sec_replay_protection_enabled`, `remote_vnet_traffic_enabled`, `virtual_wan_traffic_enabled`, `radius_server`, `virtual_network_gateway_client_connection`, `policy_group` and `ipsec_policy` for Virtual Network Gateway.

image

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🌩️

**Comment by neil-yechenwei** [comment]
@katbyte , is it good to merge?

**Comment by manicminer** [comment]
@neil-yechenwei Looks like we have a new test failure, the resource entered a failed state

Screenshot 2023-10-12 at 23 28 46

**Comment by neil-yechenwei** [comment]
@manicminer , after rerun, all related test cases passed.

image

**Review by katbyte — CHANGES_REQUESTED** [review]
@neil-yechenwei - it looks like there is something flaky here, 2 tests are failing in the last run, a different error here:
```

------- Stdout: -------
=== RUN   TestAccVirtualNetworkGatewayConnection_updatingSharedKey
=== PAUSE TestAccVirtualNetworkGatewayConnection_updatingSharedKey
=== CONT  TestAccVirtualNetworkGatewayConnection_updatingSharedKey
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        
        Error: waiting for completion of Virtual Network Gateway: (Name "acctest-231106210457835008" / Resource Group "acctestRG-231106210457835008"): Code="RetryableError" Message="A retryable error occurred." Details=[{"code":"RetryableErrorDueToAnotherOperation","message":"Operation PutVirtualNetworkGatewayOperation (3c216d95-9fa6-422d-b6fc-2dc3c258ec54) is updating resource *******. The call can be retried in 15 seconds."}]
        
          with azurerm_virtual_network_gateway.test_1,
          on terraform_plugin_test.tf line 57, in resource "azurerm_virtual_network_gateway" "test_1":
          57: resource "azurerm_virtual_network_gateway" "test_1" {
        
    testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Public Ip Address: (Name "acctest-231106210457835008" / Resource Group "acctestRG-231106210457835008"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/publicIPAddresses/acctest-231106210457835008 can not be deleted since it is still allocated to resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworkGateways/acctest-231106210457835008/ipConfigurations/vnetGatewayConfig. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
        
        
        Error: deleting Subnet (Subscription: "*******"
        Resource Group Name: "acctestRG-231106210457835008"
        Virtual Network Name: "acctestvn-231106210457835008"
        Subnet Name: "GatewaySubnet"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="ReferencedResourceNotProvisioned" Message="Cannot proceed with operation because resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworkGateways/acctest-231106210457835008 used by resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworks/acctestvn-231106210457835008/subnets/GatewaySubnet is not in Succeeded state. Resource is in Failed state and the last operation that updated/is updating the resource is PutVirtualNetworkGatewayOperation." Details=[]
        
--- FAIL: TestAccVirtualNetworkGatewayConnection_updatingSharedKey (496.71s)
FAIL
```

could you please try to account for this in the resource so users don't experience it? running tests till they pass is not acceptable. thanks

**Review by katbyte — CHANGES_REQUESTED** [review]
@neil-yechenwei - it looks like there is something flaky here, 2 tests are failing in the last run, a different error here:
```

------- Stdout: -------
=== RUN   TestAccVirtualNetworkGatewayConnection_updatingSharedKey
=== PAUSE TestAccVirtualNetworkGatewayConnection_updatingSharedKey
=== CONT  TestAccVirtualNetworkGatewayConnection_updatingSharedKey
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        
        Error: waiting for completion of Virtual Network Gateway: (Name "acctest-231106210457835008" / Resource Group "acctestRG-231106210457835008"): Code="RetryableError" Message="A retryable error occurred." Details=[{"code":"RetryableErrorDueToAnotherOperation","message":"Operation PutVirtualNetworkGatewayOperation (3c216d95-9fa6-422d-b6fc-2dc3c258ec54) is updating resource *******. The call can be retried in 15 seconds."}]
        
          with azurerm_virtual_network_gateway.test_1,
          on terraform_plugin_test.tf line 57, in resource "azurerm_virtual_network_gateway" "test_1":
          57: resource "azurerm_virtual_network_gateway" "test_1" {
        
    testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Public Ip Address: (Name "acctest-231106210457835008" / Resource Group "acctestRG-231106210457835008"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/publicIPAddresses/acctest-231106210457835008 can not be deleted since it is still allocated to resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworkGateways/acctest-231106210457835008/ipConfigurations/vnetGatewayConfig. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
        
        
        Error: deleting Subnet (Subscription: "*******"
        Resource Group Name: "acctestRG-231106210457835008"
        Virtual Network Name: "acctestvn-231106210457835008"
        Subnet Name: "GatewaySubnet"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="ReferencedResourceNotProvisioned" Message="Cannot proceed with operation because resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworkGateways/acctest-231106210457835008 used by resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworks/acctestvn-231106210457835008/subnets/GatewaySubnet is not in Succeeded state. Resource is in Failed state and the last operation that updated/is updating the resource is PutVirtualNetworkGatewayOperation." Details=[]
        
--- FAIL: TestAccVirtualNetworkGatewayConnection_updatingSharedKey (496.71s)
FAIL
```

could you please try to account for this in the resource so users don't experience it? running tests till they pass is not acceptable. thanks

**Review by katbyte — CHANGES_REQUESTED** [review]
@neil-yechenwei - it looks like there is something flaky here, 2 tests are failing in the last run, a different error here:
```

------- Stdout: -------
=== RUN   TestAccVirtualNetworkGatewayConnection_updatingSharedKey
=== PAUSE TestAccVirtualNetworkGatewayConnection_updatingSharedKey
=== CONT  TestAccVirtualNetworkGatewayConnection_updatingSharedKey
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        
        Error: waiting for completion of Virtual Network Gateway: (Name "acctest-231106210457835008" / Resource Group "acctestRG-231106210457835008"): Code="RetryableError" Message="A retryable error occurred." Details=[{"code":"RetryableErrorDueToAnotherOperation","message":"Operation PutVirtualNetworkGatewayOperation (3c216d95-9fa6-422d-b6fc-2dc3c258ec54) is updating resource *******. The call can be retried in 15 seconds."}]
        
          with azurerm_virtual_network_gateway.test_1,
          on terraform_plugin_test.tf line 57, in resource "azurerm_virtual_network_gateway" "test_1":
          57: resource "azurerm_virtual_network_gateway" "test_1" {
        
    testing_new.go:90: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Public Ip Address: (Name "acctest-231106210457835008" / Resource Group "acctestRG-231106210457835008"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/publicIPAddresses/acctest-231106210457835008 can not be deleted since it is still allocated to resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworkGateways/acctest-231106210457835008/ipConfigurations/vnetGatewayConfig. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]
        
        
        Error: deleting Subnet (Subscription: "*******"
        Resource Group Name: "acctestRG-231106210457835008"
        Virtual Network Name: "acctestvn-231106210457835008"
        Subnet Name: "GatewaySubnet"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="ReferencedResourceNotProvisioned" Message="Cannot proceed with operation because resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworkGateways/acctest-231106210457835008 used by resource /subscriptions/*******/resourceGroups/acctestRG-231106210457835008/providers/Microsoft.Network/virtualNetworks/acctestvn-231106210457835008/subnets/GatewaySubnet is not in Succeeded state. Resource is in Failed state and the last operation that updated/is updating the resource is PutVirtualNetworkGatewayOperation." Details=[]
        
--- FAIL: TestAccVirtualNetworkGatewayConnection_updatingSharedKey (496.71s)
FAIL
```

could you please try to account for this in the resource so users don't experience it? running tests till they pass is not acceptable. thanks

**Comment by neil-yechenwei** [comment]
@katbyte , seems your same comment is added three times.
1. I assume the test prefix in teamcity needs to be set to "TestAccVirtualNetworkGateway_" since I only changed the azurerm_virtual_network_gateway. All related test cases passed in the latest run.
image
2. TestAccVirtualNetworkGateway_vpnGw1 can pass after rerun.
3. Teamcity returns the error that is same with the error in the last daily run with main branch after rerun test case TestAccVirtualNetworkGatewayConnection_updatingSharedKey. As of the error for this test case, I suggest to submit another PR to fix it since it's not related with this PR.
image

**Review by katbyte — APPROVED** [review]
LGTM 📨

**Comment by neil-yechenwei** [comment]
@katbyte , is it good to be merge?

**Pull request merged**
