### PR TITLE
`azurerm_hdinsight_kafka_cluster`, `azurerm_hdinsight_spark_cluster`, `azurerm_hdinsight_interactive_query_cluster`, `azurerm_hdinsight_hbase_cluster`, `azurerm_hdinsight_hadoop_cluster` - Add support for `VMGroupName` and `encryptDataDisks` properties

### PR DESCRIPTION
**Pull request by jiaweitao001**
* Add support for `VMGroupName` and `encryptDataDisks` in HDInsight clusters.
* All tests passed.

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM  provided tests pass ♻️

**Review by katbyte — CHANGES_REQUESTED** [review]
lots of test failures:
image

**Comment by jiaweitao001** [comment]
Hi @katbyte , the tests were failing of timeout for some reason. Now they're passing in pipeline.

**Comment by jiaweitao001** [comment]
[Test reults](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=328876&tab=buildResultsDiv&buildTypeId=TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_HDINSIGHT). As you can see, the failing ones are the same as main branch, so these are actually irrelevant.

**Review by katbyte — APPROVED** [review]
LGTM provided tests pass 🧾

**Comment by jiaweitao001** [comment]
Synced with HDInsight service team, these 2 attributes are not required anymore. Will withdraw the PR.

**Pull request closed without merging**
