### PR TITLE
`network`: upgrade sdk to kermit@2022-11-01

### PR DESCRIPTION
**Pull request by wuxu92**
New feature require the new API version.

**Draft for TC**

### CODE REVIEW

**Comment by wuxu92** [comment]
> @wuxu92 `network` is now available in `hashicorp/go-azure-sdk` - which we're migrating across too, which new feature requires this / why are we using Kermit here?

go-azure-sdk is fine too! I just need the new API version. is the migration on processing by other one now?

**Comment by wuxu92** [comment]
> @wuxu92 `network` is now available in `hashicorp/go-azure-sdk` - which we're migrating across too, which new feature requires this / why are we using Kermit here?

go-azure-sdk is fine too! I just need the new API version. is the migration on processing by other one now?

**Comment by tombuildsstuff** [comment]
@wuxu92 Resources are being ported-over as needed, (for example https://github.com/hashicorp/terraform-provider-azurerm/pull/22425) - so it should be possible to first port the resource over to using `hashicorp/go-azure-sdk` (in one PR), and then adopt the new functionality (in the next)

API Version `2023-02-01` is available in `hashicorp/go-azure-sdk`, so we should be able to use that newer version, rather than `2022-11-01` too: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/network/2023-02-01

Hope that helps :)

**Comment by wuxu92** [comment]
@tombuildsstuff great! I'll close this PR and start work with the new version in go-azure-sdk then. thanks so much for your quick review.

**Pull request closed without merging**
