### PR TITLE
Use latest NGINXaaS API (2024-01-01-preview)

### PR DESCRIPTION
**Pull request by puneetsarna**
This is based on un-released swagger
2024-01-01-preview.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hey @puneetsarna 

Thanks for this PR.

The AzureRM Provider makes use of the Go SDK from `hashicorp/go-azure-sdk`, which pulls it's data from `hashicorp/pandora` (which in turn imports it from `Azure/azure-rest-api-specs`). When support for a new API version is merged into `Azure/azure-rest-api-specs`, we can import it into `hashicorp/pandora` which will end up generating a Go SDK for this which we can consume in this repository.

Taking a look through here [it appears the upstream Swagger PR for this one is still a WIP](https://github.com/Azure/azure-rest-api-specs/pull/27581) but once that's merged we should be able to import this into `hashicorp/pandora` by adding the new API Version [to this list](https://github.com/hashicorp/pandora/blob/1fa489cf2fd9afa17438a8c03b948445e4f75fa2/config/resource-manager.hcl#L392) - which'll allow the Go SDK to be generated for this API version (and for this to compile).

Since this one's still waiting on the upstream PR to be merged, for the moment I'm going to tag this one as `upstream/pandora` and `upstream/microsoft/blocking-swagger-issue` - but once the upstream PR has been merged and this is imported into Pandora, it should be possible to rebase this PR atop the regenerated Go SDK which'll resolve the build failures here.

Thanks!

**Comment by agazeley** [comment]
LGTM

**Comment by tombuildsstuff** [comment]
This is now available in `hashicorp/go-azure-sdk`, the version for which is being vendored here:v0.20240221.1170458

**Comment by puneetsarna** [comment]
@tombuildsstuff Thanks for sharing the updates around the go SDK. I have updated this PR to vendor the latest code and swapped the NGINXaaS API. Can you please take a look at this change?

**Review by katbyte — APPROVED** [review]
LGTM 🧁

**Pull request merged**
