### PR TITLE
`azurerm_storage_account` - support for the `public_network_access_enabled` property

### LINKED ISSUE #17976: Storage account network rules never set to 'disabled'
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.201.18

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_network_rules, azurerm_storage_account

### Terraform Configuration Files

```hcl
Using either a network_rules block inside the azurerm_storage_account resource like this:

resource "azurerm_storage_account" "main" {
  name                            = var.storage_account_name
  resource_group_name             = var.storage_account_rg
  location                        = var.storage_account_location
  account_tier                    = var.storage_account_tier
  account_replication_type        = var.storage_account_replication_type
  account_kind                    = var.storage_account_kind
  min_tls_version                 = var.storage_account_tls
  large_file_share_enabled        = var.large_file_share_enabled
  enable_https_traffic_only       = var.enable_https_traffic_only
  allow_nested_items_to_be_public = var.allow_nested_items_to_be_public
  tags                            = var.storage_account_tags

network rules {
default_action             = "Deny"
}
}

or using the seperate azurerm_storage_account_network_rules resource

resource "azurerm_storage_account_network_rules" "main" {
  storage_account_id = azurerm_storage_account.main.id
  default_action             = "Deny"
}

It never sets it to disabled
```

### Debug Output/Panic Output

```shell
module.storage-accounts["christest"].azurerm_storage_account_network_rules.main: Modifying... [id=/subscriptions/<removed>/resourceGroups/rg-test/providers/Microsoft.Storage/storageAccounts/stchristest1]
module.storage-accounts["christest"].azurerm_storage_account_network_rules.main: Modifications complete after 2s [id=/subscriptions/<removed>/resourceGroups/rg-test/providers/Microsoft.Storage/storageAccounts/stchristest1]
```

### Expected Behaviour

It should set the storage account to 'disabled'

image

### Actual Behaviour

It only ever sets it to 'enabled from selected networks and IP addresses'

image

### Steps to Reproduce

terraform apply

### Important Factoids

Running from either a self hosted agent or Microsoft hosted agent

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
Fix #17976

## Test

```shell
💢  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run='TestAccStorageAccount_publicNetworkAccess'
=== RUN   TestAccStorageAccount_publicNetworkAccess
=== PAUSE TestAccStorageAccount_publicNetworkAccess
=== CONT  TestAccStorageAccount_publicNetworkAccess
--- PASS: TestAccStorageAccount_publicNetworkAccess (192.58s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       192.588s
```

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🚁

**Review by katbyte — APPROVED** [review]
once docs are add as it seems like they are missing?

**Comment by magodo** [comment]
@katbyte Sorry, the doc is now added.

**Comment by magodo** [comment]
image

**Pull request merged**
