### PR TITLE
azurerm_cdn_frontdoor_route - make cdn_frontdoor_rule_set_ids an ordered list

### PR DESCRIPTION
**Pull request by sammeidroid**
use TypeList instead of TypeSet

fixes: #22364

### CODE REVIEW

**Comment by sammeidroid** [comment]
@manicminer Do I have to do anything else to get an approval?

**Comment by WodansSon** [comment]
Hi @sammeidroid, @manicminer is correct I believe there will need to be a lot more testing to verify this change does not break the current implementation of this resource and other resources, especially the `azurerm_cdn_frontdoor_rule_set_association`. I originally switched `cdn_frontdoor_rule_set_ids` to a `TypeSet` from a `TypeList` it was because the Azure RP was returning the `cdn_frontdoor_rule_set_ids` in the reverse order they were sent:

**Values Returned From Azure:**
```bash
"ruleSets":[{"id":".../ruleSets/acctestrulesetthree"},
            {"id":".../ruleSets/acctestrulesettwo"},
            {"id":".../ruleSets/acctestrulesetone"}],
```
But Terraform persists them to the state file the way they were defined in the configuration file:

**Values In Terraform State File:**
```bash
"cdn_frontdoor_rule_set_ids": [
              ".../ruleSets/acctestrulesetone",
              ".../ruleSets/acctestrulesettwo",
              ".../ruleSets/acctestrulesetthree"
            ],
```
Then on your next `plan`/`apply` you will see an unexpected diff because Terraform wants to put the `cdn_frontdoor_rule_set_ids` values back in the same order as they appear in the config file, resulting in a very confusing diff:

**Values In Terraform Diff on Plan/Apply:**
```bash
~ cdn_frontdoor_rule_set_ids = [
    - ".../ruleSets/acctestrulesetthree",
    - ".../ruleSets/acctestrulesettwo",
      ".../ruleSets/acctestrulesetone",
    + ".../ruleSets/acctestrulesettwo",
    + ".../ruleSets/acctestrulesetthree",
  ]
```

The RP may have changed and it now honors the order of the `cdn_frontdoor_rule_set_ids` were sent, I do not know.

**Comment by katbyte** [comment]
related pr #18600

**Comment by WodansSon** [comment]
Hi @sammeidroid, I am going to go ahead and close this as there hasn't been any activity on this PR for over a month now. 🚀

**Pull request closed without merging**
