### PR TITLE
`azurerm_disk_pool_iscsi_target` - Fix an import issue due to unexpected type

### PR DESCRIPTION
**Pull request by magodo**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

`azurerm_disk_pool_iscsi_target` - Fix an import issue due to unexpected type

Meanwhile, align the type expectation for the typed sdk model generation tool.

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [ ] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [ ] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [ ] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [ ] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_disk_pool_iscsi_target` - Fix an import issue due to unexpected type [GH-00000]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by stephybun — COMMENTED** [review]
@magodo, the tests are failing with 
```
        Error: creating Disk Pool (Subscription: "*******"
        Resource Group Name: "acctestRG-diskspool-240704173347097087"
        Disk Pool Name: "acctest-diskspool-0igo0"): unexpected status 404 (404 Not Found) with error: InvalidResourceNamespace: The resource namespace 'Microsoft.StoragePool' is invalid.
```
Would you mind taking a look?

**Comment by magodo** [comment]
@stephybun This issue has nothing to do with my PR, suspicoulsy there the RP is not registered by the running subscription?

**Comment by magodo** [comment]
@stephybun That said, the error message `The resource namespace 'Microsoft.StoragePool' is invalid.` indicates the RP is not registered by the test subscription, could you please verify that on your side?

**Comment by stephybun** [comment]
@magodo the RP returned by the error message doesn't exist and upon closer inspection this resource is deprecated and will be removed in v4.0.

Since this isn't testable and the RP doesn't exist anymore I'm going to close this PR. You're welcome to open a separate PR for the changes made to the typed model generator tool.

**Pull request closed without merging**
