### PR TITLE
`AppService` - Add support for `ip_restriction_default_action` and `scm_ip_restriction_default_action` to all app service resources

### LINKED ISSUE #22593: Support for ipSecurityRestrictions within linux_web_app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The resource Microsoft.Web/sites (represented in Terraform by `linux_web_app` or `windows_web_app`) has a property called `siteConfig.ipSecurityRestrictionsDefaultAction` which gets used to configure the resource's access restrictions default behavior if no access rule matches.

Even though the Azure Portal and the Azure CLI are using this property in their API requests, it has not been documented in the API specifications (see issue https://github.com/Azure/azure-rest-api-specs/issues/24215), and I guess this is why it is missing in Terraform.

Same for the property `siteConfig.scmIpSecurityRestrictionsDefaultAction` (rules for the Web App's "Advanced tool site").

### New or Affected Resource(s)/Data Source(s)

linux_web_app, windows_web_app

### Potential Terraform Configuration

```hcl
The Terraform resource could looke like this:

resource "azurerm_linux_web_app" "example" {
  public_network_access_enabled = true

  site_config {
    ip_restrictions_default_action = "Deny"

    ip_restriction {
      name       = "example rule"
      action     = "Allow"
      priority   = 100
      ip_address = "1.1.1.1/32"
    }
  }
}
```

### References

- https://github.com/Azure/azure-rest-api-specs/issues/24215

### PR DESCRIPTION
**Pull request by jackofallops**
supersedes #24519 and #24464 
closes #22593

### CODE REVIEW

**Review by stephybun — APPROVED** [review]
Thanks @jackofallops, there's one minor mistake in the documentation, but otherwise LGTM 🦫

**Comment by jackofallops** [comment]
Tests loog good, failures are transient:

image

**Comment by drdamour** [comment]
the default value for this in azure portal is null...y did terraform default it to true?

**Comment by arno-bootcamp-ghas** [comment]
Are there any plans to also add support for this to `azurerm_logic_app_standard`?

**Comment by mattmshell** [comment]
Firewall rules implicitly set the default rule to Deny. Adding this property reverse that because it defaults to Allow. As a result AzureRM 3.95 opens up App and SCM endpoints to the Internet. Pretty dangerous change!

**Comment by drdamour** [comment]
@mattmshell i think it's only deny by default if you have a private endpoint..that's how i read the docs.

if default action is null then it's allow unless a private endpoint exists then it's deny

but 100% agree this seems to be the wrong default value for this setting.  @jackofallops any thoughts?

**Comment by rellis-of-rhindleton** [comment]
Hey folks ... this looks like a major breaking change. We have a number of app services (that are not on private endpoints) suddenly reverting to default = Allow, where the effective default was Deny.

**Comment by mattmshell** [comment]
I don't know if `ipSecurityRestrictionsDefaultAction` is an optional AzureRM property. If it is could we avoid specifying it in payloads if the Terraform property is unset. If it's a mandatory property can we coalesce to the current AzureRM value?

Alternatively, given the likelihood of disaster if the wrong option is chosen, can we require `ip_restriction_default_action` to be set if there are any access restriction entries present?

**Pull request merged**
