### PR TITLE
`azurerm_windows_function_app`/`azurerm_linux_function_app` - Add support for PowerShell 7.2 

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
Resolves https://github.com/hashicorp/terraform-provider-azurerm/issues/16717.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @Francisco-Gamino - LGTM but could we update the docs with the new valid value? should be good to merge after that sis done! thanks

**Comment by Francisco-Gamino** [comment]
Thank you @katbyte for the PR review. Could you please point me to the doc that needs to be updated? I am not very familiar with your repro as this is my first contribution.

**Comment by Francisco-Gamino** [comment]
Hello @katbyte -- I did a recursive search for any docs that contain `powershell_core_version` and `7`. Here is the list of files I've updated:
```
website/docs/r/linux_function_app.html.markdown
website/docs/r/linux_function_app_slot.html.markdown
website/docs/r/windows_function_app.html.markdown
website/docs/r/windows_function_app_slot.html.markdown
```
Please let me know if I am missing anything. Lastly, once this PR is merged, how long will it take to release this change? Thank you!

**Comment by Francisco-Gamino** [comment]
Thank you @mbfrahry for fixing my PR.

**Review by mbfrahry — APPROVED** [review]
Not a problem @Francisco-Gamino! LGTM!

**Comment by Francisco-Gamino** [comment]
Thank you @mbfrahry ! 

One last question: When will this change be released?

**Comment by bdorplatt** [comment]
After setting the parameter to 7.0 or 7.2, should that value be reflected in the Azure portal? We have tried both versions and under **Configuration>General Settings** the Stack is listed as **PowerShell Core** but the **PowerShell Core Version** option is blank. The versions are available in the drop-down, just neither is selected.

Is this possibly a situation where there is just a bug in the GUI and the setting is actually set on the backend?

**Comment by bdorplatt** [comment]
While support was added to the code, it doesn't appear to actually set the value of the PowerShell version.  Changing the version back and forth from 7 to 7.2 in code doesn't seem to modify the actual resource. The same thing happens when using Java as the application stack but works correctly with Node and reflects the correct version in the portal.  It appears to be the same issue as here [https://github.com/hashicorp/terraform-provider-azurerm/issues/8867](url)
But now it happens with the 3.7.0 provider with the new stack settings.

**Comment by Francisco-Gamino** [comment]
@bdorplatt -- The code change adds `7.2` to the list of valid runtime values. However, you still need to add this value to the app setting for your function app. It would look something like this for a Windows app:
```
app_settings = {
    FUNCTIONS_WORKER_RUNTIME_VERSION = "7.2"
    FUNCTIONS_WORKER_RUNTIME         = "powershell"
  }
```

**Comment by bdorplatt** [comment]
We were under the impression that the new **application_stack** block settings superseded the FUNCTIONS_WORKER_RUNTIME and FUNCTIONS_WORKER_RUNTIME_VERSION app settings and would fill the version into the app settings. It is doing this for FUNCTIONS_WORKER_RUNTIME, filling "powershell" into the app settings without us specifying it as an app setting.

The only app settings we are specifying are below:
  app_settings  = {
    "KEYVAULT_ENDPOINT"                                  = var.kv_uri
    "APPINSIGHTS_INSTRUMENTATIONKEY"        = var.ai_instrumentation_key
}
And these stack settings:
    application_stack {
      powershell_core_version     = "7.2"
    }

And we get the following result in app settings, where only "powershell" without the version is showing. It seems odd that the application stack settings would have been added but you have to specify the versions in two different places. (in stack_settings as well as app_settings)

image

**Comment by Francisco-Gamino** [comment]
@bdorplatt -- Thank you for the reply. I am new to Terraform, so I am going to get let a Terraform SME answer this. 
@mbfrahry -- Could you please help answer the question above on what is the recommend way to set the `powershell_core_version` for a function app? Thank you.

**Pull request merged**
