### PR TITLE
new resource azurerm_logz_tag_rule

### PR DESCRIPTION
**Pull request by ms-zhenhua**
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/logz/resource-manager/Microsoft.Logz/stable/2020-10-01/logz.json
https://ci-oss.hashicorp.engineering/buildConfiguration/TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_LOGZ/217040?buildTab=tests&status=passed
image

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]

**Comment by ms-zhenhua** [comment]
Hi @katbyte, Thank you for reviewing my code, I've added a commit according to your comments, please kindly help take another look, thanks!

**Comment by katbyte** [comment]
We have some test failures:
```
------- Stdout: -------
=== RUN   TestAccLogzTagRule_complete
=== PAUSE TestAccLogzTagRule_complete
=== CONT  TestAccLogzTagRule_complete
    testcase.go:109: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Logz Monitor: (Monitor Name "liftr_test_only_1111174006921708" / Resource Group "acctest-logz-211111174006921708"): logz.MonitorsClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="InvalidResourceOperation" Message="The operation for resource '/subscriptions/*******/resourceGroups/acctest-logz-211111174006921708/providers/Microsoft.Logz/monitors/liftr_test_only_1111174006921708' is invalid as it is being provisioned with state: 'Accepted'."
        
          with azurerm_logz_monitor.test,
          on terraform_plugin_test.tf line 12, in resource "azurerm_logz_monitor" "test":
          12: resource "azurerm_logz_monitor" "test" {
        
--- FAIL: TestAccLogzTagRule_complete (241.87s)
FAIL
```

**Comment by ms-zhenhua** [comment]
Hi @katbyte , Thank you for your reminder. I am looking into this issue now.

**Review by katbyte — APPROVED** [review]
Thanks @ms-zhenhua - LGTM 💯

**Pull request merged**
