### PR TITLE
`azurerm_application_insights` - delete action group when generated rule is disabled

### PR DESCRIPTION
**Pull request by teowa**
fix `TestAccApplicationInsights_disableGeneratedRule` failure:
```
------- Stdout: -------
=== RUN   TestAccApplicationInsights_disableGeneratedRule
=== PAUSE TestAccApplicationInsights_disableGeneratedRule
=== CONT  TestAccApplicationInsights_disableGeneratedRule
testing_new.go:86: Error running post-test destroy, there may be dangling resources: exit status 1
Error: deleting Resource Group "acctestRG-appinsights-230613061048111503": the Resource Group still contains Resources.
Terraform is configured to check for Resources within the Resource Group when deleting the Resource Group - and
raise an error if nested Resources still exist to avoid unintentionally deleting these Resources.
Terraform has detected that the following Resources still exist within the Resource Group:
* `/subscriptions/*******/resourceGroups/acctestRG-appinsights-230613061048111503/providers/microsoft.insights/actiongroups/Application Insights Smart Detection`
This feature is intended to avoid the unintentional destruction of nested Resources provisioned through some
other means (for example, an ARM Template Deployment) - as such you must either remove these Resources, or
disable this behaviour using the feature flag `prevent_deletion_if_contains_resources` within the `features`
block when configuring the Provider, for example:
provider "azurerm" {
features {
resource_group {
prevent_deletion_if_contains_resources = false
}
}
}
When that feature flag is set, Terraform will skip checking for any Resources within the Resource Group and
delete this using the Azure API directly (which will clear up any nested resources).
More information on the `features` block can be found in the documentation:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features
--- FAIL: TestAccApplicationInsights_disableGeneratedRule (1246.25s)
FAIL
```

test pass:
```
TF_ACC=1 go test -v ./internal/services/applicationinsights -parallel 20 -test.run=TestAccApplicationInsights_disableGeneratedRule -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApplicationInsights_disableGeneratedRule
=== PAUSE TestAccApplicationInsights_disableGeneratedRule
=== CONT  TestAccApplicationInsights_disableGeneratedRule
--- PASS: TestAccApplicationInsights_disableGeneratedRule (728.37s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/applicationinsights   728.397s

```

### CODE REVIEW

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @teowa, thanks for taking the time to look into fixing this test. Unfortunately we may not be able to take this approach to fixing it. The "Application Insights Smart Detection" action group works slightly differently from the "Failure Anomalies" Alert Rule here. Only one "Application Insights Smart Detection" is created when the first Application Insights resource on the subscription is created and any other Application Insight resources created after this will share that action group. So we wouldn't want to delete this here in case it is being used by a different resource.

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @teowa thanks for taking another look at fixing these tests. Unfortunately we will still need to take a different approach here. Even if there are no other Application Insights within the resource using the Action Group, there could still be an Application Insights in the subscription in a different resource group using the action. There could also be resources of different types using it potentially.

**Comment by teowa** [comment]
Hi @catriona-m, users are not supposed to explicitly use this auto generated action group, and seems there is no such a API to check if the action group is being used by any other resource. If no good solution, maybe this one can be closed?

**Comment by catriona-m** [comment]
Hi @teowa - I agree this probably won't be straightforward to workaround, so I will close this one for now. Thanks!

**Pull request closed without merging**
