### PR TITLE
`azurerm_[windows|linux]_function_app` - refactor `app_settings` processing for updates

### LINKED ISSUE #16244: Updating azurerm_windows_function_app app settings removes FUNCTIONS_WORKER_RUNTIME & WEBSITE_NODE_DEFAULT_VERSION app settings
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

variable resource_group_name {}

data "azurerm_resource_group" "example" {
  name = var.resource_group_name
}

resource "random_string" "suffix" {
  length  = 12
  lower   = true
  number  = true
  upper   = false
  special = false
}

resource "azurerm_storage_account" "fx" {
  name                     = "st${random_string.suffix.result}"
  resource_group_name      = data.azurerm_resource_group.example.name
  location                 = data.azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "example" {
  name                = "plan-${random_string.suffix.result}"
  resource_group_name = data.azurerm_resource_group.example.name
  location            = data.azurerm_resource_group.example.location
  os_type             = "Windows"
  sku_name            = "Y1"
}

resource "azurerm_windows_function_app" "example-njs14" {
  name                = "func-njs14-${random_string.suffix.result}"
  resource_group_name = data.azurerm_resource_group.example.name
  location            = data.azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.fx.name
  storage_account_access_key = azurerm_storage_account.fx.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  # Uncomment this block for second apply:
  # app_settings = {
  #   # Disable default landing page:
  #   AzureWebJobsDisableHomepage = true
  #
  #   # Disable editing in Azure portal:
  #   FUNCTION_APP_EDIT_MODE = "readonly"
  # }

  site_config {
    application_stack {
      node_version = "~14"
    }
  }
}
```

### Debug Output/Panic Output

```shell
terraform does not crash
```

### Expected Behaviour

The provider should have added the AzureWebJobsDisableHomepage & FUNCTION_APP_EDIT_MODE app settings without touching the FUNCTIONS_WORKER_RUNTIME & WEBSITE_NODE_DEFAULT_VERSION app settings.

### Actual Behaviour

FUNCTIONS_WORKER_RUNTIME & WEBSITE_NODE_DEFAULT_VERSION are removed.
AzureWebJobsDisableHomepage & FUNCTION_APP_EDIT_MODE are added

I'm seeing the following diff in app settings [1]:
```diff
❯ diff -ruPN /tmp/appSettingsPre.json /tmp/appSettingsPost.json
--- /tmp/appSettingsPre.json	2022-04-04 16:44:46.041560962 +0200
+++ /tmp/appSettingsPost.json	2022-04-04 16:44:56.388245506 +0200
@@ -10,19 +10,14 @@
     "value": "DefaultEndpointsProtocol=https;AccountName=stea9eg8hzgfam;AccountKey=REDACTED;EndpointSuffix=core.windows.net"
   },
   {
-    "name": "FUNCTIONS_WORKER_RUNTIME",
+    "name": "FUNCTION_APP_EDIT_MODE",
     "slotSetting": false,
-    "value": "node"
+    "value": "readonly"
   },
   {
-    "name": "WEBSITE_NODE_DEFAULT_VERSION",
+    "name": "AzureWebJobsDisableHomepage",
     "slotSetting": false,
-    "value": "~14"
-  },
-  {
-    "name": "AzureWebJobsDashboard",
-    "slotSetting": false,
-    "value": "DefaultEndpointsProtocol=https;AccountName=stea9eg8hzgfam;AccountKey=REDACTED;EndpointSuffix=core.windows.net"
+    "value": "true"
   },
   {
     "name": "WEBSITE_CONTENTSHARE",
@@ -33,6 +28,11 @@
     "name": "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING",
     "slotSetting": false,
     "value": "DefaultEndpointsProtocol=https;AccountName=stea9eg8hzgfam;AccountKey=REDACTED;EndpointSuffix=core.windows.net"
+  },
+  {
+    "name": "AzureWebJobsDashboard",
+    "slotSetting": false,
+    "value": "DefaultEndpointsProtocol=https;AccountName=stea9eg8hzgfam;AccountKey=REDACTED;EndpointSuffix=core.windows.net"
   }
 ]
```

[1] Generate the diff as follows:
```bash
az functionapp config appsettings list -n func-njs14-ea9eg8hzgfam -g REDACTED > /tmp/appSettingsPre.json
# after the second apply
az functionapp config appsettings list -n func-njs14-ea9eg8hzgfam -g REDACTED > /tmp/appSettingsPost.json

# Sort fields of both app settings alphabetically
jq 'sort_by(.name)' < /tmp/appSettingsPre.json > /tmp/appSettingsPreSorted.json
jq 'sort_by(.name)' < /tmp/appSettingsPost.json > /tmp/appSettingsPostSorted.json

# Run diff
diff -ruPN /tmp/appSettingsPreSorted.json /tmp/appSettingsPostSorted.json
```

### Steps to Reproduce

1. terraform apply
2. uncomment `app_settings` tf config block
3. run terraform apply again, TF will propose the following plan:
```BASH
❯ terraform apply -var 'resource_group_name=REDACTED'
random_string.suffix: Refreshing state... [id=ea9eg8hzgfam]
azurerm_service_plan.example: Refreshing state... [id=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/serverfarms/plan-ea9eg8hzgfam]
azurerm_storage_account.fx: Refreshing state... [id=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Storage/storageAccounts/stea9eg8hzgfam]
azurerm_windows_function_app.example-njs14: Refreshing state... [id=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/sites/func-njs14-ea9eg8hzgfam]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_service_plan.example has changed
  ~ resource "azurerm_service_plan" "example" {
        id                           = "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/serverfarms/plan-ea9eg8hzgfam"
        name                         = "plan-ea9eg8hzgfam"
      + tags                         = {}
        # (9 unchanged attributes hidden)
    }

  # azurerm_storage_account.fx has changed
  ~ resource "azurerm_storage_account" "fx" {
        id                                = "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Storage/storageAccounts/stea9eg8hzgfam"
        name                              = "stea9eg8hzgfam"
      + tags                              = {}
        # (33 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

  # azurerm_windows_function_app.example-njs14 has changed
  ~ resource "azurerm_windows_function_app" "example-njs14" {
      + app_settings                      = {}
        id                                = "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/sites/func-njs14-ea9eg8hzgfam"
        name                              = "func-njs14-ea9eg8hzgfam"
      + tags                              = {}
        # (24 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_windows_function_app.example-njs14 will be updated in-place
  ~ resource "azurerm_windows_function_app" "example-njs14" {
      ~ app_settings                      = {
          + "AzureWebJobsDisableHomepage" = "true"
          + "FUNCTION_APP_EDIT_MODE"      = "readonly"
        }
        id                                = "/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Web/sites/func-njs14-ea9eg8hzgfam"
        name                              = "func-njs14-ea9eg8hzgfam"
        tags                              = {}
        # (24 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
```

### Important Factoids

_No response_

### References

I've reported a previous issue related to unwanted removal of `WEBSITE_CONTENT*` app settings [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/15855), this new bug is very similar.

### LINKED ISSUE #16396: `azurerm_linux_function_app` broken if running `terraform apply` a second time
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "regional" {
  name                        = "${var.prefix}-loadgen-${var.location}-func"
  location                    = var.location
  resource_group_name         = var.resource_group_name
  service_plan_id             = azurerm_service_plan.regional.id
  storage_account_name        = azurerm_storage_account.regional.name
  storage_account_access_key  = azurerm_storage_account.regional.primary_access_key
  functions_extension_version = "~4"
  https_only                  = true

  identity {
    type         = "UserAssigned"
    identity_ids = [var.function_user_managed_identity_resource_id]
  }

  key_vault_reference_identity_id = var.function_user_managed_identity_resource_id

  site_config {
    application_stack {
      node_version = "14"
    }
    application_insights_connection_string = var.application_insights_connection_string
  }

  app_settings = merge(
    var.additional_app_settings,
    {
      "PLAYWRIGHT_BROWSERS_PATH"       = "0"
      "ENABLE_ORYX_BUILD"              = "true"
      "SCM_DO_BUILD_DURING_DEPLOYMENT" = "true"
      "WEBSITE_MOUNT_ENABLED"          = "1"
  })
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Terraform should not break the function

### Actual Behaviour

After the first deployment of the Function app, plus the actual Function code, using the Function core tools are complete, it looks like this and all is good:
image

From the ARM template export:
image

Next time I run `terraform apply`, the plan wants to (and will) remove the RUN_FROM_PACAKGE app setting.

image

Afterwards, not only is the package setting gone, but also all the app settings regarding the runtime version. Result: Function is not working anymore.
image

image

Even after running the Function core tools deployment again (which is successful), the Function is still broken beyond repair.

The sample shows a Node Function, but I have the same behavior on a dotnet6 function

### Steps to Reproduce

1) Create a new Function app using Terraform
2) deploy app to it using Function core tools. I'm using `func azure functionapp publish my-func --build local --javascript`
3) Run terraform apply again

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jackofallops**
* `azurerm_linux_function_app` - fix updates to `app_settings`
* `azurerm_windows_function_app` - fix updates to `app_settings`

fixes #16244
fixes #16396

### CODE REVIEW

**Comment by sebader** [comment]
will this also fix https://github.com/hashicorp/terraform-provider-azurerm/issues/16396 ?

**Comment by jackofallops** [comment]
> will this also fix #16396 ?

Hi @sebader - I believe it will, yes. Thanks for the heads up, I'll link these together.

**Review by manicminer — APPROVED** [review]
LGTM 🧨

**Comment by sebader** [comment]
@jackofallops glad to hear it!
What about the WEBSITE_RUN_FROM_PACAKGE setting? I don't see a mention of this in your code changes. Will this stay untouched as it was in the previous version of the Function app resource?

**Comment by jackofallops** [comment]
> @jackofallops glad to hear it! What about the WEBSITE_RUN_FROM_PACAKGE setting? I don't see a mention of this in your code changes. Will this stay untouched as it was in the previous version of the Function app resource?

Hi @sebader - That's a user specified attribute relating to deployments, so won't get an explicit mention in code.  Since the `app_settings` map is multi-purpose, the provider only attempts to manage items in the map that are injected into is as a result of property values "elsewhere" such as storage, or values that are needed to help maintain state/dependency evaluation for Terraform. The specific problem here was that we were not always correctly maintaining existing settings depending on the update scenario / route taken. This should now be resolved, and I've added more test cases we had not previously considered. If you find that there are still issues with this fix in place, I'm happy to re-open the related issue to investigate further.

Thanks!

**Comment by sebader** [comment]
@jackofallops I just tested 3.3.0:

so the `application_stack` is not properly kept in place :) However, WEBSITE_RUN_FROM_PACAKGE still gets removed which does break the deployed Function app until you redeploy again. When looking at the old `azurerm_function_app` resource, it explicitly mentioned this:

image

This behavior seems to be missing from the new resources

**Pull request merged**
