### PR TITLE
`azurerm_windows_function_app` `azurerm_windows_function_app_slot` expose `virtual_network_subnet_id` for vNet integration

### LINKED ISSUE #17481: Support for `virtual_network_subnet_id` in `azurerm_windows_function_app` and `azurerm_windows_function_app_slot` resources
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently this resource needs to attach to a virtual network (for virtual network integration aka vNet integration) using the `azurerm_app_service_virtual_network_swift_connection` resource. 

This method requires full vNet write permissions, which is not ideal with separation of duties (e.g. network team manages all network resources. Application teams can attach resources to the network, but not change other values, e.g. NSG, route table etc).

The [documented and supported](https://docs.microsoft.com/en-gb/azure/app-service/overview-vnet-integration#permissions) method of attaching function apps/app services to vNets is via the `virtual_network_subnet_id` property. 

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_function_app and azurerm_windows_function_app_slot

### Potential Terraform Configuration

```hcl
Expose the `virtual_network_subnet_id` property within the `azurerm_windows_function_app` and  `azurerm_windows_function_app_slot` resources.
```

### References

Issue #15213 was raised because delegated permissions can't be used with the `azurerm_app_service_virtual_network_swift_connection` resource. 

As per https://docs.microsoft.com/en-gb/azure/app-service/overview-vnet-integration#permissions, the supported method to attach an App Service to a subnet is via the new `virtual_network_subnet_id` argument.

### PR DESCRIPTION
**Pull request by bubbletroubles**
This PR adds the `virtual_network_subnet_id` property to the `azurerm_windows_function_app` and `azurerm_windows_function_app_slot` resources which enables associating a web app with a subnet with delegated permissions.

It also fixes an inconsistency in naming of resources in the acceptance tests (e.g. some resources were prefixed with LFA/Linux Function App. Its now WFA consistently).

In the (Update) section of the `azurerm_windows_function_app_slot` resource, the variable for `functionApp` has been updated so its consistent with other Windows/Linux Web/FunctionApp slot variables.

Fixes #17481, #15213

### CODE REVIEW

**Comment by bubbletroubles** [comment]
[WIP] Tests for `azurerm_windows_function_app`

**Comment by bubbletroubles** [comment]
Resources have been updated to no longer require ForceNew and to handle changes successfully. Tests have been updated to
- deploy the resource with no vNet integration
- associate with a subnet
- associate with a different subnet
- disassociate from the subnet

Tests are passing for the `azurerm_windows_function_app` and `azurerm_winddows_function_app_slot` resources.

`azurerm_windows_function_app` tests


`azurerm_windows_function_app_slot` tests

```
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/appservice -run=TestAccWindowsFunctionAppSlot_vNetIntegration -timeout 600m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccWindowsFunctionAppSlot_vNetIntegration
=== PAUSE TestAccWindowsFunctionAppSlot_vNetIntegration
=== RUN   TestAccWindowsFunctionAppSlot_vNetIntegrationUpdate
=== PAUSE TestAccWindowsFunctionAppSlot_vNetIntegrationUpdate
=== CONT  TestAccWindowsFunctionAppSlot_vNetIntegration
=== CONT  TestAccWindowsFunctionAppSlot_vNetIntegrationUpdate
--- PASS: TestAccWindowsFunctionAppSlot_vNetIntegration (366.24s)
--- PASS: TestAccWindowsFunctionAppSlot_vNetIntegrationUpdate (696.94s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice	696.962s

```

**Review by jackofallops — APPROVED** [review]
Thanks @bubbletroubles - LGTM 👍

**Comment by jackofallops** [comment]
Tests look good: 

image

**Pull request merged**
