### PR TITLE
azurerm_logic_app_standard : Updated documentation to use WorkflowStandard app plan

### PR DESCRIPTION
**Pull request by dylanmorley**
ElasticPremium app plans are no longer supported for logic app standard, updated docs to use WorkflowStandard

### CODE REVIEW

**Review by mbfrahry — COMMENTED** [review]
Hey @dylanmorley,  thanks for opening up this PR. I don't have the full context here but our logic app standard tests are using `ElasticPremium` and are still passing. 

This change seems fine but I'd just like a little more clarification before merging it in. Are you seeing an error when trying to spin up this resource with `ElasticPremium`?

**Comment by dylanmorley** [comment]
@mbfrahry yep, just started failing, been OK up until 2021-11-10

"This server farm 'THE-PLAN-NAME' cannot contain Logic Apps. Logic Apps can be deployed only to 'WorkflowStandard' Sku or App Service Environments(ASE)."

Docs have have been updated as well - https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-pricing#standard-single-tenant

I'll get the tests updated as part of this PR.

**Comment by mbfrahry** [comment]
Perfect! Thanks for getting all this sorted

**Comment by mbfrahry** [comment]
Hey @dylanmorley! We're nearly there but the tests are still failing because the new skus need to be the `elastic` kind instead of our defaulted `windows` kind

**Comment by dylanmorley** [comment]
Fixed on https://github.com/hashicorp/terraform-provider-azurerm/pull/14246 as I'm too slow :)

**Pull request closed without merging**
