### PR TITLE
apimanagement: make description field required

### PR DESCRIPTION
**Pull request by Victorp99**
**Summary**
This pull request makes the `Description` field required for the `azurerm_api_management_product` resource. 

Fixes: #13856

Output from acceptance testing:
```
$ make acctests SERVICE='apimanagement' TESTARGS='-run="^TestAccApiManagementProduct_"'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/apimanagement -run="^TestAccApiManagementProduct_" -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccApiManagementProduct_basic
=== PAUSE TestAccApiManagementProduct_basic
=== RUN   TestAccApiManagementProduct_requiresImport
=== PAUSE TestAccApiManagementProduct_requiresImport
=== RUN   TestAccApiManagementProduct_update
=== PAUSE TestAccApiManagementProduct_update
=== RUN   TestAccApiManagementProduct_subscriptionsLimit
=== PAUSE TestAccApiManagementProduct_subscriptionsLimit
=== RUN   TestAccApiManagementProduct_complete
=== PAUSE TestAccApiManagementProduct_complete
=== RUN   TestAccApiManagementProduct_approvalRequiredError
=== PAUSE TestAccApiManagementProduct_approvalRequiredError
=== CONT  TestAccApiManagementProduct_basic
=== CONT  TestAccApiManagementProduct_complete
=== CONT  TestAccApiManagementProduct_approvalRequiredError
=== CONT  TestAccApiManagementProduct_update
=== CONT  TestAccApiManagementProduct_requiresImport
=== CONT  TestAccApiManagementProduct_subscriptionsLimit
--- PASS: TestAccApiManagementProduct_approvalRequiredError (253.04s)
--- PASS: TestAccApiManagementProduct_basic (288.47s)
--- PASS: TestAccApiManagementProduct_complete (349.35s)
--- PASS: TestAccApiManagementProduct_subscriptionsLimit (350.10s)
--- PASS: TestAccApiManagementProduct_update (449.63s)
--- PASS: TestAccApiManagementProduct_requiresImport (499.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/apimanagement	499.832s
```

### CODE REVIEW

**Comment by katbyte** [comment]
Hello @Victorp99 - thank you for this PR, while the portal does seem to mark this property as required these tests are currently passing without a description being passed. Thus i'm not sure this property needs to be required?

**Comment by Victorp99** [comment]
Hello @katbyte! I updated all of the tests that had the `azurerm_api_management_product` resource within the `apimanagement` service to include a description. Are there other tests that I missed that include this resource that is passing without a description?

**Comment by Victorp99** [comment]
I think I misunderstood your question initially. I did not submit the issue this PR addresses, but this fix would allow for a similar user experience when provisioning this resource whether it be via the Portal or Terraform.

**Comment by katbyte** [comment]
It's more that it doesn't appear to be broken in terraform? from our nightly tests i can see these tests pass just fine

image

**Comment by Victorp99** [comment]
It looks like the API endpoint used by the Azure SDK for Go utilized by Terraform does not require a value for the `Description` field, which explains why the tests currently don't fail when omitted. https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-12-01/product/create-or-update. I also have verified that the behavior is the same when using ARM templates. Based on this, we will probably not want to not move forward with this change in order to be in line with the consistent management layer put in place by the Azure Resource Manager service. https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview 

When looking through the documentation, I did find that the `subscription_required` field is required when it shouldn't be based on Azure's documentation. I can create a new issue in order to address this inconsistency between the Azure documentation and Terraform implementation and fix it.

**Comment by katbyte** [comment]
Thanks for looking into it in more detail @Victorp99 - will close this as requested

**Comment by Victorp99** [comment]
Thank you for reviewing my PR!

**Pull request closed without merging**
