### PR TITLE
Load balancer new feature - inbound NAT rule port mapping

### PR DESCRIPTION
**Pull request by xiaxyi**
adding new feature for resource load balancer

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the pr @xiaxyi - we have a test failure to fix up before merge:

```
------- Stdout: -------
=== RUN   TestAccAzureRMLoadBalancerNatRule_zeroPortNumber
=== PAUSE TestAccAzureRMLoadBalancerNatRule_zeroPortNumber
=== CONT  TestAccAzureRMLoadBalancerNatRule_zeroPortNumber
    testcase.go:110: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: "frontend_port" is not a valid port number: 0
        
          with azurerm_lb_nat_rule.test,
          on terraform_plugin_test.tf line 45, in resource "azurerm_lb_nat_rule" "test":
          45:   frontend_port                  = 0
        
--- FAIL: TestAccAzureRMLoadBalancerNatRule_zeroPortNumber (2.67s)
FAIL
```

**Comment by xiaxyi** [comment]
@kt I'm checking with the upstream service team to see if 0 is an accepted value for the port number, I'll update the code once I get any confirmation.

**Comment by xiaxyi** [comment]
@tombuildsstuff Service confirmed the port zero is not being blocked from their side, though it's not an actual port. The tests can be passed in my local environment, I'm checking the acctests in hashicorp side.

**Comment by katbyte** [comment]
tests are still failing for zero:

image

**Comment by xiaxyi** [comment]
@katbyte  Thanks for the comments, I've fixed the test failures

**Review by katbyte — APPROVED** [review]
Thanks @xiaxyi - LKGTM 🌵

**Pull request merged**
