### PR TITLE
`Logz` - Disable testcases as the service is being deprecated by Azure

### PR DESCRIPTION
**Pull request by ms-zhenhua**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Disable all testcases of `Logz` as the service is being deprecated by Azure and all REST APIs will be removed by end of 2025.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_logz_monitor` - disable testcases as the service is being deprecated by Azure
* `azurerm_logz_sub_account` - disable testcases as the service is being deprecated by Azure
* `azurerm_logz_sub_account_tag_rule` - disable testcases as the service is being deprecated by Azure
* `azurerm_logz_tag_rule` - disable testcases as the service is being deprecated by Azure

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @ms-zhenhua. Could you also add deprecation messages to the resources specifying that they will be removed in the next upcoming major version as well like we do elsewhere?

**Comment by ms-zhenhua** [comment]
Hi @stephybun, thanks for your review. I have added the deprecation messages to the document.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @ms-zhenhua. The deprecation messages on the resources themselves are still missing though?

**Comment by ms-zhenhua** [comment]
> Thanks @ms-zhenhua. The deprecation messages on the resources themselves are still missing though?

Hi @stephybun, 
After confirming with the service team, there is no retirement document for now. I have created [this issue](https://github.com/Azure/azure-rest-api-specs/issues/28684) to track this problem.

**Comment by stephybun** [comment]
@ms-zhenhua thanks for raising that issue. I still think we should add the deprecation and removal message to the resource so that users using this are aware and can migrate off. Without the ability to create new instances of these resources we can't effectively maintain them going forward.

Once the deprecation messages have been added to the resources this should be good to go.

**Comment by ms-zhenhua** [comment]
Hi @stephybun, I have added the `DeprecationMessage`, kindly take another review. Thanks.

**Review by stephybun — APPROVED** [review]
Thanks @ms-zhenhua, I hope you don't mind I pushed a small fix to correct the grammar in the messages. LGTM 👍

**Pull request merged**
