### PR TITLE
`azurerm_monitor_scheduled_query_rules_alert_v2` - correctly handling `identity` block if not specified

### LINKED ISSUE #25921: Resource "azurerm_monitor_scheduled_query_rules_alert_v2" created but corrupted
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "total_ingestion_alert" {  
  name = "ingestion-alert"
  location = data.azurerm_resource_group.infrastructure_rg.location
  resource_group_name  = data.azurerm_resource_group.infra_rg.name
  scopes = [data.azurerm_log_analytics_workspace.law.id]
  severity = 2
  evaluation_frequency = "PT6H"
  window_duration = "P1D"
  description = "n/A"
  action {
    action_groups = [azurerm_monitor_action_group.action_group["actiongroup"].id]
  }
  criteria {
    operator = "GreaterThan"
    query = "Usage | where TimeGenerated > ago(24h) | summarize TotalIngestionVolGB = sum(Quantity)/1024.0"
    metric_measure_column = "TotalIngestionVolGB"
    time_aggregation_method = "Total"
    threshold = 5
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Create an alert which is not corrupted.

### Actual Behaviour

Alert is successfully created and visible in Azure Portal. However it is not being fired when criteria are met, and when trying to edit it in the portal this happend:

Screenshot 2024-04-19 141102

No summary is present. Unable to click Review+Save. Next step is Review+Save, even when Review+Save page is already open.

**After contacting Microsoft support, they could not fix the issue, and this is how they described this issue after investigating:**

"If an alert rule is created without managed identity from portal, we don't see that entry in the export template, whereas the terraform includes a Null value even though managed Identity is not enabled. Kindly ask you to reach out to terraform support and highlight this issue, they should probably fix it from their end."

This alert was working fine when creating 2 months ago, however when I need to recreate it again, with the same terraform code, this issue happened. **This issue is present for all the alerts of this kind, not only this one.**

### Steps to Reproduce

1. terraform plan
2. terraform apply

### Important Factoids

N/A

### References

_No response_

### LINKED ISSUE #25995: Creating log search alert rules with no identity leads to incorrect alert creation (last working version 3.97.1)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
provider "azurerm" {
skip_provider_registration = "true"
features{}
}

resource "azurerm_monitor_scheduled_query_rules_alert_v2" "example" {
  name                = "exampleterraform"
  resource_group_name = "REDACTED"
  location            = "eastus"

  evaluation_frequency = "PT10M"
  window_duration      = "PT10M"
  scopes               = ["REDACTED"]
  severity             = 4
  criteria {
    query  = <<-QUERY
Heartbeat
    | take 1
  QUERY
    time_aggregation_method = "Count"
    threshold               = 0
    operator                = "GreaterThan"
    failing_periods {
      minimum_failing_periods_to_trigger_alert = 1
      number_of_evaluation_periods             = 1
    }
  }

  auto_mitigation_enabled          = false
  workspace_alerts_storage_enabled = false
  description                      = "example sqr"
  display_name                     = "example-sqr"
  enabled                          = true
  query_time_range_override        = "PT1H"
  skip_query_validation            = true
}
```

### Debug Output/Panic Output

```shell
No errors
```

### Expected Behaviour

When no identity is included in the configuration, the alert rule should create normally and use the default authentication mechanism, which is not to use identity

### Actual Behaviour

Even though the alert rule is created, the authentication does not work and alert rule never fires. The last working version is 3.97.1

### Steps to Reproduce

Create a log search alert V2 without any identity specified in any module above 3.97.1
Alert will successfully create, but will be unknown in resource health and never fires as authentication does not work.

### Important Factoids

None

### References

None

### LINKED ISSUE #26347: Alert rules do not trigger and cannot be saved in the portal using the "azurerm_monitor_scheduled_query_rules_alert_v2" resource
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "RoutesChangedTest" {
  for_each                         = { for rt in var.route_tables : rt.name => rt if rt.create_route_change_alert == true }
  name                             = "Alert-${var.alerts_data.alerts_subtitle}-RouteTable-RoutesChanged (${each.value.name}) TEST"
  resource_group_name              = var.alerts_data.resource_group_name
  scopes                           = [azurerm_route_table.RouteTable[each.value.name].id]
  description                      = "This alert will trigger when routes are amended in the route table"
  severity                         = 4
  auto_mitigation_enabled          = false
  enabled                          = true
  evaluation_frequency             = "PT5M"
  window_duration                  = "PT4H"
  location                         = var.location
  workspace_alerts_storage_enabled = false
  target_resource_types            = ["Microsoft.Network/routeTables"]
  tags                             = merge(var.resource_tags, { "DataClassification" = "N/A" })

  criteria {
    query = <<-QUERY
      AzureActivity 
        | where OperationNameValue == "MICROSOFT.NETWORK/ROUTETABLES/ROUTES/WRITE"
        | where ActivityStatusValue == "Success"
        | where Properties contains "${each.value.name}"
      QUERY

    resource_id_column      = null
    time_aggregation_method = "Count"
    threshold               = 0
    operator                = "GreaterThan"

    failing_periods {
      number_of_evaluation_periods             = 1
      minimum_failing_periods_to_trigger_alert = 1
    }
  }

  action {
    action_groups = [for grp in each.value.alert_action_groups : local.action_group_resource_map[grp]]
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

1. Alert rules gets created and triggers when a route change is made.
2. Alert can be edited and saved in the Azure portal after creation.

### Actual Behaviour

1. Alert rules gets created but never triggers when making a route change.
2. Alert cannot be saved in the Azure portal. It does not show the review summary and the save button is unresponsive.
3. The issue is not specific to this particular alert. It appears to affect all log query alerts.

### Steps to Reproduce

- Deploy alert with azurerm 3.98.0 onwards.
- The alert works fine with any version prior to 3.98.0.
- 3.98.0 introduced the ability to use the identity block which is documented as an optional parameter. It appears that an identity has to be provided as manually choosing the system managed identity option in the portal allows me to save the alert.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by teowa**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

context: https://github.com/hashicorp/terraform-provider-azurerm/pull/25365

Confirmed with service team that identity `None type means no access, so alert won't be trigger.` So we cannot send `identity[type: None]` but need to omit the identity block if not specified.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
```
TF_ACC=1 go test -v ./internal/services/monitor -parallel 5 -run TestAccMonitorScheduledQueryRulesAlertV2_identity -timeout 2h -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMonitorScheduledQueryRulesAlertV2_identitySystemAssigned
=== PAUSE TestAccMonitorScheduledQueryRulesAlertV2_identitySystemAssigned
=== RUN   TestAccMonitorScheduledQueryRulesAlertV2_identityUpdate
=== PAUSE TestAccMonitorScheduledQueryRulesAlertV2_identityUpdate
=== CONT  TestAccMonitorScheduledQueryRulesAlertV2_identitySystemAssigned
=== CONT  TestAccMonitorScheduledQueryRulesAlertV2_identityUpdate
--- PASS: TestAccMonitorScheduledQueryRulesAlertV2_identitySystemAssigned (210.99s)
--- PASS: TestAccMonitorScheduledQueryRulesAlertV2_identityUpdate (327.96s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor       327.992s
```

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_monitor_scheduled_query_rules_alert_v2` - correctly handling `identity` block if not specified

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #26347
Fixes #25921
Fixes #25995

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🌪️

**Comment by babula000** [comment]
Please review this fix, as it seems to to be applicable for new resources only. For existing alerts identity remains None which is causing the alert to fail.

**Comment by teowa** [comment]
Hi @babula000 , we can only fix the issue for newly create/update alert rule. So a update need to be triggered to fix the issue for existing rules, e.g. modifing the tags.

**Comment by babula000** [comment]
Hi @teowa I have tried updating the tag for the alerts but identity property remain unchanged as None. Please check the scenario from your end

**Comment by teowa** [comment]
Apologize @babula000 , updating other properties doesn't work, you may need to update the `identity` property, or recreate the resource with `terraform apply -replace='azurerm_monitor_scheduled_query_rules_alert_v2.example'`

**Comment by babula000** [comment]
@teowa any plan to provide fix for this in future release ?

**Pull request merged**
