### PR TITLE
azure_kubernetes_service: Add support for BYO cni #15663

### PR DESCRIPTION
**Pull request by ekarlso**

### CODE REVIEW

**Comment by ekarlso** [comment]
@katbyte can i have a rerun?

**Comment by ekarlso** [comment]
Does this look ok to merge or ?

**Comment by ekarlso** [comment]
I tested this locally and it seems that the "none" option is not passed to Azure as my cluster gets `kubenet` for networking instead of being CNI-less then.

**Comment by katbyte** [comment]
got a test failure here @ekarlso 

```
------- Stdout: -------
=== RUN   TestAccDataSourceKubernetesCluster_advancedNetworkingNoneByOCNI
=== PAUSE TestAccDataSourceKubernetesCluster_advancedNetworkingNoneByOCNI
=== CONT  TestAccDataSourceKubernetesCluster_advancedNetworkingNoneByOCNI
    testcase.go:110: Step 1/1 error: Check failed: Check 2/6 error: data.azurerm_kubernetes_cluster.test: Attribute 'network_profile.0.network_plugin' expected "none", got "azure"
--- FAIL: TestAccDataSourceKubernetesCluster_advancedNetworkingNoneByOCNI (537.86s)
FAIL
```

**Comment by ekarlso** [comment]
@katbyte tried to fix this but still getting this error that I dont know why, I even tried setting it to `null`  but it still reports replacement. ```
                  - ip_versions        = [
                      - "IPv4",
                    ] -> null # forces replacement
                    ```

**Comment by ekarlso** [comment]
If anyone could help take a stab at this I'd be grateful!

**Comment by ekarlso** [comment]
All tests are passing @katbyte , could you take a look ?

**Comment by stephybun** [comment]
@ekarlso, thanks for your effort here so far. We generally don't expose the value `none` explicitly within the provider. When a property is omitted it should imply `none` or null, this behaviour is widespread throughout the provider and something that we are continually moving towards. However in this particular case we have some concerns about the UX as explained by [this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/15663#issuecomment-1094728190). We have an upcoming meeting with the AKS team this week where we will discuss the possibility of renaming the enum to a value more representative of this functionality. Until then i'm going to mark this issue as Blocked.

Thanks for your patience.

**Comment by ekarlso** [comment]
@stephybun Any news on this after the meeting with the AKS team? We're in dire need of this one due to Cilium.

**Comment by mr-twendt** [comment]
I used this PR to deploy several clusters with BYO CNI and cilium and it works just fine.

**Pull request merged**
