### PR TITLE
New Resource `azurerm_network_manager_subscription_connection`

### PR DESCRIPTION
**Pull request by teowa**
Notes:

- This resource is the `Virtual network manager hub connection`(with subscription) metioned in [cross-tenant-connection](https://learn.microsoft.com/en-us/azure/virtual-network-manager/concept-cross-tenant#cross-tenant-connection) doc,  testcases of this resource uses a single tenant due to test limitations.
- swagger: https://github.com/Azure/azure-rest-api-specs/blob/df77748f7dff3fe12c13b7262e9b307c719e6918/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/networkManagerConnection.json#L37

Test:
```
TF_ACC=1 go test -v ./internal/services/network -test.run=TestAccNetworkManager -timeout 1440m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccNetworkManager
=== RUN   TestAccNetworkManager/Manager
=== RUN   TestAccNetworkManager/Manager/basic
=== RUN   TestAccNetworkManager/Manager/complete
=== RUN   TestAccNetworkManager/Manager/update
=== RUN   TestAccNetworkManager/Manager/requiresImport
=== RUN   TestAccNetworkManager/SubscriptionConnection
=== RUN   TestAccNetworkManager/SubscriptionConnection/basic
=== RUN   TestAccNetworkManager/SubscriptionConnection/complete
=== RUN   TestAccNetworkManager/SubscriptionConnection/update
=== RUN   TestAccNetworkManager/SubscriptionConnection/requiresImport
--- PASS: TestAccNetworkManager (1895.33s)
    --- PASS: TestAccNetworkManager/Manager (998.15s)
        --- PASS: TestAccNetworkManager/Manager/basic (163.77s)
        --- PASS: TestAccNetworkManager/Manager/complete (200.20s)
        --- PASS: TestAccNetworkManager/Manager/update (354.39s)
        --- PASS: TestAccNetworkManager/Manager/requiresImport (279.80s)
    --- PASS: TestAccNetworkManager/SubscriptionConnection (897.18s)
        --- PASS: TestAccNetworkManager/SubscriptionConnection/basic (222.60s)
        --- PASS: TestAccNetworkManager/SubscriptionConnection/complete (158.37s)
        --- PASS: TestAccNetworkManager/SubscriptionConnection/update (337.07s)
        --- PASS: TestAccNetworkManager/SubscriptionConnection/requiresImport (179.14s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       1896.529s

```

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@teowa can you resolve the merge conflicts?

**Comment by teowa** [comment]
Provisioning two Network Manager using one subscription as scope leads to an error, to avoid test failure, temporary close this PR. 

Please review #19593 first.

**Comment by teowa** [comment]
image

**Review by katbyte — APPROVED** [review]
LGTM 🦕

**Pull request merged**
