### PR TITLE
Support outbound type migration in aks service

### PR DESCRIPTION
**Pull request by MartinForReal**
outbound type migration is added https://learn.microsoft.com/en-us/azure/aks/egress-outboundtype#updating-outboundtype-after-cluster-creation-preview

### CODE REVIEW

**Comment by stephybun** [comment]
Thanks for this PR @MartinForReal.

Although we do support preview features before they've gone GA, talking about this internally, this particular preview feature which is related to the networking of a cluster has several constraints/rules/conditions for when it can be applied, which makes the implementation trickier. Furthermore as you're probably already aware preview features can change in behaviour over time without warning, we've seen this happen with other network related preview features in the past.

Whilst I'd like to thank you or your contribution I'm going to close this PR for the time being. We're happy to reopen and revisit this once this feature goes GA.

**Comment by MartinForReal** [comment]
This feature is now GA.

**Comment by MartinForReal** [comment]
@stephybun Do you think If we can reopen this pr again?

**Comment by stephybun** [comment]
@MartinForReal this has been completed by https://github.com/hashicorp/terraform-provider-azurerm/pull/25021

**Pull request closed without merging**
