### PR TITLE
New Resource: `azurerm_nginx_deployment`

### PR DESCRIPTION
**Pull request by wuxu92**
Support  New service RP `Nginx/Nginx` and new resource of `azurerm_nginx_deployment`.

## Attention: 
the subscription id used to create Nginx deployment need to be configured with a valid Payment. Or create API will response error like `SaaS Purchase Payment Check Failed as validationResponse was {\"isEligible\":false,\"errorMessage\":\"Purchase has failed because we couldn't find a valid credit card nor a payment method associated with your Azure subscription. Please use a different Azure subscription or add......`. If this happens in TeamCity please contact me and I'll feedback to the service team to add this subscription id to their whitelist to skip this check.

```
--- PASS: TestAccNginxDeployment_basic (582.99s)
--- PASS: TestAccNginxDeployment_update (672.30s)
--- PASS: TestAccNginxDeployment_identity (676.70s)
PASS
```

### CODE REVIEW

**Comment by dkuzmenok** [comment]
@wuxu92 
Is there an API document? Can't find any somehow.

**Comment by wuxu92** [comment]
@dkuzmenok swagger link: https://github.com/Azure/azure-rest-api-specs/blob/1d9c9c68844d2b5883621069d5bf0c958841782f/specification/nginx/resource-manager/NGINX.NGINXPLUS/stable/2022-08-01/swagger.json

**Comment by dkuzmenok** [comment]
@wuxu92 Thanks. I see `Identity` is supported. Would be great to include it in the resource.

**Comment by wuxu92** [comment]
@dkuzmenok thanks for your reminder. `identity` added( but only UserIdentity supported )

**Review by katbyte — CHANGES_REQUESTED** [review]
tests are failing:
```
Test Failed

------- Stdout: -------
=== RUN   TestAccNginxDeployment_basic
=== PAUSE TestAccNginxDeployment_basic
=== CONT  TestAccNginxDeployment_basic
=== CONT  TestAccNginxDeployment_basic
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: waiting delete Nginx Deployment (Subscription: "*******"
        Resource Group Name: "acctestRG-auto-220928061149196089"
        Deployment Name: "acctest-220928061149196089"): Code="Failed" Message="The async operation failed." AdditionalInfo=[{"id":"/providers/Nginx.NginxPlus/locations/WESTEUROPE/operationStatuses/373df08e-e8e5-43cd-8db3-f8e22bbf27b0*9CFF51192EFD92717BAA147C73E0CF9FCA635DDC343DE76BC3962DB5C95A1AF1","name":"373df08e-e8e5-43cd-8db3-f8e22bbf27b0*9CFF51192EFD92717BAA147C73E0CF9FCA635DDC343DE76BC3962DB5C95A1AF1","resourceId":"/subscriptions/*******/resourceGroups/acctestRG-auto-220928061149196089/providers/Nginx.NginxPlus/nginxDeployments/acctest-220928061149196089","startTime":"2022-09-28T06:19:47.8571124Z","status":"Failed"}]
        
        waiting delete Nginx Deployment (Subscription:
        "*******"
        Resource Group Name: "acctestRG-auto-220928061149196089"
        Deployment Name: "acctest-220928061149196089"): Code="Failed" Message="The
        async operation failed."
        AdditionalInfo=[{"id":"/providers/Nginx.NginxPlus/locations/WESTEUROPE/operationStatuses/373df08e-e8e5-43cd-8db3-f8e22bbf27b0*9CFF51192EFD92717BAA147C73E0CF9FCA635DDC343DE76BC3962DB5C95A1AF1","name":"373df08e-e8e5-43cd-8db3-f8e22bbf27b0*9CFF51192EFD92717BAA147C73E0CF9FCA635DDC343DE76BC3962DB5C95A1AF1","resourceId":"/subscriptions/*******/resourceGroups/acctestRG-auto-220928061149196089/providers/Nginx.NginxPlus/nginxDeployments/acctest-220928061149196089","startTime":"2022-09-28T06:19:47.8571124Z","status":"Failed"}]
--- FAIL: TestAccNginxDeployment_basic (724.12s)
```

**Comment by katbyte** [comment]
@wuxu92 - i think you'll need to add a TeamCity config to ensure this runs in the right regions:

```
Test Failed

------- Stdout: -------
=== RUN   TestAccNginxDeployment_basic
=== PAUSE TestAccNginxDeployment_basic
=== CONT  TestAccNginxDeployment_basic
=== CONT  TestAccNginxDeployment_basic
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Nginx Deployment (Subscription: "*******"
        Resource Group Name: "acctestRG-auto-220929161345049532"
        Deployment Name: "acctest-220929161345049532"): nginxdeployment.NginxDeploymentClient#DeploymentsCreate: Failure sending request: StatusCode=0 -- Original Error: Code="LocationNotAvailableForResourceType" Message="The provided location 'westus2' is not available for resource type 'NGINX.NGINXPLUS/nginxDeployments'. List of available regions for the resource type is 'westcentralus,australiaeast,westeurope,westus,eastus2'."
        
          with azurerm_nginx_deployment.test,
          on terraform_plugin_test.tf line 52, in resource "azurerm_nginx_deployment" "test":
          52: resource "azurerm_nginx_deployment" "test" {
        
        creating Nginx Deployment (Subscription:
        "*******"
        Resource Group Name: "acctestRG-auto-220929161345049532"
        Deployment Name: "acctest-220929161345049532"):
        nginxdeployment.NginxDeploymentClient#DeploymentsCreate: Failure sending
        request: StatusCode=0 -- Original Error:
        Code="LocationNotAvailableForResourceType" Message="The provided location
        'westus2' is not available for resource type
        'NGINX.NGINXPLUS/nginxDeployments'. List of available regions for the
        resource type is 'westcentralus,australiaeast,westeurope,westus,eastus2'."
--- FAIL: TestAccNginxDeployment_basic (84.46s)
```

**Comment by wuxu92** [comment]
@katbyte yes, it's related to the region. I'm reaching out to the service team to confirm this. I test successfully with `eastus2euap` region but this region not available to TC subscription.

**Comment by wuxu92** [comment]
@katbyte Nginx deployment not supported in westus2 for now, I changed the location to eastus2 in the environment it is success now

image

**Review by katbyte — APPROVED** [review]
Thanks @wuxu92 ! LGTM 🤖

**Pull request merged**
