### PR TITLE
`example`: Add examples for Azure Disk Encryption VM Extension and Managed Disk Property

### PR DESCRIPTION
**Pull request by myc2h6o**

### CODE REVIEW

**Comment by katbyte** [comment]
could we fix the linting here @myc2h6o ?

**Comment by myc2h6o** [comment]
Hi @katbyte the linting is throwing below error, but `azurerm_sentinel_watchlist_item` is actually supported. It's using SDK v2, maybe the linting validation needs an update?
```
Error: Invalid resource type
│ 
│   on main.tf line 43, in resource "azurerm_sentinel_watchlist_item" "example":
│   43: resource "azurerm_sentinel_watchlist_item" "example" {
│ 
│ The provider hashicorp/azurerm does not support resource type
│ "azurerm_sentinel_watchlist_item".
```

**Comment by myc2h6o** [comment]
@katbyte I think the error for `azurerm_sentinel_watchlist_item` is because the new release was not generated at the time I ran the lint. Now there is another issue in this example after the new release, where the property name is mismatch, which should be fixed by #15421


I've actually added another example in this pr, to show what the config looks like after deprecating the required property `enabled` in `managed_disk_resource`. The linting is failing because of this new example, because `enabled` was a `Required` property, It should work fine after #15317 is checked in and released

```
Validating ./examples/managed-disks/azure-disk-encryption..
╷
│ Error: Missing required argument
│ 
│   on main.tf line 80, in resource "azurerm_managed_disk" "test":
│   80:   encryption_settings {
│ 
│ The argument "enabled" is required, but no definition was found.
```

**Comment by myc2h6o** [comment]
Hi @katbyte I've fixed the linting. And after further investigating, I found the Azure Disk Encryption is being suppressed by [Server-side Encryption](https://docs.microsoft.com/azure/virtual-machines/disk-encryption) instead which uses [disk_encryption_set_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#disk_encryption_set_id) starting from 2.0. I've added the redirect notice in the Readme.md. Although this feature doesn't suit Terraform well because the `azurerm_virtual_machine_extension` here will create an unmanaged Secret in the Key Vault, Azure Disk Encryption has some ability that the Server-side Encryption doesn't have, and due to the not-straightforward configuration, maybe adding these examples with redirect notice would be helpful?

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM 👍

**Pull request merged**
