### PR TITLE
New resource `azurerm_storage_disks_pool`

### PR DESCRIPTION
**Pull request by lonegunmanb**
Add new resource for [Azure Disks Pool](https://docs.microsoft.com/en-us/azure/virtual-machines/disks-pools)

=== RUN   TestAccStorageDisksPool_basic
=== PAUSE TestAccStorageDisksPool_basic
=== CONT  TestAccStorageDisksPool_basic
--- PASS: TestAccStorageDisksPool_basic (846.68s)
=== RUN   TestAccStorageDisksPool_standard
=== PAUSE TestAccStorageDisksPool_standard
=== CONT  TestAccStorageDisksPool_standard
--- PASS: TestAccStorageDisksPool_standard (827.07s)
=== RUN   TestAccStorageDisksPool_premium
=== PAUSE TestAccStorageDisksPool_premium
=== CONT  TestAccStorageDisksPool_premium
--- PASS: TestAccStorageDisksPool_premium (806.30s)
=== RUN   TestAccStorageDisksPool_requiresImport
=== PAUSE TestAccStorageDisksPool_requiresImport
=== CONT  TestAccStorageDisksPool_requiresImport
--- PASS: TestAccStorageDisksPool_requiresImport (905.59s)

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
looks like we have some test failures
```
------- Stdout: -------
=== RUN   TestAccStorageDisksPool_premium
=== PAUSE TestAccStorageDisksPool_premium
=== CONT  TestAccStorageDisksPool_premium
    testcase.go:109: Step 1/2 error: Error running apply: exit status 1
        
        Error: creation of "Storage Disks Pool: (Disk Pool Name \"acctest-diskspool-xt0go\" / Resource Group \"acctestRG-diskspool-211111173620746279\")": storagepool.DiskPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="400" Message="invalid request; request is malformed or invalid; unable to read `/subscriptions/*******/resourceGroups/acctestRG-diskspool-211111173620746279/providers/Microsoft.Network/virtualNetworks/acctest-vnet-211111173620746279/subnets/acctest-subnet-211111173620746279` due to permissions"
        
          with azurerm_storage_disks_pool.test,
          on terraform_plugin_test.tf line 34, in resource "azurerm_storage_disks_pool" "test":
          34: resource "azurerm_storage_disks_pool" "test" {
        
        creation of "Storage Disks Pool: (Disk Pool Name \"acctest-diskspool-xt0go\"
        / Resource Group \"acctestRG-diskspool-211111173620746279\")":
        storagepool.DiskPoolsClient#CreateOrUpdate: Failure sending request:
        StatusCode=400 -- Original Error: Code="400" Message="invalid request;
        request is malformed or invalid; unable to read
        `/subscriptions/*******/resourceGroups/acctestRG-diskspool-211111173620746279/providers/Microsoft.Network/virtualNetworks/acctest-vnet-211111173620746279/subnets/acctest-subnet-211111173620746279`
        due to permissions"
--- FAIL: TestAccStorageDisksPool_premium (112.00s)
FAIL

```

**Comment by lonegunmanb** [comment]
> looks like we have some test failures
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccStorageDisksPool_premium
> === PAUSE TestAccStorageDisksPool_premium
> === CONT  TestAccStorageDisksPool_premium
>     testcase.go:109: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: creation of "Storage Disks Pool: (Disk Pool Name \"acctest-diskspool-xt0go\" / Resource Group \"acctestRG-diskspool-211111173620746279\")": storagepool.DiskPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="400" Message="invalid request; request is malformed or invalid; unable to read `/subscriptions/*******/resourceGroups/acctestRG-diskspool-211111173620746279/providers/Microsoft.Network/virtualNetworks/acctest-vnet-211111173620746279/subnets/acctest-subnet-211111173620746279` due to permissions"
>         
>           with azurerm_storage_disks_pool.test,
>           on terraform_plugin_test.tf line 34, in resource "azurerm_storage_disks_pool" "test":
>           34: resource "azurerm_storage_disks_pool" "test" {
>         
>         creation of "Storage Disks Pool: (Disk Pool Name \"acctest-diskspool-xt0go\"
>         / Resource Group \"acctestRG-diskspool-211111173620746279\")":
>         storagepool.DiskPoolsClient#CreateOrUpdate: Failure sending request:
>         StatusCode=400 -- Original Error: Code="400" Message="invalid request;
>         request is malformed or invalid; unable to read
>         `/subscriptions/*******/resourceGroups/acctestRG-diskspool-211111173620746279/providers/Microsoft.Network/virtualNetworks/acctest-vnet-211111173620746279/subnets/acctest-subnet-211111173620746279`
>         due to permissions"
> --- FAIL: TestAccStorageDisksPool_premium (112.00s)
> FAIL
> ```

Hi @katbyte,

Apology for this failure, I forgot to mention a prerequisite that was not listed in the official document, we must register `Microsoft.StoragePool` resource provider to our subscription first as this [blog](https://www.virtualworkloads.com/2021/07/deploy-and-attach-azure-disk-pool-to-azure-vmware-solution-private-cloud/) told us at the beginning. I've updated document for this.

And for other incoming disks pool resources, we must make sure our service principal has permission to list and read other service principal's info like this:

```hcl
data "azuread_service_principal" "example" {
  display_name = "StoragePool Resource Provider"
}
```

It's required in both our acc tests and document, but for now, I think register `Microsoft.StoragePool` would fix disks pool's acc test.

If you encounter any further issues, please let me know. Thanks!

**Comment by lonegunmanb** [comment]
Hi @katbyte ,

Please forgive my previous mumbo jumbo, I'm a newbie to this project and Azure.
I've added `Microsoft.StoragePool` to required providers, and acc tests are passed now (I've checked on team city).

**Review by katbyte — APPROVED** [review]
Thanks @lonegunmanb! all the tests pass now 🙁 👍 🚀

**Comment by lonegunmanb** [comment]
Thanks @katbyte , this is my first new resource pr!

**Pull request merged**
