### PR TITLE
New Data Source: `private_dns_zone_virtual_network_link`

### PR DESCRIPTION
**Pull request by skatsaounis**
Resolves: #17760

### CODE REVIEW

**Comment by skatsaounis** [comment]
Test is successful:

```
% go test . -v -run "TestAccDataSourcePrivateDnsZoneVirtualNetworkLink_basic"
=== RUN   TestAccDataSourcePrivateDnsZoneVirtualNetworkLink_basic
=== PAUSE TestAccDataSourcePrivateDnsZoneVirtualNetworkLink_basic
=== CONT  TestAccDataSourcePrivateDnsZoneVirtualNetworkLink_basic
--- PASS: TestAccDataSourcePrivateDnsZoneVirtualNetworkLink_basic (418.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/privatedns	419.532s
```

**Comment by skatsaounis** [comment]
@katbyte another one in the DNS family. Feel free to review 😃

**Review by katbyte — APPROVED** [review]
Thanks @skatsaounis ! LGTM 🔝

**Comment by zic04** [comment]
Hello,

I encounter a problem :

```
data "azurerm_private_dns_zone_virtual_network_link" "***" {
  name                  = "***"
  resource_group_name   = "***"
  private_dns_zone_name = "privatelink.mysql.database.azure.com"
  provider              = azurerm.***
}
```

resource "azurerm_mysql_flexible_server" "***l" {
  count                  = var.*** ? 1 : 0
  name                   = "***"
  resource_group_name    = data.azurerm_resource_group.***.name
  location               = data.azurerm_resource_group.resource_group_cb.location
  administrator_login    = var.administrator_login_mysqlfl
  administrator_password = random_password.password.result
  sku_name               = "GP_Standard_D2ds_v4"
  zone                   = "3"
  delegated_subnet_id    = data.azurerm_subnet.subnet_***.id
  private_dns_zone_id    = data.azurerm_private_dns_zone_virtual_network_link.***.id
  provider               = azurerm.***
}

Error :  Error: parsing "*****": expected 8 segments within the Resource ID

Provider : 3.23.0

**Pull request merged**
