### PR TITLE
`azurerm_storage_account` - Add code check for `restore_policy` prerequisites

### LINKED ISSUE #19799: blob_properties.restore_policy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_storage

### Terraform Configuration Files

```hcl
# azurerm_storage_account
  create_storage_account                   = true
  storage_account_name                     = "sa03example${random_string.this.result}"
  storage_account_access_tier              = "Hot"
  storage_account_account_replication_type = "GRS"
  storage_account_blob_properties = {
    "blob_property_01" = {
      versioning_enabled            = true
      change_feed_enabled           = false
      change_feed_retention_in_days = null
      default_service_version       = "2020-06-12"
      last_access_time_enabled      = false
      cors_rules = {
        "cors_rule_01" = {
          allowed_headers    = ["header01", "header02"]
          allowed_methods    = ["GET", "PUT", "POST"]
          allowed_origins    = ["test01.com", "test02.de"]
          exposed_headers    = ["header01", "header02"]
          max_age_in_seconds = 4000
        }
      }
      delete_retention_policies = {
        "retention_policy_01" = {
          days = 9
        }
      }
      container_delete_retention_policies = {}
      restore_policy = {
        "restore_policy_01" = {
          days = 7
        }
      }
    }
  }
```

### Debug Output/Panic Output

```shell
╷
│ Error: updating Azure Storage Account `blob_properties` "sa03examplerpv": storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ConflictFeatureEnabled" Message="Conflicting feature 'restorePolicy' is enabled. Please disable it and retry."
│ 
│   with module.default03.azurerm_storage_account.this[0],
│   on ../../main.tf line 67, in resource "azurerm_storage_account" "this":
│   67: resource "azurerm_storage_account" "this" {
│ 
╵
```

### Expected Behaviour

storage account created with restore policy applied to it

### Actual Behaviour

╷
│ Error: updating Azure Storage Account `blob_properties` "sa03examplerpv": storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ConflictFeatureEnabled" Message="Conflicting feature 'restorePolicy' is enabled. Please disable it and retry."
│ 
│   with module.default03.azurerm_storage_account.this[0],
│   on ../../main.tf line 67, in resource "azurerm_storage_account" "this":
│   67: resource "azurerm_storage_account" "this" {
│ 
╵

### Steps to Reproduce

N/A

### Important Factoids

_No response_

### References

missing dependency not mentioned in terraform documentation or tested for in code itself : 
"Use point-in-time restore to restore one or more containers to an earlier state. If point-in-time restore is enabled, then versioning, **change feed**, and blob soft delete must also be enabled." instead of this that is reported as dependency on azure portal we have : 
"A restore_policy block as defined below. This must be used together with delete_retention_policy set and versioning_enabled set to true."

### PR DESCRIPTION
**Pull request by magodo**
Fix #19799

## Test

```shell
terraform-provider-azurerm on  storage_restore_policy_check via 🐹 v1.19
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/storage -run='TestAccStorageAccount_blobProperties'
=== RUN   TestAccStorageAccount_blobProperties
=== PAUSE TestAccStorageAccount_blobProperties
=== RUN   TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled
=== PAUSE TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled
=== RUN   TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders
=== PAUSE TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders
=== CONT  TestAccStorageAccount_blobProperties
=== CONT  TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders
=== CONT  TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled
--- PASS: TestAccStorageAccount_blobProperties_containerAndLastAccessTimeDisabled (124.90s)
--- PASS: TestAccStorageAccount_blobPropertiesEmptyAllowedExposedHeaders (149.26s)
--- PASS: TestAccStorageAccount_blobProperties (254.03s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/storage       254.041s
```

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
I'm seeing an import failure @magodo : 
```
testcase.go:110: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=5) {
         (string) (len=18) "share_properties.#": (string) (len=1) "1",
         (string) (len=20) "share_properties.0.%": (string) (len=1) "3",
         (string) (len=37) "share_properties.0.retention_policy.#": (string) (len=1) "1",
         (string) (len=39) "share_properties.0.retention_policy.0.%": (string) (len=1) "1",
         (string) (len=42) "share_properties.0.retention_policy.0.days": (string) (len=1) "7"
        }
        
        
        (map[string]string) {
        }
--- FAIL: TestAccStorageAcc
```

**Comment by magodo** [comment]
@katbyte I believe that error is not introduced by this PR, that seems to be some intermittent error by storage RP...

**Comment by katbyte** [comment]
@magodo - still something we should fix but can confirm it is intermittent:

image

**Review by katbyte — APPROVED** [review]
LGTM 💾

**Comment by katbyte** [comment]
@magodo - just need to fix up CI

**Pull request merged**
