### PR TITLE
Update storage api to 2021-09-01

### PR DESCRIPTION
**Pull request by magodo**
The motivation is that the new property required in #17513 is available only in 2021-09-01.

Tested for storage account test cases (one failed case is passing when rerunning it):

image

### CODE REVIEW

**Comment by dkuzmenok** [comment]
@tombuildsstuff @katbyte It would be great to merge this one.
There are new fields in that new API available for storage accounts. 
I would like to contribute that part, once this one is merged.

Thanks

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @magodo

**Comment by dkuzmenok** [comment]
@magodo Will you do the addition of new fields from new API? Or I can work on that?

**Comment by magodo** [comment]
@dkuzmenok I was working on this, while I realized there needs a non-trivial refactor on the underlying SDK to support the new dns zone based URL: https://github.com/tombuildsstuff/giovanni/issues/62

**Pull request merged**
