### PR TITLE
`azurerm_role_assignment` - Support `scope` to be `/providers/Subscription`

### LINKED ISSUE #17397: Unable to create role assignment at resource provider scope
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "role1" {
  scope                = "/providers/Microsoft.Subscription"
  role_definition_name = "Reader"
  principal_id         = azuread_service_principal.sp-testtest1.object_id
}
```

### Debug Output/Panic Output

```shell
% terraform plan         
╷
│ Error: ID was missing the `enrollmentAccounts` element
│ 
│   with azurerm_role_assignment.role1,
│   on main.tf line 14, in resource "azurerm_role_assignment" "role1":
│   14:   scope                = "/providers/Microsoft.Subscription"
│ 
╵
╷
│ Error: parsing "/providers/Microsoft.Subscription": expected 4 segments within the Resource ID but got 2 for "/providers/Microsoft.Subscription"
│ 
│   with azurerm_role_assignment.role1,
│   on main.tf line 14, in resource "azurerm_role_assignment" "role1":
│   14:   scope                = "/providers/Microsoft.Subscription"
│ 
╵
╷
│ Error: parsing "/providers/Microsoft.Subscription": parsing segment "subscriptions": expected the segment "providers" to be "subscriptions"
│ 
│   with azurerm_role_assignment.role1,
│   on main.tf line 14, in resource "azurerm_role_assignment" "role1":
│   14:   scope                = "/providers/Microsoft.Subscription"
│ 
╵
╷
│ Error: parsing "/providers/Microsoft.Subscription": expected 4 segments within the Resource ID but got 2 for "/providers/Microsoft.Subscription"
│ 
│   with azurerm_role_assignment.role1,
│   on main.tf line 14, in resource "azurerm_role_assignment" "role1":
│   14:   scope                = "/providers/Microsoft.Subscription"
│ 
╵
╷
│ Error: Can not parse "scope" as a resource id: No subscription ID found in: "providers/Microsoft.Subscription"
│ 
│   with azurerm_role_assignment.role1,
│   on main.tf line 14, in resource "azurerm_role_assignment" "role1":
│   14:   scope                = "/providers/Microsoft.Subscription"
│ 
╵
```

### Expected Behaviour

I expect the role assignment to be created.

According to Microsoft feedback in this thread: https://docs.microsoft.com/en-us/answers/questions/604740/user-does-not-have-access-microsoftsubscriptionali.html, it should be possible to create role assignments on the resource provider top level. Terraform's syntax checking seems to block this.

Note that assigning roles at such scope *is* possible in Powershell and az CLI:
```Connect-AzAccount -Tenant xxxxxxxx

$sp = Get-AzADServicePrincipal -DisplayName "appdisplayname"

New-AzRoleAssignment -ObjectId $[sp.Id](http://sp.id/) -Scope /providers/Microsoft.Subscription -RoleDefinitionName "Reader"
```

### Actual Behaviour

Terraform's syntax checking seems to block this scope type.

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by magodo**
Fix #17397.

The prerequisite to assign role to the subscription scope is described at https://docs.microsoft.com/en-us/answers/questions/604740/user-does-not-have-access-microsoftsubscriptionali.html. I've elevated my running account and manage the role assignment to anther sp using this scope locally successfully, via `terraform apply/plan/destroy`.

I've also tested for the management group scope, i.e. `/providers/Microsoft.Management`, where the API failed saying that this is an invalid scope.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Could we add a test for this?

**Comment by magodo** [comment]
@katbyte Unfortunately, I was only able to manage to run it via my user account. When I use a SP, the API failed with:

```
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'f4ed124d-*-*-*-*' with object id 'f4ed124d-*-*-*-*' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/providers/Microsoft.Subscription/providers/Microsoft.Authorization/roleAssignments/85b074a6-*-*-*-*' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

**Comment by katbyte** [comment]
we should still have a test for it? and if that is a limitation we should be documenting it?

**Comment by magodo** [comment]
@katbyte I believe currently we don't have a way to test via CLI auth? I've put down a comment to mention the prerequisite when setting the `scope` to `/providers/Subscription`.

**Review by katbyte — COMMENTED** [review]
@magodo - you can still write the test and run them locally, we just don't have a way to run them in TC yet so if you can detect UA/no SP and skip that would be good

**Comment by magodo** [comment]
@katbyte I've added the test which will always be skipped. As I failed to figure out a way to run acctest via CLI auth (as the `PreCheck` will always ensure the `ARM_CLIENT_ID` and `ARM_CLIENT_SECRET` is specified). The only way to fallback to CLI auth is to inlining the `data.ResourceTest`? But I think this is would expose the SDK details to the test package, which is to be avoided?

**Review by katbyte — APPROVED** [review]
as long as the test is there for future use all good - LGTM provided the config passes for you locally

**Pull request merged**
