### PR TITLE
azurerm_kubernetes_cluster - Adding support for VerticalPodAutoscaler

### PR DESCRIPTION
**Pull request by heoelri**
This PR adds support to configure the VerticalPodAutoscaler as requested in issue https://github.com/hashicorp/terraform-provider-azurerm/issues/19022. It extendds the `workload_autoscaler_profile` with two new arguments:

* `vpa_enabled` to enable or disable the vpa 
* `vpa_config` to configure the vpa

The `vpa_config` block has two arguments:

* `update_mode` which can be set to `Auto`, `Initial`, `Off` or `Recreate`
* `controlled_values` which  can be set to either `RequestsAndLimits` or `RequestsOnly`

Configuration example:

```hcl

  workload_autoscaler_profile {
    keda_enabled = false
    vpa_enabled = false

    vpa_config {
        update_mode = "Off"
        controlled_values = "RequestsOnly" # "RequestsAndLimits"
    }
  }
```

### CODE REVIEW

**Comment by heoelri** [comment]
@olsenme looping you in here as you're the creator of https://github.com/Azure/AKS/issues/3096. 

What's the point in defining the `UpdateMode` globally at the AKS cluster-level, when this is (needs to be) defined in each `VerticalPodAutoscaler` definition. Can you give me some background why, when to define it globally?

**Comment by heoelri** [comment]
Still unsure which syntax is better:

```hcl
workload_autoscaler_profile {
    vpa_enabled = true
    vpa_config {
        update_mode = "Off"
        controlled_values = "RequestsAndLimits"
    }
}
```

or 

```hcl
workload_autoscaler_profile {
    vpa_config {
        enabled = true
        update_mode = "Off"
        controlled_values = "RequestsAndLimits"
    }
}
```

The second option is probably the better one to align with what the API provides and expects.

**Comment by stephybun** [comment]
@heoelri, the behaviour of blocks in the AKS resource should be if block is present -> feature is enabled, if it's absent -> feature is disabled, we don't expose the `enabled` field to users.

**Comment by heoelri** [comment]
> @heoelri Heyko Oelrichs FTE, the behaviour of blocks in the AKS resource should be if block is present -> feature is enabled, if it's absent -> feature is disabled, we don't expose the `enabled` field to users.

Thanks @stephybun. That makes total sense. I started with `vpa_enabled` in alignment with the already existing `keda_enabled` attribute of `workload_autoscaler_profile`. While implementing it I noticed that the API provides more options for vpa than for keda. Though I'm still not clear if these options, especially `UpdateMode` on a cluster-level really make sense.

**Comment by stephybun** [comment]
@heoelri any updates on this?

**Comment by pmjacinto** [comment]
Any news on this?

**Pull request closed without merging**
