### PR TITLE
`azurerm_windows_web_app`, `azurerm_windows_web_app_slot`, `azurerm_linux_web_app`, `azurerm_linux_web_app_slot`, `azurerm_windows_function_app`, `azurerm_windows_function_app_slot`, `azurerm_linux_function_app`, `azurerm_linux_function_app_slot` - add runtime update

### PR DESCRIPTION
**Pull request by xiaxyi**
1. Add support for runtime stack - node and dotnet
`azurerm_windows_web_app`, `azurerm_windows_web_app_slot`: add `~20` for `node_version` in `application_stack`
`azurerm_linux_web_app`, `azurerm_linux_web_app_slot`: add `8.0` for `dotnet_version` & `20-lts` for `node_version` in `application_stack`
`azurerm_windows_function_app`, `azurerm_windows_function_app_slot`: add `~20` for `node_version` in `application_stack`
`azurerm_linux_function_app`, `azurerm_linux_function_app_slot`: add `20` for `node_version` in `application_stack`

resolve issue:https://github.com/hashicorp/terraform-provider-azurerm/issues/23528

### CODE REVIEW

**Comment by joshvito** [comment]
Came here looking to implement 20-lts, Thanks Friends!

**Comment by petergoldstein** [comment]
@xiaxyi Is there anything blocking this being merged in the next patch version?  It's been open for a bit.

**Comment by xanderdeseyn** [comment]
We are also waiting on this. Any release date in sight?

**Comment by LordA98** [comment]
We are also waiting on this.  Is there an update on when this will be merged?

**Comment by francisceril** [comment]
What's the update for this? Neither 18-lts nor 20-lts work.

**Comment by katbyte** [comment]
Now that the API has been updated can you please resolve the conflicts here?

**Review by katbyte — DISMISSED** [review]
please fix the tests:
```
------- Stdout: -------
=== RUN   TestAccLinuxWebApp_requiresImport
=== PAUSE TestAccLinuxWebApp_requiresImport
=== CONT  TestAccLinuxWebApp_requiresImport
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating App Service Plan (Subscription: "*******"
        Resource Group Name: "acctestRG-240209200140996370"
        Server Farm Name: "acctestASP-240209200140996370"): performing CreateOrUpdate: unexpected status 409 with response: {"Code":"Conflict","Message":"The pricing tier 'Basic' is not allowed in this resource group. Use this link to learn more: https://aka.ms/app-service-plan-scale-not-allowed","Target":null,"Details":[{"Message":"The pricing tier 'Basic' is not allowed in this resource group. Use this link to learn more: https://aka.ms/app-service-plan-scale-not-allowed"},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"04114","MessageTemplate":"The pricing tier '{0}' is not allowed in this resource group. Use this link to learn more: https://aka.ms/app-service-plan-scale-not-allowed","Parameters":["Basic"],"Code":"Conflict","Message":"The pricing tier 'Basic' is not allowed in this resource group. Use this link to learn more: https://aka.ms/app-service-plan-scale-not-allowed"}}],"Innererror":null}
        
          with azurerm_service_plan.test,
          on terraform_plugin_test.tf line 28, in resource "azurerm_service_plan" "test":
          28: resource "azurerm_service_plan" "test" {
        
        creating App Service Plan (Subscription:
        "*******"
        Resource Group Name: "acctestRG-240209200140996370"
        Server Farm Name: "acctestASP-240209200140996370"): performing
        CreateOrUpdate: unexpected status 409 with response:
        {"Code":"Conflict","Message":"The pricing tier 'Basic' is not allowed in this
        resource group. Use this link to learn more:
        https://aka.ms/app-service-plan-scale-not-allowed","Target":null,"Details":[{"Message":"The
        pricing tier 'Basic' is not allowed in this resource group. Use this link to
        learn more:
        https://aka.ms/app-service-plan-scale-not-allowed"},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"04114","MessageTemplate":"The
        pricing tier '{0}' is not allowed in this resource group. Use this link to
        learn more:
        https://aka.ms/app-service-plan-scale-not-allowed","Parameters":["Basic"],"Code":"Conflict","Message":"The
        pricing tier 'Basic' is not allowed in this resource group. Use this link to
        learn more:
        https://aka.ms/app-service-plan-scale-not-allowed"}}],"Innererror":null}
--- FAIL: TestAccLinuxWebApp_requiresImport (105.96s)
FAIL
```

**Comment by xiaxyi** [comment]
Thanks @katbyte for the review, tests are good 
image

**Review by jackofallops — APPROVED** [review]
Thanks @xiaxyi - This LGTM 👍

**Comment by jackofallops** [comment]
Tests look good:

image

**Pull request merged**
