### PR TITLE
`Site Recovery` - swap sdk and upgrade to 2022-10-01, support `network_interface.is_primary` property

### PR DESCRIPTION
**Pull request by ziyeqf**
swap sdk to `go-azure-sdk` and upgrade to `2022-10-01`

Screenshot 2022-12-07 at 12 12 46
rerun the failed one
Screenshot 2022-12-07 at 12 14 01

`TestAccSiteRecoveryReplicatedVm_des` keeps timing out for a long while both in main branch and this branch. Can we leave it for now? I will fix it in another PR when I find a way.

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM once conflicts are resolved 🦀

**Review by katbyte — CHANGES_REQUESTED** [review]
CI failure

**Comment by ziyeqf** [comment]
hi @katbyte, could you please take a look at this?

**Review by katbyte — CHANGES_REQUESTED** [review]
@ziyeqf - CI is still fialing and the tests are with: 
```
------- Stdout: -------
=== RUN   TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
=== PAUSE TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
=== CONT  TestAccSiteRecoveryReplicatedVm_targetDiskEncryption
    testcase.go:110: Step 1/2 error: Error running pre-apply refresh: exit status 1
        
        Error: InternalValidate
        
          with provider["registry.terraform.io/hashicorp/azurerm"],
          on terraform_plugin_test.tf line 13, in provider "azurerm":
          13: provider "azurerm" {
        
        Internal validation of the provider failed! This is always a bug
        with the provider itself, and not a user issue. Please report
        this bug:
        
        1 error occurred:
        	* resource azurerm_site_recovery_replicated_vm: is_primary: Default must be
        nil if computed
        
        
--- FAIL: TestAccSiteRecoveryReplicatedVm_targetDiskEncryption (11.36s)
FAIL
```

**Review by katbyte — APPROVED** [review]
LGTM 💾

**Pull request merged**
