### PR TITLE
`azurerm_managed_disk` - support for `PremiumV2_LRS`

### PR DESCRIPTION
**Pull request by neil-yechenwei**
This PR includes two changes.

1. Upgrade API version to 2022-03-02 for Disks.
2. Support new storage account type `PremiumV2_LRS` for azurerm_managed_disk. This feature only exists in [API version 2022-03-02](https://github.com/Azure/azure-rest-api-specs/blob/01efd1f79d22d073b063554319562978c0bb1b9c/specification/compute/resource-manager/Microsoft.Compute/stable/2022-03-02/DiskRP/disk.json#L537).

### CODE REVIEW

**Comment by neil-yechenwei** [comment]
Updated this PR to use Pandora SDK for Disks.

**Comment by neil-yechenwei** [comment]
Note: The TCs in below screenshot are also failed in Teamcity Nightly Run due to same error. So they aren't related with this PR.
image
image
image

**Review by katbyte — CHANGES_REQUESTED** [review]
LGTM aside from test failures:
image

the resource group not deleting is likely due to a delete call finishing to early. failing in main or not we should be fixing them as we are doing an SDK upgrade where its exceptionally important to test

**Comment by neil-yechenwei** [comment]
@katbyte , please set specific region like `west europe` while testing in teamcity because some settings are restricted in some region.

**Comment by myc2h6o** [comment]
I happened to be fixing the test failures in `compute` service. For specific test `TestAccManagedDisk_storageAccountType` that needs to be run in `west europe`, maybe @neil-yechenwei you can try a similar approach as #18331, setting `data.Locations.Primary = "westeurope"` in the test config. And one of the merge conflict reasons might be #18303 which fixes `TestAccManagedDisk_import` as well, could you help check if that's the case?

**Comment by neil-yechenwei** [comment]
@myc2h6o , I've updated code. Thanks for your reminder.

**Review by katbyte — APPROVED** [review]
LGTM 🌻

**Comment by neil-yechenwei** [comment]
@katbyte , Kindly ping. Is this PR able to be merged?

**Pull request merged**
