### PR TITLE
``azurerm_windows_web_app_slot`` - FIX node version reset to "0.12.1" during update

### PR DESCRIPTION
**Pull request by Apokalypt**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Right now, the NodeJS environment variable can be unset during an update. This PR ensure that the version is correctly set if we need to update AppSettings for any reason
I also remove the duplicate code to avoid patching/updating app settings two times

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

> Sorry but I could only run locally the tests... I've made some tests in our professional environment and it's correctly working but I will appreciate if someone can run them properly

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_web_app_slot` -  avoid "WEBSITE_NODE_DEFAULT_VERSION" to be lost during update

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Related to #25452 , #25488

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @Apokalypt but it appears that this change has introduced a regression, we have a new failing test:
```
------- Stdout: -------
=== RUN   TestAccWindowsWebAppSlot_completeUpdate
=== PAUSE TestAccWindowsWebAppSlot_completeUpdate
=== CONT  TestAccWindowsWebAppSlot_completeUpdate
    testcase.go:113: Step 5/6 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # azurerm_windows_web_app_slot.test will be updated in-place
          ~ resource "azurerm_windows_web_app_slot" "test" {
              ~ app_settings                                   = {
                  - "foo" = "bar" -> null
                }
                id                                             = "/subscriptions/*******/resourceGroups/acctestRG-240411141600104680/providers/Microsoft.Web/sites/acctestWA-240411141600104680/slots/acctestWAS-240411141600104680"
                name                                           = "acctestWAS-240411141600104680"
                tags                                           = {}
                # (18 unchanged attributes hidden)
                # (1 unchanged block hidden)
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccWindowsWebAppSlot_completeUpdate (718.10s)
FAIL
```

**Comment by Apokalypt** [comment]
> Thanks for this PR @Apokalypt but it appears that this change has introduced a regression, we have a new failing test:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccWindowsWebAppSlot_completeUpdate
> === PAUSE TestAccWindowsWebAppSlot_completeUpdate
> === CONT  TestAccWindowsWebAppSlot_completeUpdate
>     testcase.go:113: Step 5/6 error: After applying this test step, the plan was not empty.
>         stdout:
>         Terraform used the selected providers to generate the following execution
>         plan. Resource actions are indicated with the following symbols:
>           ~ update in-place
>         Terraform will perform the following actions:
>           # azurerm_windows_web_app_slot.test will be updated in-place
>           ~ resource "azurerm_windows_web_app_slot" "test" {
>               ~ app_settings                                   = {
>                   - "foo" = "bar" -> null
>                 }
>                 id                                             = "/subscriptions/*******/resourceGroups/acctestRG-240411141600104680/providers/Microsoft.Web/sites/acctestWA-240411141600104680/slots/acctestWAS-240411141600104680"
>                 name                                           = "acctestWAS-240411141600104680"
>                 tags                                           = {}
>                 # (18 unchanged attributes hidden)
>                 # (1 unchanged block hidden)
>             }
>         Plan: 0 to add, 1 to change, 0 to destroy.
> --- FAIL: TestAccWindowsWebAppSlot_completeUpdate (718.10s)
> FAIL
> ```

Hmmm I may have an idea why it's happening but can't run acceptance test... I will try with my team using terraform to make some test but it may take time (next tuesday).
If I make a push in a few minutes are you able to re-run acceptance tests to check if my idea was correct ?

**Comment by Apokalypt** [comment]
@stephybun I can confirm that the test does not pass, but this is not due to my PR, since the bug is present in the normal version of "main". In fact, I've run the test without my code on version 3.97.1 (the last version before my branch was created) and the result is the same: the plan considers that the value will be removed... Imo, this bug should be fixed in another PR and not this one.

One thing to note is that, even if the plan indicates that the value will be deleted, if you apply the plan, nothing changes! The value remains...

**Comment by Apokalypt** [comment]
Changes performed as requested on the other PR

**Comment by Apokalypt** [comment]
Changes performed as requested on the other PR

**Review by stephybun — APPROVED** [review]
Tests look good. Thanks @Apokalypt LGTM 🍕

**Pull request merged**
