### PR TITLE
azurerm_hdinsight_spark_cluster - update doc for worker_node.target_instance_count

### PR DESCRIPTION
**Pull request by neil-yechenwei**
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/15415

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hi @neil-yechenwei 

Thanks for this PR - unfortunately #15415 is a bug around autoscaling rather than a documentation issue - and as such whilst I'd like to thank you for this contribution I'm going to close this PR in favour of #15415 where we can look to fix this.

Thanks!

**Comment by neil-yechenwei** [comment]
Hi @tombuildsstuff , sorry. Seems I didn't get your point and maybe I missed something. Based on my below findings, I assume it's a document issue. Does it make sense?

Reason 1:
After tested, I found the API error indicates `worker_node.target_instance_count` must be greater than zero and there is no default value if not specified. So I assume it's a required property.

Reason 2:
After tested, I found there is no diff on `worker_node.target_instance_count` after first apply.
After `worker_node.autoscale.recurrence.schedule` is automatically triggered at backend service, `worker_node.target_instance_count` would be automatically updated to the value what we set on `worker_node.autoscale.recurrence.schedule.target_instance_count` by backend service. At this time, there is diff on `worker_node.target_instance_count` in Terraform but I assume it's expected. So I assume user has to use `ignore_changes` to ignore the diff or update `worker_node.target_instance_count` in tf config to align with Azure for this kind of issue.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei this is not a documentation issue - resources using a `target_instance_count` (or `node_count` or similar, where the field can be auto-scaled) should allow users to use `ignore_changes` on it, so this field isn't sent - which is why this is a bug in the resource. Making this field requires "fixes" this by breaking the use-case - which is why this isn't a documentation issue.

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , thanks for clarification. To fix this issue, I intend to introduce a new Computed property to store the current target instance count after the schedule is triggered. Does it make sense?

**Comment by neil-yechenwei** [comment]
raised a [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/15565) for the fix

**Pull request closed without merging**
