### PR TITLE
`azurerm_mysql_server` Add update in create function to update `public_network_access_enabled`

### LINKED ISSUE #13302: azurerm_mysql_server public_network_access_enabled setting on replica not respected on create
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.76.0

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files

**mysql.tf**

```hcl
resource "azurerm_resource_group" "rg" {
  name     = var.resource_group
  location = var.location
}


resource "azurerm_mysql_server" "mysql_primary" {
  name = "test-mysql-primary"

  location            = var.location
  resource_group_name = var.resource_group

  administrator_login          = "dbadmin"
  administrator_login_password = "superSecretP@$$w0rd!"

  sku_name   = "GP_Gen5_2"
  storage_mb = 204800
  version    = "5.7"

  create_mode               = "Default"
  creation_source_server_id = null

  auto_grow_enabled                 = true
  infrastructure_encryption_enabled = true
  public_network_access_enabled     = false
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"

  depends_on = [
    azurerm_resource_group.rg
  ]
}

resource "azurerm_mysql_server" "mysql_replica" {
  name = "test-mysql-replica"

  location            = var.location
  resource_group_name = var.resource_group

  sku_name   = "GP_Gen5_2"
  storage_mb = 204800
  version    = "5.7"

  create_mode               = "Replica"
  creation_source_server_id = azurerm_mysql_server.mysql_primary.id

  auto_grow_enabled                 = true
  infrastructure_encryption_enabled = true
  public_network_access_enabled     = false
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
}
```

**variables.tf**

```hcl
provider "azurerm" {
  features {}
}

variable "location" {
  default = "westeurope"
}
variable "resource_group" {
  default = "test-mysql-replica-pub-net-access"
}
```

### Debug Output

https://gist.github.com/andrei-tonita/f9e1ebf04d7c9129c6b4d0bcafedba5f

### Expected Behaviour

Replica's `public_network_access_enabled` should be kept false when creating.

### Actual Behaviour

When creating a MySQL replica, the `public_network_access_enabled` setting is set to `true`, ignoring the attribute value of `false`.
The primary MySQL instance has the correct configuration.

Subsequent `terraform plan` action after an initial `terraform apply`:

```hcl
Terraform will perform the following actions:

  # azurerm_mysql_server.mysql_replica will be updated in-place
  ~ resource "azurerm_mysql_server" "mysql_replica" {
        id                                = "/subscriptions/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee/resourceGroups/test-mysql-replica-pub-net-access/providers/Microsoft.DBforMySQL/servers/test-mysql-replica"
        name                              = "test-mysql-replica"
      ~ public_network_access_enabled     = true -> false
        tags                              = {}
        # (16 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

If a second `terraform apply` is performed, the replica instance will have the correct `public_network_access_enabled` configuration.

### Steps to Reproduce

1. Run `terraform plan` and `terraform apply` using the files provided above. This will result in a bad config.
2. Running `terraform plan` and `terraform apply` again will update the configuration correctly.

### References

A similar issue was fixed on the `azurerm_postgresql_server` resource:
* #11346

### PR DESCRIPTION
**Pull request by lonegunmanb**
Add update in create function to update `public_network_access_enabled` when create mode is replica.
This pr will fix #13302, basically it copied the code from #11465 .

One acc test failed:

=== RUN   TestAccMySQLServer_update
=== PAUSE TestAccMySQLServer_update
=== CONT  TestAccMySQLServer_update
    testcase.go:110: Step 5/10 error: Error running apply: exit status 1
        
        Error: creating Server: (Name "acctestmysqlsvr-220422192116295294" / Resource Group "acctestRG-mysql-220422192116295294"): mysql.ServersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameterValue" Message="Invalid value given for parameter 'MinimalTlsVersion'. Specify a valid parameter value."
        
          with azurerm_mysql_server.test,
          on terraform_plugin_test.tf line 19, in resource "azurerm_mysql_server" "test":
          19: resource "azurerm_mysql_server" "test" {
        
--- FAIL: TestAccMySQLServer_update (782.84s)

But this test also failed in main branch, so I guess it's irrelevant to this pr.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Failing test to fix:

```
------- Stdout: -------
=== RUN   TestAccMySQLServer_update
=== PAUSE TestAccMySQLServer_update
=== CONT  TestAccMySQLServer_update
    testcase.go:110: Step 5/10 error: Error running apply: exit status 1
        
        Error: creating Server: (Name "acctestmysqlsvr-220512184925225287" / Resource Group "acctestRG-mysql-220512184925225287"): mysql.ServersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameterValue" Message="Invalid value given for parameter 'MinimalTlsVersion'. Specify a valid parameter value."
        
          with azurerm_mysql_server.test,
          on terraform_plugin_test.tf line 19, in resource "azurerm_mysql_server" "test":
          19: resource "azurerm_mysql_server" "test" {
        
--- FAIL: TestAccMySQLServer_update (631.89s)
FAIL
```

**Comment by katbyte** [comment]
either or @lonegunmanb just needs fixing

**Comment by lonegunmanb** [comment]
Hi @katbyte , I've fixed the test:

=== RUN   TestAccMySQLServer_basicFiveSeven
=== PAUSE TestAccMySQLServer_basicFiveSeven
=== CONT  TestAccMySQLServer_basicFiveSeven
--- PASS: TestAccMySQLServer_basicFiveSeven (392.26s)
=== RUN   TestAccMySQLServer_basicEightZero
=== PAUSE TestAccMySQLServer_basicEightZero
=== CONT  TestAccMySQLServer_basicEightZero
--- PASS: TestAccMySQLServer_basicEightZero (395.90s)
=== RUN   TestAccMySQLServer_autogrowOnly
=== PAUSE TestAccMySQLServer_autogrowOnly
=== CONT  TestAccMySQLServer_autogrowOnly
--- PASS: TestAccMySQLServer_autogrowOnly (577.72s)
=== RUN   TestAccMySQLServer_requiresImport
=== PAUSE TestAccMySQLServer_requiresImport
=== CONT  TestAccMySQLServer_requiresImport
--- PASS: TestAccMySQLServer_requiresImport (371.79s)
=== RUN   TestAccMySQLServer_complete
=== PAUSE TestAccMySQLServer_complete
=== CONT  TestAccMySQLServer_complete
--- PASS: TestAccMySQLServer_complete (383.33s)
=== RUN   TestAccMySQLServer_update
=== PAUSE TestAccMySQLServer_update
=== CONT  TestAccMySQLServer_update
--- PASS: TestAccMySQLServer_update (1534.47s)
=== RUN   TestAccMySQLServer_updateSKU
=== PAUSE TestAccMySQLServer_updateSKU
=== CONT  TestAccMySQLServer_updateSKU
--- PASS: TestAccMySQLServer_updateSKU (624.22s)
=== RUN   TestAccMySQLServer_createReplica

=== PAUSE TestAccMySQLServer_createReplica

=== CONT  TestAccMySQLServer_createReplica
--- PASS: TestAccMySQLServer_createReplica (1014.48s)
=== RUN   TestAccMySQLServer_createPointInTimeRestore
=== PAUSE TestAccMySQLServer_createPointInTimeRestore
=== CONT  TestAccMySQLServer_createPointInTimeRestore
--- PASS: TestAccMySQLServer_createPointInTimeRestore (1572.02s)
=== RUN   TestAccMySQLServer_infrastructureEncryption
=== PAUSE TestAccMySQLServer_infrastructureEncryption

=== CONT  TestAccMySQLServer_infrastructureEncryption
--- PASS: TestAccMySQLServer_infrastructureEncryption (380.16s)
PASS


Process finished with the exit code 0

**Review by katbyte — APPROVED** [review]
Thanks @lonegunmanb - LGTM 🦕

**Pull request merged**
