### PR TITLE
Added Speech Services Kind

### PR DESCRIPTION
**Pull request by lqdev**
When trying to provision a resource of `Speech` kind, there are errors. To correct for this, I added kind `SpeechServices` which should be compatible with the kind being used by Azure currently for that resource.

### CODE REVIEW

**Comment by katbyte** [comment]
Hi @lqdev,

Thank you for this addition. Looking at the resource & SDK its clear it needs to be updated to use the SDK enum values as I don't see `Speech`, but then I also don't see `SpeechServices`. Is this a new addition to the service? because the possible values the SDK recognizes are:

```go
	// BingSpeech ...
	BingSpeech Kind = "Bing.Speech"
	// CustomSpeech ...
	CustomSpeech Kind = "CustomSpeech"
	// SpeakerRecognition ...
	SpeakerRecognition Kind = "SpeakerRecognition"
	// SpeechTranslation ...
	SpeechTranslation Kind = "SpeechTranslation"
```

The documentation will require updating with any new values.

**Review by katbyte — DISMISSED** [review]
Hi @lqdev,

Thank you for this addition. Looking at the resource & SDK its clear it needs to be updated to use the SDK enum values as I don't see `Speech`, but then I also don't see `SpeechServices`. Is this a new addition to the service? because the possible values the SDK recognizes are:

```go
	// BingSpeech ...
	BingSpeech Kind = "Bing.Speech"
	// CustomSpeech ...
	CustomSpeech Kind = "CustomSpeech"
	// SpeakerRecognition ...
	SpeakerRecognition Kind = "SpeakerRecognition"
	// SpeechTranslation ...
	SpeechTranslation Kind = "SpeechTranslation"
```

The documentation will require updating with any new values.

**Comment by neilbailie** [comment]
Hi,

I've hit this problem before and raised an issue see -> https://github.com/terraform-providers/terraform-provider-azurerm/issues/2294 which covers the origin of the missing kind.

Neil

**Comment by katbyte** [comment]
@lqdev,

We have updated the SDK so this should be unblocked now 🙂

**Comment by lqdev** [comment]
Thanks! @katbyte

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @lqdev! I hope you don't mind but I've pushed a commit adding a test and docs for this new value

**Pull request merged**
