### PR TITLE
`azurerm_dsc_configuration` - fix resource read embedded_content error

### PR DESCRIPTION
**Pull request by wuxu92**
the response of GetContent is a literal string, which causes autorest's json.Unmarshal errors and all AccTests failed in **main branch**, as screenshot below. use a literal request/response to get the configuration's content to fix it.

--- PASS: TestAccAutomationDscConfiguration_basic (145.50s)
--- PASS: TestAccAutomationDscConfiguration_requiresImport (152.41s)
--- PASS: TestAccAutomationDscConfiguration_complete (140.91s)
--- PASS: TestAccAutomationDscNodeConfiguration_basic (147.54s)
--- PASS: TestAccAutomationDscNodeConfiguration_requiresImport (155.42s)
PASS

image

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@wuxu92 this is a Swagger bug which needs to be resolved there, whilst working around this here helps, this ultimately this has to be fixed in the Swagger too - there's a PR for fixing this on the Swagger repo currently waiting for the Service Team to take a look, any chance you could reach out to the service team for that one?

**Comment by wuxu92** [comment]
thanks for your information @tombuildsstuff  that really helps. could you please share the swagger pr link with me, then I will connect the Automation Team to have a look.

**Comment by tombuildsstuff** [comment]
Looks like it's only on the Go SDK and not the Swagger repo for now: https://github.com/Azure/azure-sdk-for-go/issues/17591#issue-1204566172

**Comment by katbyte** [comment]
@wuxu92  - i'm going to close this as its been 2 months without any activity - please do re open this when its ready for review again!

**Pull request closed without merging**
