### PR TITLE
New Resource : `azurerm_storage_mover`

### PR DESCRIPTION
**Pull request by sinbai**
Swagger Link: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storagemover/resource-manager/Microsoft.StorageMover/stable/2023-03-01/storagemover.json

Test Results:
PASS: TestAccStorageMover_basic (355.79s)
PASS: TestAccStorageMover_requiresImport (384.30s)
PASS: TestAccStorageMover_complete (371.36s)
PASS: TestAccStorageMover_update (606.43s)

### CODE REVIEW

**Review by manicminer — APPROVED** [review]
Thanks @sinbai, assuming the tests are good this LGTM

**Review by manicminer — CHANGES_REQUESTED** [review]
@sinbai This service availability seems limited, please can you update the tests to use one of eastus, eastus2, westus3 or swedencentral instead of the default location?

**Comment by sinbai** [comment]
> @sinbai This service availability seems limited, please can you update the tests to use one of eastus, eastus2, westus3 or swedencentral instead of the default location?

@manicminer thanks for your feedback. The setting of Teamcity has been updated. Could you please take another look?

**Review by katbyte — CHANGES_REQUESTED** [review]
I think we need to register the RP?

```
Error: creating Storage Mover (Subscription: "*******"
        Resource Group Name: "acctest-rg-230321013753853492"
        Storage Mover Name: "acctest-ssm-230321013753853492"): unexpected status 409 with response: {"error":{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.StorageMover'. See https://aka.ms/rps-not-found for how to register subscriptions.","details":[{"code":"MissingSubscriptionRegistration","target":"Microsoft.StorageMover","message":"The subscription is not registered to use namespace 'Microsoft.StorageMover'. See https://aka.ms/rps-not-found for how to register subscriptions."}]}}
```

**Comment by sinbai** [comment]
> 



> I think we need to register the RP?
> 
> ```
> Error: creating Storage Mover (Subscription: "*******"
>         Resource Group Name: "acctest-rg-230321013753853492"
>         Storage Mover Name: "acctest-ssm-230321013753853492"): unexpected status 409 with response: {"error":{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.StorageMover'. See https://aka.ms/rps-not-found for how to register subscriptions.","details":[{"code":"MissingSubscriptionRegistration","target":"Microsoft.StorageMover","message":"The subscription is not registered to use namespace 'Microsoft.StorageMover'. See https://aka.ms/rps-not-found for how to register subscriptions."}]}}
> ```

Yes. This is a new service. Could you please help to register `Microsoft.StorageMover` for the subscription used by Teamcity?

**Review by katbyte — CHANGES_REQUESTED** [review]
Please add it to the list of RPs to register in the `resourceproviders` package

**Comment by sinbai** [comment]
> Please add it to the list of RPs to register in the `resourceproviders` package

@katbyte Thanks for letting me know this. I have added it. Could you please take another look?

**Review by katbyte — APPROVED** [review]
Thanks @sinbai - LGTM 🧮

**Pull request merged**
