### PR TITLE
azurerm_disk_encryption_set: fix creation issue when disk encryption set and key vault in different subscriptions

### PR DESCRIPTION
**Pull request by ms-zhenhua**
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/17924

image

### CODE REVIEW

**Comment by ms-zhenhua** [comment]
Since the test infrastructure does not support cross-subscription scenario, I attached the test script here for the one who want to test this issue
[main.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/9307459/main.zip)
.

**Comment by nitgupta4** [comment]
Thanks @ms-zhenhua for fix. 
How early this can be be released? Right now applying leveraging powershell scripts to make it work but that's just a tactical solution for me.

**Comment by ms-zhenhua** [comment]
Hi @nitgupta4, I am still waiting for the PR to be reviewed and merged. After it is merged, you should be able to get the workable version within one week for the [AzureRM Provider](https://github.com/hashicorp/terraform-provider-azurerm/releases) is released every week.

**Review by katbyte — APPROVED** [review]
LGTM 🦕

**Pull request merged**
