### PR TITLE
Conditional loading of the Subscription ID / Tenant ID / Environment

### LINKED ISSUE #562: v0.3.3 azurerm provider fails to read cli auth if subscription_id is set
### Terraform Version
`Terraform v0.10.8`
also saw with `Terraform v0.10.7`

### Affected Resource(s)
- `azurerm_*`  // Any azurerm resource.

### Terraform Configuration Files
```hcl
variable "subscription_id" {}

provider "azurerm" {
  // Use version = "0.3.2" to cause terraform plan to succeed 
  version = "~> 0.3.3"
  // Comment out subscription_id to cause terraform plan to succeed.
  subscription_id = "${var.subscription_id}"
}

resource "azurerm_resource_group" "resources" {
  location = "West US"
  name = "repro-0.3.3"
}
```

### Debug Output
https://gist.github.com/JettJones/df731f1b7f370d79962dddaa1ee4594d

### Expected Behavior
Expected terraform plan to succeed, and report a resource group (in this example) that would be created.

### Actual Behavior
Terraform reports not finding CLI credentials.  At the same time I can look directly into `~/.aws/accessTokens.json` to see tokens with valid expiration times.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init`
2. `az login`
3. `terraform plan`

### Important Factoids
Running on Windows 10.
```
>az --version
azure-cli (2.0.20)
```
full output: https://gist.github.com/JettJones/d49b20f42403ba7563695098141f951c

Two notable workarounds, either of these allow me to create azure resources (without re-running az login).
- forcing the version to "0.3.2"
- removing the `subscription_id` from the provider configuration.

### PR DESCRIPTION
**Pull request by tombuildsstuff**
Needs some tests / validation - but seems promising in some initial testing

Fixes #562

### CODE REVIEW

**Comment by pmarques** [comment]
@tombuildsstuff I just had a look into your changes but it seems to be error-prone when someone has multiple subscriptions and multiple tenants (multiple accounts).
If I try to use *subscription-A* and my default subscription is *subscription-B* for a different tenant this seems to pick the wrong tenant.

**Comment by tombuildsstuff** [comment]
@pmarques thanks for the feedback, I wasn't sure that scenario was possible - so I'll update this to take that into account - thanks!

**Comment by tombuildsstuff** [comment]
@pmarques thanks for the testing suggestions :)

I've gone through and verified these scenarios:

- Specifying a Service Principal through Environment Variables
- Logging into CloudShell with a Single Subscription in a Single Tenant
- Logging into CloudShell with Multiple Subscriptions in a Single Tenant (as shown below)
- Logging into the Azure CLI with a Single Subscription in a Single Tenant
- Logging into the Azure CLI with multiple Subscriptions in the same Tenant - as shown below:

```
provider "azurerm" {
  alias           = "First"
  subscription_id = "00000000-0000-0000-0000-000000000000"
}

resource "azurerm_resource_group" "first" {
  name     = "tharvey-dev1"
  location = "West Europe"
  provider = "azurerm.First"
}

provider "azurerm" {
  alias = "Second"
}

resource "azurerm_resource_group" "second" {
  name     = "tharvey-dev2"
  location = "West Europe"
  provider = "azurerm.Second"
}

provider "azurerm" {
  alias           = "Third"
  subscription_id = "00000000-0000-0000-0000-000000000000"
  tenant_id       = "00000000-0000-0000-0000-000000000000"
}

resource "azurerm_resource_group" "third" {
  name     = "tharvey-dev3"
  location = "West Europe"
  provider = "azurerm.Third"
}
```

However I'm unable to test the scenario of using Multiple Subscriptions in different Tenants (since we don't have an account with that configuration).

If you've got access to an account with this configuration and feel comfortable - I'd really appreciate it if you could test this works - the best way to do that would be to check out this branch and build it locally [as outlined here](https://github.com/terraform-providers/terraform-provider-azurerm#developing-the-provider). That said - I'm relatively confident that this should work.

Thanks!

**Review by mbfrahry — APPROVED** [review]
LGTM

**Comment by benny-gold** [comment]
I'm still seeing this problem when I specify the Subscription ID in the provider using ```Terraform v0.11.2
+ provider.azurerm v1.1.0```

My account has multiple subscriptions and one tenant.

**Comment by pmarques** [comment]
@benny-gold this is currently working for me, do you still have issues?

**Comment by benny-gold** [comment]
all good with v.0.11.3 @pmarques thanks!

**Pull request merged**
