### PR TITLE
azurerm_virtual_network_gateway - not set bgpSettings.BgpPeeringAddress when it isn't specified

### PR DESCRIPTION
**Pull request by neil-yechenwei**
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/16285

Symptom:
    At first apply, virtual network gateway resource is created successfully without specifying "bgp_settings.0.peering_address" in TF config. Though this property isn's specified but this property bgpSettings.BgpPeeringAddress would still be set as empty string in request payload based on current TF code. So this property is always set in request body while creating/updating this resource. And then only change the tags property and perform second apply. TF would fail and throw below error message. After investigated, I found the bgpSettings.BgpPeeringAddress has default value while creating this resource with 'bgpSettings.BgpPeeringAddress = ""'. Hence, at second apply, TF is trying to update the bgpSettings.BgpPeeringAddress from default value to emty string but API doesn't allow this operation so that it failed.

Error message:
    network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VirtualNetworkGatewayBgpPeeringAddressCannotBeModified" Message="The BgpPeeringAddress for the virtual network gateway /subscriptions/xxxx/resourceGroups/test/providers/Microsoft.Network/virtualNetworkGateways/gw cannot be modified" Details=[]

--- PASS: TestAccVirtualNetworkGateway_edgeZone (614.96s)
--- PASS: TestAccVirtualNetworkGateway_enableBgp (1764.35s)
--- PASS: TestAccVirtualNetworkGateway_generation (1820.26s)
--- PASS: TestAccVirtualNetworkGateway_vpnClientConfig (1833.48s)
--- PASS: TestAccVirtualNetworkGateway_vpnClientConfigAzureAdAuth (1881.51s)
--- PASS: TestAccVirtualNetworkGateway_enableBgpWithAPIPA (1895.75s)
--- PASS: TestAccVirtualNetworkGateway_activeActiveEnableBgpWithAPIPA (1947.87s)
--- PASS: TestAccVirtualNetworkGateway_updateTagsWithBgpSettings (1990.64s)
--- PASS: TestAccVirtualNetworkGateway_vpnGw3 (1825.05s)
--- PASS: TestAccVirtualNetworkGateway_basic (2645.23s)
--- PASS: TestAccVirtualNetworkGateway_standard (2732.77s)
--- PASS: TestAccVirtualNetworkGateway_expressRoute (2827.16s)
--- PASS: TestAccVirtualNetworkGateway_vpnGw2 (1666.20s)
--- PASS: TestAccVirtualNetworkGateway_vpnClientConfigMultipleAuthTypes (1927.83s)
--- PASS: TestAccVirtualNetworkGateway_vpnClientConfigOpenVPN (1931.95s)
--- PASS: TestAccVirtualNetworkGateway_vpnGw1 (1917.64s)
--- PASS: TestAccVirtualNetworkGateway_activeActive (1712.41s)
--- PASS: TestAccVirtualNetworkGateway_lowerCaseSubnetName (2677.46s)
--- PASS: TestAccVirtualNetworkGateway_requiresImport (2783.85s)

Below TCs are also failed on Teamcity due to same error.
--- FAIL: TestAccVirtualNetworkGateway_activeActiveZoneRedundantWithP2S (2316.41s)
--- FAIL: TestAccVirtualNetworkGateway_customRoute (2519.14s)
--- FAIL: TestAccVirtualNetworkGateway_privateIpAddressEnabled (2323.57s)

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @neil-yechenwei,  I don't believe this fixes the linked issue. That issue is being caused by having create/update being combined. What we'll want to do is split that method into separate Create and Update methods. For the Update method, we'll want to grab the resource and only update the attributes that have changed through `d.HasChange`

**Comment by neil-yechenwei** [comment]
@mbfrahry , as the [`bgp_settings.0.peering_address`](https://github.com/hashicorp/terraform-provider-azurerm/blob/7c27c458db592eb8ffc47b2fe646f0b00f399f48/internal/services/network/virtual_network_gateway_resource.go#L416) is deprecated in 3.0 and we already passed 3.0, so can we remove this property to fix this issue?

**Comment by mbfrahry** [comment]
You're right! Sorry for the confusion. We should just remove this field entirely from the expand function since we're not in beta anymore and aren't planning on another 2.x release.

**Comment by neil-yechenwei** [comment]
@mbfrahry , thanks for your comment. I've updated code. Please take another look. Thanks.

**Review by katbyte — APPROVED** [review]
LGTM 🎩

**Pull request merged**
