### PR TITLE
`r\shared_image_version`: add support for `disk_encryption_set_id` `end_of_life_date` `replication_mode`

### PR DESCRIPTION
**Pull request by myc2h6o**
- `disk_encryption_set_id`: https://docs.microsoft.com/en-us/azure/virtual-machines/image-version-encryption
- `end_of_life_date`: https://docs.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#image-versions
- `replication_mode`: https://docs.microsoft.com/en-us/azure/virtual-machines/shared-image-galleries?tabs=azure-cli#shallow-replication

### CODE REVIEW

**Comment by myc2h6o** [comment]
Test result: (failed tests failed on main as well due to dangling os disk, to be fixed by #17297)
image

**Review by katbyte — APPROVED** [review]
LGTM 🦕

**Comment by katbyte** [comment]
once merge conflicts are resolved

**Comment by myc2h6o** [comment]
Hi @katbyte thanks for reviewing the pr! I've resolved the merge conflicts. Below is the updated test result:
image

**Pull request merged**
