### PR TITLE
Update Azure compute sdk version to 2021-11-01

### PR DESCRIPTION
**Pull request by myc2h6o**
Prepare for [Snapshot securityProfile](https://github.com/Azure/azure-rest-api-specs/blob/80e0bf225d3bb42a87d04696481b5c5ec4bef08a/specification/compute/resource-manager/Microsoft.Compute/stable/2021-08-01/disk.json#L2314) update
Test result (Failed tests are failed on main as well):
image

### CODE REVIEW

**Comment by myc2h6o** [comment]
There are three new test cases failing with this change, investigating
```
TestAccLinuxVirtualMachineScaleSet_disksDataDiskCaching
TestAccVirtualMachine_basicLinuxMachine_managedDisk_changeWriteAcceleratorEnabled
TestAccWindowsVirtualMachine_scalingMachineSizeUpdate
```

**Comment by myc2h6o** [comment]
Hi, I'm resolved the conflict of this change. Running the test now

**Comment by myc2h6o** [comment]
Updated test result:
image

Have compared with test results on main, failed tests are due to same reason
image

**Review by katbyte — APPROVED** [review]
LGTM 💯

**Pull request merged**
