### PR TITLE
Dont attempt to use fileServiceClient on Storage v1

### LINKED ISSUE #12485: Error refreshing State on previously created Storage Account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.13.7
Azure Provider 2.65.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "redacted" {
  name                     = "redacted"
  resource_group_name      = azurerm_resource_group.data.name
  location                 = "Australia East"
  account_tier             = "Standard"
  account_replication_type = "GRS"
  account_kind             = "Storage"
  enable_https_traffic_only = false
  tags = {
    owner       = var.tagOwner
    description = "The storage account used for App Service Backups and SQL Logs for Australia"    
    usage       = var.tagUsage
    config      = var.tagConfig
  }
}
```

### Expected Behaviour

This storage account was created >12 months ago using Terraform. The last successful run of this workspace was using provider 2.18.0 When refreshing the workspace resources in order to make an unrelated change to a different component, Terraform should not return an error.  

### Actual Behaviour

When refreshing the state Terraform returns the error:

```
Error: reading share properties for AzureRM Storage Account "redacted": storage.FileServicesClient#GetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="File is not supported for the account."
```

Speaking with Vladimir Lazarenko on Slack, the error comes from the following code:

```
	if resp.Kind == storage.FileStorage || resp.Kind != storage.BlobStorage && resp.Kind != storage.BlockBlobStorage && resp.Sku != nil && resp.Sku.Tier != storage.Premium {
		shareProps, err := fileServiceClient.GetServiceProperties(ctx, resGroup, name)
		if err != nil {
			if !utils.ResponseWasNotFound(shareProps.Response) {
				return fmt.Errorf("reading share properties for AzureRM Storage Account %q: %+v", name, err)
			}
		}
		if err := d.Set("share_properties", flattenShareProperties(shareProps)); err != nil {
			return fmt.Errorf("setting `share_properties `for AzureRM Storage Account %q: %+v", name, err)
		}
	}
```

### Steps to Reproduce

1. Make a change to a resource in a workspace that also has a Storage Account with the settings in above config.
2. Use recent Azure Provider
3. Reverting provider to 2.18.0 causes this not to be an issue. I have tried latest 5 releases of Provider and the issue is present, 2.18.0 was the version when we had our last successful run. Reverting back to this version resolves the issue.

### PR DESCRIPTION
**Pull request by f0o**
Fixes #12485 

First naive untested change - hence the Draft PR

### CODE REVIEW

**Comment by f0o** [comment]
It seems that also queueClient is having issues with StorageV1.

It its a deadline timeout, not sure how to fully debug that, trying to understand which HTTP request it is attempting to fire and what the return is/should-be.

Any pointers @tombuildsstuff ?

**Comment by katbyte** [comment]
@f0o - if it is hitting a deadline timeout you may need to increase the resoruces defaults?

**Comment by f0o** [comment]
@katbyte I can try increasing the timeouts but I doubt it will actually solve anything, 3 minutes (which I believe is the default) seems plenty already, specially considering that this is a fresh resource with nothing on it yet

**Comment by katbyte** [comment]
@f0o - 3 is pretty low, i'd saw update it at least to 5, potentially 10 as sometimes service APIs can take a while for odd reasons

**Comment by f0o** [comment]
5-10 minutes?! That seems extremely excessive to be honest

**Comment by tombuildsstuff** [comment]
hey @f0o 

Thanks for this PR / apologies for the delayed review here.

As Discussed in #12485 we're going to fix this by removing support for ZRS and StorageV1 since the Azure Portal and Services are gradually removing support for this in version 3.0 of the Azure Provider - as such whilst I'd like to thank you for this contribution I'm going to close this in favour of #12485.

Thanks!

**Pull request closed without merging**
