### PR TITLE
`azurerm_dns_txt_record` - Update dns txt resource max string

### PR DESCRIPTION
**Pull request by mikemadeja**
For issue [#24152](https://github.com/hashicorp/terraform-provider-azurerm/issues/24152)

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @mikemadeja but we have a test failure:
```
------- Stdout: -------
=== RUN   TestAccDnsTxtRecord_basic
=== PAUSE TestAccDnsTxtRecord_basic
=== CONT  TestAccDnsTxtRecord_basic
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        Error: creating/updating Record Type (Subscription: "*******"
        Resource Group Name: "acctestRG-231211110655728866"
        Dns Zone Name: "acctestzone231211110655728866.com"
        Record Type: "TXT"
        Relative Record Set Name: "myarecord231211110655728866"): unexpected status 400 with response: {"code":"BadRequest","message":"The combined length of all TXT records in a record set may not exceed 4096 characters."}
          with azurerm_dns_txt_record.test,
          on terraform_plugin_test.tf line 31, in resource "azurerm_dns_txt_record" "test":
          31: resource "azurerm_dns_txt_record" "test" {
--- FAIL: TestAccDnsTxtRecord_basic (57.49s)
FAIL
```

**Comment by mikemadeja** [comment]
> Thanks for this @mikemadeja but we have a test failure:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccDnsTxtRecord_basic
> === PAUSE TestAccDnsTxtRecord_basic
> === CONT  TestAccDnsTxtRecord_basic
>     testcase.go:113: Step 1/2 error: Error running apply: exit status 1
>         Error: creating/updating Record Type (Subscription: "*******"
>         Resource Group Name: "acctestRG-231211110655728866"
>         Dns Zone Name: "acctestzone231211110655728866.com"
>         Record Type: "TXT"
>         Relative Record Set Name: "myarecord231211110655728866"): unexpected status 400 with response: {"code":"BadRequest","message":"The combined length of all TXT records in a record set may not exceed 4096 characters."}
>           with azurerm_dns_txt_record.test,
>           on terraform_plugin_test.tf line 31, in resource "azurerm_dns_txt_record" "test":
>           31: resource "azurerm_dns_txt_record" "test" {
> --- FAIL: TestAccDnsTxtRecord_basic (57.49s)
> FAIL
> ```

Thanks. I will debug. Which step is testing this? I didn't see a failed item. Sorry, I am still kind of new to this :-)

**Comment by mikemadeja** [comment]
@stephybun, I reverted the test back to what it was. Thinking it through, I don't think I need to update it. I checked the test and didn't see a failure. Can you confirm if it's good to go?

**Review by stephybun — APPROVED** [review]
Thanks @mikemadeja LGTM 👍

**Pull request merged**
