### PR TITLE
`azurerm_recovery_services_vault` - support `immutability` property, support `UserAssigned` of `identity` property

### LINKED ISSUE #18837: Support for Immutable vaults in Azure Recovery Services vault
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Backup provides an option to ensure that recovery points that are once created cannot be deleted before their intended expiry time. Azure Backup does this by preventing any operations which could lead to loss of backup data. Hence, this helps you protect backups against threats like ransomware attacks and malicious actors by disallowing operations such as deleting backups or reducing retention in backup policies.

### New or Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Potential Terraform Configuration

```hcl
resource "azurerm_recovery_services_vault" "vault" {
  name                = "example-recovery-vault"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"

  soft_delete_enabled = true

  immutable_vault {
    immutable_vault_enabled = true
    immutable_vault_lock = true
  }
}
```

### References

https://learn.microsoft.com/en-us/azure/backup/backup-azure-immutable-vault-how-to-manage?tabs=recovery-services-vault

### PR DESCRIPTION
**Pull request by ziyeqf**
fix #18837 

Test
---
```
TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccRecoveryServicesVault -timeout=600m
=== RUN   TestAccRecoveryServicesVault_basic
=== PAUSE TestAccRecoveryServicesVault_basic
=== RUN   TestAccRecoveryServicesVault_basicWithCrossRegionRestore
=== PAUSE TestAccRecoveryServicesVault_basicWithCrossRegionRestore
=== RUN   TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
=== PAUSE TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
=== RUN   TestAccRecoveryServicesVault_zrs
=== PAUSE TestAccRecoveryServicesVault_zrs
=== RUN   TestAccRecoveryServicesVault_complete
=== PAUSE TestAccRecoveryServicesVault_complete
=== RUN   TestAccRecoveryServicesVault_update
=== PAUSE TestAccRecoveryServicesVault_update
=== RUN   TestAccRecoveryServicesVault_requiresImport
=== PAUSE TestAccRecoveryServicesVault_requiresImport
=== RUN   TestAccRecoveryServicesVault_SystemAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_SystemAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_UserAssignedIdentity
=== PAUSE TestAccRecoveryServicesVault_UserAssignedIdentity
=== RUN   TestAccRecoveryServicesVault_immutability
=== PAUSE TestAccRecoveryServicesVault_immutability
=== RUN   TestAccRecoveryServicesVault_softDelete
=== PAUSE TestAccRecoveryServicesVault_softDelete
=== RUN   TestAccRecoveryServicesVault_storageModeType
=== PAUSE TestAccRecoveryServicesVault_storageModeType
=== RUN   TestAccRecoveryServicesVault_crossRegionRestore
=== PAUSE TestAccRecoveryServicesVault_crossRegionRestore
=== RUN   TestAccRecoveryServicesVault_sku
=== PAUSE TestAccRecoveryServicesVault_sku
=== RUN   TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== PAUSE TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== RUN   TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== RUN   TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
=== PAUSE TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
=== RUN   TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== PAUSE TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== RUN   TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== PAUSE TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== RUN   TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== PAUSE TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== CONT  TestAccRecoveryServicesVault_basic
=== CONT  TestAccRecoveryServicesVault_storageModeType
=== CONT  TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey
=== CONT  TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption
=== CONT  TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey
=== CONT  TestAccRecoveryServicesVault_updateSkuWithExistingEncryption
=== CONT  TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage
=== CONT  TestAccRecoveryServicesVault_sku
--- PASS: TestAccRecoveryServicesVault_basic (380.42s)
=== CONT  TestAccRecoveryServicesVault_requiresImport
--- PASS: TestAccRecoveryServicesVault_storageModeType (610.28s)
=== CONT  TestAccRecoveryServicesVault_softDelete
--- PASS: TestAccRecoveryServicesVault_requiresImport (273.79s)
=== CONT  TestAccRecoveryServicesVault_immutability
--- PASS: TestAccRecoveryServicesVault_encryptionWithInfrastructureEncryption (810.84s)
=== CONT  TestAccRecoveryServicesVault_UserAssignedIdentity
--- PASS: TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey (1017.95s)
--- PASS: TestAccRecoveryServicesVault_changeInfrastructureEncryptionEnabledShouldHaveClearlyErrorMessage (1017.95s)
=== CONT  TestAccRecoveryServicesVault_SystemAssignedIdentity
=== CONT  TestAccRecoveryServicesVault_encryptionWithKeyVaultKey
--- PASS: TestAccRecoveryServicesVault_turnOnEncryptionWithKeyVaultKey (1260.40s)
=== CONT  TestAccRecoveryServicesVault_zrs
--- PASS: TestAccRecoveryServicesVault_updateSkuWithExistingEncryption (1289.95s)
=== CONT  TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage
--- PASS: TestAccRecoveryServicesVault_sku (1540.51s)
=== CONT  TestAccRecoveryServicesVault_update
--- PASS: TestAccRecoveryServicesVault_zrs (507.49s)
=== CONT  TestAccRecoveryServicesVault_complete
--- PASS: TestAccRecoveryServicesVault_encryptionWithKeyVaultKey (946.58s)
=== CONT  TestAccRecoveryServicesVault_crossRegionRestore
--- PASS: TestAccRecoveryServicesVault_immutability (1345.76s)
=== CONT  TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType
--- PASS: TestAccRecoveryServicesVault_SystemAssignedIdentity (1063.83s)
=== CONT  TestAccRecoveryServicesVault_basicWithCrossRegionRestore
--- PASS: TestAccRecoveryServicesVault_complete (329.46s)
--- PASS: TestAccRecoveryServicesVault_softDelete (1511.92s)
--- PASS: TestAccRecoveryServicesVault_basicWithCrossRegionRestoreAndWrongStorageType (178.36s)
--- PASS: TestAccRecoveryServicesVault_UserAssignedIdentity (1483.70s)
--- PASS: TestAccRecoveryServicesVault_turnOffEncryptionWithKeyVaultKeyShouldHaveClearlyErrorMessage (1125.34s)
--- PASS: TestAccRecoveryServicesVault_update (1048.94s)
--- PASS: TestAccRecoveryServicesVault_basicWithCrossRegionRestore (536.75s)
--- PASS: TestAccRecoveryServicesVault_crossRegionRestore (661.01s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      2626.677s
```

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @ziyeqf.

Could you please split the SDK swap over to `hashicorp/go-azure-sdk` and the addition of the new property into separate PRs. Also as a note, we should be swapping out the SDK using the same version of the SDK generated by Pandora, if we do both a swap and an upgrade it isn't entirely evident, if issues occur, whether they are due to the generated SDK or a change in behaviour of the API.

**Comment by ziyeqf** [comment]
@stephybun  I'm wondering do we really need to do so because it will add some old versions API to pandora, and what the user get will be the same not matter if we split or not. Or the plan is swap-over release for a period and then the upgradtion release?

**Comment by stephybun** [comment]
> _I'm wondering do we really need to do so because it will add some old versions API to pandora_

Older versions specified in pandora can be removed safely once the service is upgraded to the next API version, in fact we do this regularly.

> _what the user get will be the same not matter if we split or not_

Yes, but by doing this in two phases the reviews are smaller and therefore far quicker - since it's easier to root cause the problem.

> _Or the plan is swap-over release for a period and then the upgradtion release?_

Both of those PRs can go into the same release aslong as the swap happens first and then the property gets added.

**Comment by ziyeqf** [comment]
temporarily close to add swap over pr first

**Comment by ziyeqf** [comment]
hi @stephybun , made a PR (#19551) to do swap sdk, could you please take a look at that?

**Pull request closed without merging**
