### PR TITLE
dependencies: upgrading to v61.1.0 of github.com/Azure/azure-sdk-for-go

### PR DESCRIPTION
**Pull request by myc2h6o**
Prepare for new compute sdk version 2021-08-01

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
All tests are failing with:
```
<div class="rightBlock expandedDetails" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; float: right; background-color: rgba(245, 245, 245, 0.81); border-left-width: 5px; border-left-style: solid; border-left-color: rgb(255, 255, 255); border-bottom-width: 5px; border-bottom-style: solid; border-bottom-color: rgb(255, 255, 255); caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px;"><br class="Apple-interchange-newline"><div class="icon_before icon16 collapser collapser_expanded" title="Click to hide the details block" style="float: right; height: 2em; padding: 5px; cursor: pointer;"></div><div class="relatedBuildsWrapper" style="border-right-width: 3px; border-right-style: solid; border-right-color: white; float: right;">

  | Current failure: |   | #459 | Changes (4) | 06 Jan 22 15:48
-- | -- | -- | -- | -- | --
  | First failure: |   | #438 | Changes (64) | 06 Dec 21 02:11

<div id="div_iaa_17c320757f7"></div></div></div><span style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255); float: none; display: inline !important;"></span><span style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px; background-color: rgb(255, 255, 255); float: none; display: inline !important;"></span><div class="testMetadata" id="testMetadata_tdi_17c320757f5" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(31, 35, 38); color: rgb(31, 35, 38); font-family: system-ui, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif; font-size: 13px;"></div><pre class="fullStacktrace" id="fullStacktrace_240526_7942368699857484476" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; font-stretch: normal; font-size: 12px; line-height: 1.2em; font-family: Menlo, &quot;Bitstream Vera Sans Mono&quot;, &quot;Ubuntu Mono&quot;, Consolas, &quot;Courier New&quot;, Courier, monospace; padding: 3px 3px 0px; color: darkred; margin-top: 0.5em; margin-bottom: 0.5em; white-space: pre-wrap; overflow-wrap: break-word;">------- Stdout: -------
=== RUN   TestAccNotificationHubNamespace_free
=== PAUSE TestAccNotificationHubNamespace_free
=== CONT  TestAccNotificationHubNamespace_free
    testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_notification_hub_namespace.test will be updated in-place
          ~ resource "azurerm_notification_hub_namespace" "test" {
                id                  = "/subscriptions/*******/resourceGroups/acctestRG-220106155358471509/providers/Microsoft.NotificationHubs/namespaces/acctestnhn-220106155358471509"
                name                = "acctestnhn-220106155358471509"
              + namespace_type      = "NotificationHub"
                tags                = {
                    "env" = "Test"
                }
                # (5 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccNotificationHubNamespace_free (285.47s)
FAIL</pre>
```

**Comment by myc2h6o** [comment]
Test started failing at main from 12/06, seems like there is a breaking change in the service, which doesn't return namespaceType any more. I've tried using REST API as well and had the same result. I've opened an issue at https://github.com/Azure/azure-rest-api-specs/issues/17277 and will check with service team whether it's a bug or this property is no longer used any more.

image

**Comment by myc2h6o** [comment]
Rebased to main branch. Sdk version is upgraded to 61.0.0 by [this pr](https://github.com/hashicorp/terraform-provider-azurerm/pull/14771/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6)
Further updating to 61.1.0 to consume compute sdk 2021-08-01

**Comment by myc2h6o** [comment]
@katbyte I opened a separate issue for notificationhub under Azure repo as commented above. And since the version 61.0 including the breaking change is already checked in, is it ok to further upgrade the version to 61.1 so that the new compute sdk version is also included?

**Comment by dennis-menge** [comment]
This issue also has been reported already: https://github.com/hashicorp/terraform-provider-azurerm/issues/14541

**Comment by tombuildsstuff** [comment]
The Notification Hub API changes are unrelated to this SDK upgrade and tracked in #14541 / upstream in https://github.com/Azure/azure-rest-api-specs/issues/17277 - so this isn't gated on that

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @myc2h6o

**Pull request merged**
