### PR TITLE
`azurerm_mysql_flexible_server` add suport for customer_managed_key

### LINKED ISSUE #19842: Support for CMK in Azure Database for MySQL - Flexible Server
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Database for MySQL flexible servers now supports using a customer managed encryption key  for encryption of databases. The feature is currently GA. Please add support for this feature in the azurerm provider. The docs for this feature can be found here: https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-customer-managed-key

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Potential Terraform Configuration

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by bwilczynski**
Implements Customer Managed Key for MySQL Flexible Server, fixes #19842

* Switch to hashicorp/go-azure-sdk for MySQL resource
* Add `customer_managed_key` block to `azurerm_mysql_flexible_server`

Usage:
```hcl
resource "azurerm_mysql_flexible_server" "test" {
  name = "mysqlserver01"
  ...

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.test.id]
  }

  customer_managed_key {
    key_vault_key_id                    = azurerm_key_vault_key.first.id
    primary_user_assigned_identity_id   = azurerm_user_assigned_identity.test.id
  }
}
```

### CODE REVIEW

**Comment by bwilczynski** [comment]
There is an issue with this code, for some reason Terraform detects a change in a primary_user_assigned_identity_id even though the values seem to match:
```
      ~ customer_managed_key {
          ~ primary_user_assigned_identity_id = "/subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test" -> "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test"
            # (1 unchanged attribute hidden)
        }
```

**Comment by bwilczynski** [comment]
```shell
❯ make acctests SERVICE='mysql' TESTARGS='-run=TestAccMySqlFlexibleServer_createWithCustomerManagedKey' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/mysql -run=TestAccMySqlFlexibleServer_createWithCustomerManagedKey -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMySqlFlexibleServer_createWithCustomerManagedKey
=== PAUSE TestAccMySqlFlexibleServer_createWithCustomerManagedKey
=== CONT  TestAccMySqlFlexibleServer_createWithCustomerManagedKey
--- PASS: TestAccMySqlFlexibleServer_createWithCustomerManagedKey (972.74s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/mysql 973.923s
```

**Comment by bwilczynski** [comment]
❯ make acctests SERVICE='mysql' TESTARGS='-run=TestAccMySqlFlexibleServer_updateToCustomerManagedKey' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/mysql -run=TestAccMySqlFlexibleServer_updateToCustomerManagedKey -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMySqlFlexibleServer_updateToCustomerManagedKey
=== PAUSE TestAccMySqlFlexibleServer_updateToCustomerManagedKey
=== CONT  TestAccMySqlFlexibleServer_updateToCustomerManagedKey
--- PASS: TestAccMySqlFlexibleServer_updateToCustomerManagedKey (983.72s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/mysql 984.915s

**Review by katbyte — APPROVED** [review]
Thanks @bwilczynski ! LGTM 🔐

**Comment by bwilczynski** [comment]
From what I see it's planned for the next provider's release. I don't know what's the release schedule for this provider, someone from maintainers will need to answer that.

**Pull request merged**
