### PR TITLE
certificate_id an optional argument of azurerm_container_app resource

### LINKED ISSUE #24110: On azurerm_container_app adding custom domain, the field certificate_id is required and should not be
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl

```

### Debug Output/Panic Output

```shell
│ Error: Missing required argument
│
│   with module.container_apps.azurerm_container_app.container_app["capp-web"],
│   on modules\container_apps\main.tf line 15, in resource "azurerm_container_app" "container_app":
│   15: resource "azurerm_container_app" "container_app" {
│
│ The argument "ingress.0.custom_domain.0.certificate_id" is required, but no definition was found.
```

### Expected Behaviour

Adding "custom domain" with Terraform dot not raise an error that "certificate_id" is required (exporting on JSON VIEW on the Azure Portal is not required).

### Actual Behaviour

In Azure, with container app add two custom domains, go to "overview", click on JSON view and you can see the SCHEMA exported for the custom domains have 2 properties "name" and "bindingType".

Although, if you add these "custom domain" with Terraform it will raise and error that "certificate_id" is required but doing it on the Azure platform it is not required.

### Steps to Reproduce

In Azure, with container app add two custom domains, go to "overview", click on JSON view and you can see the SCHEMA exported for the custom domains have 2 properties "name" and "bindingType".

Although, if you add these "custom domain" with Terraform it will raise and error that "certificate_id" is required but doing it on the Azure platform it is not required.

```
(...)
                "customDomains": [
                    {
                        "name": "test.ambitiousbay-xxxxxxx.westeurope.azurecontainerapps.io",
                        "bindingType": "Disabled"
                    },
                    {
                        "name": "mysubdomain.example.com",
                        "bindingType": "Disabled"
                    }
                ],
(...)
```

Error on terraform adding a custom domain without certificate (only name="subdomain.example.com" and certificate_binding_type="Disabled" filled):
```
│ Error: Missing required argument
│
│   with module.container_apps.azurerm_container_app.container_app["capp-web"],
│   on modules\container_apps\main.tf line 15, in resource "azurerm_container_app" "container_app":
│   15: resource "azurerm_container_app" "container_app" {
│
│ The argument "ingress.0.custom_domain.0.certificate_id" is required, but no definition was found.
```

Source on terraform -> terraform-provider-azurerm\internal\services\containerapps\helpers\container_apps.go:
```

type CustomDomain struct {
	CertBinding   string `tfschema:"certificate_binding_type"`
	CertificateId string `tfschema:"certificate_id"`
	Name          string `tfschema:"name"`
}

func ContainerAppIngressCustomDomainSchema() *pluginsdk.Schema {
	return &pluginsdk.Schema{
		Type:     pluginsdk.TypeList,
		Optional: true,
		MaxItems: 1,
		Elem: &pluginsdk.Resource{
			Schema: map[string]*pluginsdk.Schema{
				"certificate_binding_type": {
					Type:         pluginsdk.TypeString,
					Optional:     true,
					Default:      containerapps.BindingTypeDisabled,
					ValidateFunc: validation.StringInSlice(containerapps.PossibleValuesForBindingType(), false),
					Description:  "The Binding type. Possible values include `Disabled` and `SniEnabled`. Defaults to `Disabled`",
				},

				"certificate_id": {
					Type:         pluginsdk.TypeString,
					Required:     true,
					ValidateFunc: managedenvironments.ValidateCertificateID,
				},

				"name": {
					Type:         pluginsdk.TypeString,
					Required:     true,
					ValidateFunc: validation.StringIsNotEmpty,
					Description:  "The hostname of the Certificate. Must be the CN or a named SAN in the certificate.",
				},
			},
		},
	}
}
```

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by harshavmb**
This fixes #24110 

Current `azurerm_container_app` resource has `ingress` block which has `custom_domain` which mandates `certificate_id` to be a required field even when `certificate_binding_type` set to `Disabled` by default. This contradicts with the documentation [here](https://learn.microsoft.com/en-us/azure/container-apps/custom-domains-managed-certificates?pivots=azure-portal) for Azure managed certificates. 

This PR aims to set `certificate_id` as `Optional` & only required when `certificate_binding_type` set to `SniEnabled`.

### CODE REVIEW

**Comment by caiola** [comment]
I waiting for this feature to be merged to fix my terraform code.

**Comment by jk-f5** [comment]
I'd also like to see this merged asap.

**Comment by jpmicrosoft** [comment]
@tombuildsstuff Can this move forward?

**Review by katbyte — APPROVED** [review]
LGTM 🌵

**Comment by katbyte** [comment]
noticed #24421 might replace this functionality so going to leave this for a bit

**Comment by jackofallops** [comment]
Hi @harshavmb - Thanks for this PR. This block has been deprecated due to a circular reference problem and replaced with a new resource `azurerm_container_app_custom_domain`. We're investigating the support of the Azure Managed Certificates in that resource at the moment, so I'm going to close this PR for now.  Please follow #25356 for progress.

Thanks

**Pull request closed without merging**
