### PR TITLE
`azurerm_app_configuration_feature` - `percentage_filter_value` change to accept float number

### PR DESCRIPTION
**Pull request by teowa**
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/23258

- fix filter update with `HasChange`
- change `percentage_filter_value` to be single float value.

Reference:
https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core

### CODE REVIEW

**Review by baximan — APPROVED** [review]
lgtm

**Review by stephybun — CHANGES_REQUESTED** [review]
@teowa, this is potentially a breaking change. 

Could you please do some manual testing by creating an app configuration feature with a value set for `percentage_filter_value` with v3.73.0 and then upgrade to a provider built with this change to see if Terraform is able to handle the type conversion without throwing a diff?

**Comment by teowa** [comment]
Hi @stephybun , I take a test and there is no diff for type convension.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @teowa, there's a new test failure though:
```
------- Stdout: -------
=== RUN   TestAccAppConfigurationFeature_enabledUpdate
=== PAUSE TestAccAppConfigurationFeature_enabledUpdate
=== CONT  TestAccAppConfigurationFeature_enabledUpdate
    testcase.go:113: Step 2/2 error: Check failed: Check 2/2 error: azurerm_app_configuration_feature.test: Attribute 'enabled' expected "true", got "false"
--- FAIL: TestAccAppConfigurationFeature_enabledUpdate (745.69s)
FAIL
```

**Comment by teowa** [comment]
@stephybun this test is unstable and it should pass, might related to https://github.com/Azure/AppConfiguration/issues/763#issuecomment-1570522454.

**Review by stephybun — APPROVED** [review]
Thats fine @teowa, from the TC UI it just looked like a new failing test.

LGTM 🐐

**Pull request merged**
