### PR TITLE
enhancement for synapse_spark_pool

### PR DESCRIPTION
**Pull request by ms-henglu**
image

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @ms-henglu, overall looks good. I have a few questions and left a few remarks, would be good to clarify these before we merge 🙂.

**Comment by ms-henglu** [comment]
@stephybun, Hi, thanks for code review.

I've added a commit according to your suggestions, please take another look, thanks!

**Review by stephybun — COMMENTED** [review]
Thanks for making those adjustments @ms-henglu. I left one final suggestion in the docs, once that's addressed this is good to go.

**Comment by ms-henglu** [comment]
@stephybun ,Thanks! I've added your suggestion to the commit.

**Review by stephybun — APPROVED** [review]
Thanks @ms-henglu, LGTM 👍🏼.

**Pull request merged**
