### PR TITLE
New Resource: `azurerm_container_registry_agent_pool`

### PR DESCRIPTION
**Pull request by magodo**
This PR adds a new resource `azurerm_container_registry_agent_pool`, which allows users to run their Azure Container Registry tasks in a dedicated compute environment.

## Test

```bash
💢  TF_ACC=1 go test -v -timeout=20h ./internal/services/containers -run='TestAccContainerRegistryAgentPool_'
=== RUN   TestAccContainerRegistryAgentPool_basic
=== PAUSE TestAccContainerRegistryAgentPool_basic
=== RUN   TestAccContainerRegistryAgentPool_complete
=== PAUSE TestAccContainerRegistryAgentPool_complete
=== RUN   TestAccContainerRegistryAgentPool_update
=== PAUSE TestAccContainerRegistryAgentPool_update
=== RUN   TestAccContainerRegistryAgentPool_subnet
=== PAUSE TestAccContainerRegistryAgentPool_subnet
=== RUN   TestAccContainerRegistryAgentPool_requiresImport
=== PAUSE TestAccContainerRegistryAgentPool_requiresImport
=== CONT  TestAccContainerRegistryAgentPool_basic
=== CONT  TestAccContainerRegistryAgentPool_subnet
=== CONT  TestAccContainerRegistryAgentPool_update
=== CONT  TestAccContainerRegistryAgentPool_requiresImport
=== CONT  TestAccContainerRegistryAgentPool_complete
--- PASS: TestAccContainerRegistryAgentPool_subnet (1903.48s)
--- PASS: TestAccContainerRegistryAgentPool_complete (1903.68s)
--- PASS: TestAccContainerRegistryAgentPool_basic (1903.77s)
--- PASS: TestAccContainerRegistryAgentPool_requiresImport (1903.80s)
--- PASS: TestAccContainerRegistryAgentPool_update (2591.02s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    2591.038s
```

## Reference

https://docs.microsoft.com/en-us/azure/container-registry/tasks-agent-pools

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Duplicate of #14790, which is blocked on the Azure API?

**Comment by magodo** [comment]
Sorry for the duplication, I only checked about the issues but didn't explore the RPs :|
The API under used by my PR and #14790 are actually the same, while I didn't hit that erorr, maybe due to some timings?

**Review by katbyte — CHANGES_REQUESTED** [review]
I'm seeing a failing test in teamcity:
```
------- Stdout: -------
=== RUN   TestAccContainerRegistryAgentPool_update
=== PAUSE TestAccContainerRegistryAgentPool_update
=== CONT  TestAccContainerRegistryAgentPool_update
    testcase.go:110: Step 5/6 error: Error running apply: exit status 1
        
        Error: waiting for update of Agent Pool: (Name "acctestACRAP22020291" / Registry Name "acctestACRAP22020291" / Resource Group "acctestRG-acrap-22020291"): Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
        
          with azurerm_container_registry_agent_pool.test,
          on terraform_plugin_test.tf line 20, in resource "azurerm_container_registry_agent_pool" "test":
          20: resource "azurerm_container_registry_agent_pool" "test" {
        
        waiting for update of Agent Pool: (Name "acctestACRAP22020291" / Registry
        Name "acctestACRAP22020291" / Resource Group "acctestRG-acrap-22020291"):
        Future#WaitForCompletion: context has been cancelled: StatusCode=200 --
        Original Error: context deadline exceeded
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Agent Pool: (Name "acctestACRAP22020291" / Registry Name "acctestACRAP22020291" / Resource Group "acctestRG-acrap-22020291"): containerregistry.AgentPoolsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="RegistryStatusConflict" Message="Cannot perform the operation as the resource 'acctestacrap22020291' is in 'Queued' state." Target="request"
        
        deleting Agent Pool: (Name "acctestACRAP22020291" / Registry Name
        "acctestACRAP22020291" / Resource Group "acctestRG-acrap-22020291"):
        containerregistry.AgentPoolsClient#Delete: Failure sending request:
        StatusCode=0 -- Original Error: autorest/azure: Service returned an error.
        Status=<nil> Code="RegistryStatusConflict" Message="Cannot perform the
        operation as the resource 'acctestacrap22020291' is in 'Queued' state."
        Target="request"
--- FAIL: TestAccContainerRegistryAgentPool_update (4423.95s)
FAIL
```

**Comment by magodo** [comment]
@katbyte This seems some intermittent issue on service side, will check it with the service team.

**Comment by magodo** [comment]
@katbyte The service team replies:

> Hi there, so it looks like for your update from 1 to 2 it took 286.5485293 seconds. However I don't see any requests from our side to go from 2 to 1.

See: https://github.com/Azure/azure-sdk-for-go/issues/15042#issuecomment-1034343281

**Comment by magodo** [comment]
Closing this until the issue https://github.com/Azure/azure-sdk-for-go/issues/15042 is resolved.

**Pull request closed without merging**
