### PR TITLE
azurerm_private_dns_resolver_inbound_endpoint.private_ip_allocation_method - support for the value static

### LINKED ISSUE #20961: `azurerm_private_dns_resolver_inbound_endpoint` doesn't allow to set `private_ip_allocation_method = Static`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_resolver_inbound_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_resolver_inbound_endpoint" "this" {
  name                    = "${local.resolver_name}-in"
  location                = azurerm_private_dns_resolver.this.location
  private_dns_resolver_id = azurerm_private_dns_resolver.this.id

  ip_configurations {
    private_ip_allocation_method = "Static"
    subnet_id                    = azurerm_subnet.inbound.id
    private_ip_address           = "a.b.c.d"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Based on MS documentation, it should be possible to set the allocation method to "Static" and set the inbound endpoint ip address.
https://learn.microsoft.com/en-us/azure/templates/microsoft.network/dnsresolvers/inboundendpoints?pivots=deployment-language-bicep#ipconfiguration

Looks like this is not allowed/implemented on the tf provider resource level:
https://github.com/hashicorp/terraform-provider-azurerm/blob/f25c80c637982953ba0534ab6db240e03b3df882/internal/services/privatednsresolver/private_dns_resolver_inbound_endpoint_resource.go#L82-L88

### Actual Behaviour

```
│ Error: expected ip_configurations.0.private_ip_allocation_method to be one of [Dynamic], got Static
│ 
│   with module.x.azurerm_private_dns_resolver_inbound_endpoint.this,
│   on x/dns-resolver/main.tf line 196, in resource "azurerm_private_dns_resolver_inbound_endpoint" "this":
│  196:     private_ip_allocation_method = "Static"
```

```
│ Error: Value for unconfigurable attribute
│ 
│   with module.x.azurerm_private_dns_resolver_inbound_endpoint.this,
│   on x/dns-resolver/main.tf line 198, in resource "azurerm_private_dns_resolver_inbound_endpoint" "this":
│  198:     private_ip_address           = "a.b.c.d"
│ 
│ Can't configure a value for "ip_configurations.0.private_ip_address": its value will be decided automatically based on the result of applying this configuration.
╵
```

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by katbyte**
fixes #20961

### CODE REVIEW

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Comment by MaciejBrowarski** [comment]
Hi,
This solution is partial, because when you set method to 'Static' then you have follow error:
The IP address specified in static IP configurations is empty."

But, when you set this parameter:
Can't configure a value for "ip_configurations.0.private_ip_address": its
│ value will be decided automatically based on the result of applying this
│ configuration.

Please implement entire ip_configuration block, as from original issue

  ip_configurations {
    private_ip_allocation_method = "Static"
    subnet_id                    = azurerm_subnet.inbound.id
    private_ip_address           = "a.b.c.d"
  }

Thanks,
Maciej

**Comment by gopurx** [comment]
@MaciejBrowarski I still observe the same error while using 3.94.0 or 3.93.0 provider version. Am I missing some thing here?

```
Error: Value for unconfigurable attribute
│ 
│   with azurerm_private_dns_resolver_inbound_endpoint.example1,
│   on main.tf line 12, in resource "azurerm_private_dns_resolver_inbound_endpoint" "example1":
│   12:     private_ip_address = "a.b.c.d"
│ 
│ Can't configure a value for "ip_configurations.0.private_ip_address": its value will be decided automatically based on the result of applying this
│ configuration.
```

**Comment by MaxAnderson95** [comment]
@gopurx this appears to be fixed in `3.95.0` which just released today.

**Pull request merged**
