### PR TITLE
website-scaffold: generate TF configuration example from AccTest

### PR DESCRIPTION
**Pull request by magodo**
This PR improves the webstie-scaffold tool to add supports for generating TF configuration example from AccTest.

The motivation of this PR is that I recently submit PR #13875 to fix some acctest, while I forgot to update the document accordingly (therefore I submit anther PR #13978 for that, which includes more resources). I realized that the document is easy to be out-of-sync when time goes by. One solution is to just generate the document from the passing acctest.

For above reason, I've made a small application https://github.com/magodo/terraform-provider-azurerm-example-gen to allow users to retrieve the terraform configuration from existing Acctests.

The idea behind the tool is simple. Given the code structure of the Acctest in current codebase is fixed, the tool fetch out the setup part of the specified testcase (i.e. the construction of the testdata and the resource type), then add a new print statement after it to print the first test step's configuration to the stdout. With wrapping this as a new test case, the tool will then invoke `go test -v` internally and capture the stdout content, which is the terraform configuration that the Acctest runs.

In case there is anything unexpected happend during the example generation that causes error, the website-scaffold will still fall back to its original logic that generates a TF config only for the current resource with all its required properties set. Particularly, this feature is disabled by default, unless users explicitly specified the required options.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Rebased

**Comment by katbyte** [comment]
@magodo - this one is good to go once CI is fixed up

**Comment by magodo** [comment]
@katbyte Thanks! I've updated to pass the build.

**Comment by katbyte** [comment]
@magodo - ditto for conflicts, feel free to just merge it yourself once you've resolved them

**Pull request merged**
