### PR TITLE
`azurerm_kubernetes_cluster` - set `"NodeImage"` as default value for `node_os_upgrade_channel` in version 4.0

### PR DESCRIPTION
**Pull request by hqhqhqhqhqhqhqhqhqhqhq**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description

After checking with the service team, `"NodeImage"` is set as default value for `node_os_upgrade_channel` in all scenarios if the request does not specify otherwise.

Additionally, this is no longer a preview feature, so feature flag mentioned in the doc is no longer needed.

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

No changes to current resources in current version

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

No changes to current resources in current version

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)

- solves the issue in version 4.0: https://github.com/hashicorp/terraform-provider-azurerm/issues/26519

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by ms-henglu — APPROVED** [review]
Thanks for the PR, LGTM

**Review by stephybun — APPROVED** [review]
Thanks @hqhqhqhqhqhqhqhqhqhqhq LGTM 👍

**Comment by irocker87** [comment]
@hqhqhqhqhqhqhqhqhqhqhq : We had the setting "node_os_channel_upgrade" set to "null" for a long time since we have been using azurerm v3.29 or earlier and now we are currently at azurerm v3.91. What we are observing is that the setting "node_os_channel_upgrade" is taking its default value as "NodeImage" and the upgrades have been automatically applied for the last few weeks.

Are these changes in this PR retroactively modifying the older azurerm versions and not just v3.112.0 ?

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
> @hqhqhqhqhqhqhqhqhqhqhq : We had the setting "node_os_channel_upgrade" set to "null" for a long time since we have been using azurerm v3.29 or earlier and now we are currently at azurerm v3.91. What we are observing is that the setting "node_os_channel_upgrade" has recently automatically started taking its default value as "NodeImage" and the upgrades have been automatically applied for the last few weeks, while "node_os_channel_upgrade" is still set to "null".
> 
> Are these changes in this PR retroactively modifying the older azurerm versions and not just v3.112.0 ?

@irocker87 This PR will add "NodeImage" as the default value for `node_os_channel_upgrade` (which will be renamed to `node_os_upgrade_channel`) in the coming next major release 4.0 if it is not set (/set as null).

This is because updating a Default value config is counted as a breaking change and Terraform should not trigger a plan between minor version upgrades.

Hence, for any curren versions of AzureRM, there aren't be any changes done. If the desired value for `node_os_channel_upgrade` is `Unmanaged` or `SecurityPatch` or `None`, then you need to explicitly set it in the terraform file.

**Comment by irocker87** [comment]
@hqhqhqhqhqhqhqhqhqhqhq - Sorry, there is some correction to my initial comment.  This setting "node_os_channel_upgrade" is altogether absent from our tf modules.  The value "null" is actually set for "automatic_channel_upgrade".  I am still wondering how the automatic upgrades happened when the setting "node_os_channel_upgrade" is missing. Any thoughts?

> @hqhqhqhqhqhqhqhqhqhqhq : We had the setting "node_os_channel_upgrade" set to "null" for a long time since we have been using azurerm v3.29 or earlier and now we are currently at azurerm v3.91. What we are observing is that the setting "node_os_channel_upgrade" has recently automatically started taking its default value as "NodeImage" and the upgrades have been automatically applied for the last few weeks, while "node_os_channel_upgrade" is still set to "null".
> 
> Are these changes in this PR retroactively modifying the older azurerm versions and not just v3.112.0 ?

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
> @hqhqhqhqhqhqhqhqhqhqhq - Sorry, there is some correction to my initial comment. This setting "node_os_channel_upgrade" is altogether absent from our tf modules. The value "null" is actually set for "automatic_channel_upgrade". I am still wondering how the automatic upgrades happened when the setting "node_os_channel_upgrade" is missing. Any thoughts?
> 
> image
> 
> > @hqhqhqhqhqhqhqhqhqhqhq : We had the setting "node_os_channel_upgrade" set to "null" for a long time since we have been using azurerm v3.29 or earlier and now we are currently at azurerm v3.91. What we are observing is that the setting "node_os_channel_upgrade" has recently automatically started taking its default value as "NodeImage" and the upgrades have been automatically applied for the last few weeks, while "node_os_channel_upgrade" is still set to "null".
> > Are these changes in this PR retroactively modifying the older azurerm versions and not just v3.112.0 ?

@irocker87 The reason for this behavior is that the property "node_os_channel_upgrade" does not exist in azurerm version 3.29 or earlier, hence no values were being read for "node_os_channel_upgrade" in those versions.

Note, the AKS API version used in azurerm version 3.29 or earlier might have had a different default value (not "NodeImage") set for NodeOsChannelUpgrade in the aks resource itself.

Once the Terraform file is updated to azurerm v3.91 and executed without specifying a value for "node_os_channel_upgrade" (which does exists in azurerm v3.91), the azurerm provider uses a new version of the AKS API where the default value for "node_os_channel_upgrade" is "NodeImage".

Because "node_os_channel_upgrade" is a recognized property in azurerm v3.91, it gets read into the state file with the value set as "NodeImage".

Let me know if this answers your question.

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
> Leaving this as a comment here for traceability and discussion, but this change might need to be reverted since there are AKS constellations where the API will error if Node OS Upgrade is set by default, specifically for node pools using `AvailabilitySets` instead of `VirtualMachineScaleSets`:
> 
> Here is the error message from the API:
> 
> ```
> Error: creating Kubernetes Cluster (Subscription: "1a6092a6-137e-4025-9a7c-ef77f76f2c02"
>         Resource Group Name: "acctestRG-aks-240723110207087875"
>         Kubernetes Cluster Name: "acctestaks240723110207087875"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with response: {
>           "code": "BadRequest",
>           "details": null,
>           "message": "NodeImageUpgrade is not supported on agent pool with type 'AvailabilitySet'.",
>           "subcode": ""
>          }
> ```
> 
> From memory `AvailabilitySet` is a very old and no longer fully supported option for AKS node pools so it might be worth removing support for this in 4.0 which would allow us to keep this default in place.
> 
> @hqhqhqhqhqhqhqhqhqhqhq or @ms-henglu could either one of you get in touch with the Service Team about whether removing support for `AvailabilitySet` is reasonable at this point?

@stephybun 
Thanks a lot for pointing this out.
I will confirm with the service team about `AvailabilitySet`.

But even if it can't be removed, I still thinks we should keep the value "NodeImage" as default because the AKS will set it to "NodeImage" if we don't pass anything. Which I think it would be better for us to also use this as the default value to match the AKS behaviour, and we can add more checks to restrict NodeImage to be set when `AvailabilitySet` is used?

**Comment by asifkd012020** [comment]
image
The default value for node_os_channel_upgrade is node image but the documentation does not specify it and customers are impacted with this change.

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
> image The default value for node_os_channel_upgrade is node image but the documentation does not specify it and customers are impacted with this change.

Thanks for this, doc will be updated in the upcoming version release. 
PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/27116

**Pull request merged**
