### PR TITLE
New DataSource: `azurerm_virtual_hub_inbound_route` and `azurerm_virtual_hub_outbound_route`

### PR DESCRIPTION
**Pull request by ziyeqf**
Screenshot 2023-08-31 at 11 02 40

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hi @ziyeqf 

Could you provide some context on the use-case for these data sources?

Thanks!

**Comment by ziyeqf** [comment]
> hi @ziyeqf
> 
> Could you provide some context on the use-case for these data sources?
> 
> Thanks!

It was used with this feature [`route-maps`](https://learn.microsoft.com/en-us/azure/virtual-wan/route-maps-about).
And AFAIK, the information it get will only be output to users, no resource require it to create.  will contact service team for some real world examples as it's a bit complex..

**Comment by tombuildsstuff** [comment]
@ziyeqf given that scenario, I don't see how this information would be useful in Terraform? From the document it appears that the Route Map gets applied to any/all connections?

**Comment by ziyeqf** [comment]
> @ziyeqf given that scenario, I don't see how this information would be useful in Terraform? From the document it appears that the Route Map gets applied to any/all connections?

does "wont be useful" mean not be useful to configure other resources? I thought there might be user want to take it as an output

**Comment by tombuildsstuff** [comment]
@ziyeqf can you give an example of a scenario using this data? These two data sources would need to be configured in such a way that they're only run after every other related resource has been provisioned (which'd likely become a source of bugs) - but more than that, I'm wondering where this data would be useful?

We only expose fields from resources which make are likely to be used by end-users - for example we don't expose `type` or `systemData` since this information (in the case of `systemData`) would be out of date after each update to the resource. Given the nature of the data being returned from the API, it's likely these would be stale (and that users would encounter issues with these data sources) - as such I'm struggling to understand the use-case for the data being returned here - could you elaborate?

**Comment by ziyeqf** [comment]
Hey @tombuildsstuff , per the document: https://learn.microsoft.com/en-us/azure/virtual-wan/route-maps-dashboard, these data sources work as same as the dashboard. 
And, yes, as you said, it might not be useful in Terraform scnario. 
With above, I'm closing this PR. :)

**Pull request closed without merging**
