### PR TITLE
update python version support on linux web apps

### LINKED ISSUE #24362: azurerm_linux_web_app should allow python 3.12, disallow python 3.7
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "treasure" {
  ...
  site_config {
    application_stack {
      python_version = "3.12"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected site_config.0.application_stack.0.python_version to be one of ["3.7" "3.8" "3.9" "3.10" "3.11"], got 3.12
```

### Expected Behaviour

python 3.12 should be allowed, python 3.7 should not.

### Actual Behaviour

_No response_

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

https://azure.github.io/AppService/2023/11/14/Node-20-Python-312-available-on-app-service.html

```console
$ az webapp list-runtimes --os linux | grep PYTHON
  "PYTHON:3.12",
  "PYTHON:3.11",
  "PYTHON:3.10",
  "PYTHON:3.9",
  "PYTHON:3.8",
```

### PR DESCRIPTION
**Pull request by dimbleby**
fixes #24362 

I've just copy-pasted, taking out 3.7 and adding in 3.12.  

If it's all good then great: if not then please disregard!

### CODE REVIEW

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @dimbleby thanks for submitting this! It looks like the 3.7 version still works via terraform given the `TestAccLinuxWebApp_withPython37` test is passing, although I notice it is not available as an option in the portal or cli. I think it we should use the feature flag `features.FourPointOh()` to deprecate this option rather than removing it completely, to avoid any breaking changes for users. Thanks!

**Comment by dimbleby** [comment]
I don't know what that means and - with apologies - this is not important enough to me that I care to get into the weeds.

Pleae feel free to make adjustments to this merge request as needed, or to throw it away and start over!

**Comment by dimbleby** [comment]
I will not be making changes to this MR.  As I said at the start - if it is good, then great: if it is not then please disregard.

**Comment by catriona-m** [comment]
Thanks @dimbleby - I've updated this now to retain `3.7` and resolve the conflicts.

**Review by katbyte — APPROVED** [review]
LGTM 🌧️

**Pull request merged**
