### PR TITLE
add dynamic_container_enabled support for datafactory

### PR DESCRIPTION
**Pull request by brandonros**
part of https://github.com/hashicorp/terraform-provider-azurerm/issues/15691

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
Thanks @brandonros - LGTM 👍

**Comment by gkman** [comment]
I believe this change may have broken `data_factory_datasets`

```bash
│ Error: setting `azure_blob_storage_location` for Data Factory Delimited Text Dataset Invalid address to set: []string{"azure_blob_storage_location", "0", "dynamic_container_enabled"}
│
│   with module.fusion.module.df_ds_model_input_source.azurerm_data_factory_dataset_delimited_text.self,
│   on ../../../../delimited_text.tf line 1, in resource "azurerm_data_factory_dataset_delimited_text" "self":
│    1: resource "azurerm_data_factory_dataset_delimited_text" "self" {
```

**Comment by brandonros** [comment]
Let’s work together to try to roll forward instead of roll backward. Any guesses on how to fix?

**Comment by gkman** [comment]
Oh, I'm fine with rolling forward, but I'm not entirely sure how to try fixing it. As in, I would be curious to add the needed arguments to the resources and the matching tests, but I don't yet know how/if I could use a local build in my code to prove to myself that that is the change that solved the problem.

**Comment by gkman** [comment]
So I think the PR above fixes the issue, hopefully everywhere. I feel a little out of my depth. I'm definitely making best guesses on some of this.

**Comment by mbfrahry** [comment]
Hey all, I found and fixed the issue with #16514. What happened was that `dynamic_container_enabled` wasn't added to the schema for `azure_blob_storage_location`. That has been fixed with #16514 and should go out in the next release!

**Comment by gkman** [comment]
@mbfrahry So I have a PR open for this too with additional tests, https://github.com/hashicorp/terraform-provider-azurerm/pull/16350 but I guess I have some failing tests, but I didn't see a job failure, and I haven't gotten to digging into it yet.

**Pull request merged**
