### PR TITLE
`azurerm_firewall_policy`: fix AccTest specify `pac_file` with storage sas url instead of hard code url

### PR DESCRIPTION
**Pull request by wuxu92**
fix acc test failed cause of pac file invalid:

```
        Error: creating/updating Firewall Policy: (Name "acctest-networkfw-Policy-230815030049305328" / Resource Group "acctestRG-networkfw-230815030049305328"): 
network.FirewallPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyExplicitProxyPacFileSasUrlInvalid" 
Message="Firewall Policy /subscriptions/*******/resourceGroups/acctestRG-networkfw-230815030049305328/providers/Microsoft.Network/firewallPolicies/acctest-networkfw-Policy-230815030049305328 Pac file Sas Url is invalid"
```

image

### CODE REVIEW

**Review by WodansSon — DISMISSED** [review]
Hi @wuxu92, thank you for opening this PR, I had a look and this LGTM! 🔥

**Comment by WodansSon** [comment]
Looks like some tests are failing, can you fix the tests and I will have another look?

```bash
------- Stdout: -------
=== RUN   TestAccFirewallPolicy_inherit
=== PAUSE TestAccFirewallPolicy_inherit
=== CONT  TestAccFirewallPolicy_inherit
    testing_new.go:86: Error running post-test destroy, there may be dangling resources: exit status 1
        Error: deleting Firewall Policy "acctest-networkfw-Policy-230816215105122223-parent" (Resource Group "acctestRG-networkfw-230816215105122223"): network.FirewallPoliciesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyHasChildPolicyReferences" Message="Firewall Policy '/subscriptions/*******/resourceGroups/acctestRG-networkfw-230816215105122223/providers/Microsoft.Network/firewallPolicies/acctest-networkfw-Policy-230816215105122223-parent' can not be deleted since there are other policies that inherit from this policy."
--- FAIL: TestAccFirewallPolicy_inherit (76.50s)
FAIL
```

**Comment by wuxu92** [comment]
This two failed case should not  be caused by this PR. They occasionally fail in main branch too. I previously looked into them but no solution was found😞 

image
image

**Comment by WodansSon** [comment]
Hi @wuxu92, Yes, I understand that however if the tests do not pass I cannot merge this PR. Looking at the output it appears that something needs to be changed in the test case to get it to pass. Can you try playing with it and see if you can get it to pass?

**Comment by wuxu92** [comment]
@WodansSon Hi I have udpated the acctest configuration to fix the failed cases.

**Comment by WodansSon** [comment]
Hi @wuxu92, the following 4 test cases still fail:

* TestAccFirewallPolicy_complete
* TestAccFirewallPolicy_completePremium
* TestAccFirewallPolicy_update
* TestAccFirewallPolicy_updatePremium

```bash
Failure sending request:
  StatusCode           = 400 
  Original Error: Code = "FirewallPolicyExplicitProxyPacFileSasUrlInvalid"
  Message              = "Firewall Policy /subscriptions/.../acctest-networkfw-Policy-xxx Pac file Sas Url is invalid"
```

**Comment by wuxu92** [comment]
@WodansSon It's a bit strange that there are no changes in this run. And the reversion id 021ceae91f is not from this PR. I began a new run, but there are still two failures. Both of them are not related to this PR. I'm still working on the TestAccFirewallPolicy_completePremium failure that's been ongoing.

image

**Comment by wuxu92** [comment]
All Tests are pass now.

image

**Comment by WodansSon** [comment]
@wuxu92, thanks for that I am now trying to run the tests on the TC server, if they pass this LGTM! 🙂

**Comment by wuxu92** [comment]
@WodansSon Tests passed:

image

**Pull request merged**
