### PR TITLE
fix batch pool data source

### PR DESCRIPTION
**Pull request by xiaxyi**
Fixing the schema definition in data source.

Fixing GH issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/16702

The reason why using set is the flattenFunc is normalized, not sure if we need to split the flatten func out from the batch_pool.go?
```
"public_ips": {
Type:     pluginsdk.TypeSet,
Computed: true,
Elem: &pluginsdk.Schema{
Type: pluginsdk.TypeString,
},
},
····

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
test failure:

```

------- Stdout: -------
=== RUN   TestAccBatchPoolDataSource_complete
=== PAUSE TestAccBatchPoolDataSource_complete
=== CONT  TestAccBatchPoolDataSource_complete
    testcase.go:110: Step 1/1 error: Error running apply: exit status 1
        
        Error: creating Pool: (Name "testaccpoolw1cri" / Batch Account Name "testaccbatchw1cri" / Resource Group "testaccRG-batch-220512192233113836"): auto_user and user_name cannot be specified in the user_identity at the same time
        
          with azurerm_batch_pool.test,
          on terraform_plugin_test.tf line 63, in resource "azurerm_batch_pool" "test":
          63: resource "azurerm_batch_pool" "test" {
        
--- FAIL: TestAccBatchPoolDataSource_complete (524.82s)
FAIL
```

**Comment by xiaxyi** [comment]
The `user_name` will not be null, instead, will be an empty string if not specified. Add the logic to check the empty value.

**Comment by xiaxyi** [comment]
@stephybun No, I didn't change the api management test data

**Review by katbyte — APPROVED** [review]
LGTM 🤖

**Pull request merged**
