### PR TITLE
New resource: azurerm_virtual_network_gateway_nat_rule

### PR DESCRIPTION
**Pull request by neil-yechenwei**
To resolve the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/15348, it has to implement Virtual Network Gateway Nat Rule first. Once this PR is merged, I assume it has to submit another PR to implement  [`egressNatRules`](https://github.com/Azure/azure-rest-api-specs/blob/a70086b6711c1058aaf3c5906744a665a492a504/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/virtualNetworkGateway.json#L3386) and [`ingressNatRules`](https://github.com/Azure/azure-rest-api-specs/blob/a70086b6711c1058aaf3c5906744a665a492a504/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/virtualNetworkGateway.json#L3379) of Virtual Network Gateway Connection (azurerm_virtual_network_gateway_connection).

--- PASS: TestAccVirtualNetworkGatewayNatRule_basic (2589.57s)
--- PASS: TestAccVirtualNetworkGatewayNatRule_updatePortRange (2697.90s)
--- PASS: TestAccVirtualNetworkGatewayNatRule_complete (2774.72s)
--- PASS: TestAccVirtualNetworkGatewayNatRule_requiresImport (2803.29s)
--- PASS: TestAccVirtualNetworkGatewayNatRule_update (3078.08s)

API reference:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/virtualNetworkGateway.json#L2389

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
@neil-yechenwei based on https://github.com/hashicorp/terraform-provider-azurerm/issues/15348 it appears that we also need to split the Create and Update method for Virtual Network Gateway such that that update does a Delta update for this to work - would you be able to take a look?

Thanks!

**Comment by neil-yechenwei** [comment]
@katbyte , seems the Potential Terraform Configuration in https://github.com/hashicorp/terraform-provider-azurerm/issues/15348 has some problem. Per my understanding and testing, I assume we should implement Virtual Network Gateway Nat Rule first and then implement the [egressNatRules](https://github.com/Azure/azure-rest-api-specs/blob/a70086b6711c1058aaf3c5906744a665a492a504/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/virtualNetworkGateway.json#L3386) and [ingressNatRules](https://github.com/Azure/azure-rest-api-specs/blob/a70086b6711c1058aaf3c5906744a665a492a504/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/virtualNetworkGateway.json#L3379) of Virtual Network Gateway Connection (azurerm_virtual_network_gateway_connection) for the association. In additional, Virtual Network Gateway Connection resource is using separate API client `Network.VnetGatewayConnectionsClient` and Virtual Network Gateway Nat Rule resource is also using separate API client `Network.VnetGatewayNatRuleClient`.So I think we don't need to split the create and update method for the Virtual Network Gateway (azurerm_virtual_network_gateway). Does it make sense?

**Comment by katbyte** [comment]
Why would the fact the use a different client make a difference? they both alter the same resource and if someone wants to be able to go lifecycle ignore changes the create and update needs to be seperate. So can we please split the create and update?

**Comment by neil-yechenwei** [comment]
I referred the existing resource [nsg](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/network_security_group_resource.go) and [nsr](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/network_security_rule_resource.go). So I used the separate api client.

I splitted the create and update.

**Comment by steve-down** [comment]
Is anyone aware of where this feature currently stands with respect to testing and release? It would be really useful (especially given what a pain the portal is for setting up NAT rules on VNGs)?

**Pull request merged**
