### PR TITLE
Fix Msi support for stream analytics job

### LINKED ISSUE #19152: `azurerm_stream_analytics_job`: `account_key` is not required for `authentication_mode = "Msi"`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.30

### Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_job

### Terraform Configuration Files

```hcl
resource "azurerm_stream_analytics_job" "example" {
  job_storage_account {
    account_name        = azurerm_storage_account.example.name
    authentication_mode = "Msi"
  }
  ...
}
```

### Debug Output/Panic Output

```shell
│ Error: Missing required argument
│
│   on streamanalytics.job.tf line 19, in resource "azurerm_stream_analytics_job" "example":
│   19:   job_storage_account {
│
│ The argument "account_key" is required, but no definition was found.
```

### Expected Behaviour

No errors and planning succeeds

### Actual Behaviour

Planning fails

### Steps to Reproduce

terraform plan

### Important Factoids

_No response_

### References

PR #19120 introduced support, but `account_key` is optional when using `authentication_mode = "Msi"`

### LINKED ISSUE #19351: Unable to create a Stream Analytics Job using a Job Storage account with a System managed identity
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_job

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.31.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name = "my-resourcegroup"
  location = "eastus2"
}

resource "azurerm_storage_account" "example" {
  name                     = "jdmystoraccount123456"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_stream_analytics_job" "example" {
  compatibility_level                      = "1.2"
  content_storage_policy                   = "JobStorageAccount"
  data_locale                              = "en-US"
  events_late_arrival_max_delay_in_seconds = 5
  events_out_of_order_max_delay_in_seconds = 0
  events_out_of_order_policy               = "Adjust"
  location                                 = azurerm_resource_group.example.location
  name                                     = "my-StrAnalyticsJob"
  output_error_policy                      = "Stop"
  resource_group_name                      = azurerm_resource_group.example.name
  streaming_units                          = 1
  type                 = "Cloud"
  transformation_query = <<QUERY
    SELECT *
    INTO [YourOutputAlias]
    FROM [YourInputAlias]
QUERY

  identity {
    type = "SystemAssigned"
  }

  job_storage_account {
    account_name        = azurerm_storage_account.example.name
    authentication_mode = "Msi"
    #account_key = azurerm_storage_account.example.primary_access_key
  }

  depends_on = [
    azurerm_storage_account.example
  ]

  timeouts {}
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/c0mmad0r3/5a80c8c15c133211c2fc8ba7b93f3a0f
```

### Expected Behaviour

Stream Analytics Job should be created with a a Job Storage account set and Authentication Mode set as Managed Identity: System Assigned.

### Actual Behaviour

If using authenticated_mode="Msi," under job_storage_account with no account key, you get error message:

Error: Missing required argument
  on main.tf line 50, in resource "azurerm_stream_analytics_job" "example":
  50:   job_storage_account {

The argument "account_key" is required, but no definition was found.

After then adding account_key argument, you get error message:

Error: creating Streaming Job: (Name "my-StrAnalyticsJob" / Resource Group "my-resourcegroup"): streamanalytics.StreamingJobsClient#CreateOrReplace: Failure sending request: StatusCode=422 -- Original Error: Code="422" Message="The property 'accountKey' is not supported with property 'authenticationMode' set as 'Msi' for 'Job Storage Account'. Please remove property 'accountKey' or set property 'authenticationMode' as 'ConnectionString'." Details=[{"code":"422","correlationId":"f2634cf2-b378-6084-5c88-cbe0523c34db","message":"The property 'accountKey' is not supported with property 'authenticationMode' set as 'Msi' for 'Job Storage Account'. Please remove property 'accountKey' or set property 'authenticationMode' as 'ConnectionString'.","requestId":"8672b617-827d-40c2-ae36-c9a9ce99e91a"}]

### Steps to Reproduce

terraform apply with above tf file.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by ThreeFive-O**
Fix #19152
Fix #19351

Allow `Msi` option for `job_storage_account` `authentication_mode`.

A stream analytics job can't be directly created using `Msi` option because of cyclic dependency between job and storage account, it can be changed latter on once the job exists.
Therefore `Msi` should be supported.
This PR adds the functionality and even throws an error when using `Msi` option in the create phase.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
thanks for the PR @ThreeFive-O, overall looks good but we have a test failure:
```
------- Stdout: -------
=== RUN   TestAccStreamAnalyticsJob_jobStorageAccount_Msi
    testcase.go:120: Step 2/3 error: Error running apply: exit status 1
        
        Error: updating Streaming Job (Subscription: "*******"
        Resource Group Name: "acctestRG-230706172940933015"
        Streaming Job Name: "acctestjob-230706172940933015"): streamingjobs.StreamingJobsClient#Update: Failure responding to request: StatusCode=422 -- Original Error: autorest/azure: Service returned an error. Status=422 Code="422" Message="The Job Storage Account has AuthenticationMode set to MSI, but MSI has not been enabled for the streaming job. Please enable MSI on the streaming job and try again." Details=[{"code":"422","correlationId":"616d865f-8faf-6d54-ea43-7880f774757a","message":"The Job Storage Account has AuthenticationMode set to MSI, but MSI has not been enabled for the streaming job. Please enable MSI on the streaming job and try again.","requestId":"87b8abb6-b1fc-438c-b248-748dc58690fe"}]
        
          with azurerm_stream_analytics_job.test,
          on terraform_plugin_test.tf line 30, in resource "azurerm_stream_analytics_job" "test":
          30: resource "azurerm_stream_analytics_job" "test" {
        
--- FAIL: TestAccStreamAnalyticsJob_jobStorageAccount_Msi (191.14s)
FAIL
```

**Comment by ThreeFive-O** [comment]
@katbyte Forgot to add the system managed identity in the test block. Also used gofmt on the two GO files. Please let the tests run again.

**Comment by ThreeFive-O** [comment]
@katbyte Could you please run the CI to make sure there are no more test errors.

**Review by manicminer — CHANGES_REQUESTED** [review]
Thanks for updating @ThreeFive-O. The tests look good (see below), however I wonder if there's a way we can accommodate both Create and Update operations here, by requiring/allowing `account_key` along with `authentication_mode = "Msi"` when creating a new resource, then handling the change of authentication setup as part of the Create operation (e.g. create it with `ConnectionString` then switch it to `Msi`)? This would avoid requiring the user to perform a two-step apply which is something we try to avoid wherever possible. WDYT?

Screenshot 2023-07-18 at 18 29 46

**Comment by ThreeFive-O** [comment]
@manicminer Unfortunately I don't know how to solve the issue for "Stream analytics job with MSI with job storage account"
1. terraform creates storage account
2. terraform creates stream analytics job with account key authentication
3. terraform creates storage account permission for stream analytics job MSI
4. terraform can switch to stream analytics job with MSI

Now if we want to combine step 2 and 4 into one logic as you suggest, there would have to be a long polling on the storage account until it receives the required RBAC permission for the MSI which is step 3.
But terraform would have to create the RBAC rule (step 3) in parallel to step 2 and 4 which I think is technically not possible, since terraform won't start step 3 until step 2 is finished.
Step 2 will never finish, because step 2 also includes step 4, but at that point step 4 waits on step 3 which won't start until step 2  is finished.
I think this is a classic deadlock scenario.

Idea:
terraform yields after step 2 and lets all other resources deploy and then later on resumes with step 4.
So far I haven't seen something like that implemented in the code itself as it seems very sequential to me.

If you have any pointers on how to solve such a deadlock scenario please let me know.

**Comment by manicminer** [comment]
@ThreeFive-O Sorry, I overlooked the permissions aspect of configuring the storage account. In this case, I think we'd need to look at having a virtual resource for configuring the job storage account for the stream analytics job. This would enable configurations with a dependency on the role assignment, for example:

```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-%d"
  location = "%[3]s"
}

resource "azurerm_storage_account" "test" {
  name                     = "acctestacc%[2]s"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_stream_analytics_job" "test" {
  name                   = "acctestjob-%[4]d"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  streaming_units        = 3
  content_storage_policy = "JobStorageAccount"

  job_storage_account {
    account_name = azurerm_storage_account.test.name
    account_key  = azurerm_storage_account.test.primary_access_key
  }

  identity {
    type = "SystemAssigned"
  }

  transformation_query = <<QUERY
    SELECT *
    INTO [YourOutputAlias]
    FROM [YourInputAlias]
QUERY

  lifecycle {
    ignore_changes = [job_storage_account]
  }
}

resource "azurerm_role_assignment" "test" {
  scope                = azurerm_storage_account.test.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_stream_analytics_job.test.identity[0].principal_id
}

resource "azurerm_stream_analytics_job_storage_account" "test" {
  authentication_mode = "Msi"
  account_name        = azurerm_storage_account.test.name
}
```

It might be necessary to use `ignore_changes` as above to prevent a flapping diff. Do you think this would work?

**Comment by ThreeFive-O** [comment]
@manicminer I was thinking something along those lines but I wasn't sure how to implement such a virtual resource.
I might need some time to figure something out.

As regards to your code suggestion, a reference to the stream analytics job is also required for the virtual resource.
``` terraform
resource "azurerm_stream_analytics_job_storage_account" "test" {
  authentication_mode = "Msi"
  account_name        = azurerm_storage_account.test.name
  stream_analytics_job_id = azurerm_stream_analytics_job.test.id
}
```
Now two questions:
1. Should we use the id or name for the reference? Most times I have seen the id is used as a reference
2. Should the virtual resource also take care of assigning the `Storage Blob Data Contributor` role? Because this is always required.

**Comment by manicminer** [comment]
There are quite a lot of virtual resources around the provider you can look at for reference, e.g. [azurerm_virtual_network_dns_servers](https://github.com/hashicorp/terraform-provider-azurerm/blob/ec1d841c5ab0c4e269156d55b546c0fa5bfa7894/internal/services/network/virtual_network_dns_servers_resource.go)

We should use the ID for reference where possible, the use of resource group / name is a legacy pattern.

We likely don't want to handle the role assignment here, this would cross boundaries of responsibility and also should be up to the practitioner to decide and configure explicitly.

**Comment by ThreeFive-O** [comment]
@manicminer Thank you for the pointers and your help

**Comment by manicminer** [comment]
@ThreeFive-O Just checking in to see if you've maybe had time to work on this further?

**Comment by tombuildsstuff** [comment]
@ThreeFive-O any chance you'd had another chance to look at this one?

**Pull request closed without merging**
