### PR TITLE
changes to custom data should force new resource

### LINKED ISSUE #148: changes to `azurerm_virtual_machine.os_profile.custom_data` and `.os_profile.admin_password` are not detected
### Terraform Version

```
Terraform v0.9.10
```

### Affected Resource(s)

- `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # use environment variables
}

resource "azurerm_virtual_machine" "example" {
  name                  = "example-delete-me"
  location              = "West US 2"
  resource_group_name   = "${azurerm_resource_group.example.name}"
  network_interface_ids = ["${azurerm_network_interface.example.id}"]
  vm_size               = "Basic_A0"

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }

  storage_os_disk {
    name              = "example-os_disk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  os_profile {
    computer_name  = "example"
    admin_username = "example"
    admin_password = "Gu8da3Aeshiefee0CHANGED"
    custom_data    = <<-EOF
      #!/bin/bash
      echo THIS_CHANGED
      EOF
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  delete_os_disk_on_termination = true
}

resource "azurerm_resource_group" "example" {
  name     = "example-delete-me"
  location = "West US 2"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.42.0.0/16"]
  location            = "West US 2"
  resource_group_name = "${azurerm_resource_group.example.name}"
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet_default"
  resource_group_name  = "${azurerm_resource_group.example.name}"
  virtual_network_name = "${azurerm_virtual_network.example.name}"
  address_prefix       = "10.42.2.0/24"
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = "West US 2"
  resource_group_name = "${azurerm_resource_group.example.name}"

  ip_configuration {
    name                          = "example-nic-ip_configuration"
    subnet_id                     = "${azurerm_subnet.example.id}"
    private_ip_address_allocation = "dynamic"
  }
}
```

### Debug Output

Not including log output here because it doesn't seem critical to this issue and I'm concerned about secrets leakage. (For example, the `TF_LOG=TRACE` output contains an `Authorization: Bearer...` header. Is that safe?)

### Expected Behavior

After the HCL above is `apply`ed, if any attribute *including*

- `azurerm_virtual_machine.os_profile.custom_data`
- and `azurerm_virtual_machine.os_profile.admin_password`

are changed, then re-planning should identify the changes made and trigger a destroy/re-create of the VM.

### Actual Behavior

`terraform plan` reports that it "did not detect any differences", even though changes were made:

```diff
diff --git a/test-case.tf.original b/test-case.new.tf
index 7ed0377..525fea6 100644
--- a/test-case.tf.original
+++ b/test-case.new.tf
@@ -26,10 +26,10 @@ resource "azurerm_virtual_machine" "example" {
   os_profile {
     computer_name  = "example"
     admin_username = "example"
-    admin_password = "Gu8da3Aeshiefee0"
+    admin_password = "Gu8da3Aeshiefee0CHANGED"
     custom_data    = <<-EOF
       #!/bin/bash
-      echo foo
+      echo THIS_CHANGED
       EOF
   }
```

Changes to some *other* attributes, such as `.os_profile.admin_username`, *did* result in the expected destroy/re-create plan.

### Steps to Reproduce

1. `terraform apply` with the HCL above
2. Change any of the attributes listed under "Expected Behavior".
3. `terraform plan` and observe "did not detect any differences"

### PR DESCRIPTION
**Pull request by josmo**
~Fixes https://github.com/terraform-providers/terraform-provider-azurerm/issues/148~

custom-data changes should force a new resource creation.

### CODE REVIEW

**Comment by josmo** [comment]
@tombuildsstuff Let me know if this seems unreasonable, however it seems any change to the custom-data should forNew.

**Comment by thiagocaiubi** [comment]
Hi @josmo, 

How could you get the current customData from virtual machine? I wasn't able to retrieve this information using the API thought `https://resources.azure.com`. Maybe it's a tool limitation.
The API docs describe `customData` as an exported field.

https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/virtualmachines-get

**Comment by thiagocaiubi** [comment]
Hi @josmo, never mind. 

Just realize terraform refresh is able to retrieve the info. Thanks!

**Comment by josmo** [comment]
@thiagocaiubi cool :)

**Review by tombuildsstuff — APPROVED** [review]
Hey @josmo 

Thanks for this PR - I've taken a look and can confirm this issue:

> compute.VirtualMachinesClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="PropertyChangeNotAllowed" Message="Changing property 'customData' is not allowed."

We're currently using version `2016-04-30-preview` of the Compute API which doesn't allow updating the `CustomData` field - [however there's an issue open](https://github.com/Azure/azure-rest-api-specs/issues/895) to update to a newer API version (later than `2016-08-30` which supports updating the `CustomData` field.

Once the Swagger / SDK exists for this we'll investigate this (and presumably revert this change) - but for the moment this change LGTM :)

Thanks!

**Comment by tombuildsstuff** [comment]
Actually, investigating this further it appears this value is missing from Hash - which is why it's not being picked up. I've posted more details in #148 - however this needs some larger changes (i.e. switching from a Set to a List)

For the moment - this is fine fix the issue when paired with `terraform apply -refresh=false` - however that doesn't fix

For the moment this doesn't actually fix the issue as it's still missing from the hash - that said it'll be picked up by `terraform apply -refresh=false`. I'm going to merge this anyway, as updating customData isn't supported right now; however I'm going to leave

**Pull request merged**
