### PR TITLE
`azurerm_firewall_rule_x` - return various attribute blocks back to `Set` (#20164)

### LINKED ISSUE #20164: Return firewall rule related resources type back to `Set`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The PR https://github.com/hashicorp/terraform-provider-azurerm/pull/15008 fixed the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/11181, namely corrected the diff when the existing rule is updated, but introduced another problem. It drastically complicated the diff when an order of rules is changed (e.g., when adding/removing a rule to/from the middle of the rule collection).

The correct solution for that issue was to specify all firewall rule properties including optional:
```
resource "azurerm_firewall_network_rule_collection" "example-rule" {
  depends_on = [azurerm_firewall.example]

  name                = "Example-RuleCollection"
  azure_firewall_name = azurerm_firewall.example.name
  resource_group_name = data.azurerm_resource_group.resourcegroup.name
  priority            = 201
  action              = "Allow"

  rule {
    name                  = "Allow_From_SomeSource_TCP_01"
    source_addresses      = ["10.0.0.5"]
    destination_addresses = ["10.0.0.128"]
    destination_ports     = ["22", "80", "443"]
    protocols             = ["TCP"]

    # these properties are needed
    description           = ""
    destination_fqdns     = []
    destination_ip_groups = []
    source_ip_groups      = []
  }

  rule {
    name                  = "Allow_From_SomeSource_TCP_02"
    source_addresses      = ["10.0.0.6"]
    destination_addresses = ["10.0.0.128"]
    destination_ports     = ["3000", "445"]
    protocols             = ["TCP"]

    # these properties are needed
    description           = ""
    destination_fqdns     = []
    destination_ip_groups = []
    source_ip_groups      = []
  }
}

```
then the output shows 1 rule to delete and 1 to add which will be easy to understand, like:
```
~ update in-place

Terraform will perform the following actions:

  # azurerm_firewall_network_rule_collection.example-rule will be updated in-place
  ~ resource "azurerm_firewall_network_rule_collection" "example-rule" {
        id                  = "xxxxxxxx"
        name                = "Example-RuleCollection"
        # (4 unchanged attributes hidden)

      + rule {
          + destination_addresses = [
              + "10.0.0.128",
            ]
          + destination_fqdns     = []
          + destination_ip_groups = []
          + destination_ports     = [
              + "22",
              + "443",
              + "80",
            ]
          + name                  = "Allow_From_SomeSource_TCP_01"
          + protocols             = [
              + "TCP",
            ]
          + source_addresses      = [
              + "10.0.0.5",
            ]
          + source_ip_groups      = []
        }
      - rule {
          - destination_addresses = [
              - "10.0.0.128",
            ] -> null
          - destination_fqdns     = [] -> null
          - destination_ip_groups = [] -> null
          - destination_ports     = [
              - "443",
              - "80",
            ] -> null
          - name                  = "Allow_From_SomeSource_TCP_01" -> null
          - protocols             = [
              - "TCP",
            ] -> null
          - source_addresses      = [
              - "10.0.0.5",
            ] -> null
          - source_ip_groups      = [] -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### New or Affected Resource(s)/Data Source(s)

- azurerm_firewall_application_rule_collection
- azurerm_firewall_nat_rule_collection
- azurerm_firewall_network_rule_collection
- azurerm_firewall_policy_rule_collection

### Potential Terraform Configuration

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by AlexPykavy**
Closes #20164

### CODE REVIEW

**Review by mbfrahry — COMMENTED** [review]
Hi @AlexPykavy, thanks for taking the time to open this PR but I don't believe it will solve #20164. Sets tend to complicate plans even more because they use hashes. If you want to change a value inside of a Set, the hash for that Set will change. Terraform will see that the hash changed and want to replace everything in that block even though you just wanted to change one thing. It makes it even worse when you have Sets inside of Sets. If you change the variable in a nested Set, that will show the parent Set changing as well. 

Out of curiosity, have you seen that behavior in action? I would build the provider with the changes you've made in this PR and update something like `source_addresses` and then check out the plan that should show the cascading changes that will occur with `rule`

**Comment by AlexPykavy** [comment]
Hi @mbfrahry, I agree that `Set`s are tricky and I've spent quite a while experimenting to understand how they work. In my opinion, the most appropriate data type for firewall rules is `Map` but it implies changing resources schema.

Thus, if we need to mitigate the issue with a little blood we have to choose between `Set` and `List`. Both of them have their pros and cons and let's brush up on them (denote the source (existing) state as `S` and the target one as `T`):
- `List` elements are indexed and ordered that allows comparing elements in the same position. It assumes that without any changes we should get `S[i] == T[i]`. But when you alter the middle of a list (let's say adding/removing element at position `p`), all subsequent elements become shifted which results in the following situation: `0 <= i < p: S[i] == T[i], p < i < N: S[i] == T[i±1]`. Of course, Terraform doesn't know this and just shows all elements starting with `p` as changed.
- `Set` elements are also indexed but with a hash because the Terraform's `Set` is build with Golang's `map` and unordered. The last feature helps to avoid the issue with adding/removing new elements because comparison occurs only by hashes. But absence of order brings its own difficulties, namely it's impossible to find which updated element from `T` corresponds to an original element from `S`. That's why a plan always interpret such changes as follows: remove all unmatched elements from `S` and add all unmatched elements from `T`.

Let's see all this in action, we'll use a slightly modified sample from the https://github.com/hashicorp/terraform-provider-azurerm/issues/11181:
```
locals {
  location      = "West Europe"
  resourcegroup = "rg-mssqlvm"
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.41.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "resourcegroup" {
  name     = local.resourcegroup
  location = local.location
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-mssql"
  resource_group_name = azurerm_resource_group.resourcegroup.name
  location            = local.location
  address_space       = ["10.0.0.0/24"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "snet-mssql"
  virtual_network_name = azurerm_virtual_network.vnet.name
  resource_group_name  = azurerm_resource_group.resourcegroup.name
  address_prefixes     = ["10.0.0.0/26"]
}

resource "azurerm_subnet" "azurefirewall_subnet" {
  name                 = "AzureFirewallSubnet"
  virtual_network_name = azurerm_virtual_network.vnet.name
  resource_group_name  = azurerm_resource_group.resourcegroup.name
  address_prefixes     = ["10.0.0.64/26"]
}

resource "azurerm_firewall" "example" {
  name                = "afw-mssql"
  location            = local.location
  resource_group_name = azurerm_resource_group.resourcegroup.name
  sku_name            = "AZFW_VNet" # new required attribute
  sku_tier            = "Standard"  # new required attribute

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.azurefirewall_subnet.id
    public_ip_address_id = azurerm_public_ip.azure_firewall_pip.id
  }
}


resource "azurerm_public_ip" "azure_firewall_pip" {
  name                = "afw-mssql-pip"
  sku                 = "Standard"
  location            = local.location
  resource_group_name = azurerm_resource_group.resourcegroup.name
  allocation_method   = "Static"
}


resource "azurerm_firewall_network_rule_collection" "example-rule" {
  depends_on = [azurerm_firewall.example]

  name                = "Example-RuleCollection"
  azure_firewall_name = azurerm_firewall.example.name
  resource_group_name = azurerm_resource_group.resourcegroup.name
  priority            = 201
  action              = "Allow"

  rule {
    name                  = "Allow_From_SomeSource_TCP_01"
    source_addresses      = ["10.0.0.5"]
    destination_addresses = ["10.0.0.128"]
    destination_ports     = ["22", "80", "443", "8888"]
    protocols             = ["TCP"]

    # optional attributes needed to calculate the `rule` hash correctly
    description           = ""
    destination_fqdns     = []
    destination_ip_groups = []
    source_ip_groups      = []
  }

  rule {
    name                  = "Allow_From_SomeSource_TCP_02"
    source_addresses      = ["10.0.0.6"]
    destination_addresses = ["10.0.0.128"]
    destination_ports     = ["3000", "445"]
    protocols             = ["TCP"]

    # optional attributes needed to calculate the `rule` hash correctly
    description           = ""
    destination_fqdns     = []
    destination_ip_groups = []
    source_ip_groups      = []
  }
}
```

Then remove `Allow_From_SomeSource_TCP_01` rule.
- Original provider plan:
```
  # azurerm_firewall_network_rule_collection.example-rule will be updated in-place
  ~ resource "azurerm_firewall_network_rule_collection" "example-rule" {
        id                  = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-mssqlvm/providers/Microsoft.Network/azureFirewalls/afw-mssql/networkRuleCollections/Example-RuleCollection"
        name                = "Example-RuleCollection"
        # (4 unchanged attributes hidden)

      ~ rule {
          ~ destination_ports     = [
              - "22",
              - "80",
              - "443",
              - "8888",
              + "3000",
              + "445",
            ]
          ~ name                  = "Allow_From_SomeSource_TCP_01" -> "Allow_From_SomeSource_TCP_02"
          ~ source_addresses      = [
              - "10.0.0.5",
              + "10.0.0.6",
            ]
            # (5 unchanged attributes hidden)
        }
      - rule {
          - destination_addresses = [
              - "10.0.0.128",
            ] -> null
          - destination_fqdns     = [] -> null
          - destination_ip_groups = [] -> null
          - destination_ports     = [
              - "3000",
              - "445",
            ] -> null
          - name                  = "Allow_From_SomeSource_TCP_02" -> null
          - protocols             = [
              - "TCP",
            ] -> null
          - source_addresses      = [
              - "10.0.0.6",
            ] -> null
          - source_ip_groups      = [] -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
- Updated provider plan:
```
# azurerm_firewall_network_rule_collection.example-rule will be updated in-place
  ~ resource "azurerm_firewall_network_rule_collection" "example-rule" {
        id                  = "/subscriptions/dcd67739-c323-4e1a-b451-09840ffba76f/resourceGroups/rg-mssqlvm/providers/Microsoft.Network/azureFirewalls/afw-mssql/networkRuleCollections/Example-RuleCollection"
        name                = "Example-RuleCollection"
        # (4 unchanged attributes hidden)

      - rule {
          - destination_addresses = [
              - "10.0.0.128",
            ] -> null
          - destination_fqdns     = [] -> null
          - destination_ip_groups = [] -> null
          - destination_ports     = [
              - "22",
              - "443",
              - "80",
              - "8888",
            ] -> null
          - name                  = "Allow_From_SomeSource_TCP_01" -> null
          - protocols             = [
              - "TCP",
            ] -> null
          - source_addresses      = [
              - "10.0.0.5",
            ] -> null
          - source_ip_groups      = [] -> null
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

```

**Comment by AlexPykavy** [comment]
I've already contacted terraform owners and they suggested to use the `Map` data type which works better in such scenarios.

I agree that we need to choose but for me (and I believe that I'm not alone) using `Set` is better because shows only rules which were really changed. It does it in its own manner by showing either add, or delete, or delete/add. For me, as an end user, this indicates that specific rule(s) have changed. Yes, it's inconvenient to compare all attributes of changed object to understand what exactly is changed.

Using `List` fails when order of rules is anyhow changed and it makes plan extremely hard to interpret and it's very strange why only I faced such behavior because adding/removing a firewall rule should happen at least sometimes.

**Comment by AlexPykavy** [comment]
And to be more precise the original issue - [Terraform plan shows **all** rules in a rulecollection will be dropped and recreated, when just 1 rule is modified](https://github.com/hashicorp/terraform-provider-azurerm/issues/11181) which caused changing rule's type from `Set` to `List` was about showing all rules not rule attributes. And that issue had to be fixed by defining all rule attributes as stated in the https://github.com/hashicorp/terraform-provider-azurerm/issues/20164.

**Comment by mbfrahry** [comment]
I do understand that you're not alone that the use case you're experiencing would be better with this fix but it will also make others experience much worse. 

It does sound like we want to swap to a Map over a List or Set but that requires us to move over to the new framework. It's something we plan to do but I don't have any information I can share on exactly when we will. With that said, I'm going to close this PR and keep the issue open as one we can come back to when we've swapped to the new framework.

**Comment by AlexPykavy** [comment]
@mbfrahry, OK, then let's wait for the appropriate fix 🙂 Thank you for the review and sharing your thoughts!

I've closed the original issue because it didn't describe the problem well and was aimed to describe the change implemented in this PR. Instead, I've opened a new https://github.com/hashicorp/terraform-provider-azurerm/issues/20248 one which clearly describes the behavior from the user perspective without any mentioning implementation details.

**Pull request closed without merging**
