### PR TITLE
`azurerm_storage_account`: Support managed HSMs for CMKs

### LINKED ISSUE #14389: azurerm_storage_account_customer_managed_key fails with managed hsm id
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
      source  = "hashicorp/azurerm"
      version = "~> 2.76.0"

### Affected Resource(s)

* `azurerm_storage_account_customer_managed_key `

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account_customer_managed_key" "this" {
  storage_account_id = azurerm_storage_account.this.id
  key_vault_id       = var.azurerm_storage_account_customer_managed_key_key_vault_id
  key_name           = var.azurerm_storage_account_customer_managed_key_key_name
}
```

### Expected Behaviour

By providing a managed HSM ID like "/subscriptions/.../resourceGroups/.../providers/Microsoft.KeyVault/managedHSMs/YOURHSM" it should setup the encryption similar to: 
`az storage account update --name ... --resource-group ... --encryption-key-name ... --encryption-key-source Microsoft.Keyvault --encryption-key-vault $YOURHSMURL --subscription ...`

### Actual Behaviour

```
│ Error: ID was missing the `vaults` element
│ 
│   with module.storagecontainer.azurerm_storage_account_customer_managed_key.this,
│   on .terraform/modules/storagecontainer/main.tf line 65, in resource "azurerm_storage_account_customer_managed_key" "this":
│   65:   key_vault_id       = var.azurerm_storage_account_customer_managed_key_key_vault_id
```
This happens it checks just for classic KeyVaults via: 
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/keyvault/parse/vault.go#L60
while:
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/keyvault/parse/managed_hsm.go#L60
should be respected too.

Was first thinking to open a feature request but since both are KeyVaults I think it is more a bug.

### Steps to Reproduce

1. Use HSM ID as `key_vault_id` in `azurerm_storage_account_customer_managed_key`.
2. test it

### References

* https://github.com/hashicorp/terraform-provider-azurerm/issues/13654 not directly related but it seems the provider is slow with the managed HSM adoption

### LINKED ISSUE #23321: can't read azure resources with manually added managedHSM encryption anymore
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.65

### Affected Resource(s)/Data Source(s)

azurerm_storage_account
azurerm_mssql_server_transparent_data_encryption

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
  lifecycle {
    ignore_changes = [
      customer_managed_key
    ]
  }
}
# just used the doc example including ignore_changes
```

### Debug Output/Panic Output

```shell
╷
│ Error: internal-error: Managed HSM IDs are not supported as Key Vault Nested Items
│ 
│   with azurerm_storage_account.example,
│   on example.tf line 409, in resource "azurerm_storage_account" "example":
│  409: resource "azurerm_storage_account" "example" {
│ 
╵
while running terraform plan
```

### Expected Behaviour

Ignore customer managed key configuration outside of Terraform like in version 3.62.1 and before.

### Actual Behaviour

See error output above in Debug Output/Panic Output. Looks like a regression bug to me, since that behavior was working fine before.

Fails during plan to read Azure Resources. Also for other Azure Resources like azurerm_mssql_server_transparent_data_encryption 

### Steps to Reproduce

1. create storage via terraform
2. add manually managed HSM encrytion (since https://github.com/hashicorp/terraform-provider-azurerm/issues/14389 doesn't work)
3. run terraform plan with azurerm version 3.63+

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14389
https://github.com/hashicorp/terraform-provider-azurerm/issues/22977

### PR DESCRIPTION
**Pull request by Botje**
This PR adds separate arguments to the `customer_managed_key` block to supply HSM-backed CMKs.
For now it just adds a counterpart to the key vault uri / key ID, which does mean that the `storage_account_customer_managed_key` resource accepts a managed hsm uri + key name + version whereas `storage_account` accepts a HSM key ID.
Future work could add the HSM key ID to the `storage_account_customer_managed_key` resource as well.

It does not address the problem raised in [this comment by @tombuildsstuff](https://github.com/hashicorp/terraform-provider-azurerm/issues/22977#issuecomment-1680524708) but tries to use the suffixes as published in the environment. 

resolves #23321, resolves #14389

### CODE REVIEW

**Comment by katbyte** [comment]
I think this may be related to this pr? https://github.com/hashicorp/terraform-provider-azurerm/pull/25069

**Comment by Botje** [comment]
Thanks for that pointer. Yes, the ManagedHSMKeyID struct and associated parse/validate methods would be very helpful here. Do you suggest I wait until that gets merged and adapt to the new types and methods, or can this be merged separately and can I submit a cleanup PR later?

**Comment by Botje** [comment]
I rebased my changes on top of the mentioned PR.

**Comment by riemers** [comment]
Would this not also apply to say keyvault and disk encryption sets as you experience the same issue there too?

**Comment by Botje** [comment]
Absolutely! There is a comment in the source code to the effect that the various implementations of `customer_managed_key` blocks ought to be centralized so the same code only has to be written once. I have an approach in mind but would prefer to do it after HSM support is added.

**Comment by riemers** [comment]
From what i heard, once the #25069 is merged, it should be based of that. As if you now plan/apply on a resource that already has a hsm key it will fail to read the key out properly because of the nestedid's being used.

**Comment by Botje** [comment]
@riemers  I am not sure I follow. This PR is partially based on the mentioned PR, see "wuxu92 and others added 5 commits" in the commit list.

As my PR stands currently, the read path for `storage_account_customer_managed_key` just copies the URI to the `managed_hsm_uri` attribute and the validation for that is (much too lax, on review) "is it a HTTPS URL".

The read path for `storage_account` uses an HSM-specific "nested item ID", which really should be renamed to "HSM key id".

If you have spotted something I missed do please tell me via code comment or a simple test case, so I can fix it.

**Comment by riemers** [comment]
I overlooked the part where you said "redid the work based on the PR" Just wanted to know if that other PR is merged, if that would fix the `Error: internal-error: Managed HSM IDs are not supported as Key Vault Nested Item` if the resource gets read out. Since you can still use the azapi provider until the other items are properly supported.

**Comment by Botje** [comment]
#25069 will not fix the issue you mention by itself, because it does not change the function used to process the IDs in the various `customer_managed_key` blocks that my PR touches.

**Comment by riemers** [comment]
Thanks for the info, suppose we just have to wait a bit more until parts are moved forward.

**Comment by riemers** [comment]
FYI, there is a internal ticket under IPL-6341 with Hashicorp to look at it. All we can do now is wait i suppose ;)

**Comment by katbyte** [comment]
#25601 has been merged which has the updated id parsers and validators and unblocks this pr

**Review by mbfrahry — APPROVED** [review]
LGTM

**Review by katbyte — APPROVED** [review]
LGTM 🏗️

**Pull request merged**
