### PR TITLE
rename `azurerm_graph_account` to `azurerm_graph_services_account`

### PR DESCRIPTION
**Pull request by teowa**
There is request from service team that the resource should be called `graph_services_account`.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
this is a breaking change as is?, we cannot just rename the resource and break users who may be using it. you will need to alias the resources and deprecate the old ones to be removed in 4.0

**Comment by teowa** [comment]
> this is a breaking change as is?, we cannot just rename the resource and break users who may be using it. you will need to alias the resources and deprecate the old ones to be removed in 4.0

The old one is still usable before 4.0, I have also add a test for this.

**Comment by teowa** [comment]
```
--- PASS: TestAccGraphAccount (711.63s)
    --- PASS: TestAccGraphAccount/legacyAccount (143.91s)
        --- PASS: TestAccGraphAccount/legacyAccount/basic (143.91s)
    --- PASS: TestAccGraphAccount/account (567.73s)
        --- PASS: TestAccGraphAccount/account/basic (83.13s)
        --- PASS: TestAccGraphAccount/account/update (205.09s)
        --- PASS: TestAccGraphAccount/account/complete (140.44s)
        --- PASS: TestAccGraphAccount/account/requiresImport (139.06s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/graphservices 711.668s
```

**Comment by teowa** [comment]
Hi team, can we merge this earlier for few customer has started using the resource.

**Review by stephybun — APPROVED** [review]
Thanks @teowa LGTM 🎉

**Pull request merged**
