### PR TITLE
`azurerm_linux_web_app` - fix runtime setting for java runtime

### PR DESCRIPTION
**Pull request by xiaxyi**
The java runtime setting is quite flexible but the api doesn't have any restrictions to the user's input, which means, user can put whatever they want to the java runtime related properties. 

We need to set a clear restrictions to these java related properties since service have a very strict reference to the property `linuxFxVersion` when setting up the app from the backend.

for exmaple:
"linuxFxVersion": "JBOSSEAP|7-java8" works while `JBOSSEAP|7.0-java8` does not.

image

fix:https://github.com/hashicorp/terraform-provider-azurerm/issues/16200

fix:https://github.com/hashicorp/terraform-provider-azurerm/issues/17144

### CODE REVIEW

**Comment by xiaxyi** [comment]
Thanks @katbyte , updated test cases and slot settings
```
--- PASS: TestAccLinuxWebAppSlot_withJava11Tomcat85 (487.75s)
--- PASS: TestAccLinuxWebAppSlot_withJava11Tomcat8561 (599.95s)
--- PASS: TestAccLinuxWebAppSlot_withJava1109 (601.77s)
--- PASS: TestAccLinuxWebAppSlot_withJava8u242 (603.45s)
--- PASS: TestAccLinuxWebAppSlot_withJava11Tomcat9 (667.39s)
--- PASS: TestAccLinuxWebAppSlot_withJava8JBOSSEAP73 (550.27s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    550.963s


```

**Comment by peterprumbach-telekom** [comment]
Is this also gonna be implemented for other resources (e.g. azurerm_windows_web_app)?

**Comment by diogonborges** [comment]
@xiaxyi have you seen this request for changes?

**Review by diogonborges — APPROVED** [review]
LGTM

**Comment by jackofallops** [comment]
Closing as superseded by 19685

**Pull request closed without merging**
