### PR TITLE
azurerm_application_gateway - key_vault_secret_id, force_firewall_policy_association

### PR DESCRIPTION
**Pull request by neil-yechenwei**
This PR is to support new properties `forceFirewallPolicyAssociation` and `trustedRootCertificate.KeyVaultSecretID`.

--- PASS: TestAccApplicationGateway_backendHttpSettingsHostNameAndPick (298.43s)
--- PASS: TestAccApplicationGateway_UserAssignedIdentity (1007.32s)
--- PASS: TestAccApplicationGateway_requestRoutingRulePriority (1216.60s)
--- PASS: TestAccApplicationGateway_sslProfile (1219.18s)
--- PASS: TestAccApplicationGateway_backendAddressPoolEmptyIpList (1230.65s)
--- PASS: TestAccApplicationGateway_basic (1235.21s)
--- PASS: TestAccApplicationGateway_IncludePathWithTargetURL (1296.71s)
--- PASS: TestAccApplicationGateway_privateLink (1348.71s)
--- PASS: TestAccApplicationGateway_sslProfileWithClientCertificateVerification (1369.35s)
--- PASS: TestAccApplicationGateway_updateForceFirewallPolicyAssociation (1405.59s)
--- PASS: TestAccApplicationGateway_sslPolicy_policyType_predefined (859.55s)
--- PASS: TestAccApplicationGateway_V2SKUCapacity (2114.79s)
--- PASS: TestAccApplicationGateway_sslPolicy_policyType_custom (898.52s)
--- PASS: TestAccApplicationGateway_sslPolicy_disabledProtocols (904.22s)
--- PASS: TestAccApplicationGateway_webApplicationFirewall_exclusions (1005.10s)
--- PASS: TestAccApplicationGateway_webApplicationFirewall_disabledRuleGroups (1020.75s)
--- PASS: TestAccApplicationGateway_webApplicationFirewall (996.42s)
--- PASS: TestAccApplicationGateway_gatewayIP (2072.17s)
--- PASS: TestAccApplicationGateway_cookieAffinity (1993.97s)
--- PASS: TestAccApplicationGateway_sslCertificate_keyvault_versionless (1141.81s)
--- PASS: TestAccApplicationGateway_sslCertificate_keyvault_versioned (1151.26s)
--- PASS: TestAccApplicationGateway_withHttpListenerHostNames (920.37s)
--- PASS: TestAccApplicationGateway_sslCertificate_EmptyPassword (1241.26s)
--- PASS: TestAccApplicationGateway_settingsPickHostNameFromBackendAddress (1120.66s)
--- PASS: TestAccApplicationGateway_connectionDraining (2083.19s)
--- PASS: TestAccApplicationGateway_sslCertificate (2084.27s)
--- PASS: TestAccApplicationGateway_backendHttpSettingsHostName (1123.98s)
--- PASS: TestAccApplicationGateway_routingRedirect_httpListener (1183.82s)
--- PASS: TestAccApplicationGateway_routingRedirect_httpListenerError (201.43s)
--- PASS: TestAccApplicationGateway_probesWithPort (932.12s)
--- PASS: TestAccApplicationGateway_manualSslCertificateChangeIgnoreChanges (2016.62s)
--- PASS: TestAccApplicationGateway_rewriteRuleSets_rewriteUrl (949.74s)
--- PASS: TestAccApplicationGateway_rewriteRuleSets_backend (923.04s)
--- PASS: TestAccApplicationGateway_probesEmptyMatch (1129.77s)
--- PASS: TestAccApplicationGateway_rewriteRuleSets_redirect (1040.55s)
--- PASS: TestAccApplicationGateway_probes (1121.97s)
--- PASS: TestAccApplicationGateway_probesPickHostNameFromBackendHTTPSettings (1203.03s)
--- PASS: TestAccApplicationGateway_routingRedirect_pathBased (1067.54s)
--- PASS: TestAccApplicationGateway_customErrorConfigurations (1293.05s)
--- PASS: TestAccApplicationGateway_pathBasedRouting (1212.72s)
--- PASS: TestAccApplicationGateway_trustedRootCertificate (1060.20s)
--- PASS: TestAccApplicationGateway_customPathRuleFirewallPolicy (990.27s)
--- PASS: TestAccApplicationGateway_customFirewallPolicy (987.81s)
--- PASS: TestAccApplicationGateway_customHttpListenerFirewallPolicy (1002.82s)
--- PASS: TestAccApplicationGateway_trustedRootCertificate_keyvault (1215.04s)
--- PASS: TestAccApplicationGateway_authCertificate (1882.19s)
--- PASS: TestAccApplicationGateway_requiresImport (1166.23s)
--- PASS: TestAccApplicationGateway_autoscaleConfigurationNoMaxCapacity (896.49s)
--- PASS: TestAccApplicationGateway_overridePath (1302.70s)
--- PASS: TestAccApplicationGateway_http2 (1197.24s)
--- PASS: TestAccApplicationGateway_zones (909.47s)
--- PASS: TestAccApplicationGateway_autoscaleConfiguration (1127.05s)

### CODE REVIEW

**Comment by katbyte** [comment]
@neil-yechenwei - is this still a WIP?

**Comment by neil-yechenwei** [comment]
@katbyte , yes. it still depends on the rely from service team for the `enableFips` property and the `primary` property.

**Comment by neil-yechenwei** [comment]
@katbyte , as seems we need more time to ask service team to grant us the permission for accessing the `enableFips` property, so I intend to implement other new properties first. Once the permission access is ready, I will submit another PR to implement the `enableFips` property. Hence, I updated code. Please go ahead to review this PR. Thanks in advance.

Below is the test result after rerun:
image

**Review by katbyte — APPROVED** [review]
Thanks @neil-yechenwei - LGTM 🏗️

**Pull request merged**
