### PR TITLE
Add support of Application Packages to `azurerm_batch_pool`

### PR DESCRIPTION
**Pull request by oWretch**

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Hey @oWretch - thanks for the pr and whilst it overall looks good it appears all the tests are broken so i can't verify these changes, mind fixing them up?

```
------- Stdout: -------
=== RUN   TestAccBatchPool_completeUpdated
=== PAUSE TestAccBatchPool_completeUpdated
=== CONT  TestAccBatchPool_completeUpdated
    testcase.go:109: Step 1/4 error: Error running apply: exit status 1
        
        Error: creating Batch pool "testaccpool4ak9t" (Resource Group "testaccRG-batch-211110121542177203"): batch.PoolClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPropertyValue" Message="The value provided for one of the properties in the request body is invalid.\nRequestId:d6814a2f-3fa1-48a6-b58e-6a34508dc242\nTime:2021-11-10T12:17:21.3956231Z" Target="BatchAccount" Details=[{"code":"PropertyName","message":"nodeAgentSkuId"},{"code":"PropertyValue","message":"batch.node.ubuntu 16.04"},{"code":"Reason","message":"The specified nodeAgentSKUId does not exist."},{"code":"PropertyPath","message":"properties.deploymentConfiguration.virtualMachineConfiguration.nodeAgentSkuId"}]
        
          with azurerm_batch_pool.test,
          on terraform_plugin_test.tf line 31, in resource "azurerm_batch_pool" "test":
          31: resource "azurerm_batch_pool" "test" {
        
--- FAIL: TestAccBatchPool_completeUpdated (151.80s)
FAIL
```

**Comment by oWretch** [comment]
Thanks for the review @katbyte. I've had a look at the tests and can't find the issue - it's not reproduced in the logs from the Actions run. Did you run the tests again locally?

My confusion is because the error from your logs in that the `nodeAgentSkuId` is not valid - however the provided ID (`batch.node.ubuntu 16.04`) is a valid SKU, and is used in all the other Batch Pool tests. Are there more failures in your logs? I'm happy to update to a newer batch pool (e.g. Ubuntu 20.04) which has other advantages (e.g. longevity) if you think it's worthwhile. My concern is muddying the purpose of this PR.

**Comment by katbyte** [comment]
Sadly as of today they are still all failing for us 🙁 
```
------- Stdout: -------
=== RUN   TestAccBatchPool_autoScale_complete
=== PAUSE TestAccBatchPool_autoScale_complete
=== CONT  TestAccBatchPool_autoScale_complete
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Batch pool "testaccpoolao08r" (Resource Group "testaccRG-batch-211117232337740681"): batch.PoolClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPropertyValue" Message="The value provided for one of the properties in the request body is invalid.\nRequestId:2e6bf921-ee4a-4944-8642-75801b31544d\nTime:2021-11-17T23:25:24.7991489Z" Target="BatchAccount" Details=[{"code":"PropertyName","message":"nodeAgentSkuId"},{"code":"PropertyValue","message":"batch.node.ubuntu 16.04"},{"code":"Reason","message":"The specified nodeAgentSKUId does not exist."},{"code":"PropertyPath","message":"properties.deploymentConfiguration.virtualMachineConfiguration.nodeAgentSkuId"}]
        
          with azurerm_batch_pool.test,
          on terraform_plugin_test.tf line 31, in resource "azurerm_batch_pool" "test":
          31: resource "azurerm_batch_pool" "test" {
        
--- FAIL: TestAccBatchPool_autoScale_complete (222.37s)
FAIL
```

be great if you could update so they pass and we can get this merged!

**Comment by oWretch** [comment]
Thanks @katbyte. I've gone back to the contributor doco and realised where those tests are running.

I believe I've resolved the issue you were seeing on tests, but the test for the new code is failing as I need to add support for creating application packages before the test can actually run, since the tests all run from scratch. I will work on this, but I won't get it done in time for the 2.86.0 release.

**Comment by oWretch** [comment]
@katbyte It looks like we can't create new Application Packages via SDK. I've created a [Slack post](https://terraform-azure.slack.com/archives/CJD3VK9Q9/p1637532401080400) with my findings.

If we can't create an application package, I can't create an automated test to verify this functionality. Would we be able to commit it without a test, or do I need to resort to ARM templates or manual provisioning of application packages for the Batch accounts?

**Comment by manicminer** [comment]
Hi @oWretch, ideally we'll need to be able to create an application package so that we can test it with the `batch_pool` resource - without test coverage there's no way for us to detect regressions in this property.

Looking at the SDK / API specs, it looks like you may be right that there is no API support for creating application packages. However, it may still be possible; there is [an az-cli command for it](https://docs.microsoft.com/en-us/cli/azure/batch/application/package?view=azure-cli-latest#az_batch_application_package_create)? The workflow seems to be to upload the zip file to blob sstorage then reference the URI in the application package, which I suspect is what the portal is doing/hiding but I can't try it out myself since my naive attempt to create a dummy application isn't getting very far.

If you can provide a sample application that's accepted by Batch, but doesn't actually do anything meaningful, I could try to dig a little further :)

**Comment by oWretch** [comment]
Batch uses the term application very loosely. All you require is a zip file locally. The way it works is the zip file is downloaded to the batch pool hosts when assigned and unzipped to a folder. So any random zip file will work 🙂

**Comment by katbyte** [comment]
so a empty file with the filename ending in `.zip` should work? 🙃

**Comment by oWretch** [comment]
> so a empty file with the filename ending in `.zip` should work? 🙃

Theoretically, though in the Slack chat @manicminer found that the portal refuses a zip file smaller than 1kb, so we may need to find the exact limit.

**Comment by katbyte** [comment]
@oWretch would it accept a `file.zip` that just contains the thing zip over and over or does it validate the zip?

**Comment by oWretch** [comment]
@katbyte I've just checked and no verification is done on upload of the zip file. I created a 1mb zip file with `dd if=/dev/zero of=output.zip bs=1m count=1` and it uploaded to the portal. I expect however that would fail if we tried to deploy it to a node pool.

I then created a blank 1mb file with the same command and compressed it (zip size = 1kb) and that successfully uploaded to the portal, and will also pass the unzip test if we use it to test deploying the file to the node pool.

**Comment by katbyte** [comment]
I think that'll work @oWretch! could we update the PR and tests with that fake zip so we can test? thanks

**Comment by oWretch** [comment]
Thanks @katbyte - I can create the sample zip file, but the core issue is that the SDK doesn't support the creation of a batch application version and the required file upload. @manicminer above was offering to dig a bit further into the portal commands to see what it happening in the background and whether we can leverage the Azure CLI or another method to be able to upload the file and create the application version.

I'm at the limit of my golang knowledge here, so might not be much help from that side, but happy to do more of the Azure Batch side to assist as I know that better :)

**Comment by katbyte** [comment]
ahh thanks @oWretch - I'll connect with him internally then. thanks for all the work here! hope we can get this in sooner then later

**Pull request closed without merging**
