### PR TITLE
New Data Source: `azurerm_policy_definition_built_in`

### PR DESCRIPTION
**Pull request by wuxu92**
> re-run TC 

May Fixes: https://github.com/hashicorp/terraform-provider-azurerm/issues/19783

image

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @wuxu92, this probably wants to be created as it's own data source i.e. `azurerm_built_in_policy_definition`

**Comment by tombuildsstuff** [comment]
@wuxu92 any update on splitting this out into it's own data source?

**Comment by wuxu92** [comment]
@tombuildsstuff Have updated this PR to a new data source based on the existing policy_definition_data_source schema.

**Review by katbyte — APPROVED** [review]
LGTM 🏗️

**Pull request merged**
