### PR TITLE
New Resource: `azurerm_synapse_sql_pool_extended_auditing_policy` and `azurerm_synapse_workspace_extended_auditing_policy`

### LINKED ISSUE #11095: Add capability to enable Auditing for Azure Synapse SQL Pools
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_synapse_sql_pool

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by owenfarrell**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Summary

This pull request adds support for managing extend auditing policies for Synapse workspaces and Synapse workspace SQL pools. The implementation and the acceptance tests are largely derived from analagous implementations for SQL servers and SQL databases.

Closes #11095

Output from acceptance testing:

```
$ make acctests SERVICE='synapse' TESTARGS='-run="^TestAccSynapse(SqlPool|Workspace)ExtendedAuditingPolicy_"' TESTTIMEOUT='120m' 
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/synapse -run="^TestAccSynapse(SqlPool|Workspace)ExtendedAuditingPolicy_" -timeout 120m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_basic
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_basic
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_requiresImport
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_requiresImport
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_complete
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_complete
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_update
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_update
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_storageAccBehindFireWall
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_storageAccBehindFireWall
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_logAnalytics
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_logAnalytics
=== RUN   TestAccSynapseSqlPoolExtendedAuditingPolicy_eventhub
=== PAUSE TestAccSynapseSqlPoolExtendedAuditingPolicy_eventhub
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_basic
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_basic
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_requiresImport
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_requiresImport
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_complete
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_complete
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_update
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_update
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_storageAccBehindFireWall
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_storageAccBehindFireWall
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_logAnalytics
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_logAnalytics
=== RUN   TestAccSynapseWorkspaceExtendedAuditingPolicy_eventhub
=== PAUSE TestAccSynapseWorkspaceExtendedAuditingPolicy_eventhub
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_basic
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_basic
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_storageAccBehindFireWall
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_storageAccBehindFireWall
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_eventhub
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_logAnalytics
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_complete
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_update
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_complete (893.18s)
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_complete
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_basic (894.07s)
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_update
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_storageAccBehindFireWall (1018.45s)
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_requiresImport
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_storageAccBehindFireWall (1062.21s)
=== CONT  TestAccSynapseWorkspaceExtendedAuditingPolicy_requiresImport
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_basic (1070.20s)
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_eventhub
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_update (1178.69s)
=== CONT  TestAccSynapseSqlPoolExtendedAuditingPolicy_logAnalytics
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_eventhub (1240.18s)
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_logAnalytics (1242.89s)
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_complete (1026.65s)
--- PASS: TestAccSynapseWorkspaceExtendedAuditingPolicy_requiresImport (933.12s)
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_requiresImport (1001.42s)
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_update (1248.83s)
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_eventhub (1328.40s)
--- PASS: TestAccSynapseSqlPoolExtendedAuditingPolicy_logAnalytics (1266.63s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/synapse       2450.391s
```

### CODE REVIEW

**Comment by DesaCh01** [comment]
Hello @owenfarrell, 

Can you also add integration for scenario wherein the destination for audit logs is log analytics workspace.

**Comment by owenfarrell** [comment]
> Can you also add integration for scenario wherein the destination for audit logs is log analytics workspace.

@DesaCh01 - I'm not sure I follow. 
I _**think**_ that test scenario is covered in the acceptance test suite as part of the `_logAnalytics` tests. Those tests:
1. Enable extended audit logging
2. Connect the audit logging (SQLSecurityAuditEvents diagnostic setting) to a log analytics workspace.

Are you asking for a change to the resource implementation itself?

**Comment by DesaCh01** [comment]
Hi @owenfarrell , 

In order to link the audit logs to a log analytics workspace, would I have to do something like this...

First, 

In "azurerm_synapse_workspace_extended_auditing_policy" resource just have Workspace_id and no values for storage account as they are optional values.

Second, 
Use "azurerm_monitor_diagnostic_setting" to record "SQLSecurityAuditEvents" logs for log analytics workspace.

Is this correct?

**Comment by owenfarrell** [comment]
@DesaCh01 - Yes. But I want to make sure we're not talking past each other, so there's one important distinction to make here:

> In "azurerm_synapse_workspace_extended_auditing_policy" resource just have Workspace_id and no values for storage account as they are optional values.

In this particular context, the workspace ID is the _**Synapse**_ workspace ID, not the log analytics resource/workspace ID.  And so what you're description is specifically captured in [this](https://github.com/hashicorp/terraform-provider-azurerm/pull/12952/files#diff-f7e905a6ff5a991061a797602372168c112abc9c675b40939221e30563af5de6R376-R407) test case for Synapse workspaces, which cascade the configuration to all underlying SQL pools. There is also an analogous test for configuring an individual SQL pool if/when the workspace is _**not**_ configured to generate audit logs.

I applied a minimal configuration based on that test case:

```hcl
provider "azurerm" {
  features {}
}

resource "random_integer" "id" {
  min = 1
  max = 50000
}

resource "azurerm_resource_group" "test" {
  name     = "acctestsw${random_integer.id.result}"
  location = "eastus"
}

resource "azurerm_storage_account" "sw" {
  name                     = "acctestsw${random_integer.id.result}"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_kind             = "BlobStorage"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_data_lake_gen2_filesystem" "test" {
  name               = "acctest-${random_integer.id.result}"
  storage_account_id = azurerm_storage_account.sw.id
}

resource "azurerm_synapse_workspace" "test" {
  name                                 = "acctestsw${random_integer.id.result}"
  resource_group_name                  = azurerm_resource_group.test.name
  location                             = azurerm_resource_group.test.location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.test.id
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = "H@Sh1CoR3!"
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "acctest-LAW-${random_integer.id.result}"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_monitor_diagnostic_setting" "test" {
  name                       = "acctest-DS-${random_integer.id.result}"
  target_resource_id         = azurerm_synapse_workspace.test.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.test.id

  log {
    category = "SQLSecurityAuditEvents"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }

  // log, metric will return all disabled categories
  lifecycle {
    ignore_changes = [log, metric]
  }
}

resource "azurerm_synapse_workspace_extended_auditing_policy" "test" {
  synapse_workspace_id   = azurerm_synapse_workspace.test.id
  log_monitoring_enabled = true
}
```

...and got the following result:

Screen Shot 2021-08-16 at 8 44 23 AM

**Comment by DesaCh01** [comment]
Thanks @owenfarrell :) for this information. Eagerly waiting for "azurerm_synapse_workspace_extended_auditing_policy" resource in new azurerm version.

**Comment by sehgalnamit** [comment]
May I know when this will be released?

**Comment by owenfarrell** [comment]
@sehgalnamit - Unfortunately there have been a handful of Synapse-related changes made in parallel, so I've had to merge these changes to resolve the conflicts with those changes (some of which were mine! 😬).

In an effort to keep the commit log clean, I just rebased over `main` and reran acceptance tests - everything still checks out. And I've incorporated some feedback that I've received in other PRs (e.g., error message formats). So hopefully this is a quick spin to merge in once it is reviewed. 🤞

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for this @owenfarrell, it looks really good!

**Comment by owenfarrell** [comment]
Thanks @mbfrahry!

**Pull request merged**
