### PR TITLE
`azurerm_application_gateway` - migrate to `go-azure-sdk` and upgrade api-version to `2023-04-01`

### PR DESCRIPTION
**Pull request by teowa**
Change from API version 2022-07-01 to 2023-04-01:

The default SSL policy is changed due to API version upgration as stated in [Azure doc](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#default-tls-policy).
Existing configs (those without `ssl_policy` configured at the root level and with `ssl_policy` configured inside the `ssl_profile` block) may fail to **create new resources** with below error message from API, about `ssl_policy` conflict:
```
        Error: creating Application Gateway (Subscription: "xxx"
        Resource Group Name: "acctestRG-230927084225937967"
        Application Gateway Name: "acctestag-230927084225937967"): performing CreateOrUpdate: unexpected status 400 with error: ApplicationGatewaySslPolicyMisMatch: The newer and older SSL policies can't be used together for SSLPolicy and listener-specific SSLProfile. Yo
ur configuration's sslProfile acctest-vnet-230927084225937967-sslprof conflicts with the global sslPolicy AppGwSslPolicy20220101 set for this Application Gateway. Know more about the SSL policies. https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#usage-and-version-details


```
To avoid this error, specify the `ssl_policy` at the root level.

This limit is only for new resource created in new API version. Existing resource managed by new API has no limit for this.

### CODE REVIEW

**Comment by teowa** [comment]
@ms-zhenhua Please help take a look at this. Thanks.

**Comment by teowa** [comment]
> @teowa in this case it appears this block needs to become Required then?


It depends on config.
From the [doc](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#default-tls-policy), the `2023-02-01` or later version of the application gateway has defaultPredefinedSslPolicy:[AppGwSslPolicy20220101](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#predefined-tls-policy), so when in config if the `ssl_profile.ssl_policy.policy_name` is not configured as `AppGwSslPolicy20220101`, `ssl_policy` block is required to be specified to avoid conflict.

**Comment by tombuildsstuff** [comment]
@teowa apologies for the delayed re-review of this one.

Taking a look through here I'd agree that we should separate the fix for this issue and the SDK split - however I suspect we should change the ordering.

Firstly, to ensure compatibility/that there isn't a breaking change - we should be defaulting `ssl_profile.ssl_policy.policy_name` to `AppGwSslPolicy20150501` for the moment - and then (in 4.0) we can update this default value to be `AppGwSslPolicy20220101`. This allows users to upgrade without existing configurations breaking - whilst allowing us to document that this breaking change is coming in 4.0 / that the `ssl_policy` is required for the new(er) version.

Once that's done we should be able to update the SDK to use `hashicorp/go-azure-sdk` / adopt the latest API Version here - which then shouldn't involve any breaking changes.

Whilst I can understand the desire to move to `hashicorp/go-azure-sdk` first - since this issue already exists in the current API version, and that we're already importing 4 different versions of the `network` API into Pandora - I'd rather we didn't import a 5th version of the Network API (since these are huge) but instead fixed this first before migrating to the new SDK.

WDYT?

---

For the moment I'm going to close https://github.com/hashicorp/pandora/pull/3262, since I believe it's not needed - but we can reopen that if needed.

**Comment by teowa** [comment]
@tombuildsstuff , thanks for the review, I believe the mentioned method is a better choice. I am going to close this for now and submit another.

**Pull request closed without merging**
