### PR TITLE
fix typo in `azurerm_log_analytics_workspace` argument: reservation_capcity_in_gb_per_day to reservation_capacity_in_gb_per_day

### PR DESCRIPTION
**Pull request by aliscott**
Updates argument name `reservation_capcity_in_gb_per_day` to `reservation_capacity_in_gb_per_day`.

### CODE REVIEW

**Comment by favoretti** [comment]
Hi @aliscott, thank you for this PR. Whilst this is unfortunate, there might be cases where people are using this parameter. A such we need to add another one with correct spelling, introduce a deprecation message for the old one and then delete it it later releases (3.0?).

In other cases where typos in arguments were corrected, we basically exclude the possibility to set both and pick the value of the one that's currently set.

**Review by favoretti — CHANGES_REQUESTED** [review]
Left a comment in main thread. Arguments needs to be properly deprecated, rather than just renamed. Thanks!

**Comment by aliscott** [comment]
Thanks @favoretti! That makes a lot of sense. I've updated this based on an example I found here: https://github.com/hashicorp/terraform-provider-azurerm/pull/13881. Let me know if I'm missing anything else.

**Review by favoretti — APPROVED** [review]
LGTM! Pending maintainers review.

**Review by katbyte — APPROVED** [review]
Thanks for spotting and fixing this @aliscott !  LGTM 🏗️

**Pull request merged**
