### PR TITLE
`azurerm_security_center_subscription_pricing` - reset to `Free` tier during deletion & add existing check

### PR DESCRIPTION
**Pull request by ziyeqf**
It will be reset to `Free` tier since the resource could not be completely deleted. We may need to point it out in change log.

Test
---
```
❯ TF_ACC=1 go test -v ./internal/services/securitycenter -run=TestAccSecurityCenterSubscriptionPricing -timeout=600m
=== RUN   TestAccSecurityCenterSubscriptionPricing_update
--- PASS: TestAccSecurityCenterSubscriptionPricing_update (296.52s)
=== RUN   TestAccSecurityCenterSubscriptionPricing_cosmosDbs
--- PASS: TestAccSecurityCenterSubscriptionPricing_cosmosDbs (167.64s)
=== RUN   TestAccSecurityCenterSubscriptionPricing_storageAccountSubplan
--- PASS: TestAccSecurityCenterSubscriptionPricing_storageAccountSubplan (161.90s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/securitycenter        626.115s
```

### CODE REVIEW

**Comment by ziyeqf** [comment]
Hi @tombuildsstuff, I have updated this PR to use a feature block to control whether to reset to free tier, it might be more acceptable. Could you please take another look?

**Review by katbyte — CHANGES_REQUESTED** [review]
this seems like a bugfix, as it should have always reset to free? as such we can just make the change & call out the breaking change in the changelog without the features block toggle?

this seems like a safe/reasonable exception to making a breaking change? WDYT?

**Comment by ziyeqf** [comment]
> this seems like a bugfix, as it should have always reset to free? as such we can just make the change & call out the breaking change in the changelog without the features block toggle?
> 
> this seems like a safe/reasonable exception to making a breaking change? WDYT?

Thanks, I agreed with that.

**Review by katbyte — CHANGES_REQUESTED** [review]
test failures:
image

**Comment by ziyeqf** [comment]
Hey @katbyte, the existing check has also been added together and the tests failed because of that. To pass the tests it need manually set these printing tier to `Free` on testing Subscription. Do you think we should add them together?

**Review by katbyte — CHANGES_REQUESTED** [review]
The test should be resetting it to free?
```
// reset pricing tier to free after all tests.
	data := acceptance.BuildTestData(t, "azurerm_security_center_subscription_pricing", "test")
	data.ResourceTestSkipCheckDestroyed(t, []acceptance.TestStep{
		{
			Config: SecurityCenterSubscriptionPricingResource{}.tier("Free", "VirtualMachines"),
		},
	})
```
sounds like that may be broken and needing fixing?

**Comment by ziyeqf** [comment]
I'm still working on this, please pending review.

**Review by katbyte — APPROVED** [review]
Looks good now! thanks

LGTM 🌩️

**Comment by ziyeqf** [comment]
kindly ping for this PR has not been merged.

**Pull request merged**
