### PR TITLE
New Resource: `azurerm_mobile_network`; New DataSource: `azurerm_mobile_network`;

### PR DESCRIPTION
**Pull request by ziyeqf**
`Mobile Network` is a new RP, there will be a series of PRs, this is the first(root) one, an overall list is below. Detail of this RP could be found [here](https://learn.microsoft.com/en-us/azure/private-5g-core/)

Over view
---
```
order | name 
0     | azurerm_mobile_network                              <- this one
1     | azurerm_mobile_network_site                         
1     | azurerm_mobile_network_data_network                 
1     | azurerm_mobile_network_service                      
1     | azurerm_mobile_network_slice                        
1     | azurerm_mobile_network_sim_group                    
2     | azurerm_mobile_network_packet_core_control_plane    
2     | azurerm_mobile_network_attached_data_network        
2     | azurerm_mobile_network_sim_policy                   
3     | azurerm_mobile_network_packet_core_data_plane       
4     | azurerm_mobile_network_attached_data_network        
5     | azurerm_mobile_network_sim                           
```

Test
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/mobilenetwork -run=TestAccMobileNetwork -timeout=600m         [ tengzh/mn_0][$!+][🐹 v1.19.4][⏱ 0ms][10:33:44]
=== RUN   TestAccMobileNetworkDataSource_complete
=== PAUSE TestAccMobileNetworkDataSource_complete
=== RUN   TestAccMobileNetwork_basic
=== PAUSE TestAccMobileNetwork_basic
=== RUN   TestAccMobileNetwork_requiresImport
=== PAUSE TestAccMobileNetwork_requiresImport
=== RUN   TestAccMobileNetwork_complete
=== PAUSE TestAccMobileNetwork_complete
=== RUN   TestAccMobileNetwork_update
=== PAUSE TestAccMobileNetwork_update
=== CONT  TestAccMobileNetworkDataSource_complete
=== CONT  TestAccMobileNetwork_complete
=== CONT  TestAccMobileNetwork_update
=== CONT  TestAccMobileNetwork_requiresImport
=== CONT  TestAccMobileNetwork_basic
--- PASS: TestAccMobileNetwork_complete (261.03s)
--- PASS: TestAccMobileNetworkDataSource_complete (262.76s)
--- PASS: TestAccMobileNetwork_basic (264.69s)
--- PASS: TestAccMobileNetwork_requiresImport (275.43s)
--- PASS: TestAccMobileNetwork_update (350.87s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/mobilenetwork 352.075s
```

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
all tests are failing with:
```
Test Failed

------- Stdout: -------
=== RUN   TestAccMobileNetwork_basic
=== PAUSE TestAccMobileNetwork_basic
=== CONT  TestAccMobileNetwork_basic
=== CONT  TestAccMobileNetwork_basic
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Mobile Network (Subscription: "*******"
        Resource Group Name: "acctest-mn-230130195458543366"
        Mobile Network Name: "acctest-mn-230130195458543366"): performing CreateOrUpdate: mobilenetwork.MobileNetworkClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidResourceType" Message="The resource type could not be found in the namespace 'Microsoft.MobileNetwork' for api version '2022-11-01'."
        
          with azurerm_mobile_network.test,
          on terraform_plugin_test.tf line 24, in resource "azurerm_mobile_network" "test":
          24: resource "azurerm_mobile_network" "test" {
        
        creating Mobile Network (Subscription: "*******"
        Resource Group Name: "acctest-mn-230130195458543366"
        Mobile Network Name: "acctest-mn-230130195458543366"): performing
        CreateOrUpdate: mobilenetwork.MobileNetworkClient#CreateOrUpdate: Failure
        sending request: StatusCode=0 -- Original Error: Code="InvalidResourceType"
        Message="The resource type could not be found in the namespace
        'Microsoft.MobileNetwork' for api version '2022-11-01'."
--- FAIL: TestAccMobileNetwork_basic (77.78s)
```

**Comment by ziyeqf** [comment]
> all tests are failing with:
> 
> ```
> Test Failed
> 
> ------- Stdout: -------
> === RUN   TestAccMobileNetwork_basic
> === PAUSE TestAccMobileNetwork_basic
> === CONT  TestAccMobileNetwork_basic
> === CONT  TestAccMobileNetwork_basic
>     testcase.go:110: Step 1/2 error: Error running apply: exit status 1
>         
>         Error: creating Mobile Network (Subscription: "*******"
>         Resource Group Name: "acctest-mn-230130195458543366"
>         Mobile Network Name: "acctest-mn-230130195458543366"): performing CreateOrUpdate: mobilenetwork.MobileNetworkClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidResourceType" Message="The resource type could not be found in the namespace 'Microsoft.MobileNetwork' for api version '2022-11-01'."
>         
>           with azurerm_mobile_network.test,
>           on terraform_plugin_test.tf line 24, in resource "azurerm_mobile_network" "test":
>           24: resource "azurerm_mobile_network" "test" {
>         
>         creating Mobile Network (Subscription: "*******"
>         Resource Group Name: "acctest-mn-230130195458543366"
>         Mobile Network Name: "acctest-mn-230130195458543366"): performing
>         CreateOrUpdate: mobilenetwork.MobileNetworkClient#CreateOrUpdate: Failure
>         sending request: StatusCode=0 -- Original Error: Code="InvalidResourceType"
>         Message="The resource type could not be found in the namespace
>         'Microsoft.MobileNetwork' for api version '2022-11-01'."
> --- FAIL: TestAccMobileNetwork_basic (77.78s)
> ```


oh, it needs to onboard subsciprtion to use these resources (for now). have added for test subscriptions. Could you please run it again?

**Review by katbyte — CHANGES_REQUESTED** [review]
one last test failure:

```
est Failed

------- Stdout: -------
=== RUN   TestAccMobileNetwork_complete
=== PAUSE TestAccMobileNetwork_complete
=== CONT  TestAccMobileNetwork_complete
=== CONT  TestAccMobileNetwork_complete
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Mobile Network (Subscription: "*******"
        Resource Group Name: "acctest-mn-230131221611964754"
        Mobile Network Name: "acctest-mn-230131221611964754"): performing CreateOrUpdate: mobilenetwork.MobileNetworkClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LocationNotAvailableForResourceType" Message="The provided location 'eastus2' is not available for resource type 'Microsoft.MobileNetwork/mobileNetworks'. List of available regions for the resource type is 'westeurope,eastus'."
        
          with azurerm_mobile_network.test,
          on terraform_plugin_test.tf line 24, in resource "azurerm_mobile_network" "test":
          24: resource "azurerm_mobile_network" "test" {
        
        creating Mobile Network (Subscription: "*******"
        Resource Group Name: "acctest-mn-230131221611964754"
        Mobile Network Name: "acctest-mn-230131221611964754"): performing
        CreateOrUpdate: mobilenetwork.MobileNetworkClient#CreateOrUpdate: Failure
        sending request: StatusCode=0 -- Original Error:
        Code="LocationNotAvailableForResourceType" Message="The provided location
        'eastus2' is not available for resource type
        'Microsoft.MobileNetwork/mobileNetworks'. List of available regions for the
        resource type is 'westeurope,eastus'."
--- FAIL: TestAccMobileNetwork_complete (134.16s)

```

**Comment by ziyeqf** [comment]
@katbyte just updated to limit the test location. it's only avaiable on "eastus" for now and "northeurope" soon.

**Comment by ziyeqf** [comment]
Hey @katbyte ,Could you please take a look again? Once this one merged I will be able to run tests on TC for following PRs. Thanks!

**Review by katbyte — APPROVED** [review]
Thanks @ziyeqf - LGTM now ☎️

**Pull request merged**
