### PR TITLE
azurerm_key_vault_certificate - support versionless_id, versionless_secret_id

### LINKED ISSUE #13193: unable to Integrate Keyvault certificate to azurerm_api_management_custom_domain proxy settings
I was trying to import keyvault certificate to API Gateway to enable the Custom domain and autonegotiate the certificate., 

Steps followed: Enabled system identity is true at keyvault. added access policy mapping with apigateway.  which is successful.  

in the azurerm_api_management_custom_domain proxy settings, when we refer key_vault_id for custom domain mapping, mapping was  successful.  However it is mapping to https://myvault.vault.azure.net/secrets/certificate/version instead of mapping to certificate.  in Azure side i see the following error.
**Hostname keyvault certificate version, this prevents certificate from being refreshed when its update in keyvault.  Update hostname certificate to ensure its successful rotation**

**My Configuration**
data "azurerm_client_config" "current" {
}

#Key Vault Data
data "azurerm_key_vault" "Keyvault_nonprod" {
  name                = "Kvcertone"
  resource_group_name = "RGGroup"
}

# Access Policy Mapping to Keyvault
resource "azurerm_key_vault_access_policy" "access_poliy" {
  key_vault_id = data.azurerm_key_vault.Keyvault_nonprod.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id     = "${azurerm_api_management.API-Gateway.identity.0.principal_id}"
   
    key_permissions = [
     "Get","List",
   ]

  secret_permissions = [
    "Get","List",
  ]
}

# Keyvault Secret data reference
data "azurerm_key_vault_secret" "Keyvault_nonprod_secret" {
  name            = "secret"
  key_vault_id    = data.azurerm_key_vault.Keyvault_nonprod.id
}

# Key vault certificate
data "azurerm_key_vault_certificate" "testdotsurpakimcom" {
  name         = "certificate"
  key_vault_id = data.azurerm_key_vault.Keyvault_nonprod.id
}

# Custom Domain Configuration
resource "azurerm_api_management_custom_domain" "custom-domain" {
  api_management_id = azurerm_api_management.API-Gateway.id

  proxy {
    host_name    = var.gateway-custom-domain
    key_vault_id = data.azurerm_key_vault_certificate.certificate.secret_id
    negotiate_client_certificate  = true
  }

When i modified manually custom domain keyvault settings in azure to https://keyvault.vault.azure.net/secrets/certificate/  the warning was disappeared.  

* [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
* [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
* [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
* [Registry](https://registry.terraform.io/) issues
* Spans resources across multiple providers

If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Please run `terraform -v` to show the Terraform core version and provider version(s). If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions).
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_v2.74.0`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Custom domain should apply the latest certificate instead of referring to Thumbprint, when keyvault certificate got expired, there is no chances of auto renew this certificate in API Gateway
https://myvault.vault.azure.net/secrets/certificate/

### Actual Behaviour

https://myvault.vault.azure.net/secrets/certificate/thumbprint

### Steps to Reproduce

1. `terraform apply`

### References
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?

* #0000

### PR DESCRIPTION
**Pull request by oWretch**
Adds the `versionless_id` and `versionless_secret_id` for Key Vault certificates in the same vein as the `versionless_id` property on Secrets and Keys. Useful for API Management and Application Gateway.

 Resolves #13193.

### CODE REVIEW

**Comment by oWretch** [comment]
This will resolve #13193.

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @oWretch - looks like we have a panic in a test to solve before merging:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccKeyVaultCertificate_basicGenerateUnknownIssuer
=== PAUSE TestAccKeyVaultCertificate_basicGenerateUnknownIssuer
=== CONT  TestAccKeyVaultCertificate_basicGenerateUnknownIssuer

------- Stderr: -------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45c811d]

goroutine 661 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/keyvault.resourceKeyVaultCertificateRead(0xc003766200, {0x563e640, 0xc003906a80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/keyvault/key_vault_certificate_resource.go:619 +0x51d
github.com/hashicorp/terraform-provider-azurerm/internal/services/keyvault.resourceKeyVaultCertificateCreate(0x0, {0x563e640, 0xc003906a80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/keyvault/key_vault_certificate_resource.go:526 +0x143b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc002f49710, {0x6739b08, 0xc00257c640}, 0x2, {0x563e640, 0xc003906a80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc003121b20, {0x6739b08, 0xc00257c640}, 0xc001a17790, 0xc003766080, {0x563e640, 0xc003906a80})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc002b171b8, {0x6739b08, 0xc00257c640}, 0xc002b91a40)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc002215ac0, {0x6739bb0, 0xc000fc0480}, 0xc0043a05c0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:332 +0x6c
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5b81b20, 0xc002215ac0}, {0x6739bb0, 0xc000fc0480}, 0xc0027236e0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc001a5e8c0, {0x678a320, 0xc003652d80}, 0xc002205680, 0xc002b7cc30, 0xacfac80, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc001a5e8c0, {0x678a320, 0xc003652d80}, 0xc002205680, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x294
```

**Comment by oWretch** [comment]
Thanks @katbyte. A good reminder to never make assumptions that properties exist :(

**Review by katbyte — APPROVED** [review]
All pass now @oWretch ! thanks, LGTM 🍰

**Pull request merged**
