### PR TITLE
DataSource: `azurerm_blueprint_definition` - Fix `version` property output

### PR DESCRIPTION
**Pull request by xiaxyi**
Add version information to the blueprint definition resource.

closes https://github.com/hashicorp/terraform-provider-azurerm/issues/15177

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
have a test failure:
```
------- Stdout: -------
=== RUN   TestAccBlueprintDefinitionDataSource_basicAtChildManagementGroup
=== PAUSE TestAccBlueprintDefinitionDataSource_basicAtChildManagementGroup
=== CONT  TestAccBlueprintDefinitionDataSource_basicAtChildManagementGroup
    testcase.go:110: Step 1/1 error: Error running pre-apply refresh: exit status 1
        
        Error: reading Management Group "testAcc_staticStubGroup": managementgroups.Client#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="'/providers/Microsoft.Management/managementGroups/testAcc_staticStubGroup' not found"
        
          with data.azurerm_management_group.test,
          on terraform_plugin_test.tf line 6, in data "azurerm_management_group" "test":
           6: data "azurerm_management_group" "test" {
        
--- FAIL: TestAccBlueprintDefinitionDataSource_basicAtChildManagementGroup (9.12s)
FAIL
```

**Comment by xiaxyi** [comment]
@katbyte I notice many acc test failures are relates to this management group not found:
/providers/Microsoft.Management/managementGroups/testAcc_staticStubGroup' not found"

is it because the management group does not exists under the test subscription?

**Comment by katbyte** [comment]
@xiaxyi - the acc test shouldn't rely on existing resources, can we create the management group for the test?

**Comment by tombuildsstuff** [comment]
@xiaxyi can you update the test to create the management group as required for testing here?

**Comment by xiaxyi** [comment]
@tombuildsstuff @katbyte Thanks for the comments. 

I can try creating a new management group, however, I'm not able to create the blueprint as there is no resource https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/blueprint_definition provided in Terraform Registry so I can only rely on the existing one. 

There is one blocker that I may need to confirm with you guys, as I'm adding the version information in the data source, I may need your help to publish the BP version as I'm not able to do that from TF neither.
image

The tests went fine in my own sub:
--- PASS: TestAccBlueprintDefinitionDataSource_blueprintVersions (54.34s)
PASS

Thanks, feel free to let me know if you need more informaiton

**Comment by xiaxyi** [comment]
@katbyte @tombuildsstuff I have to hard code the test case as below since I have no knowledge about the existing blueprint in your sub. The last test failure tells me that you have 2 versions published, please can you help to confirm about it?
```
check.That(data.ResourceName).Key("versions.#").HasValue("2"),
```

Thanks, feel free to let me know if there is anything needed.

**Pull request merged**
