### PR TITLE
Update kermit version to v0.20230703.1101016

### PR DESCRIPTION
**Pull request by KenSpur**
issue: #22338
pr: #22382

### CODE REVIEW

**Comment by KenSpur** [comment]
@tombuildsstuff should be ok now

**Comment by KenSpur** [comment]
@tombuildsstuff running `go mod vendor` seems to remove the "github.com/tombuildsstuff/kermit/sdk/iotcentral/2022-10-31-preview/iotcentral" sdk since there is no dependency yet. Should i leave it out or create a small dependency?

**Comment by tombuildsstuff** [comment]
@KenSpur leaving the dependency out of this PR would be fine - we can vendor that specifically within #22382 since it's tied to that PR (and won't have merge conflicts since it's tracked in that PR) - but if you can fix that up this should otherwise be good to merge, thanks 👍

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks @KenSpur

**Pull request merged**
