### PR TITLE
`azurerm_signalr_service` - add `public_network_access_enabled`, `local_auth_enabled`, `aad_auth_enabled`, `tls_client_cert_enabled`, `serverless_connection_timeout_in_seconds` that were introduced in latest 2023-02-01 api

### PR DESCRIPTION
**Pull request by xiaxyi**
properties added:
```
1. public_network_access_enabled
2. local_auth_enabled
3. aad_auth_enabled
4. tls_client_cert_enabled
5. serverless_connection_timeout_in_seconds
```

### CODE REVIEW

**Comment by xiaxyi** [comment]
The acctests are passing and the failed one does not relate to the changes that are made in this pr.
image

**Review by katbyte — APPROVED** [review]
LGTM 📡 

could you please update the title with the properties added?

**Comment by xiaxyi** [comment]
Thanks @katbyte for the review, added the property in title, will do the same in my future prs.

**Comment by katbyte** [comment]
thanks!

**Pull request merged**
