### PR TITLE
`service/redisenterprise`: Fix acceptance test

### PR DESCRIPTION
**Pull request by favoretti**
Tags on enterprise cluster are a `SchemaDataSource`, so can't be set.

### CODE REVIEW

**Comment by favoretti** [comment]
image

**Review by katbyte — APPROVED** [review]
thanks, LGLTM 👾

**Review by katbyte — COMMENTED** [review]
actually i think this was just updated recently: https://github.com/hashicorp/terraform-provider-azurerm/pull/13084

re-ran the tests and they pass now!

**Comment by favoretti** [comment]
Oh, my bad, missed that completely. Nice though!

**Pull request closed without merging**
