### PR TITLE
azurerm_machine_learning_workspace - Update Validation to allow Hub and Project

### LINKED ISSUE #24454: Support for Azure AI Studio/Project (Microsoft.MachineLearningServices/workspaces)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

There is a new resource called Azure AI Project which was a different kind (kind = project) of family with-in `Microsoft.MachineLearningServices/workspaces` . Hence would like to enhance the `azurerm_machine_learning_workspace` to include this property.

This has been available latest stable API-Version [2023-10-01](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/stable/2023-10-01)

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_machine_learning_workspace" "example" {
  name                    = "example-workspace"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  application_insights_id = azurerm_application_insights.example.id
  key_vault_id            = azurerm_key_vault.example.id
  storage_account_id      = azurerm_storage_account.example.id
  identity {
    type = "SystemAssigned"
  }

  kind = "Project"

}
```
```


### References

_No response_

### PR DESCRIPTION
**Pull request by JonDunnDAFF**
Adding support for new Kinds of Machine Learning Workspace.

- Hub
- Project

As per resource documentation for AI Studio: https://learn.microsoft.com/en-us/azure/ai-studio/concepts/ai-resources

Providing template.json from Azure Portal export of resource as evidence of supported Kinds due to lack of information specified in Azure API documentation for resource.

[template.json](https://github.com/hashicorp/terraform-provider-azurerm/files/15084680/template.json)

## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Azure Machine Learning has been integrated into a new interface referred to as Azure AI Studio. This interface surfaces two new 'Kinds' of ML Workspace as defined in the reference documentation for AI Studio: https://learn.microsoft.com/en-us/azure/ai-studio/concepts/ai-resources

This Pull Request is to update the validation rules for the Machine Learning workspace Kind to allow these new values of Hub and Project.

## PR Checklist

- [X] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [X] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [X] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [X] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [X] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [X] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [X] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [ ] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_machine_learning_workspace` - Update Validation to allow Hub and Project

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [X] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #24454 

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @JonDunnDAFF.

Similar to #25729 I think these would want to be added as separate resources.

Looking at how the resources relate to one another in the portal, an AI Hub Project can be created within an AI Hub. Adding these as values to `kind` means the corresponding configuration in Terraform would have an `azurerm_machine_learning_workspace` referencing a parent or child `azurerm_machine_learning_workspace`, which to me seems odd and has the potential to cause confusion about the relationship and hierarchy of these resources.

Although the AI Hub and Project resources are created using the same API for the AML Workspace and have similar configuration parameters, there is the possibility for these to diverge over time.

With the above in mind I think these need to be added as separate resources instead of extending the values for `kind`. Is that something you would be able to look into?

**Comment by stephybun** [comment]
@JonDunnDAFF we usually follow the brand/commercial name of the service or product, so in this case I think `azurerm_ai_hub` and `azurerm_ai_project` are the way to go. I don't think it's necessary for users to be aware of which underlying API the resources are using and in any case that information is easily looked up in the source code.

In case it's your first time adding new resources to the provider might I suggest looking through our [contributor documentation](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/guide-new-resource.md) and ensuring that the new resources added are using the [Typed SDK](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/best-practices.md#typed-vs-untyped-resources).

**Comment by JonDunnDAFF** [comment]
Thanks @stephybun, I will have a crack at the problem based on your solution and following the documentation as described. I will close this Pull Request and create a new one once I have a working implementation of the new resources.

**Comment by marvinbuss** [comment]
Hi @JonDunnDAFF & @stephybun ,
Any progress on this topic?

**Comment by JonDunnDAFF** [comment]
> Hi @JonDunnDAFF & @stephybun , Any progress on this topic?

Not a huge amount as i try to find time to establish the required infrastructure to test changes locally. Work around using AzAPI module is possilbe at this stage to enable resource creation but thats about it.

**Comment by jamesmcroft** [comment]
I also put in a similar PR for this addition. @JonDunnDAFF, if this is something that you are struggling with capacity to implement, let me know. I can find time to dedicate to this.

**Comment by JonDunnDAFF** [comment]
> I also put in a similar PR for this addition. @JonDunnDAFF, if this is something that you are struggling with capacity to implement, let me know. I can find time to dedicate to this.

That may be best, i have managed to get by with the AzAPI call for now and the time to put in the new networking pattern properly is not something i have at the moment, happy for you to take it on if you have capacity :)

**Comment by stephybun** [comment]
FYI I believe there is already an engineer at MSFT working on this see https://github.com/hashicorp/terraform-provider-azurerm/issues/26323#issuecomment-2167097330

**Comment by jamesmcroft** [comment]
> @jamesmcroft FYI I believe there is already an engineer at MSFT working on this see [#26323 (comment)](https://github.com/hashicorp/terraform-provider-azurerm/issues/26323#issuecomment-2167097330)

I've reached out directly, looking forward to seeing this capability coming to the provider 👍🏻

**Pull request closed without merging**
