### PR TITLE
`azurerm_batch_pool` - fix accessing `azure_blob_file_system` with `user_identity` assigned.

### PR DESCRIPTION
**Pull request by liuwuliuyun**
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20503
Add `TestAccBatchPool_mountConfigurationAzureBlobFileSystemWithUserAssignedIdentity`

### CODE REVIEW

**Comment by liuwuliuyun** [comment]
I will provide test evidence after teamcity test run complete.

**Comment by liuwuliuyun** [comment]
image

**Comment by liuwuliuyun** [comment]
image
Thanks @stephybun for the review, I just rerun the tests and it looks fine. From the error message, I think it could be a temp network problem.

**Review by stephybun — APPROVED** [review]
Thanks @liuwuliuyun LGTM 🍜

**Pull request merged**
