### PR TITLE
[WIP]`azurerm_orchestrated_virtual_machine_scale_set` - Support new VMSS Flex functionality

### PR DESCRIPTION
**Pull request by WodansSon**
Orchestrated Virtual Machine Scale Sets is an update to the existing Virtual Machine Scale Sets that combines the fault domain availability constructs of Availability Sets with the autoscaling and zonal redundancy of Virtual Machine Scale Sets. This PR will expose the new fields that have been made available in the Orchestrated Virtual Machine Scale Sets public preview. 

## Dependencies:
* Upgrade compute API to latest **2021-07-01**

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@WodansSon with an Orchestrated VMSS this should be configured against the VM rather than the VMSS, else this'll conflict, is there some context for these changes?

**Comment by WodansSon** [comment]
> @WodansSon with an Orchestrated VMSS this should be configured against the VM rather than the VMSS, else this'll conflict, is there some context for these changes?

@tombuildsstuff I am not sure I understand your question. The service team has updated the API and has asked me to implement the new attributes against the existing Orchestrated VMSS resource. It does not currently have full parity with the existing VMSS, but this is a step in that direction. Did that answer you question? If I am missing something here, maybe we can take this offline to get a better understanding?

**Comment by tombuildsstuff** [comment]
@WodansSon did you hear back from the Service Team about the design issues we talked about?

**Comment by WodansSon** [comment]
> @WodansSon did you hear back from the Service Team about the design issues we talked about?

Yes, the new Orchestrated VMSS will push the VM images and manage them behind the scenes, however, they still allow for one off VM's (Linux, Windows or both) to be attached in the way it was done previously.

**Comment by tombuildsstuff** [comment]
@WodansSon if this is manageable on both ends (which it'll have to be to use the VM resources to do so) - then we can't ship that in Terraform since each resource will conflict; we'll need to work that out before proceeding here.

**Pull request closed without merging**
