### PR TITLE
dependencies: bump `go-azure-sdk` to `v0.20240320.1144505`

### PR DESCRIPTION
**Pull request by stephybun**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description
Updating to sdk version with complete data factory swagger fixes/workarounds

Blocked by changes made in https://github.com/Azure/azure-rest-api-specs/pull/28122

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Looks like the missing model we need does exist in the Swagger: https://github.com/Azure/azure-rest-api-specs/blob/44a81f85be1e4797fbf5e290fc6b41d48788a6ba/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/entityTypes/Credential.json#L98-L116

However this isn't being parsed correctly on the Pandora side, so this will want fixing there - notably this model has multiple parents and is located within a sub-directory.

**Comment by manicminer** [comment]
Fixes: #25314

**Review by catriona-m — APPROVED** [review]
LGTM once the checks pass 👍

**Comment by tombuildsstuff** [comment]
Tests look reasonable 👍

**Pull request merged**
