### PR TITLE
Fix TC for azurerm_cosmosdb_cassandra_cluster and azurerm_cosmosdb_cassandra_datacenter

### PR DESCRIPTION
**Pull request by neil-yechenwei**
This PR is to fix TCs of azurerm_cosmosdb_cassandra_cluster and azurerm_cosmosdb_cassandra_datacenter.

--- PASS: TestAccCassandraSequential/cluster (1881.87s)
        --- PASS: TestAccCassandraSequential/cluster/basic (928.21s)
        --- PASS: TestAccCassandraSequential/cluster/requiresImport (953.66s)
    --- PASS: TestAccCassandraSequential/dataCenter (5897.76s)
        --- PASS: TestAccCassandraSequential/dataCenter/requiresImport (3145.14s)
        --- PASS: TestAccCassandraSequential/dataCenter/basic (2752.63s)

image

### CODE REVIEW

**Review by WodansSon — APPROVED** [review]
@neil-yechenwei Thank you for this PR... this LGTM! 🚀

**Review by katbyte — APPROVED** [review]
LGTM 🍾

**Comment by katbyte** [comment]
@neil-yechenwei - could we fix up the tests here?

**Comment by neil-yechenwei** [comment]
@katbyte , updated this PR. And I found a dependcy check issue. It is caused by this PR 16631. So I submitted another [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/16773) to fix this issue.

**Comment by neil-yechenwei** [comment]
@katbyte , if you don't mind, could you review/merge this PR asap since I have several PRs depending on this PR. Thanks in advance.

**Review by katbyte — APPROVED** [review]
thanks LGTM 🦋

**Pull request merged**
