### PR TITLE
`azurerm_machine_learning_compute_cluster` - Fix case sensitivity of `vm_size` property causing resource re-creation issue

### PR DESCRIPTION
**Pull request by sinbai**
Fix issue #17562.

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Could we raise an issue for this in [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) and leave a comment in the code linking to it?

**Comment by tombuildsstuff** [comment]
hi @sinbai 

Taking a look into this one, it appears that the `vm_size` shouldn't become case-insensitive here, but instead (since the API is returning this in upper-case), this should be specified in the Terraform Configuration (and validated within the Schema) in upper-case.

As such, whilst I'd agree with @stephybun that we should file an issue on the Swagger repository, we should also file an issue requesting that the possible values for this field are documented in the Swagger - since there's a fixed set of values possible for this API.

Thanks!

**Comment by sinbai** [comment]
> 



> Could we raise an issue for this in [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) and leave a comment in the code linking to it?

@stephybun  thanks for your feedback. I have filed an [Api issue #20216 ](https://github.com/Azure/azure-rest-api-specs/issues/20216)to track it.

**Comment by sinbai** [comment]
> 

@tombuildsstuff thanks for your suggestion here. I have submitted an [API issue](https://github.com/Azure/azure-rest-api-specs/issues/20217) to request the possible values of AmlCompute vmSize.

**Comment by sinbai** [comment]
> hi @sinbai
> 
> Taking a look into this one, it appears that the `vm_size` shouldn't become case-insensitive here, but instead (since the API is returning this in upper-case), this should be specified in the Terraform Configuration (and validated within the Schema) in upper-case.
> 
> As such, whilst I'd agree with @stephybun that we should file an issue on the Swagger repository, we should also file an issue requesting that the possible values for this field are documented in the Swagger - since there's a fixed set of values possible for this API.
> 
> Thanks!

@tombuildsstuff  thanks for your suggestion here. I have submitted an https://github.com/Azure/azure-rest-api-specs/issues/20217 to request the possible values of AmlCompute vmSize.

**Comment by katbyte** [comment]
@sinbai - it looks like the swagger issue was incorrectly closed as won't fix, could you please follow up with that?

**Comment by sinbai** [comment]
> @sinbai - it looks like the swagger issue was incorrectly closed as won't fix, could you please follow up with that?

Sure, done.

**Pull request closed without merging**
