### PR TITLE
Fix test `TestAccIotHubDPS_linkedHubs`

### PR DESCRIPTION
**Pull request by myc2h6o**
`connection_string` is not referencing existing IoT Hubs, causing error "Unable to find the IoThub ...", fixing it by using existing reference.

### CODE REVIEW

**Comment by myc2h6o** [comment]
Test result
image

**Review by katbyte — CHANGES_REQUESTED** [review]
test failure, perhapes we need to poll/wait on creation?
```
------- Stdout: -------
=== RUN   TestAccIotHubDPS_linkedHubs
=== PAUSE TestAccIotHubDPS_linkedHubs
=== CONT  TestAccIotHubDPS_linkedHubs
    testcase.go:110: Step 1/4 error: Error running apply: exit status 1
        
        Error: creating/updating IoT Device Provisioning Service Iot Hub Dps: (Provisioning Service Name "acctestIoTDPS-220829185508492455" / Resource Group "acctestRG-220829185508492455"): iothub.IotDpsResourceClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed." InnerError={"unmarshalError":"json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string"} AdditionalInfo=[{"code":404002,"httpStatusCode":"NotFound","message":"Unable to find the IoThub `acctestIoTHub2-220829185508492455.azure-devices.net`. Check if the hub exists and the connection information is correct. If you contact a support representative please include this correlation identifier: ef2c3d4b-cd68-4a92-a2a8-4142e277a8f3, timestamp: 2022-08-29 18:58:55Z, errorcode: IH404002."}]
        
          with azurerm_iothub_dps.test,
          on terraform_plugin_test.tf line 61, in resource "azurerm_iothub_dps" "test":
          61: resource "azurerm_iothub_dps" "test" {
        
--- FAIL: TestAccIotHubDPS_linkedHubs (338.94s)
FAIL
```

**Comment by myc2h6o** [comment]
@katbyte thanks for reviewing the change! I've done some test locally and this issue does happen sometimes. I tried looking at the resource properties, and they are all same during the provisioning failure time whether the issue happens or not, and a retry can create the IotHub DPS correctly. Fortunately, the error code is 404 for this specific issue that linked hubs are not found, I'll add a poll and retry to check the 404 error.

**Review by katbyte — APPROVED** [review]
LGTM 🎩

**Pull request merged**
