### PR TITLE
Update giovanni to address #10888

### PR DESCRIPTION
**Pull request by daveneeley**

### CODE REVIEW

**Comment by daveneeley** [comment]
@alvintang here is the updated PR with only the changes for #10888 that update giovanni. Thanks for doing all of this.

**Comment by daveneeley** [comment]
@tombuildsstuff @alvintang every time I push a change github resets the approval to run workflows! Would you or someone know approve this? Hopefully this time we'll pass the build checks and we can merge this.

image

**Comment by tombuildsstuff** [comment]
@daveneeley done :)

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by daveneeley** [comment]
Ready to merge!

**Pull request merged**
