### PR TITLE
Fix #196 creating a database with create_mode PointInTimeRestore fails

### LINKED ISSUE #196: Creating a database with create_mode PointInTimeRestore fails
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- azurerm_sql_database

### Expected Behavior
Restore data of a database (`source_database_id`) to a specific date (`restore_point_in_time`) within the retention period by creating a new database.

### Actual Behavior
Terraform does not recognise argument `restore_point_in_time`. Creating a database with create_mode PointInTimeRestore fails with below error.
```hcl
Error creating SQL Database: BadRequest (400) - The point in time was not specified for restoring live database 'test'.
```

### PR DESCRIPTION
**Pull request by oguzkilcan**

### CODE REVIEW

**Comment by sebastus** [comment]
This one conflicts with PR #191. @ouzklcn what are the details of your test? I'll test similarly with my updated sql db provider.

**Comment by ouzklcn** [comment]
@sebastus You can use below resource template for testing. If you like I can fork your code fix it and open a PR to your branch as well.

```hcl
resource "azurerm_sql_database" "sql_db" {
  name                  = "test-restore"
  resource_group_name   = "testdb-rg"
  location              = "West Europe"
  server_name           = "testdb-server"
  create_mode           = "PointInTimeRestore"
  source_database_id    = "/subscriptions/00000000-1111-2222-3333-444444444444/resourceGroups/testdb-rg/providers/Microsoft.Sql/servers/testdb-server/databases/testdb"
  restore_point_in_time = "2017-07-28T08:24:37.467Z"
}
```

**Review by tombuildsstuff — COMMENTED** [review]
Hey @ouzklcn 

Thanks for this PR - apologies for the delay in reviewing this!

This change LGTM - would it be possible to add an acceptance test for this change so we can verify it's functioning as intended? [Here's an example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_sql_database_test.go#L49) from the `azurerm_sql_database` resource.

Thanks!

**Comment by ouzklcn** [comment]
Hey @tombuildsstuff 

I added a test. You can find it's output below. 

```
~/go/src/github.com/ouzklcn/terraform-provider-azurerm/azurerm$ TF_ACC=1 go test -v -run TestAccAzureRMSqlDatabase_restorePointInTime  -timeout 30m
=== RUN   TestAccAzureRMSqlDatabase_restorePointInTime
--- PASS: TestAccAzureRMSqlDatabase_restorePointInTime (1377.12s)
PASS
ok  	github.com/ouzklcn/terraform-provider-azurerm/azurerm	1377.138s
```

Unfortunately, as you can see from the output, it takes a lot time complete. Azure does not immediately creates a restorable backup once it creates a database. It takes around 10 minutes. Because of that I need to set the test to sleep for a reasonable time to wait Azure.

**Review by tombuildsstuff — APPROVED** [review]
Hey @ouzklcn 

Thanks for pushing those changes - I've taken another look and this LGTM :)

Tests pass:

```
$ TF_ACC=1 envchain azurerm go test ./azurerm -v -timeout 120m -run TestAccAzureRMSqlDatabase_

=== RUN   TestAccAzureRMSqlDatabase_basic
--- PASS: TestAccAzureRMSqlDatabase_basic (170.06s)
=== RUN   TestAccAzureRMSqlDatabase_elasticPool
--- PASS: TestAccAzureRMSqlDatabase_elasticPool (265.52s)
=== RUN   TestAccAzureRMSqlDatabase_withTags
--- PASS: TestAccAzureRMSqlDatabase_withTags (301.37s)
=== RUN   TestAccAzureRMSqlDatabase_datawarehouse
--- PASS: TestAccAzureRMSqlDatabase_datawarehouse (296.40s)
PASS
ok  	github.com/terraform-providers/terraform-provider-azurerm/azurerm	1033.369s
```

Thanks!

**Pull request merged**
