### PR TITLE
New Resource: azurerm_cosmosdb_sql_role_assignment

### PR DESCRIPTION
**Pull request by neil-yechenwei**
This PR is to support new resource `azurerm_cosmosdb_sql_role_assignment`.

image
image

Rest API Spec:
https://github.com/Azure/azure-rest-api-specs/blob/184b23b63ee3a79fb41ca3aa55a31a8d9e636772/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2021-10-15/rbac.json#L260

### CODE REVIEW

**Comment by aristosvo** [comment]
@neil-yechenwei So https://github.com/Azure/azure-rest-api-specs/issues/16560 is fixed? Didn't know that, had done a first implementation as well :)

**Comment by neil-yechenwei** [comment]
@aristosvo , Yes. Service team confirmed that the issue you mentioned has fixed. All TCs in my two PRs [15035 ](https://github.com/hashicorp/terraform-provider-azurerm/pull/15035) and [15038](https://github.com/hashicorp/terraform-provider-azurerm/pull/15038) passed on my local. So could you help review the [PR 15035](https://github.com/hashicorp/terraform-provider-azurerm/pull/15035) first? Once this PR is merged, I will update this PR to add property validation for `role_definition_id` and rerun TCs in this PR and paste the test result here. Thanks in advance.

**Comment by myc2h6o** [comment]
Hi @neil-yechenwei dependencies breaking shall be fixed by #15729

**Review by katbyte — APPROVED** [review]
LGTM 🦕

**Pull request merged**
