### PR TITLE
identity: moving SystemAssigned to use the new commonschema types

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR moves the earlier common identity types to using the newer package, located within go-azure-helpers.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Dependent on https://github.com/hashicorp/go-azure-helpers/pull/99

**Comment by tombuildsstuff** [comment]
Dependent on #15207

**Review by mbfrahry — APPROVED** [review]
LGTM

**Comment by tombuildsstuff** [comment]
Tests look good 👍

**Pull request merged**
