### PR TITLE
`azurerm_mssql_outbound_firewall_rule` - New resource

### LINKED ISSUE #14691: Support for Azure SQL Outbound Firewall rules
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for adding Azure SQL & Synapse Analytics outbound firewall rules as described here: https://docs.microsoft.com/en-us/azure/azure-sql/database/outbound-firewall-rule-overview

### References

https://docs.microsoft.com/en-us/azure/azure-sql/database/outbound-firewall-rule-overview

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #14691

## Acceptance Tests
Screenshot 2022-01-05 at 13 16 03

## To Do:
- [x] Docs `azurerm_mssql_outbound_firewall_rule`
- [x] Docs `azurerm_mssql_server`

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @aristosvo - looks like this is missing docs.. also shouldn't there be more properties for a firewall rule 🤔

**Comment by katbyte** [comment]
Hmm, it seems like this is a per server setting - ie 1:1 for the resource, and just flips a boolean setting for that server?

maybe this would be best as a `restrict_outbound_networking` property on the server rather than a separate resource?

**Comment by aristosvo** [comment]
It's two kind of settings:
- a switch to restrict outbound traffic
- a list of FQDNs which are allowed to receive traffic (the actual firewall rules)

My thinking was to mimic inbound firewall rules setup, which has:
- a switch on server level to restrict inbound traffic
- a separate resource for the rules, the firewall rules resource

**Review by katbyte — CHANGES_REQUESTED** [review]
I prefer 2b but given inbound already behaves this way so be it for consistency! thanks @aristosvo - LBTM 🚀

**Review by katbyte — APPROVED** [review]

**Pull request merged**
