### PR TITLE
New resource: `azurerm_federated_identity_credential`

### LINKED ISSUE #18617: Support for azurerm_managed_identity_federated_identity_credential
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for creating federated identity credentials for managed identity

### New or Affected Resource(s)/Data Source(s)

azurerm_managed_identity_federated_identity_credential

### Potential Terraform Configuration

```hcl
I assume basically the same as https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/application_federated_identity_credential
```

### References

I would like to use this with AKS, (docs for this feature are in this PR: https://github.com/Azure/azure-workload-identity/pull/577)

More info at https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview as well

### PR DESCRIPTION
**Pull request by favoretti**
Fixes #18617

### CODE REVIEW

**Comment by favoretti** [comment]
```
$ TF_ACC=1 go test -v ./internal/services/managedidentity -timeout=1000m -run='TestAccFederatedIdentityCredential'
=== RUN   TestAccFederatedIdentityCredential_basic
=== PAUSE TestAccFederatedIdentityCredential_basic
=== RUN   TestAccFederatedIdentityCredential_requiresImport
=== PAUSE TestAccFederatedIdentityCredential_requiresImport
=== CONT  TestAccFederatedIdentityCredential_basic
=== CONT  TestAccFederatedIdentityCredential_requiresImport
--- PASS: TestAccFederatedIdentityCredential_basic (190.41s)
--- PASS: TestAccFederatedIdentityCredential_requiresImport (210.06s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/managedidentity	211.229s
```

**Comment by favoretti** [comment]
image

**Comment by favoretti** [comment]
No regressions after API upgrade either it seems:
image

**Review by katbyte — APPROVED** [review]
Thanks @favoretti - LGTM 🍄

**Comment by weisdd** [comment]
@favoretti I've just tried to use the resource and noticed that the documentation has a small defect. - `location` is actually not part of the resource spec, and it's not needed at all. So, all references to location should be removed.

**Comment by favoretti** [comment]
@weisdd oh, you're completely correct, fixed it here: https://github.com/hashicorp/terraform-provider-azurerm/pull/19254
Resource itself works though, right?

**Comment by weisdd** [comment]
@favoretti the resource itself works well. - In our corporate terraform module, I replaced raw `azapi` resources with `azurerm_federated_identity_credential`, and then ran `terraform apply`, it all went flawlessly. Happy to see there are no migration issues.

Thanks for fixing the docs :)

**Comment by TeamDman** [comment]
Example script for future reference

```terraform
resource "azurerm_user_assigned_identity" "gifts" {
  resource_group_name = azurerm_resource_group.main.name
  name = "gifts"
  location = "canadacentral"
}

resource "azurerm_federated_identity_credential" "gifts" {
  resource_group_name = azurerm_resource_group.main.name
  parent_id = azurerm_user_assigned_identity.gifts.id
  name = "gifts"
  issuer = azurerm_kubernetes_cluster.main.oidc_issuer_url
  subject = "system:serviceaccount:gifts:gifts"
  audience = ["api://AzureADTokenExchange"]
}
```

The `azuread_application_federated_identity_credential` resource from the azure**ad** provider one asks for an application id instead of the reference to the managed identity which had me confused for a bit until I noticed that there's also an azure**rm** resource

**Pull request merged**
