### PR TITLE
[v4.0 Only] Update ACR API version to 2022-02-01-preview and add up the new properties

### LINKED ISSUE #18408: Support for soft delete policy in Azure Container Registry
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Container Registry (ACR) allows you to enable the soft delete policy to recover any accidentally deleted artifacts for a set retention period.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Potential Terraform Configuration

```hcl
resource "azurerm_container_registry" "acr" {
  name                = "containerRegistry1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Premium"
  admin_enabled       = false
  georeplications {
    location                = "East US"
    zone_redundancy_enabled = true
    tags                    = {}
  }
  georeplications {
    location                = "westeurope"
    zone_redundancy_enabled = true
    tags                    = {}
  }
  soft_delete_retention_policy {
    enabled = true
    days = 30
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/container-registry/container-registry-soft-delete-policy
https://azure.microsoft.com/en-us/updates/public-preview-soft-delete-in-azure-container-registry/

### PR DESCRIPTION
**Pull request by magodo**
This PR is a copy-paste of the reverted PR #17926, which includes following changes:

1. Updates ACR API version to 2022-02-01-preview
2. Adds up the new properties for `azurerm_container_registry`, which includes: `azuread_authentication_as_arm_policy_enabled` and `soft_delete_policy`
3. Removes the `virtual_network` property, which is deprecated in the new API. ACR service team told that they deliberatively deprecated this property since it is only used exclusively for service endpoints (which is a feature they are deprecating). They are encouraging customers to use Private Endpoints instead.

Given there is a breaking change in this PR, please don't merge it until v4.

## Test

```shell
💤  TF_ACC=1 go test -v -timeout=20h ./internal/services/containers  -run='TestAccContainerRegistry_policies$'
=== RUN   TestAccContainerRegistry_policies
=== PAUSE TestAccContainerRegistry_policies
=== CONT  TestAccContainerRegistry_policies
--- PASS: TestAccContainerRegistry_policies (258.19s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/containers    258.200s
```

Fix #18408.

### CODE REVIEW

**Comment by katbyte** [comment]
@magodo - is this PR still a draft or is it good to review?

**Comment by magodo** [comment]
@katbyte Yes, it is ready for review if this breaking change is allowed.

**Comment by tombuildsstuff** [comment]
@magodo is there a reason we can't conditionally use the older API to still support Virtual Networks until 4.x?

**Comment by magodo** [comment]
@tombuildsstuff I believe the motivation of continue reviewing this PR (it was a draft PR and meant to be merged in v4) is because this kind of breaking change is allowed, e.g. https://github.com/hashicorp/terraform-provider-azurerm/pull/17785. Regarding conditionally use the older API, I assume the condition is whether user has opt in the v4 beta? That will require us rewrite all the exapnd/flatten functions (even more) for those two different versions?

**Pull request closed without merging**
