### PR TITLE
`digitaltwins` - updating to API Version `2023-01-31` / support for User Assigned Identities

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR updates `digitaltwins` to use API Version `2023-01-31` - and adds support for User Assigned Identities, which is available in this API version.

### CODE REVIEW

**Review by manicminer — APPROVED** [review]
LGTM

**Comment by tombuildsstuff** [comment]
Dependent on https://github.com/hashicorp/terraform-provider-azurerm/pull/22803

**Comment by tombuildsstuff** [comment]
Per [this comment](https://github.com/Azure/azure-rest-api-specs/pull/25120#issuecomment-1664230909) this is fine to ship with the workaround - removing Draft status.

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2023-08-04 at 12 38 45

**Pull request merged**
