### PR TITLE
Upgrade storage sdk to 2021-04-01

### PR DESCRIPTION
**Pull request by magodo**
This PR upgrades storage SDK from 2021-01-01 to 2021-04-01, except the blob inventory policy client, due to Azure/azure-rest-api-specs#16696.

### CODE REVIEW

**Comment by magodo** [comment]
Test result:

image

The three failures here also exist in the curren main branch. One will be fixed by #14100. The other two (actually due to the same reason), I've reached out to the service team since I believe that is some kind of service behavior issue.

**Review by katbyte — COMMENTED** [review]
Is there a pressing need for this SDK upgrade? or can we wait until its fixed and can be used for all resource?

**Comment by magodo** [comment]
@katbyte Yes, this upgrading is needed for us to move on the storage shim layer, which brings some previously missing functionality to the mgmt plane API.

**Comment by katbyte** [comment]
@magodo - is that not a breaking change that should be fixed by the service sooner than later? or is there more context then exists in the linked issue?

**Comment by magodo** [comment]
@katbyte Yes, more context going through the internal email thread that the 2021-04-01 API can't be used to manage the old instance, and there is no plan to support them.

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @magodo

**Comment by tombuildsstuff** [comment]
@magodo since this is no longer going to be supported by the Service Team, presumably we should also deprecate that functionality?

**Comment by magodo** [comment]
@tombuildsstuff Do you mean to also upgrade the blob inventory to the 04-01 and cut off the earlier versions? IMO, we'd better defer it to the 3.0 upgrade.

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2021-11-15 at 08 28 51

**Comment by tombuildsstuff** [comment]
@magodo 

> Do you mean to also upgrade the blob inventory to the 04-01 and cut off the earlier versions? IMO, we'd better defer it to the 3.0 upgrade.

We'd need to deprecate this prior to 3.0 to be able to remove it there - so I think that'd need to be done now (or soon) to account for that?

**Comment by magodo** [comment]
@tombuildsstuff Sure, will submit a commit for that.

**Comment by tombuildsstuff** [comment]
@magodo cool - since this PR's otherwise good to go, I hope you don't mind but I'm going to merge this PR and we can do that in a follow-up?

**Comment by magodo** [comment]
@tombuildsstuff #14183 is submitted for the blob inventory policy. Please take a look :)

**Pull request merged**
