### PR TITLE
azurerm_function_app & azurerm_app_service - support for vnet_route_all_enabled

### LINKED ISSUE #13259: Support for vnet_route_all_enabled in azurerm_function_app
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`vnet_route_all_enabled` was added to the `azurerm_app_service` in pull request #13073 to close issue #12860. Please add the same `site_config.vnet_route_all_enabled` to `azurerm_function_app` for the same reason of controlling the VNet Configuration "Route All" / `vnetRouteAllEnabled` setting.

### New or Affected Resource(s)

* azurerm_function_app

### References

* #13073 
* #12860 
* https://docs.microsoft.com/en-us/azure/app-service/web-sites-integrate-with-vnet#application-routing

### PR DESCRIPTION
**Pull request by henrymcconville**
Fixes #13259, inspired by #13073

Acceptance Tests:
```
➜  ~/go/src/github.com/hashicorp/terraform-provider-azurerm: git:(function-app-vnet-route-all) ✗ make acctests SERVICE='web' TESTARGS='-run=VnetRouteAllEnabled'
 TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/web -run=VnetRouteAllEnabled -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled
=== PAUSE TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled
=== RUN   TestAccFunctionApp_siteConfigVnetRouteAllEnabled
=== PAUSE TestAccFunctionApp_siteConfigVnetRouteAllEnabled
=== RUN   TestAccFunctionApp_appSettingsVnetRouteAllEnabled
=== PAUSE TestAccFunctionApp_appSettingsVnetRouteAllEnabled
=== CONT  TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled
=== CONT  TestAccFunctionApp_appSettingsVnetRouteAllEnabled
=== CONT  TestAccFunctionApp_siteConfigVnetRouteAllEnabled
--- PASS: TestAccFunctionApp_siteConfigVnetRouteAllEnabled (151.79s)
--- PASS: TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled (154.94s)
--- PASS: TestAccFunctionApp_appSettingsVnetRouteAllEnabled (216.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/web	218.560s
```

### CODE REVIEW

**Comment by tdever42** [comment]
I'm waiting for this so I can start deploying my function apps with terraform.  Thanks for getting it done!

**Comment by piwi91** [comment]
This should also be added to the azurerm_app_service resource

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @henrymcconville - Thanks for this, it looks good, if you can resolve the conflicts I'll run it through tests and get it approved / merged.

**Comment by henrymcconville** [comment]
Thanks @jackofallops! Conflicts resolved and acc tests are still passing:
```
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/web -run=VnetRouteAllEnabled -timeout 180m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled
=== PAUSE TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled
=== RUN   TestAccFunctionApp_siteConfigVnetRouteAllEnabled
=== PAUSE TestAccFunctionApp_siteConfigVnetRouteAllEnabled
=== RUN   TestAccFunctionApp_appSettingsVnetRouteAllEnabled
=== PAUSE TestAccFunctionApp_appSettingsVnetRouteAllEnabled
=== CONT  TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled
=== CONT  TestAccFunctionApp_appSettingsVnetRouteAllEnabled
=== CONT  TestAccFunctionApp_siteConfigVnetRouteAllEnabled
--- PASS: TestAccFunctionAppDataSource_siteConfigVnetRouteAllEnabled (155.38s)
--- PASS: TestAccFunctionApp_appSettingsVnetRouteAllEnabled (165.74s)
--- PASS: TestAccFunctionApp_siteConfigVnetRouteAllEnabled (183.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/web	185.315s
```

**Review by katbyte — APPROVED** [review]
Thanks @henrymcconville - LGTM now 🙌

**Pull request merged**
