### PR TITLE
azurerm_[orchestrated|windows|linux]_virtual_machine_scale_set: support `placement` for os disks

### PR DESCRIPTION
**Pull request by sergelogvinov**
Add option ```placement``` to diff_disk_settings block.
 
Code was copied from ```virtual_machine.go```

```hcl
  os_disk {
    caching              = "ReadOnly"
    storage_account_type = "Standard_LRS"

    diff_disk_settings {
      option    = "Local"
      placement = "ResourceDisk"
    }
  }
```

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the pr @sergelogvinov - we'll need to update the docs with the new property as well add it to a test. thanks

**Comment by sergelogvinov** [comment]
I've update the docs/tests, and add  windows_virtual_machine_scale_set support too.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @sergelogvinov, unfortunately we have a test failure. The default value might need to be removed?
```
------- Stdout: -------
=== RUN   TestAccLinuxVirtualMachineScaleSet_disksOSDiskEphemeral
=== PAUSE TestAccLinuxVirtualMachineScaleSet_disksOSDiskEphemeral
=== CONT  TestAccLinuxVirtualMachineScaleSet_disksOSDiskEphemeral
testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
stdout:
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
# azurerm_linux_virtual_machine_scale_set.test must be replaced
-/+ resource "azurerm_linux_virtual_machine_scale_set" "test" {
~ computer_name_prefix                              = "acctestvmss-220626211113595156" -> (known after apply)
- encryption_at_host_enabled                        = false -> null
~ id                                                = "/subscriptions/*******/resourceGroups/acctestRG-220626211113595156/providers/Microsoft.Compute/virtualMachineScaleSets/acctestvmss-220626211113595156" -> (known after apply)
name                                              = "acctestvmss-220626211113595156"
~ platform_fault_domain_count                       = 0 -> (known after apply)
- secure_boot_enabled                               = false -> null
~ unique_id                                         = "616bcf0e-1720-47d4-94da-da801a213b92" -> (known after apply)
- vtpm_enabled                                      = false -> null
# (17 unchanged attributes hidden)
~ automatic_instance_repair {
~ enabled      = false -> (known after apply)
~ grace_period = "PT30M" -> (known after apply)
}
+ extension {
+ auto_upgrade_minor_version = (known after apply)
+ automatic_upgrade_enabled  = (known after apply)
+ force_update_tag           = (known after apply)
+ name                       = (known after apply)
+ protected_settings         = (sensitive value)
+ provision_after_extensions = (known after apply)
+ publisher                  = (known after apply)
+ settings                   = (known after apply)
+ type                       = (known after apply)
+ type_handler_version       = (known after apply)
}
~ network_interface {
name                          = "example"
# (3 unchanged attributes hidden)
# (1 unchanged block hidden)
}
~ os_disk {
~ disk_size_gb              = 30 -> (known after apply)
# (3 unchanged attributes hidden)
~ diff_disk_settings {
+ placement = "CacheDisk" # forces replacement
# (1 unchanged attribute hidden)
}
}
+ terminate_notification {
+ enabled = (known after apply)
+ timeout = (known after apply)
}
+ termination_notification {
+ enabled = (known after apply)
+ timeout = (known after apply)
}
# (1 unchanged block hidden)
}
Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccLinuxVirtualMachineScaleSet_disksOSDiskEphemeral (319.10s)
FAIL
```

**Comment by sergelogvinov** [comment]
@stephybun thank you for feedback. Yep, my bad. I did not test well.

Now all fine.

**Review by katbyte — APPROVED** [review]
LGTM 🌵

**Comment by NillsF** [comment]
@stephybun 
This change impacted my Terraform code for Linux scale sets. The default of CacheDisk didn't work, and I was able to solve by setting:

```hcl
diff_disk_settings {
      option    = "Local"
      placement = "ResourceDisk"
    }
```

I wonder if setting the default to ResourceDisk might be a better default value.

**Comment by sergelogvinov** [comment]
Hello. Can you tell me what instance type/region do you use?

**Comment by NillsF** [comment]
standard_e32ads_v5 in East US.

**Comment by sergelogvinov** [comment]
Yep, maybe you a right. I did not find the cache size here [eads-v5](https://docs.microsoft.com/en-us/azure/virtual-machines/easv5-eadsv5-series#eadsv5-series) either.

All my instances [eads-v4](https://docs.microsoft.com/en-us/azure/virtual-machines/eav4-easv4-series#easv4-series) use ```Temp storage``` too.

So, I vote for your idea )

**Pull request merged**
