### PR TITLE
`azurerm_dns_txt_record` - deprecate `value` and support `values`

### PR DESCRIPTION
**Pull request by neil-yechenwei**
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20640

Background:
Records are composed by a list of record. All values in all records must not exceed 1024 characters.
One record is composed by a list of value. Each value is limited in 255 characters.

Symptom:
When user wants to set one record with 260 characters and first value of this record is 10 characters and the second value of this record is 250 characters, but currently TF doesn't support this scenario and TF would separate this record to two values per 254 character limit. The first value of this record would be set to 254 characters and the second value of this record would be set to 6 characters. That's not what user expected. So we have to align with API behavior to support this scenario.

--- PASS: TestAccDnsTxtRecord_updateRecords (409.28s)
--- PASS: TestAccDnsTxtRecord_basic (327.92s)
--- PASS: TestAccDnsTxtRecord_requiresImport (358.97s)
--- PASS: TestAccDnsTxtRecord_withTags (415.29s)

### CODE REVIEW

**Comment by stephybun** [comment]
Thanks for this PR @neil-yechenwei.

Unfortunately I think this has missed the point raised in issue https://github.com/hashicorp/terraform-provider-azurerm/issues/20640 which is asking for a single top level `values` field and not a new field within the `record` block.

For clarification the configuration should allow users to specify values like below:
```
values = ["value1", "value2", ..., "valuex"]
```

In addition to this there are functionalities referenced in this PR which will not be available in `terraform-plugin-framework` which we would need to move away from.

Whilst I'd like to thank you for looking into this, this issue will require a different approach.

**Comment by neil-yechenwei** [comment]
@jmapro, could you double confirm whether the feature @stephybun mentioned is what you want?

**Comment by jmapro** [comment]
Hello !
I confirm that I need to pass `values = ["value1", "value2", ... , "valuex"]`

**Comment by neil-yechenwei** [comment]
@jmapro , Below is an example. Is it what you want?

Example:
```
resource "azurerm_dns_txt_record" "test" {
  name                = "myarecord%d"
  resource_group_name = azurerm_resource_group.test.name
  zone_name           = azurerm_dns_zone.test.name
  ttl                 = 300

  record {
    values = ["The first Record Value"]
  }

  record {
    values = [
                       "The first sub value as a single line in one Record Value", 
                       "The second sub value as a single line in one Record Value", 
                       "The third sub value as a single line in one Record Value."
                   ]
  }

  record {
    values = ["The third Record Value"]
  }
}
```

**Comment by jmapro** [comment]
@neil-yechenwei , this is exactly what I need.

**Comment by neil-yechenwei** [comment]
Hi @stephybun , I've confirmed with the owner @jmapro . I think this PR is what user expects. So could you re-enable this PR? Thanks.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei [DNS TXT Records](https://www.cloudflare.com/en-gb/learning/dns/dns-records/dns-txt-record/) expose a singular value for each record, which means that the Terraform Schema today is exposed as:

```go
"record": {
				Type:     pluginsdk.TypeSet,
				Required: true,
				Elem: &pluginsdk.Resource{
					Schema: map[string]*pluginsdk.Schema{
						"value": {
							Type:         pluginsdk.TypeString,
							Required:     true,
							ValidateFunc: validation.StringLenBetween(1, 1024),
						},
					},
				},
			}
```

As such unfortunately the [approaches outlined in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/20747#issuecomment-1498677597) don't really make sense, we could combine the `values` strings together, however that doesn't really make sense (since at what point do we split these values, we'd also be unable to validate the total length at plan time, since the total value for the `value` field can be _up to_ 1024 character strings).

However I'd tend to agree with @jmapro that the current means of exposing this isn't great, as such we should instead look to expose a single `records` field, which is a Set of String values:

```go
			"records": {
				Type:     pluginsdk.TypeSet,
				Required: true,
				Elem: &pluginsdk.Schema{
					Type: pluginsdk.TypeString,
				},
			},
```

Which, since these values can't be ordered - as each value becomes it's own DNS TXT Record under the `name`, means we can expose this in a single manner for users, in a means that makes sense given how these DNS Records work.

Unfortunately [the approach proposed in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/20747#issuecomment-1498677597) isn't something we can ship due to how DNS TXT Records work.

Hope that helps clarify why we're requiring this change to be the way it needs to be.

**Pull request closed without merging**
