### PR TITLE
Added support for patch_mode in resource_linux_virtual_machine.

### LINKED ISSUE #13257: Support for enable_automatic_updates and patch_mode in azurerm_linux_virtual_machine
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft has added support for Linux distros to the Automatic VM guest patching preview however v2.75.0 of the azurerm provider throws the following error:

```
│ Error: Unsupported argument
│ 
│   on 070-vm-jumpbox-linux.tf line 9, in resource "azurerm_linux_virtual_machine" "vm_jumpbox_linux":
│    9:   enable_automatic_updates = true
│ 
│ An argument named "enable_automatic_updates" is not expected here.
│
│ Error: Unsupported argument
│ 
│   on 070-vm-jumpbox-linux.tf line 10, in resource "azurerm_linux_virtual_machine" "vm_jumpbox_linux":
│   10:   patch_mode               = "AutomaticByPlatform"
│ 
│ An argument named "patch_mode" is not expected here.
```

### New or Affected Resource(s)

* azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "vm_jumpbox_linux" {
  name  = var.vm_jumpbox_linux_name
  resource_group_name  = var.resource_group_name
  location = var.location
  size = var.vm_jumpbox_linux_size
  admin_username  = data.azurerm_key_vault_secret.adminuser.value
  network_interface_ids = [azurerm_network_interface.vm_jumbox_linux_nic_01.id]
  enable_automatic_updates = true
  patch_mode  = "AutomaticByPlatform"
  tags  = var.tags

  admin_ssh_key {
    username  = data.azurerm_key_vault_secret.adminuser.value
    public_key = var.ssh_public_key
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = var.vm_jumpbox_linux_storage_account_type
  }

  source_image_reference {
    publisher = var.vm_jumpbox_linux_image_publisher
    offer = var.vm_jumpbox_linux_image_offer
    sku  = var.vm_jumpbox_linux_image_sku
    version = var.vm_jumpbox_linux_image_version
  }
}
```

### References

* [Preview: Automatic VM guest patching for Azure VMs](https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching)
  * [Supported OS Images](https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#supported-os-images) 
* [enable_automatic_updates](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#enable_automatic_updates) for *azurerm_windows_virtual_machine*
* [patch_mode](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#patch_mode)  for *azurerm_windows_virtual_machine*

### PR DESCRIPTION
**Pull request by atombrella**
Fixes #13257

I have not yet run the acceptance tests. I have an Azure account, but it's a bit inactive. I thought this might be a good occasion to learn a bit more about Azure :)

### CODE REVIEW

**Comment by catriona-m** [comment]
> @catriona-m Thanks for the review :) I'll try to push a "green version" of this during the weekend. Hopefully having a single test for the verification and update is fine, or do you prefer two separate tests?

@atombrella thanks for updating this, the new changes look good, only this test is still failing:

```
------- Stdout: -------
=== RUN   TestAccLinuxVirtualMachine_linuxPatchModeSetting
=== PAUSE TestAccLinuxVirtualMachine_linuxPatchModeSetting
=== CONT  TestAccLinuxVirtualMachine_linuxPatchModeSetting
testcase.go:109: Step 1/3 error: Error running apply: exit status 1
Error: At least one `admin_ssh_key` must be specified when `disable_password_authentication` is set to `true`
with azurerm_linux_virtual_machine.test,
on terraform_plugin_test.tf line 43, in resource "azurerm_linux_virtual_machine" "test":
43: resource "azurerm_linux_virtual_machine" "test" {
--- FAIL: TestAccLinuxVirtualMachine_linuxPatchModeSetting (255.06s)
FAIL
```

You may need to add an admin_ssh_key in the test data to get this working eg -  https://github.com/hashicorp/terraform-provider-azurerm/blob/59a5883e7cb28b36b5988b1c35175f65b57a0653/internal/services/compute/linux_virtual_machine_resource_auth_test.go#L155

**Comment by atombrella** [comment]
> > @catriona-m Thanks for the review :) I'll try to push a "green version" of this during the weekend. Hopefully having a single test for the verification and update is fine, or do you prefer two separate tests?
> 
> @atombrella thanks for updating this, the new changes look good, only this test is still failing:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccLinuxVirtualMachine_linuxPatchModeSetting
> === PAUSE TestAccLinuxVirtualMachine_linuxPatchModeSetting
> === CONT  TestAccLinuxVirtualMachine_linuxPatchModeSetting
> testcase.go:109: Step 1/3 error: Error running apply: exit status 1
> Error: At least one `admin_ssh_key` must be specified when `disable_password_authentication` is set to `true`
> with azurerm_linux_virtual_machine.test,
> on terraform_plugin_test.tf line 43, in resource "azurerm_linux_virtual_machine" "test":
> 43: resource "azurerm_linux_virtual_machine" "test" {
> --- FAIL: TestAccLinuxVirtualMachine_linuxPatchModeSetting (255.06s)
> FAIL
> ```
> 
> You may need to add an admin_ssh_key in the test data to get this working eg -
> 
> https://github.com/hashicorp/terraform-provider-azurerm/blob/59a5883e7cb28b36b5988b1c35175f65b57a0653/internal/services/compute/linux_virtual_machine_resource_auth_test.go#L155

Done. Thanks :)

**Review by katbyte — APPROVED** [review]
Thanks @atombrella - LGTM 💯

**Comment by atombrella** [comment]
Good :) @katbyte I think probably I forgot to add something to read the new property under the `read`-function.

**Pull request merged**
