### PR TITLE
`azurerm_kusto_cluster_customer_managed_key` - support auto key rotation

### PR DESCRIPTION
**Pull request by liuwuliuyun**
- Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20569
- Change property key_version to optional
- Change TestAccKustoClusterCustomerManagedKey_basic
- Add TestAccKustoClusterCustomerManagedKey_complete

### CODE REVIEW

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_basic_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_basic_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoClusterCustomerManagedKey_basic\E$ #gosetup
=== RUN   TestAccKustoClusterCustomerManagedKey_basic
=== PAUSE TestAccKustoClusterCustomerManagedKey_basic
=== CONT  TestAccKustoClusterCustomerManagedKey_basic
--- PASS: TestAccKustoClusterCustomerManagedKey_basic (1520.65s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_complete_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_complete_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoClusterCustomerManagedKey_complete\E$ #gosetup
=== RUN   TestAccKustoClusterCustomerManagedKey_complete
=== PAUSE TestAccKustoClusterCustomerManagedKey_complete
=== CONT  TestAccKustoClusterCustomerManagedKey_complete
--- PASS: TestAccKustoClusterCustomerManagedKey_complete (1251.41s)
PASS


Process finished with the exit code 0

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this @liuwuliuyun but we have some test failures
```
------- Stdout: -------
=== RUN   TestAccKustoClusterCustomerManagedKey_updateKey
=== PAUSE TestAccKustoClusterCustomerManagedKey_updateKey
=== CONT  TestAccKustoClusterCustomerManagedKey_updateKey
testcase.go:110: Step 1/4 error: Check failed: Check 4/4 error: azurerm_kusto_cluster_customer_managed_key.test: Attribute 'key_version' expected to be set
--- FAIL: TestAccKustoClusterCustomerManagedKey_updateKey (1028.35s)
FAIL
```
```
------- Stdout: -------
=== RUN   TestAccKustoClusterCustomerManagedKey_requiresImport
=== PAUSE TestAccKustoClusterCustomerManagedKey_requiresImport
=== CONT  TestAccKustoClusterCustomerManagedKey_requiresImport
testcase.go:110: Step 1/2 error: Check failed: Check 4/4 error: azurerm_kusto_cluster_customer_managed_key.test: Attribute 'key_version' expected to be set
--- FAIL: TestAccKustoClusterCustomerManagedKey_requiresImport (1030.75s)
FAIL
```

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_requiresImport_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_requiresImport_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoClusterCustomerManagedKey_requiresImport\E$ #gosetup
=== RUN   TestAccKustoClusterCustomerManagedKey_requiresImport
=== PAUSE TestAccKustoClusterCustomerManagedKey_requiresImport
=== CONT  TestAccKustoClusterCustomerManagedKey_requiresImport
--- PASS: TestAccKustoClusterCustomerManagedKey_requiresImport (1354.59s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_updateKey_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_updateKey_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoClusterCustomerManagedKey_updateKey\E$ #gosetup
=== RUN   TestAccKustoClusterCustomerManagedKey_updateKey
=== PAUSE TestAccKustoClusterCustomerManagedKey_updateKey
=== CONT  TestAccKustoClusterCustomerManagedKey_updateKey
--- PASS: TestAccKustoClusterCustomerManagedKey_updateKey (1312.70s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_basic_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto__1_.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_basic_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto__1_.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoClusterCustomerManagedKey_basic\E$ #gosetup
=== RUN   TestAccKustoClusterCustomerManagedKey_basic
=== PAUSE TestAccKustoClusterCustomerManagedKey_basic
=== CONT  TestAccKustoClusterCustomerManagedKey_basic
--- PASS: TestAccKustoClusterCustomerManagedKey_basic (1248.85s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_complete_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto__1_.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoClusterCustomerManagedKey_complete_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto__1_.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoClusterCustomerManagedKey_complete\E$ #gosetup
=== RUN   TestAccKustoClusterCustomerManagedKey_complete
=== PAUSE TestAccKustoClusterCustomerManagedKey_complete
=== CONT  TestAccKustoClusterCustomerManagedKey_complete
--- PASS: TestAccKustoClusterCustomerManagedKey_complete (1226.81s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
Thanks @stephybun for the review. I have updated the code and rerun tests.

**Review by stephybun — APPROVED** [review]
Thanks @liuwuliuyun LGTM 🍊

**Pull request merged**
