### PR TITLE
`azurerm_container_registry` - Avoid unnecessary recreate when georeplication.tags update

### PR DESCRIPTION
**Pull request by magodo**
This PR fixes two things:

- The first commit fixes some problematic code introduced in https://github.com/hashicorp/terraform-provider-azurerm/pull/15340, where those code only handles v2.0 correctly, but are meaningless for v3.0
- The second commit fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/24960, where the georeplication's zone redundency enabled flag is checked by pointer, instead of value,to tell whether a recreate of those georeplications are needed.

### CODE REVIEW

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @magodo 

It looks like this has some test failures, but once those are addressed we can take another look at this. Thanks!

```
------- Stdout: -------
=== RUN   TestAccContainerRegistry_geoReplication
=== PAUSE TestAccContainerRegistry_geoReplication
=== CONT  TestAccContainerRegistry_geoReplication
    testcase.go:113: Step 5/10 error: After applying this test step, the plan was not empty.
        stdout:
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        Terraform will perform the following actions:
          # azurerm_container_registry.test will be updated in-place
          ~ resource "azurerm_container_registry" "test" {
                id                            = "/subscriptions/*******/resourceGroups/acctestRG-acr-240223113953509225/providers/Microsoft.ContainerRegistry/registries/testacccr240223113953509225"
                name                          = "testacccr240223113953509225"
                tags                          = {}
                # (16 unchanged attributes hidden)
              ~ georeplications {
                  ~ location                  = "eastus2" -> "westeurope"
                    tags                      = {}
                    # (2 unchanged attributes hidden)
                }
              ~ georeplications {
                  ~ location                  = "westeurope" -> "eastus2"
                  + tags                      = {}
                    # (2 unchanged attributes hidden)
                }
            }
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccContainerRegistry_geoReplication (484.36s)
FAIL
```

**Comment by magodo** [comment]
Hi @catriona-m, this is not an issue introduced by this PR, as if you switch the order of the `ARM_TEST_LOCATION_ALT` and `ARM_TEST_LOCATION_ALT2`, it shall pass.

You can find the details here: https://github.com/hashicorp/terraform-provider-azurerm/issues/17987#issuecomment-1216095257.

**Comment by catriona-m** [comment]
> Hi @catriona-m, this is not an issue introduced by this PR, as if you switch the order of the `ARM_TEST_LOCATION_ALT` and `ARM_TEST_LOCATION_ALT2`, it shall pass.
> 
> You can find the details here: [#17987 (comment)](https://github.com/hashicorp/terraform-provider-azurerm/issues/17987#issuecomment-1216095257).

Thanks for explaining @magodo. Would it make sense to fix those tests as part of this PR?

**Comment by magodo** [comment]
@catriona-m Sure, I've updated the test and verified that both order of the locations pass the test locally.

**Review by stephybun — COMMENTED** [review]
Thanks @magodo. Unfortunately the test is still failing with the same error on Team City. Is there an explanation for that?

**Comment by magodo** [comment]
@stephybun I have no idea... I tried to run it locally and on teamcity, with the same setting as the failing test case, all passed:

image
image

**Review by stephybun — APPROVED** [review]
How odd, thanks for double checking. Thanks @magodo LGTM 👍

**Pull request merged**
