### PR TITLE
Don't remove the revison suffix from the api_id of the API tag

### LINKED ISSUE #24705: terraform always wants to recreate azurerm_api_management_api_tag
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.1

### AzureRM Provider Version

3.89.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api_tag

### Terraform Configuration Files

Hi,

When dealing with `azurerm_api_management_api_tag` terraform always wants to recreate the same item because the suffix  `;rev=10` is being ignored.

Example:

### Debug Output/Panic Output

Output from `tf plan` 

### module.api_management_2[0].azurerm_api_management_api_tag.apim_api_tag[11] must be replaced
```
-/+ resource "azurerm_api_management_api_tag" "apim_api_tag" {
      ~ api_id = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/apim001/apis/atest-2-v7" -> "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/apim001/apis/test-2-v7;rev=10" # forces replacement
      ~ id     = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/apim001/apis/test-2-v7/tags/test2" -> (known after apply)
        name   = "test2"
    }
```

After applying, the same change is still present when issuing a new plan.

Output from `tf state` for this resource:

### module.api_management_2[0].azurerm_api_management_api_tag.apim_api_tag[11]:
```
resource "azurerm_api_management_api_tag" "apim_api_tag" {
    api_id = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/apim001/apis/test-2-v7"
    id     = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/apim001/apis/test-2-v7/tags/test2"
    name   = "test2"
}

```

We can see that the suffix `;rev=10` is missing in the state.

### Expected Behaviour

The API tag should not be identified as a change because it's already present.

### Actual Behaviour

The API tag is always recreated.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by alexwiese**
This fixes #24705 by removing the code that stripped the API ID of the `;rev=XYZ` revision segment in the ID. This was causing the API tag to be recreated on each run, even if the tag did not change.

### CODE REVIEW

**Comment by alexwiese** [comment]
@katbyte thoughts?

**Comment by alexwiese** [comment]
/cc @mbfrahry 
This fixes one of the issues introduced by #23031

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @alexwiese. Apologies it's taken a while to get a review done.

While the proposed changes would fix the management of this resource for newly created `azurerm_api_management_api_tag` resources, it would break existing resources since we're changing the resource ID format. This would require a state migration for this resource as well as the `azurerm_api_management_api_tag_description` resource which relies on the API tag resource ID.

Although I'm not extremely familiar with the APIM service, having poked around in the portal and finding that an API tag appears to be applicable only to an APIM API and not an APIM API _revision_, I think we can fix this by simply adding a `DiffSuppressFunc` to the `api_id` field instead of changing the resource ID format.

Would you be able to look into that and also add a note in the docs on this particularity?

**Comment by alexwiese** [comment]
Hey @stephybun 

> Although I'm not extremely familiar with the APIM service, having poked around in the portal and finding that an API tag appears to be applicable only to an APIM API and not an APIM API revision

This isn’t correct. You can have different tags for different revisions. See below from the portal showing revision 2 and revision 3 having different tags:

image

image


Additionally that was a core part of my testing (making sure I could apply different tags to different revisions of an API using terraform). 

In that case will we need to do a state migration?

I based my code off of the code in #23031 which is the PR that introduced the issue. In that PR the author changed the ID of the api_management_api_release resource as well, without doing a state migration. Migration was only done for api_management_api resource. Was that done incorrectly, or was that acceptable in that case?

**Comment by stephybun** [comment]
Thanks for the additional info @alexwiese. 

You're right, I can assign tags to a specific revision in the portal after changing which revision is the current one. However the REST API doesn't appear to support this behaviour. Updating the tag ID to include the revision results in an API error regardless of whether it is current or not.

Here is the REST call:
```
$ az rest -u "https://management.azure.com/subscriptions/*********/resourceGroups/acctest/providers/Microsoft.ApiManagement/service/acctestAM-sw/apis/acctestapi;rev=1/tags/acctest-tag-gmatbaeyh?api-version=2022-08-01"

Not Found({"error":{"code":"ResourceNotFound","message":"Tag not found.","details":null}})
```

Looking at the swagger spec for the APIM API Tags resource the endpoints don't indicate that tags can be set on a revision, [the example doesn't include a revision in the API Id segment of the request](https://github.com/Azure/azure-rest-api-specs/blob/e6a20fec72ed3bcb4b43c559ee20b56ca2786ec0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/examples/ApiManagementCreateApiTag.json#L7). Whereas the APIM API resource which supports creation of revisions, does have an accompanying [example](https://github.com/Azure/azure-rest-api-specs/blob/e6a20fec72ed3bcb4b43c559ee20b56ca2786ec0/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/examples/ApiManagementCreateApiRevisionFromExistingApi.json#L7).

The Portal appears to be setting tags on revisions by setting the `isCurrent` property on the APIM API resource before creating the tag. Supporting the notion of whether something is current or not for another resource to depend on isn't something that we can support in the provider.

My suggestion at this point would be to raise a feature request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) to have the API extended to allow tags to be set on a revision without needing it to be current. In the meantime, in order to make this resource somewhat more usable we can add the `DiffSuppress` to prevent Terraform from trying to repeatedly recreate the resource. WDYT?

**Comment by stephybun** [comment]
Thanks for the input and clarification @alexwiese!

You're right, I can apply a tag to a revision in the portal after switching which revision is current. I also unfortunately had an error in my test config when verifying whether the API supports the behaviour of tagging a revision, so apologies for the false statement.

I was hesitant to suggest a state migration to fix the issue since I wasn't sure whether it actually would. Having looked further into it I think it will not be able to resolve the problem. 

The state migration would be updating the ID of the tag to include the revision, but a caveat of state migrations is that they only have access to what is already in state and do not have access to information provided in a user's configuration. The APIM API Tag resource strips that information before setting it in to state, so it is effectively just gone and we're unable to reconstruct the correct ID for the tag in the state migration.

I can think of 2 options on how we can proceed here:

1. Make this a breaking change for 4.0. This does mean that all API Tags will have to be recreated when this comes into effect. I'm not sure how disruptive that would be since I don't know what behaviour the tags control for an API.
2. Since the APIM API resource now supports revisions, we could in-line the tags that apply to a revision in the resource itself and deprecate+remove `azurerm_api_management_api_tag` in 4.0.

Let me know your thoughts or concerns on the suggestions.

**Comment by sven5** [comment]
@stephybun  when will this be merged?

**Comment by stephybun** [comment]
@sven5, this cannot be merged as is. 

I've provided some options on how we could proceed in my [last comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/25168#issuecomment-2078697263) but am yet to receive a response. You're welcome to weigh in on the discussion.

**Comment by alexwiese** [comment]
Apologies for the delay @stephybun 
I think we should go with option 1. 
API tags depend on a seperate resource existing (the azurerm_api_management_tag resource) as well as the API itself;  it’s easier to reason about the dependency graph if those are explicitly declared as individual resources IMO. It’s also going to be a less disruptive change to leave it as its own resource. 
 
The impact of recreating the API tag is extremely low, it’s a very lightweight resource (effectively just the assignment of a tag to an API). In my testing recreation of the tags takes a few hundred milliseconds. The tags are used for filtering of APIs on the developer portal, the azure portal, and via the management APIs. The only impact would be if one of these queries was performed during the very small window that the tag was not assigned to the API then that API would not be returned in the list of results. 

If you’re happy with this approach please let me know what needs to be done to include this in 4.0.

**Review by stephybun — CHANGES_REQUESTED** [review]
No worries @alexwiese. Appreciate your perspective and input on this!

We basically just need to wrap the changes you've suggested using the `features.FourPointOh()` flag. I can't leave code suggestions on lines that have been deleted or unmodified so I left code snippet suggestions as comments in-line.

We can merge this once that's done and the API tags will be recreated with the new resource ID when 4.0 is released!

**Review by stephybun — APPROVED** [review]
Thanks @alexwiese LGTM 👍

**Pull request merged**
