### PR TITLE
[TestCase] `azurerm_bot_channel_direct_line_speech` - fix acctest

### PR DESCRIPTION
**Pull request by neil-yechenwei**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
Recently test cases related with Bot Channel Direct Line Speech failed on Teamcity Daily Run. After I checked, I noticed that TF complains that the target resource under test cannot be found when this target resource under test isn't defined in the config of the test steps as prerequisite.

Note: As service team confirmed that it needs to wait a moment until cognitive account is ready and then create direct line speech channel after cognitive account is created, so waiting logic is still needed in the test case. And service team mentioned that user wouldn't immediately create Bot Channel Direct Line Speech after Cognitive Account is created as real business scenario.

Error Message:
```
=== CONT  TestAccBotChannelDirectLineSpeech_update
    testcase.go:173: Step 1/8 error: Pre-apply plan check(s) failed:
        azurerm_bot_channel_direct_line_speech.test - Resource not found in plan ResourceChanges
--- FAIL: TestAccBotChannelDirectLineSpeech_update (13.00s)
```

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [x] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

image

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* [TestCase] `azurerm_bot_channel_direct_line_speech` - fix acctest

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
the sleep is indicative of a bug in the cognitive resource. we should not have to wait for it to be ready because it should only finish creating whenn the resource is ready.

instead can we add logic into the account resource that polls the API and doens't return from creation until the resource is ready?

**Comment by neil-yechenwei** [comment]
@katbyte , Service team confirmed that there is no property/flag in the cognitive account to indicate that the additional configuration is fully completed, so we have to use the sleep to wait.

**Comment by katbyte** [comment]
@neil-yechenwei  regardless having a sleep in configs is not acceptable, the parent resource needs to be completely done and ready to use when the resources finishes so the fix needs to be done there, not in the dependant resource and certainly nor via terraform like this. 

Regardless of if this is presumed to be a typical use case or not this will affect anyone standing up a cognitive account and a direct channel with terraform so it needs to be fixed correctly.

If is no property/provisioning state 1st could we pelase open an issue on the rest specs calling it out that the resource is returning before it is completed/ready to use, and two is there any .get or other API calls that will fail/behave different between not ready and ready?

**Comment by neil-yechenwei** [comment]
@katbyte , the issue https://github.com/Azure/azure-rest-api-specs/issues/21242 is filed. In the meanwhile, I will close this PR.

**Pull request closed without merging**
