### PR TITLE
remove resource_discovery_mode attribute

### LINKED ISSUE #17007: Evaluating compliance before remediation is only supported for remediations at subscription scope and below
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_remediation

### Terraform Configuration Files

```hcl
resource "azurerm_management_group" "example" {
  display_name = "Example Management Group"
}

data "azurerm_policy_definition" "example" {
  display_name = "Allowed locations"
}

resource "azurerm_management_group_policy_assignment" "example" {
  name                 = "exampleAssignment"
  management_group_id  = azurerm_management_group.example.id
  policy_definition_id = data.azurerm_policy_definition.example.id
  parameters = jsonencode({
    "listOfAllowedLocations" = {
      "value" = ["East US"]
    }
  })
}

resource "azurerm_management_group_policy_remediation" "example" {
  name                    = "exampleRemediation"
  management_group_id     = azurerm_management_group.example.id
  policy_assignment_id    = azurerm_management_group_policy_assignment.example.id
  resource_discovery_mode = "ReEvaluateCompliance"
}
```

### Debug Output/Panic Output

```shell
policyinsights.RemediationsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidCreateRemediationRequest" Message="The request to create remediation 'c92d3bc8-0677-4b77-99e1-ff8129b55636' is invalid. Evaluating compliance before remediation is only supported for remediations at subscription scope and below. The requested scope was '/providers/Microsoft.Management/managementGroups/policy_dev'."
```

### Expected Behaviour

This is the expected behaviour as compliance as part of remediation is not supported at the MG level, so should be removed from the resource accepted arguments.

### Steps to Reproduce

1. terraform apply

### References

[See: compliance as part of remediation is not supported at the MG level.](https://github.com/Azure/azure-powershell/issues/10891)

### PR DESCRIPTION
**Pull request by gettek**
fixes #17007

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @gettek - however we cannot just remove this property, it will need to be deprecated and put behind the 4.0 beta flag (which will remove it from schema). an example of that can be found here: https://github.com/hashicorp/terraform-provider-azurerm/blob/b1c3975546219fb9366cdd4c0838c4250b4e9d41/internal/services/bot/bot_channels_registration_resource.go#L152

**Comment by gettek** [comment]
Thanks @katbyte, have added the appropriate fixes and messages

**Comment by gettek** [comment]
@katbyte any updates on this please?

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @gettek - could we fix up the CI here? thanks!

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @gettek - LGTM and good to merge once merge conflicts are resolved ♻️

**Review by katbyte — APPROVED** [review]

**Comment by gettek** [comment]
@katbyte sorry had bit of a merge madness hence all the labels, hope we can approve this soon as to avoid more conflicts!
Thanks

**Review by katbyte — APPROVED** [review]
no bother! thanks for fixing that @gettek - LGTM and merging soon as GHAs are done 🔒

**Pull request merged**
