### PR TITLE
Update eventhub_resource.go

### PR DESCRIPTION
**Pull request by unique-dominik**
AFAICS this is needed and also stated somehow here https://github.com/hashicorp/terraform-provider-azurerm/issues/2049 but was never actually done.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hey @unique-dominik 

Thanks for this PR - sorry to ask so soon after opening, but would you mind rebasing this PR on top of `main`?

We've been trying to diagnose an issue with Github Actions that necessitated breaking the `main` branch temporarily (since fixed), and unfortunately this PR got opened in the few minutes between [intentionally] breaking `main` (#20479) and merging the PR to fix it (#20481) - hence the error message above (which is a false-positive) - in order to fix this, this PR will need to be rebased on top of `main` - but once that's done we should be able to take a look here, apologies for any inconvenience.

Thanks!

**Comment by unique-dominik** [comment]
> hey @unique-dominik
> 
> Thanks for this PR - sorry to ask so soon after opening, but would you mind rebasing this PR on top of `main`?
> 
> We've been trying to diagnose an issue with Github Actions that necessitated breaking the `main` branch temporarily (since fixed), and unfortunately this PR got opened in the few minutes between [intentionally] breaking `main` (#20479) and merging the PR to fix it (#20481) - hence the error message above (which is a false-positive) - in order to fix this, this PR will need to be rebased on top of `main` - but once that's done we should be able to take a look here, apologies for any inconvenience.
> 
> Thanks!

Sure no worries, ping me when to rebase 👍

**Comment by tombuildsstuff** [comment]
@unique-dominik `main` is fixed, so whenever works for you - thanks for the understanding 😅

**Comment by unique-dominik** [comment]
@tombuildsstuff I did "sync" with the GH UI. It is up to date even though not rebased yet.

**Review by katbyte — APPROVED** [review]
LGTM 🌤️

**Pull request merged**
