### PR TITLE
Provider - Add the missing `suppress.CaseDifference` for case-insensitive string properties

### LINKED ISSUE #15173: azurerm_storage_account allows Storagev2 as valid option then forces replacement on subsequent apply
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Tested using the following versions:

```bash
Terraform v1.1.0
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

and:

```bash
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.94.0"
    }
    random = {
      source = "hashicorp/random"
    }
  }
  required_version = ">= 1.0"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "rg-test"
  location = "uksouth"
}

resource "random_string" "test" {
  length  = 8
  special = false
  upper   = false
}

resource "azurerm_storage_account" "test" {
  name                     = "test${random_string.test.result}"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "Storage"
}
```

### Expected Behaviour

Changing `account_kind` from `Storage` to `Storagev2` (note the lowercase `v`) should fail as the valid option is `StorageV2` (capital `V`)

### Actual Behaviour

Changing `account_kind` to `Storagev2` is allowed and shows the initial plan as an in-place update:

```hcl
  # azurerm_storage_account.test will be updated in-place
  ~ resource "azurerm_storage_account" "test" {
      ~ account_kind = "Storage" -> "Storagev2"
```

However, subsequent plans show a forced replacement, even when the config hasn't changed:

```hcl
  # azurerm_storage_account.test must be replaced
-/+ resource "azurerm_storage_account" "test" {
      ~ access_tier  = "Hot" -> (known after apply)
      ~ account_kind = "StorageV2" -> "Storagev2" # forces replacement
  ...
```

If the above plan was applied then all data within the storage account would be lost; a huge impact :(

It seems the validation is not case-sensitive.

### Steps to Reproduce

1. `terraform apply`
1. Change `account_kind` from `Storage` to `Storagev2` (lowercase `v`)
1. `terraform apply` and note the in-place upgrade
1. `terraform apply` again (without making any changes) and note `forces replacement` is shown in the plan

### PR DESCRIPTION
**Pull request by magodo**
For string properties whose `ValidateFunc` is set to `validation.StringInSlice` with **case-insensitive** flag set to `true`, ensure it comes with the `DiffSuppressFunc: suppress.CaseDifference` or the alike.

With the help of `gogrep` (`gogrep -x '$_: {$*_, Type: pluginsdk.TypeString, $*_}' -g 'validation.StringInSlice($_, true)' -v 'suppress.CaseDifference' ./...`), I've complemented all the properties that are not met.

PS: I assume either `StateFunc: state.IgnoreCase` or `DiffSuppressFunc:
 uppress.CaseDifference` does the trick. So I didn't add up for the `StateFunc`.

Fixes #15173

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hey @magodo 

Thanks for this PR.

Whilst this is one approach to solve this issue, unfortunately this is actually a slightly different bug insofar as these fields should be case-sensitive instead of case-insensitive (and have incorrectly been marked as `true` instead of `false` here). As such would you mind invert this PR, by removing the DiffSuppressFunc and making these case-sensitive instead so that we can fix this and flag these at validation time, which should fix #15173?

Thanks!

**Comment by magodo** [comment]
@tombuildsstuff I'm not sure whether it is totally fine to make all of them to be case-sensitiv. E.g. [some of them](https://github.com/hashicorp/terraform-provider-azurerm/blob/d37dacdbbb518b2832985320d036864623dc3357/internal/services/blueprints/blueprint.go#L34) are marked as case-insensitive for walking around service issues? Also, it might breaks some users' existing configurations?

**Comment by tombuildsstuff** [comment]
@magodo Identity is being reworked to make it consistent (see #15187) - so those will be fixed as a part of that, if there's others we should look into normalizing those too fwiw?

**Comment by magodo** [comment]
@tombuildsstuff Thank you for mentioning the identity issue, that makes a lot of sense. While for the other properties, we are still not sure whether it is safe to make them case sensitive for the same reason. This PR is to complement the in correct case-insensitive usages, about whether to make some of them to be case-sensitive, how about we open another issue/PR for that?

**Comment by katbyte** [comment]
@magodo - all enums should be case sensitive and only when its absolutely required to work around a bug should we be ignoring case, and there should be a linked issue documenting it somewhere on the rest specs. also in those cases we can just change the casing on read to match what the enums are if the service refuses to respect the enum casing while still enforcing the correct case in terraform.

**Comment by magodo** [comment]
@katbyte I absolutely agree that we should always allow users to specify enum in case sensitive manner, unless there is a necessary need to work around something. While this PR is not for this purpose, it just make sure thoese **already** marked as case insensitive (no matter on purpose or not) enums are really acting as case insensitively, i.e. apply with uppercase previously and then change it to lowercase won't cause a diff. This is accomplished by adding the suppression.

In order to identify which case insensitve enums are not necessary is another topic, from my opinion, it should be done case by case, with some decent test to verify. Also, doing that change might break some existing configs users are using. So I'd suggest to make it in another PR(s). WDYT?

**Comment by katbyte** [comment]
At this point so close to 3.0 i suggest we do the opposite, remove the case insensitive bool on validation with a 3.0 flag and make the move towards can sensitivity. this is a large pr to fix a single issue with storagev2

**Comment by magodo** [comment]
@katbyte I've refined the PR to modify all the places listed by `gogrep -x 'validation.StringInSlice($_, true)' ./internal/...` with following changes:

- If the enums has non-alphabetic only (e.g. number only), change the `true` to `false` in the `validation.StringInSlice()`
- Otherwise, change the `true` to `!features.ThreePointOh()`
- Change the `DiffSuppressFunc` to `suppress.CaseDifferenceV2Only`, which only take effect if `!features.ThreePointOh()`
- Remove the `StateFunc: state.IgnoreCase` if exists. As it doesn't contribute a lot when we want case insensitive, and will bring problems if we want case sensitive in v3.0, as it will always lowercase the string when persists in state.

As discussed offline, some of the enums listed in the `validation.StringInSlice` are hardcoded - rather than using SDK const. For this case, we regard those hardcoded values are of correct casing.

Also, we can expect some of these schemas will be reverted back to be case insensitive in case the backend API has case problems. In that case, we will want a PR to do the revert (either via resetting them to be case insensitive, or do the casing conversion during flatten), together with a Swagger issue to track the issue.

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @magodo - now just need to fix up the merge conflicts and runt ests to check case

**Comment by magodo** [comment]
@katbyte I've resolved the conflicts now. Now the output of `gogrep -x 'validation.StringInSlice($_, !features.ThreePointOh())' -p 2 -v 'DiffSuppressFunc: suppress.CaseDifferenceV2Only' ./internal/...` only shows 7 locations, where each of them is verified.

**Review by katbyte — APPROVED** [review]
Thanks @magodo - LGTM 🏗️

**Pull request merged**
