### PR TITLE
Connections object needs to be treated differently

### PR DESCRIPTION
**Pull request by DavidTanner**
When the `$connections` parameter is added the API connection for Service Bus Receive don't work.  This is the only change I needed to make to fix permissions in the Azure portal to get them working.  I'm not sure if this is the best route, but it is the first I came up with.  Type is not a required parameter in the Go SDK, but is being required by this function in the Terraform Provider. 

I have filed an issue with Azure support, but don't have high hopes that the issue will be fixed on that side.

Other possible solutions:

- Add flag that could specify not to add the Type attribute
- Add a parameter that silently specifies the type, but is not sent to the API

### CODE REVIEW

**Comment by DavidTanner** [comment]
Another option would be not to require workflow_parameters, as this doesn't need to exist in both Parameters location.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @DavidTanner but it looks like this change is causing the test to fail
```
------- Stdout: -------
=== RUN   TestAccLogicAppWorkflow_parameters
=== PAUSE TestAccLogicAppWorkflow_parameters
=== CONT  TestAccLogicAppWorkflow_parameters
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        Error: [ERROR] Error creating Logic App Workflow Workflow (Subscription: "*******"
        Resource Group Name: "acctestRG-logic-231211154725586017"
        Workflow Name: "acctestlaw-231211154725586017"): unexpected status 403 with error: LinkedAuthorizationFailed: The client has permission to perform action 'Microsoft.Web/connections/join/action' on scope '/subscriptions/*******/resourceGroups/acctestRG-logic-231211154725586017/providers/Microsoft.Logic/workflows/acctestlaw-231211154725586017', however the linked subscription 'xxx' was not found.
          with azurerm_logic_app_workflow.test,
          on terraform_plugin_test.tf line 26, in resource "azurerm_logic_app_workflow" "test":
          26: resource "azurerm_logic_app_workflow" "test" {
--- FAIL: TestAccLogicAppWorkflow_parameters (121.06s)
FAIL
```

**Comment by DavidTanner** [comment]
@stephybun the tests are passing in the github actions.  Is there a way for me to see the failing tests?

**Comment by stephybun** [comment]
@DavidTanner the tests that are run in GHA are the unit tests in the provider. The acceptance tests for the service/resource in question are run on a private Team City instance. 

You should be able to reproduce and debug the test failure by running the `TestAccLogicAppWorkflow_parameters` test locally, just be aware that it will incur costs in your Azure subscription.

**Pull request merged**
