### PR TITLE
set TransactionOptimizedAccessTier to default

### LINKED ISSUE #17622: azurerm_storage_share no default access_tier set
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azuretest"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "azureteststorage"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "example" {
  name                 = "sharename"
  storage_account_name = azurerm_storage_account.example.name
  quota                = 50

  acl {
    id = "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI"

    access_policy {
      permissions = "rwdl"
      start       = "2019-07-02T09:38:21.0000000Z"
      expiry      = "2019-07-02T10:38:21.0000000Z"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_storage_share.example will be updated in-place
  ~ resource "azurerm_storage_share" "example" {
      - access_tier          = "TransactionOptimized" -> null
        id                   = "https://azureteststorage.file.core.windows.net/sharename"
        name                 = "sharename"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

`TransactionOptimized` should not be set back to null because `TransactionOptimized` is the default access tier according to [the documentation](https://docs.microsoft.com/en-us/azure/storage/files/storage-how-to-create-file-share?tabs=azure-portal#create-a-file-share)

### Actual Behaviour

The default access_tier of `TransactionOptimized` is set to null on every plan/apply

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by IanMoroney**
Fixes #17622

### CODE REVIEW

**Comment by IanMoroney** [comment]
@katbyte or @tombuildsstuff, would someone mind reviewing this? it's just a small quality of life fix, and it means the plan will show no changes, which is less confusing for people 👍

**Comment by IanMoroney** [comment]
@WodansSon , or @tombuildsstuff , is there someone that could review and approve this PR?

**Comment by IanMoroney** [comment]
@tombuildsstuff , I don't have permission to request reviewers, but this small fix has been pending for a month :( 
Would someone be able to review?

**Review by katbyte — CHANGES_REQUESTED** [review]
Hi @IanMoroney - thanks for the PR,

This could end up being a breaking change for users who currently do not have a value yet set there and rely on computed, that said this seems like a bug as if that is the default, should the service not be returning that value instead of nil? or is it returning nil if the default has not been changed? this seems like a bug on the services side.

if so could you open an issue on the rest api specs and drop a link here?

these lines of code may have to be modified to work around that:
```
accessTier := ""
	if props.AccessTier != nil {
		accessTier = string(*props.AccessTier)
	}
	d.Set("access_tier", accessTier)
```

**Comment by IanMoroney** [comment]
@katbyte , this PR is already linked to an issue which outlines the details here:
https://github.com/hashicorp/terraform-provider-azurerm/issues/17622

**Comment by katbyte** [comment]
@IanMoroney - what i'm saying is that if the property is computed it should be saved back into state if the API is returning it, default should not be required. So is the API returning TransactionOptimized ? 

we generally shouldn't be changing defaults like this outside a major version as some users might de relying on the behaviour, so i think we need to figure out why computed doesn't seem to be working and work around that

**Comment by IanMoroney** [comment]
Yes, `TransactionOptimized` is now the default coming back from the API.

**Comment by mbfrahry** [comment]
Hi @IanMoroney, I've done a little digging and unfortunately we can't accept this change. 

If a storage account has an `account_tier` of `Premium`, any storage share created from that storage account has a defaulted `access_tier` of `Premium` as well. This change would be a breaking change for any person using `Premium`. 

I unfortunately can't replicate your issue either. It has been some time since you've submitted that issue and I'd like to confirm you're still experiencing it. 

I'm going to close this PR down since it's not something we can accept without breaking people so let's move your issue discussion back to https://github.com/hashicorp/terraform-provider-azurerm/issues/17622

**Pull request closed without merging**
