### PR TITLE
#24103 : Support sku_tier argument as part of azurerm_spring_cloud_service

### LINKED ISSUE #24103: Support for azurerm_spring_cloud_service tier=StandardGen2
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Please allow resource to support new StandardGen2 tier = pay-as you go.
This will require either new SKUs or adding a new "tier" attribute, due to Azure using the same naming as the old Standard "S0":

`    "sku": {
      "capacity": null,
      "name": "S0",
      "tier": "StandardGen2"
    },`

Also, this will require a reference to container-environments by id. Therefore this change should be simple to integrate.

### New or Affected Resource(s)/Data Source(s)

azurerm_spring_cloud_service

### Potential Terraform Configuration

```hcl
resource "azurerm_spring_cloud_service" "service" {
  name                = var.service_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku_name            = var.sku
  tier                = "StandardGen2"
  container_environment_id = var.container_environment_id
}
```

### References

_No response_

### PR DESCRIPTION
**Pull request by harshavmb**
Support `sku_tier` argument as part of `azurerm_spring_cloud_service` resource.

Fixes #24103

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the pr @harshavmb - looks like we have a test failure thou:

```
------- Stdout: -------
=== RUN   TestAccSpringCloudService_containerRegistry
=== PAUSE TestAccSpringCloudService_containerRegistry
=== CONT  TestAccSpringCloudService_containerRegistry
    testcase.go:113: Step 1/4 error: Error running apply: exit status 1
        
        Error: creating Spring Cloud Service: (Spring Name "acctest-sc-231206075149083916" / Resource Group "acctestRG-spring-231206075149083916"): appplatform.ServicesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadArgument" Message="Invalid arguments: The field Name is invalid." Details=[{"code":"BadArgument","details":null,"message":"The field Name is invalid.","target":"Sku.Name"},{"code":"BadArgument","details":null,"message":"The field Tier is invalid.","target":"Sku.Tier"}]
        
          with azurerm_spring_cloud_service.test,
          on terraform_plugin_test.tf line 42, in resource "azurerm_spring_cloud_service" "test":
          42: resource "azurerm_spring_cloud_service" "test" {
        
--- FAIL: TestAccSpringCloudService_containerRegistry (132.11s)
```

**Comment by harshavmb** [comment]
Hi @katbyte ,

I see the reason for test failure is not setting `sku_tier` to `Enterprise` for `E0`. It is defaulted to `Standard` & the same is passed to API. The test case could be fixed by explicitly adding this argument but that would break & force the existing users to specify it for non `Standard` sku tiers. 

I'll try to embed some logic to add it only when `sku_tier` is passed by end users in tandem with `sku_name`.

**Comment by harshavmb** [comment]
Hi @dgensert ,

Indeed it was an oversight. I'll try adding `container_environment_id` & setting `sku_tier` accordingly.

**Review by katbyte — APPROVED** [review]
Nope just delayed due to the holidays, looks good not! thanks 🧮

**Pull request merged**
