### PR TITLE
Corrects diff supression for linked storage accounts

### PR DESCRIPTION
**Pull request by Nepomuceno**
Just adding diff supression.
Fix for #18546

### CODE REVIEW

**Comment by katbyte** [comment]
I think this will be fixed by #18547?

**Comment by Nepomuceno** [comment]
I dont get this pr it is the #18547 no ?

**Comment by katbyte** [comment]
whoops, sorry bad copy paste: #18116

**Comment by katbyte** [comment]
on main this line is now added when not in 4.0 beta:
image

**Comment by Nepomuceno** [comment]
Makes sense! It was not there yesterday :) 
after rebase I am having errors but it is probably related to #18556 
will close this one and also add the link to the pr that fixed it in the issue.
By the way didn't know that you could add properties to the schema this way, it is interesssing but I found it a bit harder to read.

**Comment by katbyte** [comment]
@Nepomuceno - we try not to but it is the easiest way to handle the 4.0 flag so when we release 4.0 we just have to flip the flag and can slowly remove the old code over time

**Pull request closed without merging**
