### PR TITLE
`azurerm_linux_function_app` and `azurerm_linux_function_app_slot` remove `RequiredWith` constraints on app insights settings

### LINKED ISSUE #16077: azurerm_linux_function_app requires both connection string and instrumentation key for app insights
Function Apps only require the instrumentation key to connect to Application Insights. There is no need to provide both a connection string and an instrumentation key.

│ Error: Missing required argument
│ 
│   with azurerm_linux_function_app
│   application_insights_key = var.app_insights_instrumentation_key
│ 
│ "site_config.0.application_insights_key": all of
│ `site_config.0.application_insights_connection_string,site_config.0.application_insights_key`
│ must be specified

### PR DESCRIPTION
**Pull request by jackofallops**
resolves #16077

### CODE REVIEW

**Comment by tiagoboeing** [comment]
Will this fix enter on the next release?

**Comment by jackofallops** [comment]
> Will this fix enter on the next release?

HI @tiagoboeing - This will ship in the v3.1.0 release, yes.

**Comment by tiagoboeing** [comment]
> > Will this fix enter on the next release?
> 
> HI @tiagoboeing - This will ship in the v3.1.0 release, yes.

@jackofallops exist a way to install a version appointing to this snapshot? I'm having this issue linking my function app with the application insights resource created.

**Comment by enorlando** [comment]
Hi @jackofallops 
We are getting a similar issue with the `azurerm_windows_function_app` resource where setting the argument `application_insights_connection_string` under the site_config` block causes the following error

│ Error: Missing required argument
│ 
│   with azurerm_windows_function_app.xxx,
│   on xxx.tf line 75, in resource "azurerm_windows_function_app" "xxx":
│   75:     application_insights_connection_string = azurerm_application_insights.xxx.connection_string
│ 
│ "site_config.0.application_insights_connection_string": all of `site_config.0.application_insights_connection_string,site_config.0.application_insights_key` must be specified

Will this fix this issue too?

**Comment by tiagoboeing** [comment]
@enorlando see this https://github.com/hashicorp/terraform-provider-azurerm/issues/16077#issuecomment-1091831840

**Comment by enorlando** [comment]
@tiagoboeing Thank you very much. Adding both `application_insights_key` and `application_insights_connection_string` uner the `site_config` block fixed the issue

**Pull request merged**
