### PR TITLE
Adding ipSecurityRestrictionsDefaultAction and scmIpSecurityRestrictionsDefaultAction to SiteConfig

### LINKED ISSUE #22593: Support for ipSecurityRestrictions within linux_web_app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The resource Microsoft.Web/sites (represented in Terraform by `linux_web_app` or `windows_web_app`) has a property called `siteConfig.ipSecurityRestrictionsDefaultAction` which gets used to configure the resource's access restrictions default behavior if no access rule matches.

Even though the Azure Portal and the Azure CLI are using this property in their API requests, it has not been documented in the API specifications (see issue https://github.com/Azure/azure-rest-api-specs/issues/24215), and I guess this is why it is missing in Terraform.

Same for the property `siteConfig.scmIpSecurityRestrictionsDefaultAction` (rules for the Web App's "Advanced tool site").

### New or Affected Resource(s)/Data Source(s)

linux_web_app, windows_web_app

### Potential Terraform Configuration

```hcl
The Terraform resource could looke like this:

resource "azurerm_linux_web_app" "example" {
  public_network_access_enabled = true

  site_config {
    ip_restrictions_default_action = "Deny"

    ip_restriction {
      name       = "example rule"
      action     = "Allow"
      priority   = 100
      ip_address = "1.1.1.1/32"
    }
  }
}
```

### References

- https://github.com/Azure/azure-rest-api-specs/issues/24215

### PR DESCRIPTION
**Pull request by TrueSvenpai**
Both ipSecurityRestrictionsDefaultAction and scmIpSecurityRestrictionsDefaultAction were not configurable and had to be updated via azapi. 
To overcome this workaround this PR adds ipSecurityRestrictionsDefaultAction and scmIpSecurityRestrictionsDefaultAction to the SiteConfig and fixes #22593 

**UPDATE**: Adjusted property naming, adopting from #24519 

Partially duplicate of PR #24519 as they are sending the attributes differently during updates and this PR (#24464) doesn't cover windows yet and misses documentation updates

### CODE REVIEW

**Comment by xiaxyi** [comment]
Thanks @TrueSvenpai for raising this PR, I see you only added the property for Linux web app & slot. I included your code into my pr and covered the feature for windows web app as well. Would you mind taking a look at my pr and feel free to let me know if you have any suggestions about it?

**Comment by TrueSvenpai** [comment]
Thanks @xiaxyi for pointing out, that I missed the windows web apps! I will push them later.
I will have a look at your PR later this day :) 
Happy coding!

**Comment by xiaxyi** [comment]
Thank @TrueSvenpai for the reply! There is another thing that I would like to mention is that we have a naming convention that can be found: https://hashicorp.github.io/terraform-provider-azurerm/topics/reference-naming/, it would be great if you could change the name and the definition of the property in your PR following the guidance as well, you can refer to my PR for some details. Let me know if you have any questions.

**Comment by TrueSvenpai** [comment]
Thank you @xiaxyi. I will update my properties, matching your naming schema (also refering it). 
Thanks again for the collaboration

**Comment by jackofallops** [comment]
Hi @TrueSvenpai 
Thanks for this PR, and for working with @xiaxyi on the changes. There are some conflicts, and the approach needs changing unfortunately. I have opened another PR collecting all supporting resources into the required approach. 

For context, the setting shouldn't be a bool. The `_enabled` pattern is typically for on/off values, where this is an explicit setting for an action to take when rules are not matched. It's possibly a grey area in naming, but I feel it is the correct approach to use the `enum` values here.  

Due to the above, I'm going to close this PR, please follow #25131 for updates as this covers all apps and their respective slots for these 2 properties.

Thanks again!

**Comment by TrueSvenpai** [comment]
Hi @jackofallops,
was a pleasure working with you all! I understand the conflicts and the reason for closing this PR.
Thank you for your work!

**Pull request closed without merging**
