### PR TITLE
Support `v8.0` for the `dotnet_version` to `azurerm_windows_web_app` and `azurerm_linux_web_app`

### LINKED ISSUE #23496: Support dotnet 8.0 in azurerm_linux_web_app
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

dotnet 8 is available for azure webApp, but resource azurerm_linux_web_app expects application_stack.dotnet_version to be one of ["3.1" "5.0" "6.0" "7.0"]

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by shibayan**
.NET 8 has been officially released, I would like to add. Close #23496

### Acctests

```
--- PASS: TestAccLinuxWebApp_withDotNet80 (209.35s)
--- PASS: TestAccLinuxWebAppSlot_withDotNet80 (266.59s)
--- PASS: TestAccWindowsWebApp_withDotNet80 (150.46s)
--- PASS: TestAccWindowsWebAppSlot_withDotNet8 (198.80s)
```

### CODE REVIEW

**Comment by sven5** [comment]
Please also add to `azurerm_linux_function_app`

**Comment by shibayan** [comment]
Support for Azure Functions was not included since another PR (#23638) has already been created.

**Comment by madhusameena** [comment]
Hi, any plan when can we expect the release ?

**Comment by ansehh** [comment]
Please go for this! Waiting for that one! 👍

**Comment by VultureJD** [comment]
Since #23638 has already been merged for Function apps, can we merge this change too? Waiting on this for webapps

**Comment by roycornelissen** [comment]
We're also waiting for this!

**Comment by akudlik** [comment]
Same :)

**Comment by vlasovt** [comment]
Same on our side, we are doing the .NET 8 upgrade and this is blocking us from finishing our job.

**Comment by sven5** [comment]
@jackofallops  Could you please provide a milestone for this change. thanks.

**Comment by borislavml** [comment]
We're also waiting on this 🙏

**Comment by andriikaplanovskyi** [comment]
Any miletstone for this change please? We're waiting for it.

**Comment by gfurtadoalmeida** [comment]
Could this go to milestone v3.83.0?

**Comment by VultureJD** [comment]
Could this be merged please? It's been nearly two weeks since .NET8 released and the web_app provider still doesn't support it. @jackofallops @stephybun Tagging you because you commented/approved the function_app provider update.

**Review by jackofallops — APPROVED** [review]
Thanks @shibayan - This LGTM 👍

**Comment by jackofallops** [comment]
Test look good:

image

**Pull request merged**
