### PR TITLE
managedhsm: introducing dedicated Resource ID Parsers for the Data Plane Versioned and Versionless Key IDs

### PR DESCRIPTION
**Pull request by tombuildsstuff**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

This PR introduces dedicated Resource ID parsers for Managed HSM Data Plane Keys - it _doesn't_ yet refactor the Role Assignments/Definitions to the same pattern since the current Resource IDs differ [from those defined in the API](https://learn.microsoft.com/en-us/rest/api/keyvault/managedhsm-rbac/role-definitions/create-or-update?view=rest-keyvault-managedhsm-rbac-7.4&tabs=HTTP) - but that'll come in a bit.

This PR refactors the Managed HSM package to introduce a consistent set of Resource ID parsers which take into account the Domain Suffix.

Whilst this should be mostly complete, due to a number of issues with the existing resources - this isn’t quite as far as I wanted this to be before I headed out, and the following remains:

1. Adding RequiresImport tests
2. Updating the exists functions
3. Update the documentation to account for `managed_hsm_id` being the new preference rather than `vault_base_url`
4. Update all of the timeouts to 30m
5. Investigate whether we should deprecate `resource_manager_id`?

### CODE REVIEW

**Comment by Botje** [comment]
Hi Tom,

I rebased #25088 on top of this PR and I found two small gaps this PR might want to address too:
1. The Azure APIs return a triple of (base URI, key name, key version) when reading resources.
In order to know whether a given base URI belongs to a key vault or a managed HSM you have to inspect the hostname.
I abstracted that logic into [internal/services/managedhsm/helpers/is_managed_hsm_uri.go](https://github.com/hashicorp/terraform-provider-azurerm/pull/25088/files#diff-7e1648ecacc1db864f200df6ada80aa86d711feb01a1488b4e2dfb58765cdab4)

2. Continuing from the above, reconstituting the HSM key ID from the parts returned by the Azure API requires checking whether the key version is empty or not. That could also be abstracted into a function like `canonicalManagedHSMKeyIdFromParts(keyVaultURI, keyName, keyVersion string).

What do you think?

**Review by katbyte — APPROVED** [review]
LGTM 🥅

**Review by mbfrahry — APPROVED** [review]
LGTM!

**Comment by riemers** [comment]
Think you missed the removal of the scope in the data example here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_managed_hardware_security_module_role_assignment
Also, if i dont have access to the read of the hsm but i do have read admin rights on the key the module now still wants me to have read rights on the hsm itself.

**Comment by manicminer** [comment]
@riemers Could you open a new issue for this so we can track this? Thanks!

**Pull request merged**
