### PR TITLE
SDK: updating `DNS`, `Maps` and `SignalR` to use the new base layer from `hashicorp/go-azure-sdk`

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR updates the Services for `DNS`, `Maps` and `SignalR` to use the new base layer from `hashicorp/go-azure-sdk`, and also updates `hashicorp/go-azure-sdk` to `v0.20230228.1160358`.

Associated changelog:

```
* dependencies: updating to `v0.20230228.1160358` of `github.com/hashicorp/go-azure-sdk` [GH-20688]
* `dns`: refactoring to use `hashicorp/go-azure-sdk` as a base layer rather than `Azure/go-autorest` [GH-20688]
* `maps`: refactoring to use `hashicorp/go-azure-sdk` as a base layer rather than `Azure/go-autorest` [GH-20688]
* `signalr`: refactoring to use `hashicorp/go-azure-sdk` as a base layer rather than `Azure/go-autorest` [GH-20688]
```

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
Dependent on https://github.com/hashicorp/go-azure-sdk/pull/339

**Comment by tombuildsstuff** [comment]
Maps tests pass:

Screenshot 2023-02-28 at 17 59 58

**Review by jackofallops — APPROVED** [review]
Thanks @tombuildsstuff - LGTM 👍

**Comment by tombuildsstuff** [comment]
Request/Response Logging is (intentionally) being added in a follow up PR

**Pull request merged**
