### PR TITLE
azurerm_stream_analytics_output_eventhub - support for property_columns

### PR DESCRIPTION
**Pull request by alex-mozejko**

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the pr @alex-mozejko - overall looks good but could we update the docs with the new property? thanks

**Review by katbyte — APPROVED** [review]
Sure is! thanks @alex-mozejko - LGTM 🏗️

**Comment by katbyte** [comment]
just need to fix ci @alex-mozejko

**Comment by alex-mozejko** [comment]
heya @katbyte, i think the latest changes fixed the ci? please let me know if i should do anything else :)

**Comment by katbyte** [comment]
Yep looks good now! thanks 🙂

**Pull request merged**
