### PR TITLE
update spring sdk to 2022-05-01-preview

### PR DESCRIPTION
**Pull request by ms-henglu**
~~blocked by https://github.com/Azure/azure-rest-api-specs/issues/19328~~

image

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
build failure:
image
image

**Comment by ms-henglu** [comment]
Hi @katbyte - All passed!
image

**Review by katbyte — APPROVED** [review]
Thanks @ms-henglu - LGTM and we just need to fix the merge conflicts 🌵

**Comment by ms-henglu** [comment]
Hi @katbyte - conflicts resolved! Please take a look again.

**Pull request merged**
