### PR TITLE
`service/netapp`: Various additions

### LINKED ISSUE #14357: Support for "ThroughputMibps" argument for Azure Netapp File
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Issue:
Getting error while creating NFS volumes via Terraform. 
### Error:
Code="BadRequest" Message="Missing value for 'ThroughputMibps'"  
```json
waiting for creation of NetApp Volume "example-netappvolume" (Resource Group "example-resources"): Code="BadRequest" Message="Missing value for 'ThroughputMibps'" Details=[{"code":"MissingValue","message":"Missing value for 'ThroughputMibps'"}]
```

### Cause:
"QoS type" for the "Capacity pool" was set to "Manual" (from the portal).

## Requirements:  
- Argument (optional) for value "ThroughputMibps" is required for the scenarios when "QoS type" set as "Manual".
- Also, having an argument to set the "QoS type" for  "Capacity pool" will be helpful.  

## Scenario:  

- Users can get into the scenario where "QoS type" is required to be manual. 
- There is no argument present in terraform to set the "QoS type".
- So user have to change it from portal. 
- Later, user can get a requirement to add new volumes. 
- Since there is no argument in terraform to set the value of ThroughputMibps manually, user will run their code and get the same error mentioned above. 
- User can create new volumes from portal and set the ThroughputMibps manually. 
- However, in terraform there is no argument for "ThroughputMibps".
- If we had an argument to set the value for "ThroughputMibps", user can deploy new volumes in their infrastructure without deleting the "Capacity pool" and "volumes".   

## Affected resource
* azurerm_netapp_volume

### Potential Terraform Configuration

```hcl
resource "azurerm_netapp_pool" "example" {
  name                = "example-netapppool"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  account_name        = azurerm_netapp_account.example.name
  service_level       = "Ultra"
  size_in_tb          = 4
  qos_type            = manual ######## requested argument
}

resource "azurerm_netapp_volume" "example" {
  lifecycle {
    prevent_destroy = false
  }

  name                       = "example2-netappvolume"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  account_name               = azurerm_netapp_account.example.name
  pool_name                  = azurerm_netapp_pool.example.name
  volume_path                = "my-unique-file-path2"
  service_level              = "Ultra"
  subnet_id                  = azurerm_subnet.example.id
  protocols                  = ["NFSv3"]
  security_style             = "Unix"
  storage_quota_in_gb        = 2048
  snapshot_directory_visible = false
  throughput_in_mibps        = 100  ######## requested argument
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/netapp_volume

### PR DESCRIPTION
**Pull request by favoretti**
`r/azurerm_netapp_pool`: Add support for `qos_type` argument
`r/azurerm_netapp_volume`: Add support for `throughput_in_mibps` argument

Fixes #14357

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
have a test failure here:
```
------- Stdout: -------
=== RUN   TestAccNetAppVolume_basic
=== PAUSE TestAccNetAppVolume_basic
=== CONT  TestAccNetAppVolume_basic
    testcase.go:110: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_netapp_volume.test will be updated in-place
          ~ resource "azurerm_netapp_volume" "test" {
                id                         = "/subscriptions/*******/resourceGroups/acctestRG-netapp-211130231522298203/providers/Microsoft.NetApp/netAppAccounts/acctest-NetAppAccount-211130231522298203/capacityPools/acctest-NetAppPool-211130231522298203/volumes/acctest-NetAppVolume-211130231522298203"
                name                       = "acctest-NetAppVolume-211130231522298203"
              - throughput_in_mibps        = 1.6 -> null
                # (12 unchanged attributes hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccNetAppVolume_basic (1719.17s)
FAIL
```

**Comment by favoretti** [comment]
Oh, peculiar. Thanks, will do some local runs.

**Comment by favoretti** [comment]
@katbyte should be fixed now.

**Review by katbyte — APPROVED** [review]
Thanks @favoretti ! LGTM 🚀

**Pull request merged**
