### PR TITLE
`policy_remediation_xxx_resource` - support for the `resource_count`, `parallel_deployments` and `failure_percentage` properties

### PR DESCRIPTION
**Pull request by wuxu92**
add support for `resource_count`, `parallel_deployments` and `failure_percentage`

--- PASS: TestAccAzureRMManagementGroupPolicyRemediation_basic (270.60s)
--- PASS: TestAccAzureRMManagementGroupPolicyRemediation_complete (270.16s)
--- PASS: TestAccAzureRMResourceGroupPolicyRemediation_basic (389.06s)
--- PASS: TestAccAzureRMResourceGroupPolicyRemediation_complete (406.42s)
--- PASS: TestAccAzureRMResourcePolicyRemediation_basic (281.65s)
--- PASS: TestAccAzureRMResourcePolicyRemediation_complete (407.79s)
--- PASS: TestAccAzureRMSubscriptionPolicyRemediation_basic (232.30s)
--- PASS: TestAccAzureRMSubscriptionPolicyRemediation_complete (299.02s)
PASS

Process finished with the exit code 0

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
test failures:
image

**Comment by wuxu92** [comment]
@katbyte TeamCity tests all pass now

**Review by katbyte — CHANGES_REQUESTED** [review]
Policy issue has been resolved but getting actual test failures now
```
------- Stdout: -------
=== RUN   TestAccAzureRMResourcePolicyRemediation_complete
=== PAUSE TestAccAzureRMResourcePolicyRemediation_complete
=== CONT  TestAccAzureRMResourcePolicyRemediation_complete
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating/updating Virtual Network: (Name "acctestvn-jmqqz" / Resource Group "acctest-policy-jmqqz"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource 'acctestvn-jmqqz' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"acctestpa-220809064807723908\",\"id\":\"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-220809064807723908\"},\"policyDefinition\":{\"name\":\"Allowed locations\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\"}}]'." Target="acctestvn-jmqqz" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"location","expressionKind":"Field","expressionValue":"westus2","operator":"NotIn","path":"location","result":"True","targetValue":["eastus2"]},{"expression":"location","expressionKind":"Field","expressionValue":"westus2","operator":"NotEquals","path":"location","result":"True","targetValue":"global"},{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Network/virtualNetworks","operator":"NotEquals","path":"type","result":"True","targetValue":"Microsoft.AzureActiveDirectory/b2cDirectories"}]},"policyAssignmentDisplayName":"","policyAssignmentId":"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-220809064807723908","policyAssignmentName":"acctestpa-220809064807723908","policyAssignmentParameters":{"listOfAllowedLocations":["eastus2"]},"policyAssignmentScope":"/subscriptions/*******","policyDefinitionDisplayName":"Allowed locations","policyDefinitionEffect":"deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c"},"type":"PolicyViolation"}]
        
          with azurerm_virtual_network.test,
          on terraform_plugin_test.tf line 12, in resource "azurerm_virtual_network" "test":
          12: resource "azurerm_virtual_network" "test" {
        
--- FAIL: TestAccAzureRMResourcePolicyRemediation_complete (65.99s)
FAIL
```

**Comment by wuxu92** [comment]
Hi @katbyte I reruned the tests and i believe the root cause of the failure is the parallel running of the test cases and the `TestAccAzureRMResourcePolicyRemediation_basic`'s network creating was blocked by a policy `acctestpa-sub-220811031923028140` which is created by another test case `TestAccAzureRMSubscriptionPolicyRemediation_complete`. I renamed the policy assignment resource name by kind as below:

image


```html
------- Stdout: -------
=== RUN   TestAccAzureRMResourcePolicyRemediation_basic
=== PAUSE TestAccAzureRMResourcePolicyRemediation_basic
=== CONT  TestAccAzureRMResourcePolicyRemediation_basic
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating/updating Virtual Network: (Name "acctestvn-g20gr" / Resource Group "acctest-policy-g20gr"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: 
StatusCode=403 -- Original Error: 
Code="RequestDisallowedByPolicy" Message="Resource 'acctestvn-g20gr' was disallowed by policy. 
Policy identifiers: '[{\"policyAssignment\":{\"name\":\"acctestpa-sub-220811031923028140\",
\"id\":\"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-sub-220811031923028140\"},\"
policyDefinition\":{\"name\":\"Allowed locations\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\"}}]'." Target="acctestvn-g20gr" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"location","expressionKind":"Field","expressionValue":"westus2","operator":"NotIn","path":"location","result":"True","targetValue":["westeurope"]},
{"expression":"location","expressionKind":"Field","expressionValue":"westus2","operator":"NotEquals","path":"location","result":"True","targetValue":"global"},
{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Network/virtualNetworks","operator":"NotEquals","path":"type","result":"True","targetValue":"Microsoft.AzureActiveDirectory/b2cDirectories"}]},"policyAssignmentDisplayName":"","policyAssignmentId":"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-sub-220811031923028140","policyAssignmentName":"acctestpa-sub-220811031923028140","policyAssignmentParameters":
{"listOfAllowedLocations":["westeurope"]},"policyAssignmentScope":"/subscriptions/*******","policyDefinitionDisplayName":"Allowed locations","policyDefinitionEffect":"deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c"},"type":"PolicyViolation"}]
        
          with azurerm_virtual_network.test,
          on terraform_plugin_test.tf line 12, in resource "azurerm_virtual_network" "test":
          12: resource "azurerm_virtual_network" "test" {
        
--- FAIL: TestAccAzureRMResourcePolicyRemediation_basic (63.90s)
FAIL
```

**Review by katbyte — CHANGES_REQUESTED** [review]
i'm still seeing a fialure?
```
------- Stdout: -------
=== RUN   TestAccAzureRMResourcePolicyRemediation_basic
=== PAUSE TestAccAzureRMResourcePolicyRemediation_basic
=== CONT  TestAccAzureRMResourcePolicyRemediation_basic
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating/updating Virtual Network: (Name "acctestvn-2ekph" / Resource Group "acctest-policy-2ekph"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource 'acctestvn-2ekph' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"acctestpa-sub-220823155941064475\",\"id\":\"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-sub-220823155941064475\"},\"policyDefinition\":{\"name\":\"Allowed locations\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\"}},{\"policyAssignment\":{\"name\":\"acctestpa-sub-220823155941158871\",\"id\":\"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-sub-220823155941158871\"},\"policyDefinition\":{\"name\":\"Allowed locations\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c\"}}]'." Target="acctestvn-2ekph" AdditionalInfo=[{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"location","expressionKind":"Field","expressionValue":"eastus2","operator":"NotIn","path":"location","result":"True","targetValue":["westus2"]},{"expression":"location","expressionKind":"Field","expressionValue":"eastus2","operator":"NotEquals","path":"location","result":"True","targetValue":"global"},{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Network/virtualNetworks","operator":"NotEquals","path":"type","result":"True","targetValue":"Microsoft.AzureActiveDirectory/b2cDirectories"}]},"policyAssignmentDisplayName":"","policyAssignmentId":"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-sub-220823155941064475","policyAssignmentName":"acctestpa-sub-220823155941064475","policyAssignmentParameters":{"listOfAllowedLocations":["westus2"]},"policyAssignmentScope":"/subscriptions/*******","policyDefinitionDisplayName":"Allowed locations","policyDefinitionEffect":"deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c"},"type":"PolicyViolation"},{"info":{"evaluationDetails":{"evaluatedExpressions":[{"expression":"location","expressionKind":"Field","expressionValue":"eastus2","operator":"NotIn","path":"location","result":"True","targetValue":["westus2"]},{"expression":"location","expressionKind":"Field","expressionValue":"eastus2","operator":"NotEquals","path":"location","result":"True","targetValue":"global"},{"expression":"type","expressionKind":"Field","expressionValue":"Microsoft.Network/virtualNetworks","operator":"NotEquals","path":"type","result":"True","targetValue":"Microsoft.AzureActiveDirectory/b2cDirectories"}]},"policyAssignmentDisplayName":"","policyAssignmentId":"/subscriptions/*******/providers/Microsoft.Authorization/policyAssignments/acctestpa-sub-220823155941158871","policyAssignmentName":"acctestpa-sub-220823155941158871","policyAssignmentParameters":{"listOfAllowedLocations":["westus2"]},"policyAssignmentScope":"/subscriptions/*******","policyDefinitionDisplayName":"Allowed locations","policyDefinitionEffect":"deny","policyDefinitionId":"/providers/Microsoft.Authorization/policyDefinitions/e56962a6-4747-49cd-b67b-bf8b01975c4c","policyDefinitionName":"e56962a6-4747-49cd-b67b-bf8b01975c4c"},"type":"PolicyViolation"}]
        
          with azurerm_virtual_network.test,
          on terraform_plugin_test.tf line 12, in resource "azurerm_virtual_network" "test":
          12: resource "azurerm_virtual_network" "test" {
        
--- FAIL: TestAccAzureRMResourcePolicyRemediation_basic (134.64s)
FAIL
```

**Comment by wuxu92** [comment]
the error message shows the source reason is the policy assignment of subscription (`azurerm_subscription_policy_assignment`) is not deleted and it blocked the virtual net creation of `TestAccAzureRMResourcePolicyRemediation_basic`.

 I run the single test of `TestAccAzureRMResourcePolicyRemediation_basic` and its success with PASS. I will try to find out if it any possibility that the delete of `azurerm_subscription_policy_assignment` will fail or delay.

image

**Comment by wuxu92** [comment]
Hi @katbyte i realize that we have to add all three locations to the rule of `TestAccAzureRMSubscriptionPolicyRemediation_complete`. then all test shall pass. and sorry that I `push -f` to the source branch (for rebasing origin/main) so have to find the new commit-id in TeamCity manually.

image


image

**Review by katbyte — APPROVED** [review]
Thanks @wuxu92 - LGTM 🎩

**Pull request merged**
