### PR TITLE
`azurerm_mssql_database`: Fix error with OnlineSecondary with auditing on Primary

### LINKED ISSUE #14176: cannot configure `extended_auditing_policy` in secondary create mode
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "managed" {
  name            = var.name
  create_mode     = "Default"
  server_id       = data.azurerm_mssql_server.managed.id
  collation       = var.collation
  max_size_gb     = var.max_size_gb
  sku_name        = var.elasticpool_name == null ? var.sku_name : "ElasticPool"
  read_scale      = var.read_scale
  zone_redundant  = var.zone_redundant
  elastic_pool_id = var.elasticpool_name == null ? null : data.azurerm_mssql_elasticpool.managed[0].id
  tags            = local.tags

  dynamic "short_term_retention_policy" {
    for_each = var.short_term_retention_policy == null ? [] : [var.short_term_retention_policy]
    content {
      retention_days = short_term_retention_policy.value.retention_days
    }
  }

  dynamic "long_term_retention_policy" {
    for_each = var.long_term_retention_policy == null ? [] : [var.long_term_retention_policy]
    content {
      weekly_retention  = long_term_retention_policy.value.weekly_retention
      monthly_retention = long_term_retention_policy.value.monthly_retention
      yearly_retention  = long_term_retention_policy.value.yearly_retention
      week_of_year      = long_term_retention_policy.value.week_of_year
    }
  }
}

resource "azurerm_mssql_database" "managed_secondary" {
  count                       = local.secondary ? 1 : 0
  name                        = var.name
  create_mode                 = "OnlineSecondary"
  creation_source_database_id = azurerm_mssql_database.managed.id
  server_id                   = data.azurerm_mssql_server.managed_secondary[0].id
  collation                   = var.collation
  sku_name                    = var.elasticpool_name == null ? var.sku_name : "ElasticPool"
  read_scale                  = var.read_scale
  zone_redundant              = false
  elastic_pool_id             = var.elasticpool_name == null ? null : data.azurerm_mssql_elasticpool.managed_secondary[0].id
  tags                        = local.tags
}

resource "azurerm_mssql_database_extended_auditing_policy" "managed" {
  database_id            = azurerm_mssql_database.managed.id
  log_monitoring_enabled = true
}

```
### Actual Behaviour

Running `terraform apply` creates both databases successfully, but subsequent applies to change a property results in an error:

```
│ Error: cannot configure `extended_auditing_policy` in secondary create mode for Database: (Name "failover" / Server Name "oeeeo-ukwest" / Resource Group "terraform-managed-database-fixturesoeeeo-sql-ukwest")
```

### Steps to Reproduce

- terraform apply
- change some property
- terraform apply

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #14176

No AccTests specified, not sure if that would be necessary, happy to add if necessary

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
This looks great but a test would be perfect 🙈

**Comment by aristosvo** [comment]
@mbfrahry Here they are! :rocket:

**Comment by mbfrahry** [comment]
Thanks for that but I'm seeing an issue with this test now `TestAccMsSqlDatabase_createOnlineSecondaryMode`

```
------- Stdout: -------
=== RUN   TestAccMsSqlDatabase_createOnlineSecondaryMode
=== PAUSE TestAccMsSqlDatabase_createOnlineSecondaryMode
=== CONT  TestAccMsSqlDatabase_createOnlineSecondaryMode
testcase.go:110: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
(map[string]string) (len=1) {
(string) (len=11) "create_mode": (string) (len=9) "Secondary"
}
(map[string]string) (len=1) {
(string) (len=11) "create_mode": (string) (len=15) "OnlineSecondary"
}
--- FAIL: TestAccMsSqlDatabase_createOnlineSecondaryMode (648.86s)
FAIL
```

**Comment by aristosvo** [comment]
Sorry! I didn't commit all of it apparently😢

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for this @aristosvo

**Pull request merged**
