### PR TITLE
`azurerm_windows_function_app`, `azurerm_windows_web_app` - adding  property `push` 

### PR DESCRIPTION
**Pull request by xiaxyi**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)

The failed test result is not related to the property that's covered in this PR

```
    testcase.go:113: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # azurerm_windows_function_app.test will be updated in-place
          ~ resource "azurerm_windows_function_app" "test" {
              ~ ftp_publish_basic_authentication_enabled       = false -> true
                id                                             = "/subscriptions/85xxx/resourceGroups/acctestRG-WFA-240412131534550431/providers/Microsoft.Web/sites/acctest-WFA-240412131534550431"
                name                                           = "acctest-WFA-240412131534550431"

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccWindowsFunctionApp_withPush (434.63s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    438.595s
FAIL
make: *** [GNUmakefile:99: acctests] Error 1

=== CONT  TestAccWindowsWebApp_push
=== CONT  TestAccWindowsWebApp_pushUpdate
    testcase.go:113: Step 1/6 error: After applying this test step, the plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # azurerm_windows_web_app.test will be updated in-place
          ~ resource "azurerm_windows_web_app" "test" {
              ~ ftp_publish_basic_authentication_enabled       = false -> true
                id                                             = "/subscriptions/85bxx/resourceGroups/acctestRG-240412113304891243/providers/Microsoft.Web/sites/acctestWA-240412113304891243"
                name                                           = "acctestWA-240412113304891243"
              ~ webdeploy_publish_basic_authentication_enabled = false -> true
                # (18 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccWindowsWebApp_pushUpdate (176.60s)
=== NAME  TestAccWindowsWebApp_push
    testcase.go:113: Step 1/2 error: After applying this test step, the plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # azurerm_windows_web_app.test will be updated in-place
          ~ resource "azurerm_windows_web_app" "test" {
              ~ ftp_publish_basic_authentication_enabled       = false -> true
                id                                             = "/subscriptions/85xx/resourceGroups/acctestRG-240412113304891144/providers/Microsoft.Web/sites/acctestWA-240412113304891144"
                name                                           = "acctestWA-240412113304891144"
              ~ webdeploy_publish_basic_authentication_enabled = false -> true
                # (19 unchanged attributes hidden)

                # (3 unchanged blocks hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccWindowsWebApp_push (440.26s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    459.262s
FAIL
make: *** [GNUmakefile:99: acctests] Error 1

```
## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_function_app`, `azurerm_windows_web_app`  - support for the `push` property 

This is a (please select all that apply):

- [ ] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [x] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #0000

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks for this PR @xiaxyi. I've left several suggestions in-line, in particular the following design considerations:

1. Looking at how the block behaves it might not be necessary to expose `is_push_enabled` as a property.
2. It appears that some `app_settings` keys are worth exposing as properties, `MS_NotificationHubId` in particular would be worth managing through a property instead of the `app_settings` block, this would become a required property within the `push_settings` block and means we can remove the helper functions that determine whether a notification hub is connected or not. [This validation function](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/validate/app_settings.go) will help manage the `app_settings` key

**Comment by xiaxyi** [comment]
Thanks @stephybun for the review!

I did more tests and removed the notification hub check as the api doesn't validate the notification hub connection. I will follow the same practice as the api.
```
--- PASS: TestAccWindowsWebApp_push (423.76s)
--- PASS: TestAccWindowsWebApp_pushUpdate (698.71s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    720.730s
--- PASS: TestAccWindowsFunctionApp_withPushUpdate (705.54s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    722.310s
--- PASS: TestAccWindowsFunctionApp_withPush (438.18s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    455.628s
```

As for other parts, updated property naming in doc/ modified the error message/ removed the default part for notification hub  connection string.

let me know if everything is ok to you.

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks @xiaxyi.

Aside from one of the previous review comments which hasn't been resolved yet, could you please provide some proof that this works end to end without specifying the notification hub ID or notification hub connection string through some manual testing?

**Comment by xiaxyi** [comment]
This PR is blocked by api issue:https://github.com/Azure/azure-rest-api-specs/issues/29744

**Comment by stephybun** [comment]
Thanks for opening and linking the issue on the Azure Rest API Specs. Since this is blocked I'm going to close this PR for the time being. Once the upstream issue is resolved we can reopen this.

**Pull request closed without merging**
