### PR TITLE
`azurerm_app_service_connection`, `azurerm_spring_cloud_connection`: add acc tests for key vault, replacing documentation example code

### PR DESCRIPTION
**Pull request by jiaweitao001**
* Replaced example in documentation per service team's request.

* Add acc tests for key vault as target resource.

```
--- PASS: TestAccServiceConnectorSpringCloudKeyVault_basic (951.26s)
PASS

--- PASS: TestAccServiceConnectorAppServiceKeyVault_basic (831.23s)
PASS

```

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
test failure:
```
------- Stdout: -------
=== RUN   TestAccServiceConnectorSpringCloudCosmosdb_update
=== PAUSE TestAccServiceConnectorSpringCloudCosmosdb_update
=== CONT  TestAccServiceConnectorSpringCloudCosmosdb_update
    testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: listing resources in Resource Group: (Resource Group "acctestRG-220920144758530259"): resources.Client#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'acctestRG-220920144758530259' could not be found."
        
--- FAIL: TestAccServiceConnectorSpringCloudCosmosdb_update (1377.28s)
FAIL
```

**Comment by jiaweitao001** [comment]
> test failure:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccServiceConnectorSpringCloudCosmosdb_update
> === PAUSE TestAccServiceConnectorSpringCloudCosmosdb_update
> === CONT  TestAccServiceConnectorSpringCloudCosmosdb_update
>     testing_new.go:84: Error running post-test destroy, there may be dangling resources: exit status 1
>         
>         Error: listing resources in Resource Group: (Resource Group "acctestRG-220920144758530259"): resources.Client#ListByResourceGroup: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'acctestRG-220920144758530259' could not be found."
>         
> --- FAIL: TestAccServiceConnectorSpringCloudCosmosdb_update (1377.28s)
> FAIL
> ```

Retried in teamcity, all [tests](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=343629&buildTypeId=TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_SERVICECONNECTOR&tab=testsInfo) are passing now.

**Review by katbyte — APPROVED** [review]
LGTM 🪶  just need to fix the merge conflicts @jiaweitao001

**Comment by jiaweitao001** [comment]
The corresponding acc tests are failing of upstream resources. Closing this PR for now, will reopen once the issues are fixed.

**Pull request closed without merging**
