### PR TITLE
Change PostgreSQL password after instance was promoted from Replica to Default mode

### LINKED ISSUE #14377: Support for changing PostgreSQL admin password when promoting from Replica to Default mode
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Situation

Terraform plan is
```hcl
# module.tenant.module.iwddm-service.module.postgres.azurerm_postgresql_server.psql_server will be updated in-place
  ~ resource "azurerm_postgresql_server" "psql_server" {
      + administrator_login_password      = (sensitive value)
      ~ create_mode                       = "Replica" -> "Default"
        id                                = "/subscriptions/.../resourceGroups/service-...-dev/providers/Microsoft.DBforPostgreSQL/servers/pg01-...-dev"
        name                              = "pg01-...-dev"
        tags                              = {
            "environment" = "dev"
        }
        # (16 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Terraform apply fails:
```hcl
module.tenant.module.iwddm-service.module.postgres.azurerm_postgresql_server.psql_server: Still modifying... [id=/subscriptions/.../servers/pg01-...-dev, 7m40s elapsed]

Error: updating PostgreSQL Server "pg01-...-dev" (Resource Group "service-...-dev"): postgresql.ServersClient#Update: Failure sending request: StatusCode=500 -- Original Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '36f5a9b8-...-af82148f241e'"

  on .terraform/modules/tenant.iwddm-service.postgres/postgres-module/main.tf line 57, in resource "azurerm_postgresql_server" "psql_server":
  57: resource azurerm_postgresql_server psql_server {
```

### Description
Azure backend does not allow changing PostgreSQL password when instance is in the Replica mode. Azure Portal has this button hidden, CLI and API requests fail with 500 error:

```
az postgres server update \
--resource-group service-...-dev \
--name pg01-...-dev \
--admin-password <pwd>
```
or
```
curl -k -v -X PATCH -d '{"properties":{"administratorLoginPassword":"AAA","replicationRole":"None"},"location":"eastus2"}' -H 'Content-Type: application/json; charset=utf-8' -H 'Accept-Encoding: gzip' -H 'Authorization: Bearer <token>' https://management.azure.com/subscriptions/<subscription>/resourceGroups/<resource group>/providers/Microsoft.DBforPostgreSQL/servers/<server>?api-version=2017-12-01
```
fail with
```
Error: updating PostgreSQL Server "pg01-...2-dev" (Resource Group "service-...-dev"): postgresql.ServersClient#Update: Failure sending request: StatusCode=500 -- Original Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '...'"
```

### Proposal
If we change instance mode from Replica to Default as well as password, why not change the instance type first and then the password? It will require two API calls but allow to avoid 500 error

Please find the implemented workaround and share your thoughts: https://github.com/hashicorp/terraform-provider-azurerm/pull/14376

### PR DESCRIPTION
**Pull request by sheffsky**
Discussion https://github.com/hashicorp/terraform-provider-azurerm/issues/14377

(Fixes #14377)

### CODE REVIEW

**Review by aristosvo — COMMENTED** [review]
Hi @sheffsky! It looks good in general, have you already tried writing [Acceptance Tests](internal/services/postgres/postgresql_server_resource_test.go)? It should not be to hard adding a new test based on the existing ones.

With regard to the list of updates, I prefer myself a more explicit approach instead of looping over a list. I'm not 100% sure where the HC maintainers are in these, but that would look like this:
```go
	oldCreateMode, newCreateMode := d.GetChange("create_mode")
	replicaUpdatedToDefault := postgresql.CreateMode(oldCreateMode.(string)) == postgresql.CreateModeReplica && postgresql.CreateMode(newCreateMode.(string)) == postgresql.CreateModeDefault
	if replicaUpdatedToDefault {
		properties.ServerUpdateParametersProperties.ReplicationRole = utils.String("None")
	}

	// Update Admin Password in a separate call when Replication is stopped: https://github.com/Azure/azure-rest-api-specs/issues/16898
 	if d.HasChange("administrator_login_password") && !replicaUpdatedToDefault {
 		properties.ServerUpdateParametersProperties.AdministratorLoginPassword = utils.String(d.Get("administrator_login_password").(string))
 	}

	future, err := client.Update(ctx, id.ResourceGroup, id.Name, *properties)
	if err != nil {
	    return fmt.Errorf("updating %q: %+v", id, err)
	}
	if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
		return fmt.Errorf("waiting for update of %q: %+v", id, err)
	}

	// Update Admin Password in a separate call when Replication is stopped: https://github.com/Azure/azure-rest-api-specs/issues/16898
 	if d.HasChange("administrator_login_password") && replicaUpdatedToDefault {
		props := postgresql.ServerUpdateParameters{
			Identity: expandServerIdentity(d.Get("identity").([]interface{})),
			ServerUpdateParametersProperties: &postgresql.ServerUpdateParametersProperties{
				AdministratorLoginPassword: utils.String(d.Get("administrator_login_password").(string)),
			},
			Sku:  sku,
			Tags: tags.Expand(d.Get("tags").(map[string]interface{})),
		})

		future, err := client.Update(ctx, id.ResourceGroup, id.Name, *props)
		if err != nil {
			return fmt.Errorf("updating Admin Password of %q: %+v", id, err)
		}
		if err = future.WaitForCompletionRef(ctx, client.Client); err != nil {
			return fmt.Errorf("waiting for Admin Password update of %q: %+v", id, err)
		}
 	}
```
It makes the exception we're now facing more explicit and easier to remove in case it gets fixed.

Thanks a lot anyway, nice work!

**Comment by abarshev** [comment]
Hi @aristosvo 
Thank you very much for your comment. Initially I was going to make changes similar to the way you suggested, but then decided to use loop as more "elegant" solution. Of course you're right, it will be easier to remove this workaround once backend is fixed. I've pushed the changes.
Acceptance tests are on the way.

**Comment by aristosvo** [comment]
Nice, thank you so much!

Btw, if you'd add `Fixes #14377` to the first comment, the PR is linked to the issue. This also triggers closing of the issue if the PR is merged 👍🏽

**Comment by sheffsky** [comment]
This change has been successfully tested on my real environment.

**Comment by sheffsky** [comment]
It looks like this workaround is going to be permanent according to the Azure team's answer:
> We do not allow updating server password along with the replication promote operation in the same request.
>You would need to split this into 2 operations where you first promote the replica server and then update the password on the newly promoted server separately.
>We also do not support updating the password on a replica server.

https://docs.microsoft.com/en-us/answers/questions/643509/azure-db-for-postgresql-fails-promoting-replica-to.html?childToView=648972#answer-648972

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @sheffsky - code looks good but we have a test failure:

```
------- Stdout: -------
=== RUN   TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword
=== PAUSE TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword
=== CONT  TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword
    testcase.go:110: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=1) {
         (string) (len=25) "creation_source_server_id": (string) ""
        }
--- FAIL: TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword (1079.60s)
FAIL
```

**Comment by sheffsky** [comment]
@katbyte, thank you. I've fixed the test:
```
make acctests SERVICE=postgres TESTARGS='-run=TestAccPostgreSQLServer_updateReplicaToDefault' TESTTIMEOUT='60m' 
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/postgres -run=TestAccPostgreSQLServer_updateReplicaToDefault -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccPostgreSQLServer_updateReplicaToDefault
=== PAUSE TestAccPostgreSQLServer_updateReplicaToDefault
=== RUN   TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword
=== PAUSE TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword
=== CONT  TestAccPostgreSQLServer_updateReplicaToDefault
=== CONT  TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword
--- PASS: TestAccPostgreSQLServer_updateReplicaToDefault (1073.07s)
--- PASS: TestAccPostgreSQLServer_updateReplicaToDefaultAndSetPassword (1191.06s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/postgres      1191.121s
```

**Review by katbyte — APPROVED** [review]
Thanks @sheffsky ! LGTM now 🍰

**Pull request merged**
