### PR TITLE
New Resource : `azurerm_api_management_gateway_certificate_authority`

### PR DESCRIPTION
**Pull request by sinbai**
Support API Management Gateway Certificate Authority. [Here ](https://cs.github.com/Azure/azure-rest-api-specs/blob/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/apimgateways.json#L1201)is the API spec.

Test Results:

>  PASS: TestAccApiManagementGatewayCertificateAuthority_basic (5260.60s)
>  PASS: TestAccApiManagementGatewayCertificateAuthority_requiresImport (4989.60s)
>  PASS: TestAccApiManagementGatewayCertificateAuthority_complete (5553.21s)
>  PASS: TestAccApiManagementGatewayCertificateAuthority_update (5328.52s)

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🌩️

**Comment by magodo** [comment]
@sinbai Can you please resolve the conflicts?

**Comment by sinbai** [comment]
> @sinbai Can you please resolve the conflicts?

Sure, fixed.

**Comment by magodo** [comment]
image

**Pull request merged**
