### PR TITLE
`azurerm_key_vault` - add support for the `NestedItemTypeStorageKey` to key vault `nested_item`

### LINKED ISSUE #22694: key vault 'NestedItemType' should be one of: keys, secrets, certificates, got "storage"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_managed_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_managed_storage_account" "sa" {
  depends_on                   = [azurerm_key_vault.kv, azurerm_key_vault_access_policy.terraform_access_policy]
  count                        = var.sas_enabled ? 1 : 0
  name                         = var.storage
  key_vault_id                 = azurerm_key_vault.kv.id
  storage_account_id           = var.storage_id
  storage_account_key          = "key1"
  regenerate_key_automatically = true
  regeneration_period          = "P90D"
}
```

### Debug Output/Panic Output

```shell
##[error]Terraform command 'plan' failed with exit code '1'.
##[error]╷
│ Error: key vault 'NestedItemType' should be one of: keys, secrets, certificates, got "storage"
│ 
│   with module.basis.module.altinn-keyvault.azurerm_key_vault_managed_storage_account.sa[0],
│   on .terraform/modules/basis/modules/aks-keyvault/storage-sas-token.tf line 1, in resource "azurerm_key_vault_managed_storage_account" "sa":
│    1: resource "azurerm_key_vault_managed_storage_account" "sa" {
```

### Expected Behaviour

Terraform should run through with result no change.

### Actual Behaviour

Terraform plan fail.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

Regression from 3.62.0 to 3.63.0

https://github.com/hashicorp/terraform-provider-azurerm/compare/v3.62.0...v3.63.0

I guess this section should include 'storage'

"internal/services/keyvault/parse/nested_item.go"
```
type NestedItemObjectType string

const (
	// KeyVaultObjectType Keys...
	NestedItemTypeKey NestedItemObjectType = "keys"
	// KeyVaultObjectType Secrets...
	NestedItemTypeSecret NestedItemObjectType = "secrets"
	// KeyVaultObjectType Certificates...
	NestedItemTypeCertificate NestedItemObjectType = "certificates"
)
```

### PR DESCRIPTION
**Pull request by WodansSon**
(fixes #22694 and #22757)

### CODE REVIEW

**Comment by WodansSon** [comment]
image

## NOTE:

The one test failure seems unrelated to my change as it is due to a `Status=403 Code="AuthenticationFailed"` which I suspect is a test case issue.

```bash
------- Stdout: -------
=== RUN   TestAccKeyVaultManagedStorageAccountSasTokenDefinition_recovery
=== PAUSE TestAccKeyVaultManagedStorageAccountSasTokenDefinition_recovery
=== CONT  TestAccKeyVaultManagedStorageAccountSasTokenDefinition_recovery
    testcase.go:113: Step 4/5 error: Error running apply: exit status 1
        Error: reading queue properties for AzureRM Storage Account "unlikely23exst2acctpicrt": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:3d0ed4a3-1003-004e-5053-c0c858000000\nTime:2023-07-27T06:28:15.7724500Z"
          with azurerm_storage_account.test,
          on terraform_plugin_test.tf line 34, in resource "azurerm_storage_account" "test":
          34: resource "azurerm_storage_account" "test" {
--- FAIL: TestAccKeyVaultManagedStorageAccountSasTokenDefinition_recovery (411.95s)
FAIL
```

**Review by catriona-m — CHANGES_REQUESTED** [review]
Thanks for this @WodansSon - this looks good, but maybe we could add a test for this case in internal/services/keyvault/parse/nested_item_test.go?

**Comment by WodansSon** [comment]
@catriona-m, thanks for taking a look at the PR. I do not believe adding test cases will be neccessary for this code change as  the following tests already test this scenario and are currently failing:

image

### Error Detail:
```bash
------- Stdout: -------
=== RUN   TestAccKeyVaultManagedStorageAccount_basic
=== PAUSE TestAccKeyVaultManagedStorageAccount_basic
=== CONT  TestAccKeyVaultManagedStorageAccount_basic
    testcase.go:113: Step 1/2 error: Error running apply: exit status 1
        Error: key vault 'NestedItemType' should be one of: keys, secrets, certificates, got "storage"
          with azurerm_key_vault_managed_storage_account.test,
          on terraform_plugin_test.tf line 66, in resource "azurerm_key_vault_managed_storage_account" "test":
          66: resource "azurerm_key_vault_managed_storage_account" "test" {
    testing_new.go:86: Error running post-test destroy, there may be dangling resources: exit status 1
        Error: key vault 'NestedItemType' should be one of: keys, secrets, certificates, got "storage"
--- FAIL: TestAccKeyVaultManagedStorageAccount_basic (176.61s)
FAIL
```

**Review by katbyte — APPROVED** [review]
LGTM ☔

**Pull request merged**
