### PR TITLE
Allow blob upload in archive tier

### PR DESCRIPTION
**Pull request by ppodgorsek**
Changed the order in which the access tier change is done, to avoid issues when blobs are uploaded in the archive tier.

This PR relate to issue #22249.

### CODE REVIEW

**Comment by magodo** [comment]
@ppodgorsek Thank you for this PR! The reason why this works is because the blob's tier is "Hot" by default. By swapping the update order works here, but it might bring some security issue: imagine a user wants to archive a blob by setting the tier, whilst the `source` somehow changed unexpectedly, instead of declining the upload of the blob after archiving, the operation succeeded and unexpected change to the blob sneaks in.

**Comment by ppodgorsek** [comment]
@magodo Thank you for the explanation, and sorry for the delay in replying. I have a few questions to better understand this issue.

According to the Azure documentation, the blob's tier is the same as the tier of its container by default, rather than `Hot` by default. Is that different when uploading via the SDK?

Regarding your example, isn't this the same problem as doing it manually?
Even if there is still a risk of archiving the wrong blob, the risk is much smaller here doing it automatically a few milliseconds later than if we have to manually go and change the tier afterwards, no?

Does this mean we should introduce a dedicated resource to update a blob's tier? Thinking about it, such a resource might be useful in other scenarios too. What do you think?

**Review by catriona-m — CHANGES_REQUESTED** [review]
Hi @ppodgorsek could we add a test to validate this scenario? Then we can take another look, thanks!

**Comment by tombuildsstuff** [comment]
hey @magodo - any chance you'd be able to take a look into adding a test covering this one?

**Comment by magodo** [comment]
@tombuildsstuff I've added the test case, regardless my concern above.

**Review by stephybun — APPROVED** [review]
Thanks @ppodgorsek and @magodo LGTM 👍

**Pull request merged**
