### PR TITLE
`azurerm_storage_share` set `metadata` `Computed` and set `acl` `start` and `expiry` `Optional`

### PR DESCRIPTION
**Pull request by yupwei68**
Fix `azurerm_storage_sync_cloud_endpoint` acctest problems, https://github.com/terraform-providers/terraform-provider-azurerm/pull/8540

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @yupwei68, can you go into a little detail about why we're making MetaData computed. I can see that you're doing a lifecycle ignore in the PR you linked but I didn't see how it was affecting that resource. 

Also can you write a test to confirm that we can create a storage share with an ACL but not setting `expiry` and `start`. We'll also want to update the documentation as well

**Comment by yupwei68** [comment]
Hi @mbfrahry here's the `metadata` will be changed once we have created a `azurerm_storage_sync_cloud_endpoint` with reference to it.
```
 After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        UPDATE: azurerm_storage_share.test
          ...
          metadata.azurebackupprotected:     "False" => ""
          metadata.postbackupuri:            "/subscriptions/.../resourceGroups/.../providers/microsoft.storagesync/storageSyncServices/.../syncGroups/.../cloudEndpoints/.../postbackup?api-version=2017-06-05-preview" => ""
          metadata.postrestoreuri:           "/subscriptions/..../resourceGroups/.../providers/microsoft.storagesync/storageSyncServices/.../syncGroups/.../cloudEndpoints/..../postrestore?api-version=2017-06-05-preview" => ""
          metadata.prebackupuri:             "/subscriptions/.../resourceGroups/.../providers/microsoft.storagesync/storageSyncServices/.../syncGroups/.../cloudEndpoints/.../prebackup?api-version=2017-06-05-preview" => ""
          metadata.prerestoreuri:            "/subscriptions/.../resourceGroups/.../providers/microsoft.storagesync/storageSyncServices/.../syncGroups/.../cloudEndpoints/.../prerestore?api-version=2017-06-05-preview" => ""
          metadata.restoreheartbeaturi:      "/subscriptions/.../resourceGroups/.../providers/microsoft.storagesync/storageSyncServices/.../syncGroups/.../cloudEndpoints/.../restoreheartbeat?api-version=2017-06-05-preview" => ""
          metadata.syncgroup:                "..." => ""
          metadata.syncservice:              "..." => ""
          metadata.syncsignature:            "...." => ""
          ...
        
```

**Comment by yupwei68** [comment]
@mbfrahry THanks for your comments. An additional test has been added. Please continue reviewing.
=== RUN   TestAccAzureRMStorageShare_aclGhostedRecall
=== PAUSE TestAccAzureRMStorageShare_aclGhostedRecall
=== CONT  TestAccAzureRMStorageShare_aclGhostedRecall
--- PASS: TestAccAzureRMStorageShare_aclGhostedRecall (134.55s)

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for taking the time to explain the metadata issue @yupwei68

**Pull request merged**
