### PR TITLE
`azurerm_kubernetes_cluster` - `scale_down_mode` can be updated

### PR DESCRIPTION
**Pull request by ms-henglu**
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/19815

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Can we update the existing test to update the value

**Comment by ms-henglu** [comment]
Hi @stephybun ,

Thanks for code review! It seems that there's already a test for this scenario. https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_cluster_other_resource_test.go#L309

**Review by stephybun — COMMENTED** [review]
Thanks @ms-henglu, just the CI needs to be fixed then this can be merged.

**Review by stephybun — APPROVED** [review]
Thanks @ms-henglu LGTM 🚀

**Pull request merged**
