### PR TITLE
`azurerm_sql_managed_instance`: Support for `identity`

### LINKED ISSUE #14049: Principal ID as Outputs
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.0.9
* AzureRM Provider version: 2.83

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Description / Feedback

There is no option to enable System managed identity for Azure SQL Managed Instance Module.
Also there should Principal ID should be provided as Output for the resource when we enable System Managed Identity

### PR DESCRIPTION
**Pull request by aristosvo**
Fixes #14049

### Acceptance Tests
- [x] Passing locally

### CODE REVIEW

**Comment by aristosvo** [comment]
Running the last checks, validating update possibilities after assigning a `SystemAssigned` identity

**Review by katbyte — APPROVED** [review]
Thanks @aristosvo! LGTM 🙌

**Comment by aristosvo** [comment]
@katbyte Any reason this isn't merged? Last test run on my side went well.

**Comment by katbyte** [comment]
was just waiting for our internal CI to finish! merging now 🙂

**Pull request merged**
