### PR TITLE
resource `azurerm_shared_image` - add architecture option.

### PR DESCRIPTION
**Pull request by sergelogvinov**
Add `architecture` option to `azurerm_shared_image` resource.

source doc - https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azgalleryimagedefinition?view=azps-8.0.0

### CODE REVIEW

**Comment by sergelogvinov** [comment]
Hello, @tombuildsstuff can you review this PR. It option helps me to upload arm-arch images to the azure.

Thank you.

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @sergelogvinov - overall looks good but we have some test failures:
```
Test ended in panic.

------- Stdout: -------
=== RUN   TestAccDataSourceAzureRMSharedImage_basic
=== PAUSE TestAccDataSourceAzureRMSharedImage_basic
=== CONT  TestAccDataSourceAzureRMSharedImage_basic

------- Stderr: -------
panic: Invalid address to set: []string{"architecture"}

goroutine 438 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0xc004341500, {0x6255916, 0xc}, {0x5774d60, 0xc001eee6f0})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go:230 +0x291
github.com/hashicorp/terraform-provider-azurerm/internal/services/compute.dataSourceSharedImageRead(0x7fea541963f8?, {0x58c0f00?, 0xc003741500?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/internal/services/compute/shared_image_data_source.go:134 +0x8cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x624690e?, {0x6ac0ba8?, 0xc001f53e80?}, 0xc001ca8c90?, {0x58c0f00?, 0xc003741500?})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000ecbea0, {0x6ac0ba8, 0xc001f53e80}, 0xc004341380, {0x58c0f00, 0xc003741500})
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:569 +0xf7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc00140c000, {0x6ac0ba8, 0xc001f53e80}, 0xc0002eb0e0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:1133 +0x339
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc001464180, {0x6ac0c50?, 0xc001c27d40?}, 0xc0021f6c30)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:478 +0x31b
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler({0x5e6dbe0?, 0xc001464180}, {0x6ac0c50, 0xc001c27d40}, 0xc0016221e0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00146a000, {0x6ad23e8, 0xc004072f00}, 0xc001fa66c0, 0xc00203e8d0, 0xac35770, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc00146a000, {0x6ad23e8, 0xc004072f00}, 0xc001fa66c0, 0x0)
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:1617 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5e6516bb4d10eb66/vendor/google.golang.org/grpc/server.go:938 +0x28a
```

**Comment by sergelogvinov** [comment]
oh, i did something bad here. I've rebase the PR and did not check that this PR has changes....

**Comment by sergelogvinov** [comment]
rebase + small refactoring

**Review by katbyte — APPROVED** [review]
Thanks @sergelogvinov - LGTM 💾

**Pull request merged**
