### PR TITLE
New Resource: `azurerm_automation_hybrid_runbook_worker_group`

### LINKED ISSUE #14622: Support for Automation Hybrid Runbook Worker Group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a request for a new resource in automation category for [Hybrid Runbook Worker Group](https://docs.microsoft.com/en-us/azure/automation/extension-based-hybrid-runbook-worker-install#create-hybrid-worker-group).

### New or Affected Resource(s)

* azurerm_automation_hybrid_runbook_worker_group

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/Azure/azure-sdk-for-go/blob/main/services/automation/mgmt/2019-06-01/automation/hybridrunbookworkergroup.go

### PR DESCRIPTION
**Pull request by wuxu92**
support Automation/HybridRunbookWorkerGroup, fixes #14622 

--- PASS: TestAccHybridRunbookWorkerGroup_basic (784.66s)
--- PASS: TestAccHybridRunbookWorkerGroup_update (335.80s)

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🏝️

**Comment by magodo** [comment]
@wuxu92 Can you please resolve the merge conflicts?

**Comment by wuxu92** [comment]
@magodo all checks have passed now

**Comment by magodo** [comment]
image

**Pull request merged**
