### PR TITLE
Enable Workload Profiles for Container Apps Environment with VNET Integration

### PR DESCRIPTION
**Pull request by icornett**
There's presently no way to create a workload-profile enabled Container App Environment.  This issue costs me a few days as it wasn't evident what the issue was due to Azure not responding with an error and just timing out after failing to provision.  Once I passed the value from CLI, it succeeded.  This replicates that behavior.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
Will this work with https://github.com/hashicorp/terraform-provider-azurerm/pull/23478 ?

**Comment by icornett** [comment]
@davidkarlsen I think it would, I couldn't get the non-consumption profile to work.  I take it you tested on consumption for that and the app itself as well?

**Comment by jackofallops** [comment]
Hi @icornett - Thanks for this PR. I'm afraid this is a duplicate of the work started by @wuxu92 in #23478 and since that was opened earlier and there has already been several rounds of changes and work done there I'm going to have to close this PR out in favour of that one. We'll be working to get this feature in as quickly as we can.  
Thanks again for your contribution here.

**Comment by icornett** [comment]
@jackofallops I generally concur, but noticed that PR is missing the ability to bind the container app to the workload profile.  This has that work in it.

**Pull request closed without merging**
