### PR TITLE
`azurerm_bastion_host` - support new SKU `Premium` and feature `Session recording`

### LINKED ISSUE #27013: Support for Azure Bastion Premium SKU
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure Bastion now has a premium sku available, it is not currently supported by the provider.

### New or Affected Resource(s)/Data Source(s)

azurerm_bastion_host

### Potential Terraform Configuration

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by T0biii**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for PR followers and do not help prioritize for review

## Description
We want to use Bastion Premium and the feature session recording 

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have written new tests for my resource or datasource changes & updated any relevent documentation.
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
- [ ] (For changes that include a **state migration only**). I have manually tested the migration path between relevant versions of the provider.

## Testing 

- [x] My submission includes Test coverage as described in the [Contribution Guide](../blob/main/contributing/topics/guide-new-resource.md) and the tests pass. (if this is not possible for any reason, please include details of why you did or could not add test coverage)
image

~~currently have no test subscription~~ ~~and also i think #27277 needs to be merged first~~

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_bastion_host` - support new SKU `Premium` and feature `Session recording`

This is a (please select all that apply):

- [ ] Bug Fix
- [x] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #27013
#27277 needs to be merged first

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Comment by T0biii** [comment]
Needs to be adjusted also for Premium:

https://github.com/hashicorp/terraform-provider-azurerm/blob/a135c6f17e80bfc9342a5ae2c30e0b6a0b3232eb/internal/services/network/bastion_host_resource.go#L188-L210

**Comment by T0biii** [comment]
Test seems to pass now :)
image

**Comment by T0biii** [comment]
image

**Review by katbyte — CHANGES_REQUESTED** [review]
It looks like we have a test failure here:

```
------- Stdout: -------
=== RUN   TestAccBastionHost_premiumSku
=== PAUSE TestAccBastionHost_premiumSku
=== CONT  TestAccBastionHost_premiumSku
    testcase.go:130: Step 1/3 error: Error running apply: exit status 1
        
        Error: `session_recording_enabled` is only supported when `sku` is `Premium`
        
          with azurerm_bastion_host.test,
          on terraform_plugin_test.tf line 58, in resource "azurerm_bastion_host" "test":
          58: resource "azurerm_bastion_host" "test" {
        
--- FAIL: TestAccBastionHost_premiumSku (158.69s)
FAIL
```

**Comment by T0biii** [comment]
> It looks like we have a test failure here:
> 
> ```
> ------- Stdout: -------
> === RUN   TestAccBastionHost_premiumSku
> === PAUSE TestAccBastionHost_premiumSku
> === CONT  TestAccBastionHost_premiumSku
>     testcase.go:130: Step 1/3 error: Error running apply: exit status 1
>         
>         Error: `session_recording_enabled` is only supported when `sku` is `Premium`
>         
>           with azurerm_bastion_host.test,
>           on terraform_plugin_test.tf line 58, in resource "azurerm_bastion_host" "test":
>           58: resource "azurerm_bastion_host" "test" {
>         
> --- FAIL: TestAccBastionHost_premiumSku (158.69s)
> FAIL
> ```

this Error i already fixed, are you on the latest Version? (I force pushed this branch)

**Review by T0biii — COMMENTED** [review]
The Error was when this was == and not !=

**Review by katbyte — APPROVED** [review]
Than ks LGTM 🌻

**Pull request merged**
