### PR TITLE
`azurerm_batch_pool` - add json processing logic to `settings_json`

### PR DESCRIPTION
**Pull request by liuwuliuyun**
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20530

Testing evidence will be provided after TC run.

### CODE REVIEW

**Comment by liuwuliuyun** [comment]
GOROOT=C:\Users\yunliu1\go\go1.19.3 #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
C:\Users\yunliu1\go\go1.19.3\bin\go.exe test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccBatchAccount_cmk_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_batch.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/batch #gosetup
C:\Users\yunliu1\go\go1.19.3\bin\go.exe tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccBatchAccount_cmk_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_batch.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccBatchAccount_cmk\E$ #gosetup
=== RUN   TestAccBatchAccount_cmk
=== PAUSE TestAccBatchAccount_cmk
=== CONT  TestAccBatchAccount_cmk
--- PASS: TestAccBatchAccount_cmk (397.16s)
PASS


Process finished with the exit code 0

**Comment by liuwuliuyun** [comment]
image
Fixing other failed test cases in https://github.com/hashicorp/terraform-provider-azurerm/pull/20706

**Review by katbyte — CHANGES_REQUESTED** [review]
could we instead use the existing normalize json functions in the util package?

**Comment by liuwuliuyun** [comment]
Thanks @katbyte for the review. Sure we could, but I read that in https://hashicorp.github.io/terraform-provider-azurerm/topics/high-level-overview/ it says ```./utils
This primarily contains helper functions for converting simple types (e.g. bool/int/strings) to pointers (e.g. utils.String(“someValue”).
We intend to deprecate this folder in time and new functionality should be added to individual service packages where possible. The existing functions will be gradually moved (via aliasing) into another repository.``` That is the reason I add this seperately.

**Comment by katbyte** [comment]
@liuwuliuyun - for new functionality that is true. this is an existing function so it is fine to use as its not adding something new to move.

in the long run i believe we would be moving this into go-azure-helpers library.

**Comment by katbyte** [comment]
also we have a number of test failureS:
```
------- Stdout: -------
=== RUN   TestAccBatchPool_certificates
=== PAUSE TestAccBatchPool_certificates
=== CONT  TestAccBatchPool_certificates
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Pool (Subscription: "*******"
        Resource Group Name: "testaccbatch230320175052396306"
        Batch Account Name: "testaccbatchsei3i"
        Pool Name: "testaccpoolsei3i"): pool.PoolClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PropertyCannotBeUpdated" Message="A property that cannot be updated was specified as part of the request.\nRequestId:c6c0ed53-1f79-4576-9dc8-0ddfb8058fe7\nTime:2023-03-20T17:56:35.5855997Z" Target="BatchAccount" Details=[{"code":"Reason","message":"A property that cannot be updated was specified as part of the request."},{"code":"PropertyName","message":"displayName"},{"code":"PropertyPath","message":"properties.displayName"}]
        
          with azurerm_batch_pool.test,
          on terraform_plugin_test.tf line 47, in resource "azurerm_batch_pool" "test":
          47: resource "azurerm_batch_pool" "test" {
        
    testing_new.go:86: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Certificate (Subscription: "*******"
        Resource Group Name: "testaccbatch230320175052396306"
        Batch Account Name: "testaccbatchsei3i"
        Certificate Name: "SHA1-42c107874fd0e4a9583292a2f1098e8fe4b2edda"): polling after Delete: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=409 -- Original Error: Code="PoolsReferencingCertificate" Message="The specified certificate is being used by the below mentioned pool(s)\nRequestId:6b360be1-16c6-4413-ab3b-3ccf3e085123\nTime:2023-03-20T18:01:23.6085998Z" Target="BatchAccount" Details=[{"code":"Pools","message":"testaccpoolsei3i"}]
        
        
        Error: deleting Certificate (Subscription: "*******"
        Resource Group Name: "testaccbatch230320175052396306"
        Batch Account Name: "testaccbatchsei3i"
        Certificate Name: "SHA1-312d31a79fa0cef49c00f769afc2b73e9f4edf34"): polling after Delete: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=409 -- Original Error: Code="PoolsReferencingCertificate" Message="The specified certificate is being used by the below mentioned pool(s)\nRequestId:835e26fb-fec3-4ea0-a9f4-f00608704f18\nTime:2023-03-20T18:01:23.8908641Z" Target="BatchAccount" Details=[{"code":"Pools","message":"testaccpoolsei3i"}]
        
--- FAIL: TestAccBatchPool_certificates (631.59s)
```

**Comment by liuwuliuyun** [comment]
Hi @katbyte , I have added `StateFunc: utils.NormalizeJson,` here, but we still need flatten and expand json func added because we need to convert json bytes to an string. There is a function called `pluginsdk.ExpandJsonFromString` but this will generate a map. So I have to manually add flattern function here.

**Comment by liuwuliuyun** [comment]
Will rerun the AccTest and give you feedback on that.

**Comment by liuwuliuyun** [comment]
image

**Review by katbyte — CHANGES_REQUESTED** [review]
I'm sorry but i don't understand why you cannot use existing functions here?

pluginsdk.FlattenJsonToString & pluginsdk.ExpandJsonFromString look to be identical to the ones you have written?

```
func ExpandJsonFromString(jsonString string) (map[string]interface{}, error) {
	var result map[string]interface{}

	err := json.Unmarshal([]byte(jsonString), &result)

	return result, err
}

func FlattenJsonToString(input map[string]interface{}) (string, error) {
	if len(input) == 0 {
		return "", nil
	}

	result, err := json.Marshal(input)
	if err != nil {
		return "", err
	}

	return string(result), nil
}

```

**Comment by liuwuliuyun** [comment]
The reason that json property in sdk is stored as `string` instead of `map[string]interface{}` here.

**Comment by liuwuliuyun** [comment]
close this PR till further agreement.

**Pull request closed without merging**
