### PR TITLE
`redisenterprise`: updating to API Version `2023-11-01`

### PR DESCRIPTION
**Pull request by tombuildsstuff**
This PR updates `redisenterprise` to use API Version `2023-11-01` from API Versions `2023-07-01` and `2023-10-01-preview`

### CODE REVIEW

**Review by catriona-m — APPROVED** [review]
LGTM!

**Comment by tombuildsstuff** [comment]
Looks like this API version isn't rolled out fully yet:

```
 Error: waiting for creation of Redis Enterprise (Subscription: "*******"
        Resource Group Name: "acctestRG-redisEnterprise-231110163233435734"
        Redis Enterprise Name: "acctest-rec-231110163233435734"): performing Create: unexpected status 400 with error: NoRegisteredProviderFound: No registered resource provider found for location 'eastus' and API version '2023-11-01' for type 'redisEnterprise'. The supported api-versions are '2023-10-01-preview, 2023-07-01, 2023-03-01-preview, 2022-11-01-preview, 2022-01-01, 2021-08-01, 2021-03-01, 2021-02-01-preview, 2020-04-01-preview, 2020-10-01-preview'. The supported locations are 'eastus, westeurope, westus, eastus2, westus2, westus3, northcentralus, southcentralus, uksouth, southeastasia, australiaeast, northeurope, centralus, centralindia, westcentralus, canadacentral, brazilsouth, japaneast, eastasia'.
```

**Review by katbyte — APPROVED** [review]
LGTM ⚖️

**Comment by tombuildsstuff** [comment]
Still blocked on the Azure API not being rolled out, when `apiVersions` from the below command contains `2023-11-01` this should be good to go/run the tests:

> az rest --method get --url "/subscriptions/XXX/providers/Microsoft.Cache?api-version=2020-01-01" --query "resourceTypes[?resourceType=='redisEnterprise/databases'].{resourceType:resourceType,apiVersions:apiVersions}"

**Comment by tombuildsstuff** [comment]
Still hasn't been deployed - closing for now.

**Pull request closed without merging**
