### PR TITLE
[Bug Fix]  `azurerm_pim_active_role_assignment`, `azurerm_pim_eligible_role_assignment`

### PR DESCRIPTION
**Pull request by xuzhang3**
Trying to fix `azurerm_pim_active_role_assignment`, `azurerm_pim_eligible_role_assignment` related issues. As the ID has be fixed to format `{scope}|{roleDefinitionId}|{principalId}`. The ID will not be changed, which makes the code tedious but functional and backward compatibility with previous versions though I want the add the `schedule ID ` and the `schedule request ID` to make this part simple

Updates:
1. Support manage pending(not active) role assignments(schedules) . 
2. Replace the Instance API by Schedule API. Instance API can get the active Role Assignments but Schedule can get all the Role Assignments including not active assignments(waiting for approval etc.)
3. Use the Schedule Request ID to get the Schedule Request not Schedule ID
4. Use cancel API to cancel the pending(not active) role assignment. Not active role assignment can only be canceled by this API.

Related issues: #23111  #24118  #23366

### CODE REVIEW

**Comment by xuzhang3** [comment]
image
image

**Comment by srnebu** [comment]
what is missing to merge this PR?

**Comment by MohnJadden** [comment]
@manicminer Could we request an expedite on your review of the PR?  #23111 is eagerly waiting for the possible fix.

**Comment by Scarlettliuyc** [comment]
hi @manicminer , good day. Could we confirm when you will review and approve this fix? We have many customers got these kinds of issue and we are waiting for the fix to update. The fix has been updated more than one month. Thanks, in advance.

**Review by manicminer — APPROVED** [review]
@xuzhang3 Thanks for working on this! The PIM APIs are a challenge and switching to the `/roleAssignmentScheduleRequests` / `/roleEligibilityScheduleRequests` endpoints seems the right way to go. I've made a few linting and code style stweaks, but this otherwise LGTM 👍

**Pull request merged**
