### PR TITLE
`azurerm_kubernetes_cluster`: Set default upgrade channel to `none` on create

### PR DESCRIPTION
**Pull request by favoretti**

### CODE REVIEW

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by tombuildsstuff** [comment]
Tests pass:

Screenshot 2021-09-28 at 14 03 10

**Comment by DanielHajduk2-TomTom** [comment]
Hi, Im using version: hashicorp/azurerm v2.79.0
And we still get:
"Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled. Please see https://aka.ms/aks/previews for how to enable features."

When this parameter is not specified. Default value seems not to be None.

**Comment by sossickd** [comment]
Experiencing the same issue as of 2.79.0

**Comment by fcatacut** [comment]
I'd expect that defaulting to `none` should also allow you to explicitly set `automatic_channel_upgrade = none`. However, I get the following on `terraform plan`:

```bash
Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none
```

**Comment by tombuildsstuff** [comment]
@fcatacut you can specify `none` by omitting the field / setting this value to `null`

**Comment by Sanverik** [comment]
> @fcatacut you can specify `none` by omitting the field / setting this value to `null`

`Original Error: Code="BadRequest" Message="Feature Microsoft.ContainerService/AutoUpgradePreview is not enabled.`

I set `automatic_channel_upgrade` to `null`, but still have the same error

**Pull request merged**
