### PR TITLE
Fix `azurerm_sql_database` blob auditing error under online secondary create mode

### LINKED ISSUE #6269: Error creating secondary DB using azurerm_sql_database resource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
AzureRM 2.1,2.2. TF core 0.12.23

### Affected Resource(s)

azurerm_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_sql_database" "database_secondary" {
  for_each = local.db_secondary_map

  name                = each.value.db_name
  location            = each.value.location
  resource_group_name = var.regional_data_rg[each.value.location].name
  server_name         = azurerm_sql_server.instance[each.value.location].name

  create_mode        = "OnlineSecondary"
  source_database_id = azurerm_sql_database.database_primary[each.value.db_name].id
  edition            = var.sql_pool_tier

  elastic_pool_name = azurerm_mssql_elasticpool.elasticpool[each.value.location].name

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output

Error: Error issuing create/update request for SQL Database "DB" Blob Auditing Policies(SQL Server "sqlsvr"/ Resource Group "resourcegroup"): sql.ExtendedDatabaseBlobAuditingPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BlobAuditingIsNotSupportedOnGeoDr" Message="Blob auditing can be configured on primary databases only."
2020-03-20T17:31:11.5032312Z 
2020-03-20T17:31:11.5032410Z   on ..\..\hosting-modules\data\sql\main.tf line 128, in resource "azurerm_sql_database" "database_secondary":
2020-03-20T17:31:11.5032545Z  128: resource "azurerm_sql_database" "database_secondary" {
https://gist.github.com/rohanvirmani/f7d90ba445ce0c6420f4f3796665c8fd
### Expected Behavior

Terraform should create/update the SQL databases as normal. This issue happens specifically when using version 2.1 and greater of the AzureRM provider.

Note that we are not defining the extended_auditing_policy block anywhere in our TF code.

### Steps to Reproduce
Create a new secondary database using terraform using the AzureRM provider (>2.1)

Execute 'terraform apply'

### References

**support for the `extended_auditing_policy` property - added as of AzureRM 2.1.0**
https://github.com/terraform-providers/terraform-provider-azurerm/pull/5036
* #0000

### LINKED ISSUE #6283: Support for extended_auditing_policy for azurerm_mssql_database
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the release of azurerm_mssql_database, some parameters were not ported over from azurerm_sql_database.  extended_auditing_policy was one of those features not ported over.

### New or Affected Resource(s)

* azurerm_mssql_database

### Potential Terraform Configuration

extended_auditing_policy - (Optional) A extended_auditing_policy block as defined below.

### References

https://www.terraform.io/docs/providers/azurerm/r/sql_database.html

### PR DESCRIPTION
**Pull request by yupwei68**
Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/6269
sql db secondary pass
Fix https://github.com/terraform-providers/terraform-provider-azurerm/issues/6283

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for this @yupwei68, should we also make the change for `azurerm_mssql_database` resource?

**Comment by yupwei68** [comment]
hi @katbyte , you mean add `blob auditing policies` in `mssql_database`?

**Comment by katbyte** [comment]
@yupwei68 - yep, given they are both basically the same resource just mssql is using the newer API

**Comment by yupwei68** [comment]
hi @katbyte , auditing polices are added to `azurerm_mssql_database`. All tests have been passed.
=== RUN   TestAccAzureRMMsSqlDatabase_basic
=== PAUSE TestAccAzureRMMsSqlDatabase_basic
=== CONT  TestAccAzureRMMsSqlDatabase_basic
--- PASS: TestAccAzureRMMsSqlDatabase_basic (327.69s)
=== RUN   TestAccAzureRMMsSqlDatabase_requiresImport
=== PAUSE TestAccAzureRMMsSqlDatabase_requiresImport
=== CONT  TestAccAzureRMMsSqlDatabase_requiresImport
--- PASS: TestAccAzureRMMsSqlDatabase_requiresImport (486.89s)
=== RUN   TestAccAzureRMMsSqlDatabase_complete
=== PAUSE TestAccAzureRMMsSqlDatabase_complete
=== CONT  TestAccAzureRMMsSqlDatabase_complete
--- PASS: TestAccAzureRMMsSqlDatabase_complete (324.84s)
=== RUN   TestAccAzureRMMsSqlDatabase_elasticPool
=== PAUSE TestAccAzureRMMsSqlDatabase_elasticPool
=== CONT  TestAccAzureRMMsSqlDatabase_elasticPool
--- PASS: TestAccAzureRMMsSqlDatabase_elasticPool (270.30s)
=== RUN   TestAccAzureRMMsSqlDatabase_GP
=== PAUSE TestAccAzureRMMsSqlDatabase_GP
=== CONT  TestAccAzureRMMsSqlDatabase_GP
--- PASS: TestAccAzureRMMsSqlDatabase_GP (293.69s)
=== RUN   TestAccAzureRMMsSqlDatabase_GP_Serverless
=== PAUSE TestAccAzureRMMsSqlDatabase_GP_Serverless
=== CONT  TestAccAzureRMMsSqlDatabase_GP_Serverless
--- PASS: TestAccAzureRMMsSqlDatabase_GP_Serverless (306.51s)
=== RUN   TestAccAzureRMMsSqlDatabase_BC
=== PAUSE TestAccAzureRMMsSqlDatabase_BC
=== CONT  TestAccAzureRMMsSqlDatabase_BC
--- PASS: TestAccAzureRMMsSqlDatabase_BC (721.70s)
=== RUN   TestAccAzureRMMsSqlDatabase_HS
=== PAUSE TestAccAzureRMMsSqlDatabase_HS
=== CONT  TestAccAzureRMMsSqlDatabase_HS
--- PASS: TestAccAzureRMMsSqlDatabase_HS (836.07s)
=== RUN   TestAccAzureRMMsSqlDatabase_createCopyMode
=== PAUSE TestAccAzureRMMsSqlDatabase_createCopyMode
=== CONT  TestAccAzureRMMsSqlDatabase_createCopyMode
--- PASS: TestAccAzureRMMsSqlDatabase_createCopyMode (505.46s)
=== RUN   TestAccAzureRMMsSqlDatabase_createPITRMode
=== PAUSE TestAccAzureRMMsSqlDatabase_createPITRMode
=== CONT  TestAccAzureRMMsSqlDatabase_createPITRMode
--- PASS: TestAccAzureRMMsSqlDatabase_createPITRMode (1320.76s)
=== RUN   TestAccAzureRMMsSqlDatabase_createSecondaryMode
=== PAUSE TestAccAzureRMMsSqlDatabase_createSecondaryMode
=== CONT  TestAccAzureRMMsSqlDatabase_createSecondaryMode
--- PASS: TestAccAzureRMMsSqlDatabase_createSecondaryMode (423.64s)
=== RUN   TestAccAzureRMMsSqlDatabase_threatDetectionPolicy
=== PAUSE TestAccAzureRMMsSqlDatabase_threatDetectionPolicy
=== CONT  TestAccAzureRMMsSqlDatabase_threatDetectionPolicy
--- PASS: TestAccAzureRMMsSqlDatabase_threatDetectionPolicy (429.83s)
=== RUN   TestAccAzureRMSqlDatabase_withBlobAuditingPolices
=== PAUSE TestAccAzureRMSqlDatabase_withBlobAuditingPolices
=== CONT  TestAccAzureRMSqlDatabase_withBlobAuditingPolices
--- PASS: TestAccAzureRMSqlDatabase_withBlobAuditingPolices (599.26s)

**Review by katbyte — APPROVED** [review]
Thanks @yupwei68! LGTM 👍

**Pull request merged**
