### PR TITLE
`azurerm_[linux|windows]_web_app[_slot]` - fix a bug in `app_settings` 

### LINKED ISSUE #22379: DOCKER_REGISTRY_SERVER_URL re-applied in every run
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
# New config
resource "azurerm_linux_web_app" "example" {

  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  service_plan_id = azurerm_service_plan.example.id

  site_config {
    application_stack {
      docker_image_name = "${local.docker_name}:${local.docker_tag}"
    }
  }
}
```

### Debug Output/Panic Output

```shell
resource "azurerm_linux_web_app" "example" {
      ~ app_settings                      = {
          + "DOCKER_REGISTRY_SERVER_URL"               = "example.azurecr.io"
            # (XX unchanged elements hidden)
        }
        id                                = "example-id"
        name                              = "example"
        # (XX unchanged attributes hidden)

        # (X unchanged blocks hidden)
    }
```

### Expected Behaviour

I would expect the `DOCKER_REGISTRY_SERVER_URL` to be saved correctly in the state so it does not re-apply the change to the App Service over and over again.

Recently switched from old config

```terraform
resource "azurerm_linux_web_app" "example" {

  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    application_stack {
      docker_image     = local.docker_name
      docker_image_tag = local.docker_tag
    }
  }
}
```

### Actual Behaviour

Terraform applies the application setting even if it already exists.

### Steps to Reproduce

terraform apply

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #23525: azurerm_linux_web_app docker settings silently deleted on update
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.3.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_container_registry" "this" {
  name                = "example"
  resource_group_name = "example"
}


data "azurerm_service_plan" "this" {
  name                = "example"
  resource_group_name = "example"

}

resource "azurerm_linux_web_app" "this" {
  name                = "docker-test-service"
  resource_group_name = data.azurerm_service_plan.this.resource_group_name
  location            = data.azurerm_service_plan.this.location
  service_plan_id     = data.azurerm_service_plan.this.id

  https_only                = true
  client_affinity_enabled   = false

  site_config {
    always_on         = "true"
    ftps_state        = "Disabled"
    use_32_bit_worker = true

    application_stack {
      docker_image_name        = "hello-world:latest"
      docker_registry_url      = "https://${data.azurerm_container_registry.this.login_server}"
      docker_registry_username = data.azurerm_container_registry.this.admin_username
      docker_registry_password = data.azurerm_container_registry.this.admin_password
    }
  }

  app_settings = {
    ExampleVar = "ExampleValue"
  }

  lifecycle {
    ignore_changes = [ 
      site_config[0].application_stack[0].docker_image_name,
      app_settings
    ]
  }
}
```

### Debug Output/Panic Output

```shell
1st plan:

Terraform will perform the following actions:

  # azurerm_linux_web_app.this will be created
  + resource "azurerm_linux_web_app" "this" {
      + app_settings                      = {
          + "ExampleVar" = "ExampleValue"
        }
      + client_affinity_enabled           = false
      + client_certificate_enabled        = false
      + client_certificate_mode           = "Required"
      + custom_domain_verification_id     = (sensitive value)
      + default_hostname                  = (known after apply)
      + enabled                           = true
      + hosting_environment_id            = (known after apply)
      + https_only                        = true
      + id                                = (known after apply)
      + key_vault_reference_identity_id   = (known after apply)
      + kind                              = (known after apply)
      + location                          = "westeurope"
      + name                              = "docker-test-service"
      + outbound_ip_address_list          = (known after apply)
      + outbound_ip_addresses             = (known after apply)
      + possible_outbound_ip_address_list = (known after apply)
      + possible_outbound_ip_addresses    = (known after apply)
      + public_network_access_enabled     = true
      + resource_group_name               = "***"
      + service_plan_id                   = "/subscriptions/***/resourceGroups/***/providers/Microsoft.Web/serverfarms/***"
      + site_credential                   = (sensitive value)
      + zip_deploy_file                   = (known after apply)

      + site_config {
          + always_on                               = true
          + container_registry_use_managed_identity = false
          + default_documents                       = (known after apply)
          + detailed_error_logging_enabled          = (known after apply)
          + ftps_state                              = "Disabled"
          + health_check_eviction_time_in_min       = (known after apply)
          + http2_enabled                           = false
          + linux_fx_version                        = (known after apply)
          + load_balancing_mode                     = "LeastRequests"
          + local_mysql_enabled                     = false
          + managed_pipeline_mode                   = "Integrated"
          + minimum_tls_version                     = "1.2"
          + remote_debugging_enabled                = false
          + remote_debugging_version                = (known after apply)
          + scm_minimum_tls_version                 = "1.2"
          + scm_type                                = (known after apply)
          + scm_use_main_ip_restriction             = false
          + use_32_bit_worker                       = false
          + vnet_route_all_enabled                  = false
          + websockets_enabled                      = false
          + worker_count                            = (known after apply)

          + application_stack {
              + docker_image_name        = "hello-world:latest"
              + docker_registry_password = (sensitive value)
              + docker_registry_url      = "https://***.azurecr.io"
              + docker_registry_username = "***"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

2nd plan:

Terraform will perform the following actions:

  # azurerm_linux_web_app.this will be updated in-place
  ~ resource "azurerm_linux_web_app" "this" {
        id                                = "/subscriptions/***/resourceGroups/***/providers/Microsoft.Web/sites/docker-test-service"
        name                              = "docker-test-service"
        tags                              = {}
        # (19 unchanged attributes hidden)

      ~ site_config {
          ~ use_32_bit_worker                       = false -> true
            # (21 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

Docker app settings (DOCKER_REGISTRY_SERVER_PASSWORD DOCKER_REGISTRY_SERVER_URL DOCKER_REGISTRY_SERVER_USERNAME) are unchanged.

### Actual Behaviour

Docker app settings are silently deleted.

### Steps to Reproduce

1. Terraform apply - create an app service with docker application_stack settings set
2. Assert the app service has the docker settings
3. Change any irrelevant setting so terraform detects infrastructure changes on the app service
4. Terraform apply - terraform will report that it will only change the irrelevant settings
5. Assert the app service docker settings have been deleted

### Important Factoids

_No response_

### References

_No response_

### LINKED ISSUE #23632: Docker-related app_settings are removed when updating site_config or app_settings => unsettling application_stack
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "app_service" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  service_plan_id     = var.service_plan_id

  app_settings = var.app_settings

  site_config {
    application_stack {
      docker_image_name   = "core/app:latest"
      docker_registry_url = "https://containerregistry.azurecr.io"
    }
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_linux_web_app.app_service will be updated in-place
~ resource "azurerm_linux_web_app" "app_service" {
    id                                = "..."
    name                              = "..."
    tags                              = {}
    # (20 unchanged attributes hidden)

  ~ site_config {
        # (22 unchanged attributes hidden)

      ~ application_stack {
          ~ docker_image_name   = "containerregistry.azurecr.io/core/app:latest" -> "core/app:latest"
          + docker_registry_url = "https://containerregistry.azurecr.io"
        }
    }

    # (2 unchanged blocks hidden)
}
```

### Expected Behaviour

1. `application_stack` settles and does not appear on subsequent runs of `terraform apply`.
2. App settings `DOCKER_REGISTRY_SERVER_URL`, `DOCKER_REGISTRY_SERVER_USERNAME`, `DOCKER_REGISTRY_SERVER_PASSWORD` are present in Azure Portal.

### Actual Behaviour

1. `application_stack` does not settle, it appears in every run of `terraform apply`. It takes time to update it on every run. Besides, it causes conflicts with updates that are implicitly triggered by other resources (e.g., Traffic Manager endpoints).
2. The aforementioned app settings are present and could be seen in Azure Portal.

### Steps to Reproduce

Option 1:
1. Define an `azurerm_linux_web_app` resource. Specify `site_config.application_stack` with `docker_image_name` and `docker_registry_url`. Apply it.
2. Change any property under `site_config` (e.g., `remote_debugging_enabled`). Apply it.
3. Run `terraform apply` once again.

Option 2:
1. Define an `azurerm_linux_web_app` resource. Specify `site_config.application_stack` with `docker_image_name` and `docker_registry_url`. Apply it.
2. Create any new app setting. Apply it.
3. Run `terraform apply` once again.

### Important Factoids

_No response_

### References

This behavior was mentioned in comments in the (already closed) #22379.

My research in the code shows that docker-related app settings are wiped-out because of these lines:
1. [linux_web_app_resource.go:766](https://github.com/hashicorp/terraform-provider-azurerm/blob/415dbc0189a48ebecb3d9279fd1e2c554606e1a5/internal/services/appservice/linux_web_app_resource.go#L766C67-L766C67) - there it will call `ExpandForUpdate` when there are changes to `site_config`.
2. [linux_web_app_schema.go:896](https://github.com/hashicorp/terraform-provider-azurerm/blob/dbf1097f896342e4424953a892a96c24d23c4f9a/internal/services/appservice/helpers/linux_web_app_schema.go#L896) - under this condition it will create the docker-related settings, but only when there are changes to `site_config.application_stack`.
3. [linux_web_app_schema.go:951](https://github.com/hashicorp/terraform-provider-azurerm/blob/dbf1097f896342e4424953a892a96c24d23c4f9a/internal/services/appservice/helpers/linux_web_app_schema.go#L951) - there it will unconditionally expand app settings (once again, only when `site_config` is changed - see point 1), **but will not create docker-related settings**.
4. [linux_web_app_resource.go:807](https://github.com/hashicorp/terraform-provider-azurerm/blob/415dbc0189a48ebecb3d9279fd1e2c554606e1a5/internal/services/appservice/linux_web_app_resource.go#L807) - coming back in the stacktrace - there it will expand app settings if they are changed. Once again, docker-related settings will not be created.
5. And the last thing: [linux_web_app_resource.go:612](https://github.com/hashicorp/terraform-provider-azurerm/blob/415dbc0189a48ebecb3d9279fd1e2c554606e1a5/internal/services/appservice/linux_web_app_resource.go#L612) - during read it will try to take docker-related settings, but if it can't find it, then it will take the plain `LinuxFxVersion` and assign it to `docker_image_name`. That is not what we have in our terraform code, thus we see it as a diff.

So, the real problem is that changing `site_config` or `app_settings` deletes docker-related settings. It finally leads to the unsettling `docker_image_name` and `docker_registry_url` - and that's how the bug appears to us.

I am unsure how this issue should be fixed:
1. Either the docker-related settings should always be set when expanding app settings for update.
2. Or the docker-related settings should be completely ignored, instead relying on decoding of the `LinuxFxVersion`.

Let me mention the guys that I've seen in the discussion of the bug: @xiaxyi @jackofallops

### LINKED ISSUE #24046: Image pull error from azure acr after linux_web_app initial deploy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.82.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

terraform {
  required_version = "1.5.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.0"
    }
  }
}

data "azurerm_subscription" "this" {}

locals {
  namespace = "testissue"
  location = "westeurope"
  resource_group_name = "MyResourceGroup"
  subscription_id = data.azurerm_subscription.this.id
}

resource "azurerm_service_plan" "this" {
  name                = "${local.namespace}plan"
  location            = local.location
  resource_group_name = local.resource_group_name
  os_type             = "Linux"
  sku_name            = "B1"
  worker_count        = 1
}

resource "azurerm_linux_web_app" "this" {
  name                = "${local.namespace}appservice"
  resource_group_name = local.resource_group_name
  location            = local.location
  service_plan_id     = azurerm_service_plan.this.id
  https_only          = true

  key_vault_reference_identity_id = azurerm_user_assigned_identity.this.id

  site_config {
    always_on                                     = false
    worker_count                                  = 1
    container_registry_use_managed_identity       = true
    container_registry_managed_identity_client_id = azurerm_user_assigned_identity.this.client_id
    application_stack {
      docker_image_name   = "test/appsvc-tutorial-custom-image:latest"
      docker_registry_url = "https://mytestregistry11.azurecr.io"
    }
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.this.id]
  }
}
resource "azurerm_user_assigned_identity" "this" {
  name                = "${local.namespace}-app-service"
  location            = local.location
  resource_group_name = local.resource_group_name
}

resource "azurerm_role_definition" "acr_access" {
  name        = "${local.namespace}-acr-access-${local.location}"
  scope       = local.subscription_id
  description = "Custom role to access acr"

  permissions {
    actions     = ["Microsoft.ContainerRegistry/registries/pull/read"]
    not_actions = []
  }

  assignable_scopes = [
    local.subscription_id
  ]
}

resource "azurerm_role_assignment" "acr_access" {
  scope = azurerm_linux_web_app.this.id
  role_definition_name = "AcrPull"
  principal_id         = azurerm_user_assigned_identity.this.principal_id
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Image pull from azr should be working both with identity and credentials after the initial deploy

### Actual Behaviour

Image pull error
ERROR

To fix this, I can go to deployment center and change image version to any other one and click "save". After this, everything starts to work

### Steps to Reproduce

Setup azure containers registry, push any image
Create resource group
Change corresponding values in terraform code(resource_group_name,docker_image_name, docker_registry_url)
Terraform apply

Check deployment center logs

To fix this, I can go to deployment center and change image version to any other one and click "save". After this, everything starts to work
SUCCESS

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by jackofallops**
* `azurerm_linux_web_app` - fix a bug in `app_settings` where settings could be lost
* `azurerm_linux_web_app_slot` - fix a bug in `app_settings` where settings could be lost
* `azurerm_windows_web_app` - fix a bug in `app_settings` where settings could be lost
* `azurerm_windows_web_app_slot` - fix a bug in `app_settings` where settings could be lost

closes #24046
closes #23632
closes #23525
closes #22379 

supersedes #24086

### CODE REVIEW

**Review by stephybun — APPROVED** [review]
Thanks @jackofallops LGTM 👍

**Comment by cleverer** [comment]
Does this maybe also fix any of #16876, #22878, or #23713?

**Comment by jackofallops** [comment]
> Does this maybe also fix any of #16876, #22878, or #23713?

Hi @cleverer - I've not tested for that or had time to try and repro it for this change. It _might_, but wasn't the intent of the change, so I can't guarantee it's the same root issue being fixed. I'm due to go on holiday leave after today, so if it's not resolved it, I'll try and look into it when I'm back in the New Year if nobody else gets there first.

**Comment by jackofallops** [comment]
Tests passing, apart from one transient fail:

image

**Comment by cleverer** [comment]
Unfortunately the fix here seems to still not solve the original issues. :(

Repro still produces the old known behaviour: https://github.com/Contactify-AG/terraform-bug-reproduction

**Pull request merged**
