### PR TITLE
`azurerm_monitor_action_group` - fix `event_hub_receiver` when dependent event_hub is not in the same resource group

### PR DESCRIPTION
**Pull request by teowa**
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/17091
- In terraform config, when the `azurerm_monitor_action_group` and its dependency `azurerm_event_hub` are in different resource groups. A `terraform plan` command right after `terraform apply` will still show changes exist. This bug happened by replace `event_hub_name`,  `event_hub_namespace` ,and `subscription_id` with `event_hub_id` in terraform schema, and when perform Read() function, use the Action Group's resource group to construct the `event_hub_id` and then write it to the state (see [source code](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_action_group_resource.go#L547)), but `event_hub_id` has a different resource group.
- To fix this, use seperate properties(`event_hub_name`,  `event_hub_namespace` ,and `subscription_id`) in terraform schema which is same with [REST API](https://github.com/Azure/azure-rest-api-specs/blob/b0f48ad950e29525d407607c336b549bcfb15333/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-09-01/actionGroups_API.json#L920).
- see also: [original PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14771), [swagger file](https://github.com/Azure/azure-rest-api-specs/blob/b0f48ad950e29525d407607c336b549bcfb15333/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-09-01/actionGroups_API.json#L920)
<details>
<summary>Test Result</summary>

```
TF_ACC=1 go test -v ./internal/services/monitor -run=TestAccMonitorActionGroup_ -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccMonitorActionGroup_basic
=== PAUSE TestAccMonitorActionGroup_basic
=== RUN   TestAccMonitorActionGroup_requiresImport
=== PAUSE TestAccMonitorActionGroup_requiresImport
=== RUN   TestAccMonitorActionGroup_emailReceiver
=== PAUSE TestAccMonitorActionGroup_emailReceiver
=== RUN   TestAccMonitorActionGroup_itsmReceiver
=== PAUSE TestAccMonitorActionGroup_itsmReceiver
=== RUN   TestAccMonitorActionGroup_azureAppPushReceiver
=== PAUSE TestAccMonitorActionGroup_azureAppPushReceiver
=== RUN   TestAccMonitorActionGroup_smsReceiver
=== PAUSE TestAccMonitorActionGroup_smsReceiver
=== RUN   TestAccMonitorActionGroup_webhookReceiver
=== PAUSE TestAccMonitorActionGroup_webhookReceiver
=== RUN   TestAccMonitorActionGroup_automationRunbookReceiver
=== PAUSE TestAccMonitorActionGroup_automationRunbookReceiver
=== RUN   TestAccMonitorActionGroup_voiceReceiver
=== PAUSE TestAccMonitorActionGroup_voiceReceiver
=== RUN   TestAccMonitorActionGroup_logicAppReceiver
=== PAUSE TestAccMonitorActionGroup_logicAppReceiver
=== RUN   TestAccMonitorActionGroup_azureFunctionReceiver
=== PAUSE TestAccMonitorActionGroup_azureFunctionReceiver
=== RUN   TestAccMonitorActionGroup_armRoleReceiver
=== PAUSE TestAccMonitorActionGroup_armRoleReceiver
=== RUN   TestAccMonitorActionGroup_eventHubReceiver
=== PAUSE TestAccMonitorActionGroup_eventHubReceiver
=== RUN   TestAccMonitorActionGroup_complete
=== PAUSE TestAccMonitorActionGroup_complete
=== RUN   TestAccMonitorActionGroup_disabledUpdate
=== PAUSE TestAccMonitorActionGroup_disabledUpdate
=== RUN   TestAccMonitorActionGroup_singleReceiverUpdate
=== PAUSE TestAccMonitorActionGroup_singleReceiverUpdate
=== RUN   TestAccMonitorActionGroup_multipleReceiversUpdate
=== PAUSE TestAccMonitorActionGroup_multipleReceiversUpdate
=== CONT  TestAccMonitorActionGroup_basic
=== CONT  TestAccMonitorActionGroup_logicAppReceiver
=== CONT  TestAccMonitorActionGroup_smsReceiver
=== CONT  TestAccMonitorActionGroup_multipleReceiversUpdate
--- PASS: TestAccMonitorActionGroup_smsReceiver (176.22s)
=== CONT  TestAccMonitorActionGroup_singleReceiverUpdate
--- PASS: TestAccMonitorActionGroup_basic (177.45s)
=== CONT  TestAccMonitorActionGroup_disabledUpdate
--- PASS: TestAccMonitorActionGroup_logicAppReceiver (188.07s)
=== CONT  TestAccMonitorActionGroup_complete
--- PASS: TestAccMonitorActionGroup_multipleReceiversUpdate (437.50s)
=== CONT  TestAccMonitorActionGroup_eventHubReceiver
--- PASS: TestAccMonitorActionGroup_disabledUpdate (271.34s)
=== CONT  TestAccMonitorActionGroup_armRoleReceiver
--- PASS: TestAccMonitorActionGroup_complete (366.55s)
=== CONT  TestAccMonitorActionGroup_azureFunctionReceiver
--- PASS: TestAccMonitorActionGroup_armRoleReceiver (154.52s)
=== CONT  TestAccMonitorActionGroup_automationRunbookReceiver
--- PASS: TestAccMonitorActionGroup_eventHubReceiver (260.93s)
=== CONT  TestAccMonitorActionGroup_voiceReceiver
--- PASS: TestAccMonitorActionGroup_azureFunctionReceiver (218.85s)
=== CONT  TestAccMonitorActionGroup_webhookReceiver
--- PASS: TestAccMonitorActionGroup_automationRunbookReceiver (206.60s)
=== CONT  TestAccMonitorActionGroup_requiresImport
=== CONT  TestAccMonitorActionGroup_azureAppPushReceiver
--- PASS: TestAccMonitorActionGroup_voiceReceiver (142.67s)
--- PASS: TestAccMonitorActionGroup_webhookReceiver (88.95s)
=== CONT  TestAccMonitorActionGroup_itsmReceiver
--- PASS: TestAccMonitorActionGroup_azureAppPushReceiver (96.10s)
=== CONT  TestAccMonitorActionGroup_emailReceiver
--- PASS: TestAccMonitorActionGroup_requiresImport (172.85s)
--- PASS: TestAccMonitorActionGroup_itsmReceiver (212.75s)
--- PASS: TestAccMonitorActionGroup_emailReceiver (156.27s)
--- PASS: TestAccMonitorActionGroup_singleReceiverUpdate (1208.86s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor       1385.119s
```

</details>

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
How does the service know what eventhub to use as cannot you not have eventhubs with the same name in 2 different resource groups? if you create a test with the same named eventhub in two different resource groups what happens then?

**Comment by teowa** [comment]
> How does the service know what eventhub to use as cannot you not have eventhubs with the same name in 2 different resource groups? if you create a test with the same named eventhub in two different resource groups what happens then?

Hi @katbyte , thanks for review, the eventhub ID is like `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.EventHub/namespaces/namespace1/eventhubs/eventhub1`, the eventhub namespace name (e.g. namespace1) is unique. From [doc](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-create#create-an-event-hubs-namespace), eventhub namespace is used to concat a domain name(`//<my namespace>.servicebus.windows.net`):
image I also test that we cannot create two same eventhub namespace in two different subscription.

So with `event_hub_namespace` and `event_hub_name`, service can comfirm a specific eventhub. It is ok for same named eventhub in two different resource groups (in two different namespace), it is also OK for same named eventhub in same resource group but in two different eventhub namespaces.

**Review by katbyte — CHANGES_REQUESTED** [review]
👍 

Have some test failures to fix and then this should be good:
image

**Comment by teowa** [comment]
I have submit another PR https://github.com/hashicorp/terraform-provider-azurerm/pull/18190 to fix the failed tests.

**Review by katbyte — APPROVED** [review]
LGTM 🚜

**Pull request merged**
