### PR TITLE
Writing the property `default_hostname`  back to state for function apps

### PR DESCRIPTION
**Pull request by xiaxyi**
fixing issue:https://github.com/hashicorp/terraform-provider-azurerm/issues/16263

### CODE REVIEW

**Comment by reifnir** [comment]
Hi @xiaxyi , it looks like there are now conflicts with this MR due to recent merges.

**Comment by reifnir** [comment]
I'm happy to make the changes to fix this, but don't want to steal your thunder if you want to take care of it

**Review by katbyte — APPROVED** [review]
Thanks @xiaxyi - LGTM once the merge conflicts are fixed (and theres a test failure that would be good to fix up too)

```
------- Stdout: -------
=== RUN   TestAccWindowsFunctionApp_addAppSettings
=== PAUSE TestAccWindowsFunctionApp_addAppSettings
=== CONT  TestAccWindowsFunctionApp_addAppSettings
    testcase.go:110: Step 3/6 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_windows_function_app.test will be updated in-place
          ~ resource "azurerm_windows_function_app" "test" {
                id                                = "/subscriptions/*******/resourceGroups/acctestRG-LFA-220706171542149292/providers/Microsoft.Web/sites/acctest-WFA-220706171542149292"
                name                              = "acctest-WFA-220706171542149292"
                tags                              = {}
                # (25 unchanged attributes hidden)
        
        
              ~ site_config {
                    # (23 unchanged attributes hidden)
        
                  + application_stack {
                      + node_version                = "~14"
                      + use_dotnet_isolated_runtime = false
                    }
                }
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccWindowsFunctionApp_addAppSettings (378.66s)
FAIL
```

**Comment by xiaxyi** [comment]
Thanks @katbyte , the test failure should have nothing to do with the property in this pr. I will check the test failures and submit a pr for the fix once I find the cause.

**Comment by xiaxyi** [comment]
> I'm happy to make the changes to fix this, but don't want to steal your thunder if you want to take care of it
Thanks for offering the help! I resolved the conflicts. :)

**Pull request merged**
