### PR TITLE
hdinsight: migrate to go-azure-sdk

### PR DESCRIPTION
**Pull request by katbyte**

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
x-link: https://github.com/hashicorp/go-azure-sdk/issues/518

**Comment by tombuildsstuff** [comment]
Should be possible to pick this one up now after a rebase, details are in the ticket above

**Comment by jackofallops** [comment]
@mbfrahry - Could you take a look at the related SDK Issue to unblock this? 
https://github.com/hashicorp/go-azure-sdk/issues/518#issuecomment-1663296263
Thanks!

**Comment by tombuildsstuff** [comment]
This needs rework & rebasing - closing this / will reopen a replacement shortly.

**Pull request closed without merging**
