### PR TITLE
azurerm_kusto_eventgrid_data_connection - support database_routing, eventgrid_resource_id, managed_identity_resource_id

### PR DESCRIPTION
**Pull request by liuwuliuyun**
…nnection.

### CODE REVIEW

**Comment by liuwuliuyun** [comment]
Add `database_routing` `eventgrid_resource_id` `managed_identity_resource_id` to azurerm_kusto_eventgrid_data_connection

**Comment by liuwuliuyun** [comment]
Testing evidence will be provided in the next comment.

**Comment by liuwuliuyun** [comment]
After fixing the testing and format problem, here are the test results:

2022-07-06T07:17:48.5279039Z ##[debug]Evaluating condition for step: 'Run test in parallel'
2022-07-06T07:17:48.5280449Z ##[debug]Evaluating: SucceededNode()
2022-07-06T07:17:48.5280949Z ##[debug]Evaluating SucceededNode:
2022-07-06T07:17:48.5281878Z ##[debug]=> True
2022-07-06T07:17:48.5282337Z ##[debug]Result: True
2022-07-06T07:17:48.5283028Z ##[section]Starting: Run test in parallel
2022-07-06T07:17:48.5290952Z ==============================================================================
2022-07-06T07:17:48.5291228Z Task         : Bash
2022-07-06T07:17:48.5291453Z Description  : Run a Bash script on macOS, Linux, or Windows
2022-07-06T07:17:48.5291761Z Version      : 3.201.1
2022-07-06T07:17:48.5291961Z Author       : Microsoft Corporation
2022-07-06T07:17:48.5292257Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2022-07-06T07:17:48.5292650Z ==============================================================================
2022-07-06T07:17:48.5472734Z ##[debug]Using node path: /home/vsts/agents/2.206.0/externals/node10/bin/node
2022-07-06T07:17:48.6521315Z ##[debug]agent.TempDirectory=/home/vsts/work/_temp
2022-07-06T07:17:48.6539378Z ##[debug]loading inputs and endpoints
2022-07-06T07:17:48.6547279Z ##[debug]loading INPUT_TARGETTYPE
2022-07-06T07:17:48.6560221Z ##[debug]loading INPUT_FILEPATH
2022-07-06T07:17:48.6561941Z ##[debug]loading INPUT_SCRIPT
2022-07-06T07:17:48.6563863Z ##[debug]loading INPUT_WORKINGDIRECTORY
2022-07-06T07:17:48.6565412Z ##[debug]loading INPUT_FAILONSTDERR
2022-07-06T07:17:48.6567025Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2022-07-06T07:17:48.6568862Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2022-07-06T07:17:48.6570603Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2022-07-06T07:17:48.6577002Z ##[debug]loading SECRET_ARM_SUBSCRIPTION_ID
2022-07-06T07:17:48.6578389Z ##[debug]loading SECRET_ARM_CLIENT_ID
2022-07-06T07:17:48.6579790Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2022-07-06T07:17:48.6581174Z ##[debug]loading SECRET_ARM_TENANT_ID
2022-07-06T07:17:48.6581810Z ##[debug]loading SECRET_ARM_CLIENT_SECRET
2022-07-06T07:17:48.6582362Z ##[debug]loaded 13
2022-07-06T07:17:48.6587155Z ##[debug]Agent.ProxyUrl=undefined
2022-07-06T07:17:48.6587717Z ##[debug]Agent.CAInfo=undefined
2022-07-06T07:17:48.6588271Z ##[debug]Agent.ClientCert=undefined
2022-07-06T07:17:48.6588850Z ##[debug]Agent.SkipCertValidation=undefined
2022-07-06T07:17:48.6597188Z ##[debug]check path : /home/vsts/work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.201.1/task.json
2022-07-06T07:17:48.6599985Z ##[debug]adding resource file: /home/vsts/work/_tasks/Bash_6c731c3c-3c68-459a-a5c9-bde6e6595b5b/3.201.1/task.json
2022-07-06T07:17:48.6600831Z ##[debug]system.culture=en-US
2022-07-06T07:17:48.6614308Z ##[debug]failOnStderr=false
2022-07-06T07:17:48.6617459Z ##[debug]workingDirectory=/home/vsts/work/1/s/20220706.1/go/src/github.com/terraform-providers/terraform-provider-azurerm
2022-07-06T07:17:48.6619209Z ##[debug]check path : /home/vsts/work/1/s/20220706.1/go/src/github.com/terraform-providers/terraform-provider-azurerm
2022-07-06T07:17:48.6619966Z ##[debug]targetType=inline
2022-07-06T07:17:48.6620516Z ##[debug]bashEnvValue=undefined
2022-07-06T07:17:48.6621499Z ##[debug]script=TF_ACC=1 go test -parallel 20 -v ./internal/services/kusto -run=TestAccKustoEventGridDataConnection_ -timeout '720m' -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
2022-07-06T07:17:48.6629364Z Generating script.
2022-07-06T07:17:48.6632447Z ##[debug]which 'bash'
2022-07-06T07:17:48.6642892Z ##[debug]found: '/usr/bin/bash'
2022-07-06T07:17:48.6643260Z Script contents:
2022-07-06T07:17:48.6644129Z TF_ACC=1 go test -parallel 20 -v ./internal/services/kusto -run=TestAccKustoEventGridDataConnection_ -timeout '720m' -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
2022-07-06T07:17:48.6644913Z ##[debug]Agent.Version=2.206.0
2022-07-06T07:17:48.6645497Z ##[debug]agent.tempDirectory=/home/vsts/work/_temp
2022-07-06T07:17:48.6646396Z ##[debug]check path : /home/vsts/work/_temp
2022-07-06T07:17:48.6652639Z ========================== Starting Command Output ===========================
2022-07-06T07:17:48.6655961Z ##[debug]which '/usr/bin/bash'
2022-07-06T07:17:48.6657438Z ##[debug]found: '/usr/bin/bash'
2022-07-06T07:17:48.6658206Z ##[debug]/usr/bin/bash arg: /home/vsts/work/_temp/795d439d-c681-44bf-a7cd-68bbdf103188.sh
2022-07-06T07:17:48.6662421Z ##[debug]exec tool: /usr/bin/bash
2022-07-06T07:17:48.6662972Z ##[debug]arguments:
2022-07-06T07:17:48.6664708Z ##[debug]   /home/vsts/work/_temp/795d439d-c681-44bf-a7cd-68bbdf103188.sh
2022-07-06T07:17:48.6665497Z [command]/usr/bin/bash /home/vsts/work/_temp/795d439d-c681-44bf-a7cd-68bbdf103188.sh
2022-07-06T07:24:39.5251180Z === RUN   TestAccKustoEventGridDataConnection_basic
2022-07-06T07:24:39.5291561Z === PAUSE TestAccKustoEventGridDataConnection_basic
2022-07-06T07:24:39.5292471Z === RUN   TestAccKustoEventGridDataConnection_requiresImport
2022-07-06T07:24:39.5293374Z === PAUSE TestAccKustoEventGridDataConnection_requiresImport
2022-07-06T07:24:39.5294237Z === RUN   TestAccKustoEventGridDataConnection_complete
2022-07-06T07:24:39.5294669Z === PAUSE TestAccKustoEventGridDataConnection_complete
2022-07-06T07:24:39.5295082Z === RUN   TestAccKustoEventGridDataConnection_mappingRule
2022-07-06T07:24:39.5295683Z === PAUSE TestAccKustoEventGridDataConnection_mappingRule
2022-07-06T07:24:39.5296174Z === RUN   TestAccKustoEventGridDataConnection_userAssignedIdentity
2022-07-06T07:24:39.5296693Z === PAUSE TestAccKustoEventGridDataConnection_userAssignedIdentity
2022-07-06T07:24:39.5297194Z === RUN   TestAccKustoEventGridDataConnection_systemAssignedIdentity
2022-07-06T07:24:39.5297716Z === PAUSE TestAccKustoEventGridDataConnection_systemAssignedIdentity
2022-07-06T07:24:39.5298193Z === RUN   TestAccKustoEventGridDataConnection_update
2022-07-06T07:24:39.5298657Z === PAUSE TestAccKustoEventGridDataConnection_update
2022-07-06T07:24:39.5299121Z === CONT  TestAccKustoEventGridDataConnection_basic
2022-07-06T07:24:39.5299618Z === CONT  TestAccKustoEventGridDataConnection_userAssignedIdentity
2022-07-06T07:24:39.5300105Z === CONT  TestAccKustoEventGridDataConnection_update
2022-07-06T07:24:39.5300583Z === CONT  TestAccKustoEventGridDataConnection_systemAssignedIdentity
2022-07-06T07:24:39.5301074Z === CONT  TestAccKustoEventGridDataConnection_complete
2022-07-06T07:24:39.5301533Z === CONT  TestAccKustoEventGridDataConnection_mappingRule
2022-07-06T07:24:39.5302016Z === CONT  TestAccKustoEventGridDataConnection_requiresImport
2022-07-06T07:45:42.8888255Z --- PASS: TestAccKustoEventGridDataConnection_userAssignedIdentity (1263.36s)
2022-07-06T07:46:47.1343231Z --- PASS: TestAccKustoEventGridDataConnection_basic (1327.61s)
2022-07-06T07:47:27.6423006Z --- PASS: TestAccKustoEventGridDataConnection_mappingRule (1368.11s)
2022-07-06T07:47:42.6616521Z --- PASS: TestAccKustoEventGridDataConnection_requiresImport (1383.13s)
2022-07-06T07:47:46.8084330Z --- PASS: TestAccKustoEventGridDataConnection_systemAssignedIdentity (1387.28s)
2022-07-06T07:47:47.2849007Z --- PASS: TestAccKustoEventGridDataConnection_complete (1387.76s)
2022-07-06T07:51:08.4404934Z --- PASS: TestAccKustoEventGridDataConnection_update (1588.91s)
2022-07-06T07:51:09.2353421Z PASS
2022-07-06T07:51:09.2354976Z ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto	1588.939s
2022-07-06T07:51:09.2375564Z ##[debug]Exit code 0 received from tool '/usr/bin/bash'
2022-07-06T07:51:09.2376796Z ##[debug]STDIO streams have closed for tool '/usr/bin/bash'
2022-07-06T07:51:09.2383221Z ##[debug]task result: Succeeded
2022-07-06T07:51:09.2386240Z ##[debug]Processed: ##vso[task.complete result=Succeeded;done=true;]
2022-07-06T07:51:09.2392190Z ##[section]Finishing: Run test in parallel

**Comment by liuwuliuyun** [comment]
Test result after Change database_routing to database_routing_type:
GOROOT=D:\Program Files\Go #gosetup
GOPATH=C:\Users\yunliu1\go #gosetup
"D:\Program Files\Go\bin\go.exe" test -c -o C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoEventGridDataConnection_complete_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto__1_.test.exe github.com/hashicorp/terraform-provider-azurerm/internal/services/kusto #gosetup
"D:\Program Files\Go\bin\go.exe" tool test2json -t C:\Users\yunliu1\AppData\Local\Temp\GoLand\___TestAccKustoEventGridDataConnection_complete_in_github_com_hashicorp_terraform_provider_azurerm_internal_services_kusto__1_.test.exe -test.v -test.paniconexit0 -test.run ^\QTestAccKustoEventGridDataConnection_complete\E$ #gosetup
=== RUN   TestAccKustoEventGridDataConnection_complete
=== PAUSE TestAccKustoEventGridDataConnection_complete
=== CONT  TestAccKustoEventGridDataConnection_complete
--- PASS: TestAccKustoEventGridDataConnection_complete (1418.79s)
PASS


Process finished with the exit code 0

**Review by katbyte — APPROVED** [review]
LGTM 🦕

**Pull request merged**
