### PR TITLE
azurerm_machine_learning_compute_cluster, azurerm_machine_learning_compute_cluster, azurerm_machine_learning_synapse_spark - support for local_auth_enabled

### PR DESCRIPTION
**Pull request by ms-henglu**

### CODE REVIEW

**Comment by katbyte** [comment]
Looks like we have a test failure:
```
------- Stdout: -------
=== RUN   TestAccComputeInstance_complete
=== PAUSE TestAccComputeInstance_complete
=== CONT  TestAccComputeInstance_complete
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Subnet: (Name "internal" / Virtual Network Name "acctest21102183" / Resource Group "acctestRG-ml-211021215647677883"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet internal is in use by /subscriptions/6f0c81c6-8c1e-44be-834a-6818378c1b83/resourceGroups/c185c517-19c5-43ee-bf68-7875ba800082-AzureBatch-CloudService/providers/Microsoft.Network/networkInterfaces/|providers|Microsoft.Compute|virtualMachineScaleSets|c185c517-19c5-43ee-bf68-7875ba800082-AzureBatch-Deployment|virtualMachines|1|networkInterfaces|nic1/ipConfigurations/ip1 and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
        
--- FAIL: TestAccComputeInstance_complete (935.12s)
```

**Comment by ms-henglu** [comment]
image

Test passed in local

**Comment by ms-henglu** [comment]
@katbyte , Hi, I run tests on tc again, though there still are some failures, but the cause is exist key vault error. The `TestAccComputeInstance_complete` test is passed. Please take another look, thanks!

image

**Review by katbyte — APPROVED** [review]
Thanks @ms-henglu - LGTM< 🔥

**Pull request merged**
