### PR TITLE
Dataset blob store location path can be empty

### PR DESCRIPTION
**Pull request by gkman**
Screen Shot 2022-03-30 at 3 45 54 PM

### CODE REVIEW

**Comment by gkman** [comment]
I hope I did this right and I didn't assume anything.

**Comment by jackofallops** [comment]
Hi @gkman - Could you add a test case that covers a configuration without a value for `path`? I suspect that this will reveal there will need to be other code changes (in `expandDataFactoryDatasetAzureBlobStorageLocation`) to correctly handle this schema change.

**Comment by gkman** [comment]
@jackofallops Sure thing, I think I added a test properly covering your request. I am however getting some inconsistent errors in the `Vendor Dependencies Check` and the `GoLang Linting` check. TBH, I have yet to full setup a local dev environment for this project, so I currently am not running all the tests, specifically the `Acceptance Tests`.

**Comment by gkman** [comment]
@jackofallops just checking, was there anything else I'm missing

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @gkman - overall looks good! tests pass so just need the docs updated changing from required to optional and this is good to merge :)

**Comment by gkman** [comment]
oh whoops, so worried about functionality, I forgot about the docs!

**Review by katbyte — APPROVED** [review]
thanks @gkman - LGTM now 🚀

**Pull request merged**
