### PR TITLE
`keyvault`: populating the cache using both the Key Vault List and Resources API to workaround incomplete/stale data being returned

### LINKED ISSUE #25548: Error: Unable to determine the Resource ID for the Key Vault at URL
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
# Just a bunch of secrets

terraform {
  required_version = "1.6.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.96.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.47.0"
    }
  }
}


resource "azurerm_key_vault_secret" "my_secret" {
  name         = "my-secret"
  value        = data.aiven_service_component.kafka_sasl.host
  key_vault_id = var.key_vault_id
  tags         = {}
}
```

### Debug Output/Panic Output

```shell
# Terraform destroy fails with and bunch of these errors when destroying secrets in the KV.

Error: Unable to determine the Resource ID for the Key Vault at URL "https://test-1234-kv.vault.azure.net/"
```

### Expected Behaviour

destroy completes successfully

### Actual Behaviour

destroy fails with 

Error: Unable to determine the Resource ID for the Key Vault at URL "https://test-1234-kv.vault.azure.net/"

### Steps to Reproduce

terraform destroy -auto-approve -input=false -no-color -lock=false

### Important Factoids

_No response_

### References

This ticket is closed but it looks like it's still a problem with latest azurerm provider
https://github.com/hashicorp/terraform-provider-azurerm/issues/19322

### PR DESCRIPTION
**Pull request by tombuildsstuff**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description

Through a significant amount of testing and validation - plus open issues, we've identified an issue when populating the available Key Vaults for the cache, where the Key Vaults List API returns stale data. Having spend a significant amount of time investigating this issue, the API itself appears to only add and remove from the cache - rather than invalidating the cache when something changes - meaning that if there's an issue on the Azure side (or slow replication, etc) the list of available Key Vaults is invalid, and thus Key Vaults which exist are not returned through this API.

Digging into the Azure CLI implementation, the command `az keyvault list` returns a list of both Key Vaults and Managed HSMS (by default together, but this can be filtered to either type using an argument). Notably however, when loading Key Vaults this is done using an old version of the Resources API (`2015-11-01`) which is curious - and having spent a decent chunk of time digging into the Azure CLI source code, I can't find a documented reason for this, particularly for an API version this old. By contrast, when obtaining a list of Managed HSMs the Managed HSMs List API is used (that is `/subscriptions/XXX/providers/Microsoft.KeyVaults/managedHsms`).

Whilst for the life of me I can't find any meaningful context for why the Azure CLI is using this older API, since that's what the Azure CLI is using, it feels reasonable for us to also use that API version (so that users have a consistent experience when querying the available data).

Therefore.. this PR updates the Key Vault caching logic to first query using the Key Vaults List API (that is, `/subscriptions/XXX/providers/Microsoft.KeyVaults/vaults`) and then to query using the Resources API to populate the list of Key Vaults within the current Subscription. This means we are making an extra API call, but given that both of these APIs (in addition to the Resource Graph API) have known caching issues - I'm honestly not sure what we else we can do here, so this feels like a reasonable compromise.

In my testing this resolves the issues that we've been seeing (now that we can reproduce this) where there's 10 Key Vaults currently in our Subscription, but only 2 are returned when using the Key Vaults List API (even when crossing all pages) - and all 10 are returned via the Resources API - and as such I _believe_ this'll also solve #25548.

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `keyvault` - populating the Key Vaults cache using both the Key Vaults List and Resources API to workaround incomplete/stale data being returned from the API [GH-26070]

## Related Issue(s)

Fixes #25548

Dependent on #26069

### CODE REVIEW

**Review by manicminer — APPROVED** [review]
Thanks @tombuildsstuff, this LGTM ⚓

**Comment by danielino** [comment]
Hello @tombuildsstuff , i might have found a bug within the refresh after apply because an error is raised:

i have a disk encryption set that uses a key from a keyvault named xxxxxxxxxxxx (in the logs).

an error is raised because another keyvault (named zzzzzzzzzzzz in logs) is not found. 
i don't know why this vault are returned from the api, because it doesn't exists anymore.

```
│ Error: validating Key Vault Key "https://xxxxxxxxxxxx.vault.azure.net/keys/xxxxxxxxxxxxxxxx" for Disk Encryption Set: retrieving the Resource ID the Key Vault at URL "https://xxxxxxxxxxxxxxxx.vault.azure.net/": populating the Key Vaults cache for Subscription (Subscription: "my_subscription"): retrieving Key Vault (Subscription: "my_subscription"
│ Resource Group Name: "yyyyyyyyyyyyyyy"
│ Key Vault Name: "zzzzzzzzzzzz"): unexpected status 404 (404 Not Found) with error: ResourceGroupNotFound: Resource group 'OTHER_RG' could not be found.
```

**Comment by tombuildsstuff** [comment]
@danielino thanks for reporting this - I've opened https://github.com/hashicorp/terraform-provider-azurerm/pull/26199 which should resolve that

**Comment by danielino** [comment]
> @danielino thanks for reporting this - I've opened #26199 which should resolve that

you're awesome, thanks!

**Pull request merged**
