### PR TITLE
``azurerm_windows_web_app_slot``, ``azurerm_windows_function_app_slot`` - Fix error 500/409 when using virtual network subnet

### LINKED ISSUE #24618: Creating azurerm_windows_web_app_slot with virtual_network_subnet_id specified results in Internal server error (500)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0

### AzureRM Provider Version

3.88.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app_slot

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app_slot" "this" {
  name           = "test"
  app_service_id = "***"
  virtual_network_subnet_id = "***"

  site_config {
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating Windows Web App Slot: (Slot Name "***" / Site Name "***" / Resource Group "***"): web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=500 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]
│
│   with azurerm_windows_web_app_slot.this,
│   on main.tf line 144, in resource "azurerm_windows_web_app_slot" "this":
│  144: resource "azurerm_windows_web_app_slot" "this" {
│
│ creating Windows Web App Slot: (Slot Name "***" / Site Name "***" / Resource Group "***"): web.AppsClient#CreateOrUpdateSlot: Failure sending request: StatusCode=500 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"An error has occurred."}]
╵
```

### Expected Behaviour

A web app slot is created with virtual network integration

### Actual Behaviour

Error 500 is thrown, web app slot is not created.

### Steps to Reproduce

Deploy a windows web app slot with subnet specified, make sure to use v3.88.0. Issue does not occur on v3.87.0 and earlier.

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by Apokalypt**
## Community Note
* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## Description
Since the release `3.88.0`, Azure reject the creation of web app slot and function app slot when there is a virtual network subnet. Initially the API rejects all calls with an error 500 but since this morning the error is clearer and validate analysis perform by few users in the issue linked :
image

## PR Checklist

- [x] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have updated/added Documentation as required written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 

## Changes to existing Resource / Data Source

- [x] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [x] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.
> I could only run local test and not acceptance tests see below the explanation...

## Change Log

Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_windows_web_app_slot` - Force "serverFarmId" to be set when "virtualNetworkSubnetId" is set as requested by Azure API #24618 
* `azurerm_windows_function_app_slot` - Force "serverFarmId" to be set when "virtualNetworkSubnetId" is set as requested by Azure API #24618 

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

## Related Issue(s)
Fixes #24618

### CODE REVIEW

**Comment by xiaxyi** [comment]
Thanks @Apokalypt for the PR, can we please hold adding the serverFarmId in the request as I'm trying to confirm with the app service team to see if it's required. I will update the thread once I have a progress, thanks for your understanding!

**Comment by Apokalypt** [comment]
> Thanks @Apokalypt for the PR, can we please hold adding the serverFarmId in the request as I'm trying to confirm with the app service team to see if it's required. I will update the thread once I have a progress, thanks for your understanding!

Ok thanks. We will wait for your answer @xiaxyi .
If you need it for your discussion with app service team, you can find the 2 cURL request used by me to verify the error and the solution:
- Request without "serverFarmId" property --> Error 409 with body as shown in the PR description (before it was an error 500)
```Bash
curl --location --request PUT 'https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Web/sites/<web-app-name>/slots/test-error-slot?api-version=2022-09-01' \
--header 'authorization: Bearer <token>' \
--header 'content-type: application/json' \
--data '{
    "location": "West Europe",
    "kind": "app",
    "properties": {
        "virtualNetworkSubnetId": "/subscriptions/<subscription-id>/resourceGroups/<resource-group-vnet—name>/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/<subnet-name>",
        "siteConfig": {}
    }
}'
```
- Request with "serverFarmId" property --> Slot successfully created
```Bash
curl --location --request PUT 'https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Web/sites/<web-app-name>/slots/test-error-slot?api-version=2022-09-01' \
--header 'authorization: Bearer <token>' \
--header 'content-type: application/json' \
--data '{
    "location": "West Europe",
    "kind": "app",
    "properties": {
        "virtualNetworkSubnetId": "/subscriptions/<subscription-id>/resourceGroups/<resource-group-vnet—name>/providers/Microsoft.Network/virtualNetworks/<vnet-name>/subnets/<subnet-name>",
        "serverFarmId": "/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Web/serverfarms/<service-plan-name>",
        "siteConfig": {}
    }
}'
```

**Comment by xiaxyi** [comment]
Thanks @Apokalypt , I will let you know about any progress.

**Comment by Apokalypt** [comment]
@xiaxyi Have you had any news on this subject?

**Comment by sgnrl** [comment]
@xiaxyi Any updates?

**Comment by AndrewChastell** [comment]
It would be great to get this PR approved, thanks.

**Comment by SallyBirch1** [comment]
Also waiting on this PR to be approved to help unblock us.

**Comment by birenshah2** [comment]
Hi, also looking for an update on this...

**Comment by tdkeeley** [comment]
> Thanks @Apokalypt for the PR, can we please hold adding the serverFarmId in the request as I'm trying to confirm with the app service team to see if it's required. I will update the thread once I have a progress, thanks for your understanding!

@xiaxyi were you able to confirm with the app service team? [Dmitrii034](https://github.com/Dmitrii034), in the issue thread, says he confirmed with Microsoft: https://github.com/hashicorp/terraform-provider-azurerm/issues/24618#issuecomment-2009133582

[saveler](https://github.com/saveler) says a similar thing but with the specific change: https://github.com/hashicorp/terraform-provider-azurerm/issues/24618#issuecomment-2023131433

Based on the curl examples provided by @Apokalypt, serverFarmId not included, it fails, serverFarmId included, it works. The solution seems pretty clear. What else do we need in order to feel like this is an appropriate fix? This has been a blocker for a lot of us since January...

**Comment by tdkeeley** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/issues/24618#issuecomment-2110487959

> @tdkeeley Sorry, we did not get much else from that investigation. **They recommended us to specify the parameter ourselves**, but it is currently not possible due to validation on the provider. The only other thing of note is that they told us that they would make the resulting error clearer. This is probably why the new error now states that the parameter is missing. Not sure what is the reason for the current delay.

@xiaxyi what are your feelings about this? Sounds like Dmitrii034 from the issue thread was advised to specify the serverFarmId.

**Comment by xiaxyi** [comment]
Thanks everyone for your patience, we just got some updates from the service team, but still in the discussion about the api behavior, will update once we confirmed the final action

**Comment by mistyflip** [comment]
Eagerly awaiting this fix. Do you have an idea when we would have an action? Will Microsoft need to release an update as a dependency? Thankyou!

**Comment by saveler** [comment]
Hello @xiaxyi 

Do you have any idea when it will be merged?
We are blocked due to this issue, and we are waiting for the fix.

Thank you!

**Comment by xiaxyi** [comment]
@stephybun the code change looks good to me, tests are good, failed ones are not related.
- For windows web app slot:
image
- For windows function app slot:
image

More information about the api behavior:
Confirmed that the `serverFarmId` is required when creating the slot with a vNet integrated as the api needs to check whether the vNet can be enabled based on the sku level, it's just the api doesn't take the parent app service's serverFarmId as the default serverFarm for its slot currently (Not sure about the future api change...).

Even the `service_plan_id` is not a required field in the Terraform schema, however, adding the serverFarmId in the api payload won't be a breaking change to those users who are not specifying the `service_plan_id` in their config as Terraform check the parent app service's serverFarm and use it as the default severFarm for the slot.

Would you mind taking another look and let me know if you have any other concerns?

**Comment by saveler** [comment]
Hello @stephybun 

Looks like xiaxui reviewed and approves the change.
Please merge it ASAP.

Thank you in advance!

**Review by stephybun — APPROVED** [review]
Thanks @Apokalypt, thanks @xiaxyi LGTM 💯

**Pull request merged**
