### PR TITLE
`azurerm_hdinsight_kafka_cluster`, `azurerm_hdinsight_spark_cluster`, `azurerm_hdinsight_interactive_query_cluster`, `azurerm_hdinsight_hbase_cluster`, `azurerm_hdinsight_hadoop_cluster` - Add support for `extension` property

### PR DESCRIPTION
**Pull request by jiaweitao001**
* All test cases passed.

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
I think we're missing docs?

**Comment by jiaweitao001** [comment]
Hi @katbyte , documentations are updated. Thanks! The tests are also [passing](https://ci-oss.hashicorp.engineering/viewLog.html?buildId=331576&buildTypeId=TerraformOpenSource_TerraformProviders_AzureRMPublic_AZURERM_SERVICE_PUBLIC_HDINSIGHT).

**Review by katbyte — APPROVED** [review]
LGTM 🚡

**Review by katbyte — APPROVED** [review]
LGTM 🥚

**Pull request merged**
