### PR TITLE
`policy_assignment`: upate to `hashicorp/go-azure-sdk` with version `2022-06-01`

### PR DESCRIPTION
**Pull request by wuxu92**
to add featrure policy assignment overrides and resource selector.

image

### CODE REVIEW

**Comment by stephybun** [comment]
Hi @wuxu92, is this ready for review?

**Comment by wuxu92** [comment]
> Hi @wuxu92 Xu Wu FTE, is this ready for review?

@stephybun there is one Test still failing in TeamCity, i'm working on it.

**Comment by wuxu92** [comment]
Hi @stephybun this is ready for review now. thanks!

**Review by katbyte — APPROVED** [review]
LGTM 🔐

**Pull request merged**
