### PR TITLE
Upgrade Bot Email Channel API version from 2021-05-01-preview to 2022-09-15

### PR DESCRIPTION
**Pull request by neil-yechenwei**
--- PASS: TestAccBotChannelsRegistration/channel/emailBasic (202.67s)
--- PASS: TestAccBotChannelsRegistration/channel/emailUpdate (230.22s)

### CODE REVIEW

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , I raised this PR to use go-azure-sdk and change the version to 2022-09-15. Please take a look. Thanks. Once this PR is merged, I will update another PR https://github.com/hashicorp/terraform-provider-azurerm/pull/23129 accordingly.

**Review by stephybun — COMMENTED** [review]
Thanks @neil-yechenwei. Can you resolve the merge conflict? This should be good to go then.

**Comment by neil-yechenwei** [comment]
@stephybun , I resolved the conflict. Please take another look. Thanks.

**Review by stephybun — APPROVED** [review]
Thanks @neil-yechenwei LGTM 👍

**Pull request merged**
