### PR TITLE
Fix function slot  WEBSITE_CONTENTSHARE secretly changes

### LINKED ISSUE #14206: Function app slot (azurerm_function_app_slot) WEBSITE_CONTENTSHARE  secretly changes
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform version
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.11. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_function_app_slot`

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "example" {
  name = "dev-walter"
}

resource "random_integer" "example" {
  min = 1
  max = 999
}

resource "azurerm_storage_account" "example" {
  name                     = format("swaptest%s", random_integer.example.result)
  resource_group_name      = data.azurerm_resource_group.example.name
  location                 = data.azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "example" {
  name                = format("func-swaptest-plan-%s", random_integer.example.result)
  location            = data.azurerm_resource_group.example.location
  resource_group_name = data.azurerm_resource_group.example.name
  kind                = "elastic"

  sku {
    capacity = 1
    tier     = "ElasticPremium"
    size     = "EP2"
  }
}

resource "azurerm_function_app" "example" {
  name                       = format("func-swaptest-%s", random_integer.example.result)
  location                   = data.azurerm_resource_group.example.location
  resource_group_name        = data.azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  version                    = "~3"
  enable_builtin_logging     = false

  os_type = ""

  app_settings = {
    FUNCTIONS_WORKER_RUNTIME     = "node"
    WEBSITE_NODE_DEFAULT_VERSION = "~14"
    DUMMY                        = 1
  }
}

# Slot
resource "azurerm_function_app_slot" "example" {
  name                       = "staging"
  location                   = data.azurerm_resource_group.example.location
  resource_group_name        = data.azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  function_app_name          = azurerm_function_app.example.name
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  version                    = "~3"
  enable_builtin_logging     = false


  app_settings = {
    FUNCTIONS_WORKER_RUNTIME     = "node"
    WEBSITE_NODE_DEFAULT_VERSION = "~14"
    DUMMY                        = 2
  }
}
```

### Expected Behaviour

When I apply the code above a new function app and its function slot is created. In my case:
* func-swaptest-736 
* func-swaptest-736/staging

The app settings WEBSITE_CONTENTSHARE is automatically set and it assumes the following values:
* func-swaptest-7368310 (for the function)
* **staging25dd** (for the slot staging)

If I'm going to change something in the function definition and in its slot I'm not expecting to see any changes in WEBSITE_CONTENTSHARE.

### Actual Behaviour
Let's assume to set the app settings DUMMY to 2 in the function app and 3 in the function app slot.
After these changes has been applied when I check the value inside WEBSITE_CONTENTSHARE this is what I found out:
* func-swaptest-7368310 (function appp)
* staging2fdf (slot staging )

As you can see the WEBSITE_CONTENTSHARE value for the staging slot "secretly" changed breaking the function app slot.

### Steps to Reproduce

1. `terraform apply`
2. edit the functions.tf file and change the app settings values DUMMY.
3. check from the portal the value inside the app settings WEBSITE_CONTENTSHARE for slot staging
4. run `terraform apply` again
5. check from the portal the value inside the app settings WEBSITE_CONTENTSHARE for slot staging and compare it with the value you get at the step 3.

### References

* #0000

### PR DESCRIPTION
**Pull request by uolter**
This PR is aiming to fix the issue reported here:
fixes #14206

### CODE REVIEW

**Comment by uolter** [comment]
@jackofallops the real changes to apply are in the file:
internal/services/web/function_app_slot_resource.go
I've tried to use the same logic already in place for the function itself in:
* internal/services/web/function_app.go
* internal/services/web/function_app_resource.go
I hope you are going to fix this issue soon :-)

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @uolter - Apologies for the delay.  Thanks for this PR.

It looks mostly good, just a couple comments that need removing.  Also, could you remove the unrelated files from the PR?  Once that's addressed, I can authorise the workflows and get this through testing.

Thanks again!

**Comment by uolter** [comment]
@jackofallops thanks for coming back to me. I've applied all changes you suggested.
Please, let me know if something else is not appropriate.

**Review by jackofallops — APPROVED** [review]
Thanks for the quick updates @uolter, this LGTM now 👍

**Comment by jackofallops** [comment]
Tests passing:
image

**Pull request merged**
