### PR TITLE
feat: add `activated` property onto `azurerm_data_factory_trigger_schedule`

### PR DESCRIPTION
**Pull request by BrendanThompson**
This PR will bring the `trigger_schedule` in line with other `triggers` for Data Factory.

Resolves: #9018

### CODE REVIEW

**Comment by BrendanThompson** [comment]
@tombuildsstuff / @katbyte – is there anything further required in this one to get it pushed through?

**Review by katbyte — DISMISSED** [review]
Thanks for the pr @BrendanThompson - could we add that property to a test and update the docs? thanks

**Comment by BrendanThompson** [comment]
Ahh the docs, good callout!

**Comment by BrendanThompson** [comment]
@katbyte I have updated as requested 😃

**Review by tombuildsstuff — APPROVED** [review]
LGTM - thanks for this @BrendanThompson 👍

**Comment by BrendanThompson** [comment]
@katbyte – apologies for the delay, I will look into this today.

**Comment by BrendanThompson** [comment]
@katbyte are we able to kick off the acceptance testing?

**Comment by katbyte** [comment]
Thanks @BrendanThompson - looks like we have a new test failure:
```
------- Stdout: -------
=== RUN   TestAccDataFactoryTriggerSchedule_complete
=== PAUSE TestAccDataFactoryTriggerSchedule_complete
=== CONT  TestAccDataFactoryTriggerSchedule_complete
    testcase.go:88: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) {
        }
        
        
        (map[string]string) (len=1) {
         (string) (len=9) "activated": (string) (len=4) "true"
        }
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting Data Factory Trigger Schedule "acctestdf210902174441726681" (Resource Group "acctestRG-df-210902174441726681" / Data Factory "acctestdf210902174441726681"): datafactory.TriggersClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="TriggerEnabledCannotUpdate" Message="Cannot update enabled Trigger; the trigger needs to be disabled first. "
        
--- FAIL: TestAccDataFactoryTriggerSchedule_complete (94.74s)
FAIL
```

**Comment by BrendanThompson** [comment]
Thanks @katbyte will have a look at this shortly

**Comment by katbyte** [comment]
closing in favour of #13390

**Pull request closed without merging**
