### PR TITLE
Update Storage SDK to 2021-09-01

### PR DESCRIPTION
**Pull request by marc-sensenich**
- Updates the Storage SDK to 2021-09-01 as a prerequisite for https://github.com/hashicorp/terraform-provider-azurerm/issues/17083
- Resolves bugs in `d/azurerm_storage_management_policy` leading to test failures

### CODE REVIEW

**Comment by marc-sensenich** [comment]
## Local Acceptance Test Status

All tests passed for me, except for the following noted below
- TestAccStorageAccount_edgeZone
  - I don't have edge zones enabled for my testing subscription, therefore I get the error `no extended locations were found for the location "westus"`
- TestAccStorageAccount_updateToUsingIdentityAndCustomerManagedKey
  - Getting the following error with Storage SDK `2021-04-01` or `2021-09-01` and could be looked at in a separate issue.
```
testcase.go:110: ImportStateVerify attributes not equivalent. Difference is shown below. Top is actual, bottom is expected.
        
        (map[string]string) (len=5) {
         (string) (len=18) "share_properties.#": (string) (len=1) "1",
         (string) (len=20) "share_properties.0.%": (string) (len=1) "3",
         (string) (len=37) "share_properties.0.retention_policy.#": (string) (len=1) "1",
         (string) (len=39) "share_properties.0.retention_policy.0.%": (string) (len=1) "1",
         (string) (len=42) "share_properties.0.retention_policy.0.days": (string) (len=1) "7"
        }
        
        
        (map[string]string) {
        }
```

**Comment by ltalirz** [comment]
Looking forward to this contribution being merged!

**Review by katbyte — CHANGES_REQUESTED** [review]
THanks for the PR @marc-sensenich - looks good aside from these properties need to be added to the docs, once thats done (and acctest pass) this should be good to merge!

**Comment by katbyte** [comment]
also it looks like this was duplicated by #17523 which upgraded the SDK to this api version, but didn't add those properties so i would merge main before continuing

**Pull request closed without merging**
