### PR TITLE
Update link milestone GHA to securely link milestones for PRs from forked repos

### PR DESCRIPTION
**Pull request by stephybun**
As per security guidelines an explicit checkout should be avoided when using `pull_request_target`. Unfortunately this functionality relies on the contents of the CHANGELOG.md in order to determine the version number of the next release which corresponds to the milestones used in this project. Thus a checkout of the code is unavoidable and this needed to be split into two separate GHA.

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 🙌

**Comment by katbyte** [comment]
one comment upon a 2nd read - instead of reading the changelog would it be possible to grab a list of all milestones and instead default to the lowest open one? ie if we have `2.84, 2.85, 2.86,3.0` as open milestones we pick 2.84 and thus avoid checking out any code?

**Comment by stephybun** [comment]
Yeah, that thought had occurred to me as I opened the PR last night. I wanted to double check our process around the milestones e.g. is any part of it already semi automated like the closing/creation of them.

Converting this to a draft PR to redo.

**Comment by katbyte** [comment]
No, typically just before  i do the release i move all the remaining open issues/PRs to the next milestone (Creating it and the next X if it doesn't) and then closing the old one so the lowest unclosed milestone will always be the correct one. 

When we do a hotfix that milestone is usually created populated and closed pretty quick - thou your code could easily avoid those by only looking for x.y.0 milestones and not assigning anything to x.y.[1-9] as those are always special rare cases

**Comment by stephybun** [comment]
Closing in favour of #14190

**Pull request closed without merging**
