### PR TITLE
`azurerm_postgresql_flexible_server_*` - Add lock to avoid operation conflict

### PR DESCRIPTION
**Pull request by neil-yechenwei**
Service team confirmed that the service API doesn't allow to operate `azurerm_postgresql_flexible_server_configuration`, `azurerm_postgresql_flexible_server_database` and `azurerm_postgresql_flexible_server_firewall_rule` simultaneously.
So submitted this PR to fix this issue against the service API limitation for them.

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@neil-yechenwei these would indicate we need to add Locks to workaround this, this isn't something users should need to workaround in their configs - can we look to add locks rather than pushing this on users instead?

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , seems the resource name or resource id is required while adding locks. But these resources cannot know their respective resource name or resource id. So seems I cannot add lock for them.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei this can be computed based on the fields available, so this is possible.

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , is there any sample for your suggestion?

**Comment by tombuildsstuff** [comment]
@neil-yechenwei we can lock on the Postgres Flexible Server ID, since these resources all operate against a server.

**Comment by neil-yechenwei** [comment]
@tombuildsstuff , thanks for the suggestion. Updated PR.

**Comment by neil-yechenwei** [comment]
image

**Review by katbyte — APPROVED** [review]
LGTM 🔒

**Pull request merged**
