### PR TITLE
WIP - Support for new Azure Front Door Standard/Premium

### PR DESCRIPTION
**Pull request by heoelri**
Hi folks,

this is a first attempt (still work in progress) to implement support for the new (still in preview) Azure Front Door Standard/Premium service. Other than the name suggests is this a whole new service and requires new resources instead of extending the existing `azurerm_frontdoor` resources.

@WodansSon / @joaomoreno / @sebader not sure if anyone else is already working on this. Creating this as a draft PR for your awareness and to invite you to join the discussion and perhaps to get this done together.

## Current state
Given the fact that the new Front Door services is under the `Microsoft.Cdn` namespace, I've started with resource names following this theme. What's currently there:

* `azurerm_cdn_frontdoor_profile` This is just an alias for `azurerm_cdn_profile`. The `azurerm_cdn_profile` was modified to support the two new SKUs `Standard_AzureFrontDoor` and `Premium_AzureFrontDoor`.
* `azurerm_cdn_frontdoor_endpoint` New resource to create endpoints.
* `azurerm_cdn_frontdoor_endpoint_route` New resource to create endpoint routes.
* `azurerm_cdn_frontdoor_origin_group` New resource to create origin groups.
* `azurerm_cdn_frontdoor_origin` New resource to create origins.
* `azurerm_cdn_frontdoor_custom_domain` New resource to create custom domains.

The arguments for the newly implemented resources are already partially documented on the corresponding docs pages.

image

## Todo
* `azurerm_cdn_frontdoor_endpoint_route` using custom domains and caching does currently not work.
* `azurerm_cdn_frontdoor_origin` using `private_link` is currently not working. I have not figured out yet how to handover the arguments as `SharedPrivateLinkResource` in `AFDOriginProperties`.
* Missing functionality and resources: RuleSets, Security and Secrets.

### CODE REVIEW

**Comment by heoelri** [comment]
As mentioned in the TODO section of this PR I struggle with the implementation of a few things.

## Private Link in `azurerm_cdn_frontdoor_origin`

I've tried to implement private link support for `azurerm_cdn_frontdoor_origin` but I struggle with the concrete implementation. Here are the arguments:

https://github.com/heoelri/terraform-provider-azurerm/blob/e47738ac6fb4aa04eeff9ac8736f6e0d7ef42a04/internal/services/cdn/afd_origin_resource.go#L105-L138

I've created a separate function called `expandPrivateLinkSettings` here:

https://github.com/heoelri/terraform-provider-azurerm/blob/e47738ac6fb4aa04eeff9ac8736f6e0d7ef42a04/internal/services/cdn/afd_origin_resource.go#L213-L237

But neither create nor update does work and always fails.

	// if d.HasChange("private_link") {
	// 	privateLink := d.Get("private_link").([]interface{})
	// 	originUpdateProperties.SharedPrivateLinkResource = expandPrivateLinkSettings(privateLink)
	// }

## Updating enabledState for various resources

Another issue I'm facing is updating the `EnabledState`. Creation in for example `azurerm_cdn_frontdoor_endpoint` and `azurerm_cdn_frontdoor_origin` works fine, but updating it doesn't work.

Here's for example the creation:

```golang
	afdOrigin := cdn.AFDOrigin{
		AFDOriginProperties: &cdn.AFDOriginProperties{
			HostName:  &hostname,
			Priority:  &priority,
			Weight:    &weight,
			HTTPPort:  &httpPort,
			HTTPSPort: &httpsPort,
		},
	}


	if enabled {
		afdOrigin.EnabledState = cdn.EnabledStateEnabled
	} else {
		afdOrigin.EnabledState = cdn.EnabledStateDisabled
	}

	// ...

	future, err := client.Create(ctx, id.ResourceGroup, id.ProfileName, originGroup.OriginGroupName, originname, afdOrigin)
```
https://github.com/heoelri/terraform-provider-azurerm/blob/e47738ac6fb4aa04eeff9ac8736f6e0d7ef42a04/internal/services/cdn/afd_origin_resource.go#L170-L184

Update therefore fails:

```golang
	if d.HasChange("enabled") {
		if d.Get("enabled").(bool) {
			// originUpdateProperties.EnabledState = cdn.EnabledStateEnabled
		} else {
			// originUpdateProperties.EnabledState = cdn.EnabledStateDisabled
		}
	}
```
https://github.com/heoelri/terraform-provider-azurerm/blob/e47738ac6fb4aa04eeff9ac8736f6e0d7ef42a04/internal/services/cdn/afd_origin_resource.go#L292-L298

```error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4686b5c]

goroutine 131 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceAfdOriginsUpdate(0xc00011c380, {0x56b2be0, 0xc00107f500})
        /home/heoelri/go/src/github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/afd_origin_resource.go:294 +0x35c
```

These are just the most pressing issues currently blocking me.

**Comment by heoelri** [comment]
Added a ton of additional documentation for the already existing resources:

* `azurerm_cdn_frontdoor_custom_domain`
* `azurerm_cdn_frontdoor_endpoint_route`
* `azurerm_cdn_frontdoor_endpoint`
* `azurerm_cdn_frontdoor_origin_group`
* `azurerm_cdn_frontdoor_origin`
* `azurerm_cdn_frontdoor_profile`

Extended `azurerm_cdn_frontdoor_profile` (which is an alias for `azurerm_cdn_profile`) to export `header_frontdoor_id`, only when SKU is set to `Standard_AzureFrontDoor` or `Premium_AzureFrontDoor`. Should not have an impact on the use of `azurerm_cdn_profile`.

# What's still missing?

* New resource for rule sets + association
* New resource for secrets + association
* Private Link support for `azurerm_cdn_frontdoor_origin` is not working
* Custom domain association for `azurerm_cdn_frontdoor_endpoint_route` is not working

**Comment by heoelri** [comment]
Private Link support for `azurerm_cdn_frontdoor_origin` is now working - at least on a rudimentary basis.

The number of available resources is still very limited. 

```hcl
resource "azurerm_cdn_frontdoor_origin" "example_origin_with_pl" {
  name            = "pl-origin-new"
  origin_group_id = azurerm_cdn_frontdoor_origin_group.example.id
  host_name       = "pl.new.xyz.com"
  weight          = 10
  priority        = 1

  enabled = true

  private_link {
    location = "westus2"
    resource_id = "/subscriptions/cb8d2bb0-ed2c-44e5-a01b-cde33c0320a4/resourceGroups/AFD-premium-rg/providers/Microsoft.Network/privateLinkServices/private-lk-srv" # azurerm_storage_account.example.id 
    approval_message = "Private Link approval request from Front Door"
  }
}
```

Thanks to @sebader for figuring out the details and helping me to test it. 

I still struggle with the `azurerm_cdn_frontdoor_endpoint_route` resource. Creating and updating this resource type fails from time to time and I haven't figured out yet why. Here's the JSON output from `terraform apply` (with `TF_LOG` set to `debug`)

```json
{
    "properties": {
        "customDomains": [
            {
                "id": "/subscriptions/cb8dxxxx-xxxx-xxxx-xxxx-cde33c0320a4/resourceGroups/afdv2demo/providers/Microsoft.Cdn/profiles/afdv2demo/customDomains/frontdoor-heyko-dev"
            }
        ],
        "enabledState": "Enabled",
        "forwardingProtocol": "MatchRequest",
        "httpsRedirect": "Disabled",
        "linkToDefaultDomain": "Disabled",
        "originGroup": {
            "id": "/subscriptions/cb8dxxxx-xxxx-xxxx-xxxx-cde33c0320a4/resourceGroups/afdv2demo/providers/Microsoft.Cdn/profiles/afdv2demo/originGroups/afdorigingroup1"
        },
        "patternsToMatch": [
            "/mypattern/*",
            "/*"
        ],
        "queryStringCachingBehavior": "NotSet",
        "ruleSets": [],
        "supportedProtocols": [
            "Https",
            "Http"
        ]
    }
}
```

And the error message is 

```console
{
  "error": {
    "code": "BadRequest",
    "message": "The requested operation cannot be executed on the entity in the current state."
  }
}
```

**Comment by heoelri** [comment]
Ok, seems like the `azurerm_cdn_frontdoor_custom_domain` resource can be added to the `azurerm_cdn_frontdoor_endpoint_route`'s `custom_domains` list. But, only after it was successfully validated.

```hcl
resource "azurerm_cdn_frontdoor_profile" "example" {
  name                = "afdv2demo"
  location            = "global"
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium_AzureFrontDoor"
}

resource "azurerm_cdn_frontdoor_origin_group" "example" {
  name = "afdorigingroup1"

  profile_id = azurerm_cdn_frontdoor_profile.example.id
}

resource "azurerm_cdn_frontdoor_endpoint" "example" {
  name       = "afdendpoint1"
  profile_id = azurerm_cdn_frontdoor_profile.example.id
}

resource "azurerm_cdn_frontdoor_custom_domain" "example" {
  name       = "frontdoor-heyko-dev"
  profile_id = azurerm_cdn_frontdoor_profile.example.id
  host_name  = "frontdoor.heyko.dev"

  tls {
    certificate_type    = "ManagedCertificate"
    minimum_tls_version = "TLS12"
  }
}

resource "azurerm_cdn_frontdoor_endpoint_route" "example" {
  name            = "example-route"
  endpoint_id     = azurerm_cdn_frontdoor_endpoint.example.id
  origin_group_id = azurerm_cdn_frontdoor_origin_group.example.id

  origin_path = "/api/*"

  forwarding_protocol = "MatchRequest"

  enable_caching                = true
  query_string_caching_behavior = "UseQueryString"
  content_types_to_compress = [
    "application/json",
    "application/gzip",
    "image/png"
  ]

  patterns_to_match = [
    "/*"
  ]

  supported_protocols = [
    "Https"
  ]

  custom_domains = [
    azurerm_cdn_frontdoor_custom_domain.example.id,
  ]
}
```

image

image

From my point of view does it not really make sense to let the `azurerm_cdn_frontdoor_custom_domain` resource wait till the domain was validated before it finishes, because it could be a manual activity, in theory, but it needs some kind of mechanism to wait till it's validated before it can be associated to an endpoint.

`DomainValidationState` in `cdn.AFDDomainProperties` holds the right information.

**Comment by heoelri** [comment]
> From my point of view does it not really make sense to let the `azurerm_cdn_frontdoor_custom_domain` resource wait till the domain was validated before it finishes, because it could be a manual activity, in theory, but it needs some kind of mechanism to wait till it's validated before it can be associated to an endpoint.
> 
> `DomainValidationState` in `cdn.AFDDomainProperties` holds the right information.

I've now implemented a check on `DomainValidationState`:

```golang
// -- domain validation -- //
domainClient := meta.(*clients.Client).Cdn.AFDCustomDomainsClient
domainId, err := parse.AfdCustomDomainID(resourceId)
if err != nil {
	return err
}

domain, err := domainClient.Get(ctx, domainId.ResourceGroup, domainId.ProfileName, domainId.CustomDomainName)
if err != nil {
	return err
}

if domain.DomainValidationState != cdn.DomainValidationStateApproved {
	return fmt.Errorf("custom domain %s (%s) cannot be associated. Validation state is %s", domainId.CustomDomainName, *domain.HostName, domain.DomainValidationState)
}
// -- end of domain validation -- //
```

That fails the creation (and update) of `azurerm_cdn_frontdoor_endpoint_route` when `DomainValidationState` is not `Approved`:

image

This is probably not the most beautiful solution, but it works. It will succeed as soon as the domain is in `Approved` state. When deploying all together (dns, txt, custom domain etc) a proper wait should be implemented on the hcl side.

**Comment by heoelri** [comment]
I struggle a bit with the new rules engine. I do not fully understand yet how to use `BasicDeliveryRuleAction` in `models.go`. 

https://github.com/hashicorp/terraform-provider-azurerm/blob/241d3d9b3155af4164c1eefd08d51faefdfd9d86/vendor/github.com/Azure/azure-sdk-for-go/services/cdn/mgmt/2020-09-01/cdn/models.go#L3147-L3158

I found something similar in `bot`, but there they're treating every channel as a separate resource. Not sure if that's the best/only way to implement that.

**Comment by WodansSon** [comment]
@heoelri thanks for this, I was actually just assigned this task to create this resource, but since you already got a jump on it would you mind if we could work on it together? I will look over the PR in more detail in the near future to have a better idea of the current state. Thanks again for opening this PR. 🚀

**Comment by heoelri** [comment]
@WodansSon that would be great! To summarize my previous comments here, I've created a couple of new resources:

* `azurerm_cdn_frontdoor_profile` This is just an alias for `azurerm_cdn_profile`. The * `azurerm_cdn_profile` was modified to support the two new SKUs `Standard_AzureFrontDoor` and `Premium_AzureFrontDoor`. It was also extended to export the `header_frontdoor_id` attribute when set to sku `*_AzureFrontDoor`.
* `azurerm_cdn_frontdoor_endpoint` New resource to create endpoints.
* `azurerm_cdn_frontdoor_endpoint_route` New resource to create endpoint routes. `azurerm_cdn_frontdoor_custom_domain` can only be associated to a `azurerm_cdn_frontdoor_endpoint_route` when `DomainValidationState` is `Approved`.
* `azurerm_cdn_frontdoor_origin_group` New resource to create origin groups.
* `azurerm_cdn_frontdoor_origin` New resource to create origins. Including support for private link service endpoints.
* `azurerm_cdn_frontdoor_custom_domain` New resource to create custom domains.


I've also added the corresponding docs and initial tests for most resources. The last thing i've started to work on is `azurerm_cdn_frontdoor_rule_set` and `azurerm_cdn_frontdoor_rule_set_rule`. But that's in a very early state - especially `azurerm_cdn_frontdoor_rule_set_rule` is still giving me a hard time.

# Open
* RuleSets and RuleSetRules (started)
* Secrets
* Security 
* Some inter-resource dependency need to be further analyzed, for example 
  * you cannot delete the last remaining origin in an origin group that is associated to an endpoint route.
  * custom domains can only be associated when in `DomainValidationState` `Approved`.

That's all I can think of right now. Please take a look if you can use some of my work. Looking forward to learn from you. How to implement the missing components and how to get this done :)

**Comment by WodansSon** [comment]
@heoelri, sound great... I am now activly working on this, starting with a detailed review of the PR and see if we can use some of this or if we need to start from the ground up again... hopefully not. I have been in contact with the service team and they want the resource to be renamed to `azurerm_frontdoor_profile` instead of `azurerm_cdn_frontdoor_profile`. Once I am done with the PR review I will let you know what I think and we can talk about next steps then... fair? 🙂

**Comment by heoelri** [comment]
> @heoelri Heyko Oelrichs FTE, sound great... I am now activly working on this, starting with a detailed review of the PR and see if we can use some of this or if we need to start from the ground up again... hopefully not. I have been in contact with the service team and they want the resource to be renamed to `azurerm_frontdoor_profile` instead of `azurerm_cdn_frontdoor_profile`. Once I am done with the PR review I will let you know what I think and we can talk about next steps then... fair? 🙂

That sounds great! But, please don't waste your time, in case you think it's easier to start from scratch, please do it. It was still a fun excercise for me.

**Comment by WodansSon** [comment]
@heoelri Sounds good, I will mention this PR in the new PR for tracking purposes and note that the new one supersedes this one.

**Pull request closed without merging**
