### PR TITLE
check if nic.NetworkInterfaceReferenceProperties.Primary field exists…

### PR DESCRIPTION
**Pull request by sschne**
… before trying to dereference it #207

### CODE REVIEW

**Review by tombuildsstuff — COMMENTED** [review]
Hey @pather87 

Thanks for opening this PR + issue :)

I've spent a little while trying to reproduce this machine configuration within Azure and I'm having a hard-time doing so (although, I can see this response is valid by the API documentation). Out of interest would it be possible to know how this machine was created? It'd be great if we could get a reproducible configuration for this so we could add an acceptance test to ensure we don't cause this error again - however this otherwise LGTM :)

Thanks!

**Comment by pather87** [comment]
Hey @tombuildsstuff 

I have checked the Debug output of the terraform run on a working version. We have around 30 machines running in Azure and it appears that only 2 specific machines show this behaviour. Our terraform configuration of all these machines is quite the same, so i doubt that it has something to do with that.
What i can see from tfstate history is, that these machines have been setup last year with terraform version 0.7.0, but again also have been other machines, so i also doubt that it is related to a specific terraform version. 

These were one of the first machines that have been setup, so i am uncertain that this can be reproduced. IMO it might be related to a special behaviour of Azure at the time of installation.

Regards

**Comment by tombuildsstuff** [comment]
Hey @pather87 

> Our terraform configuration of all these machines is quite the same, so i doubt that it has something to do with that. [..] These were one of the first machines that have been setup, so i am uncertain that this can be reproduced. IMO it might be related to a special behaviour of Azure at the time of installation.

Got you - so from my understanding Azure appears to have some kind of schema for machines - given those two machines were provisioned a while ago, they're likely to be using an older schema. When I've seen this in the past I believe `redeploying` these machines (either in the Portal or the CLI) - or altering a property of these machines (e.g. attaching an extra data disk) will force an update to the latest schema (and Azure VM Agent).

All that said - this PR LGTM and I'm just running the tests now :)

Thanks!

**Review by tombuildsstuff — APPROVED** [review]
Hey @pather87 

Thanks for this change - this LGTM! :)

**Comment by tombuildsstuff** [comment]
Ignoring a subscription-specific test failure - the tests pass: 
screen shot 2017-08-04 at 10 59 04

**Pull request merged**
