### PR TITLE
New Resource: `azurerm_synapse_sql_script`

### PR DESCRIPTION
**Pull request by ms-henglu**

### CODE REVIEW

**Review by mbfrahry — CHANGES_REQUESTED** [review]
Hey @ms-henglu! This PR is looking nearly there with a couple things to follow up on.

**Comment by ms-henglu** [comment]
@mbfrahry, Hi! Thanks for code review. I've added a commit according to your suggestions, please take another look, thanks!

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for addressing the review!

**Review by mbfrahry — CHANGES_REQUESTED** [review]
It doesn't look like the tests are passing in TeamCity.  We'll need that passing before we can merge

```
Service returned an error. Status=403 Code="ClientIpAddressNotAuthorized"
```

**Comment by ms-henglu** [comment]
Hi @mbfrahry , this is a known issue, it happens randomly. We've located the bug and ask service team to fix it, but no ETA.

Could you please re-run the tests?

FYI:
The bug cause is that after firewall created, the workspace will refresh firewall cache in about one minute, so sometimes firewall is not taken effect in workspace when create resources inside of workspace.

**Comment by katbyte** [comment]
> The bug cause is that after firewall created, the workspace will refresh firewall cache in about one minute, so sometimes firewall is not taken effect in workspace when create resources inside of workspace

should we be adding a state wait/something that polls and waits for the firewall to finish? or is there no way to get the status and wait? (as we should not sleep) @ms-henglu

**Comment by ms-henglu** [comment]
@katbyte , there's no way to get the status. 

> (as we should not sleep)
Can we add a sleep in firewall resource as a temporary way to fix it?

**Comment by katbyte** [comment]
@ms-henglu - no we never add sleeps as they can be unreliable. so in the `azurerm_synapse_firewall_rule` there is no "provisioning" status/state/property?

**Comment by katbyte** [comment]
we have run this many times and it never passes:
image

**Comment by ms-henglu** [comment]
@katbyte , 
>  so in the azurerm_synapse_firewall_rule there is no "provisioning" status/state/property?

Yes, there is. But after provisioning state = succeeded, it still take about 1 minute to propagate firewall changes to workspace. And no way to check the propagation state currently.

**Comment by katbyte** [comment]
doesn't seem to matter how many times we try to run the tests they fail :/

**Comment by tombuildsstuff** [comment]
Hey @ms-henglu

Thanks for this PR - unfortunately this PR is currently blocked on the Azure Service Team who need to make changes to the upstream API (so that the API only returns that the Firewall Rule is provisioned once it's provisioned).

Once the Azure Service Team has updated the Firewall Rules API to wait for the Firewall Rule to be fully provisioned (presumably by making this a Long Running Operation) - we can reopen this PR and take another look, however rather than leaving this PR in limbo I've assigned this to the Blocked milestone and I'm going to close this PR for the moment.

Thanks!

**Pull request closed without merging**
