### PR TITLE
Allow empty_dir volume shared across containers in container group

### PR DESCRIPTION
**Pull request by hterik**
fixes hashicorp/terraform-provider-azurerm#11444

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @hterik - overall this looks good but it seems all the tests have broken recently:
```
------ Stdout: -------
=== RUN   TestAccContainerGroup_SystemAssignedIdentity
=== PAUSE TestAccContainerGroup_SystemAssignedIdentity
=== CONT  TestAccContainerGroup_SystemAssignedIdentity
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating/updating container group "acctestcontainergroup-210916192259326918" (Resource Group "acctestRG-210916192259326918"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InaccessibleImage" Message="The image 'microsoft/aci-helloworld:latest' in container group 'acctestcontainergroup-210916192259326918' is not accessible. Please check the image and registry credential."
        
          with azurerm_container_group.test,
          on terraform_plugin_test.tf line 11, in resource "azurerm_container_group" "test":
          11: resource "azurerm_container_group" "test" {
        
--- FAIL: TestAccContainerGroup_SystemAssignedIdentity (65.81s)
```

could you update tests with a new image so we can test this and get it in? Also could we add a new test with an empty dir so we can ensure this stays fixed going forward? thanks!

**Comment by hterik** [comment]
Hi, I'm not sure what you mean by updating test with new image? Is this something that got broken by this change?

I can look into creating a new test using an empty_dir but will not be able to do it within a week i think, the acctest environment and giving it a az subscription is also new for me which will be some barrier, if any maintainer would like to continue on this you are more than welcome, otherwise i'll give it a shot next week.

btw, once this gets merged, how long until does it normally take for a change like this to become available in a release? Asking to know how invested i should get into workarounds or if i should just wait it out.

**Comment by hterik** [comment]
Please see f2ddce2 including a test for this change.
The test fails without the change and passes with it. 

Note that the test actually doesn't fail if the test-file don't get picked up by the reader-image, since the framework only checks if the resource exists (`check.That(data.ResourceName).ExistsInAzure`), which it does even if the containers keep restarting. I couldn't find a way to test this any deeper with my limited knowledge in this area. At least it confirms that the container group can be created with this configuration.

I still could not run the old TestAccContainerGroup_emptyDirVolume test, neither with nor without this fix. It appears /bin/bash is missing from the seanmckenna/aci-hellofiles image which the test expects to use. Correct me if I'm wrong but I believe this is not affected by this change.

**Comment by catriona-m** [comment]
Thanks for updating this @hterik, LGTM now 👍

**Pull request merged**
