### PR TITLE
New Resource: `azurerm_site_recovery_vmware_replication_policy_classic`

### PR DESCRIPTION
**Pull request by ziyeqf**
test
---
```
terraform-provider-azurerm ❯ TF_ACC=1 go test -v ./internal/services/recoveryservices -run=TestAccSiteRecoveryReplicationPolicyV2A -timeout=600m
=== RUN   TestAccSiteRecoveryReplicationPolicyV2A_basic
=== PAUSE TestAccSiteRecoveryReplicationPolicyV2A_basic
=== RUN   TestAccSiteRecoveryReplicationPolicyV2A_noSnapshots
=== PAUSE TestAccSiteRecoveryReplicationPolicyV2A_noSnapshots
=== RUN   TestAccSiteRecoveryReplicationPolicyV2A_wrongSettings
=== PAUSE TestAccSiteRecoveryReplicationPolicyV2A_wrongSettings
=== CONT  TestAccSiteRecoveryReplicationPolicyV2A_basic
=== CONT  TestAccSiteRecoveryReplicationPolicyV2A_wrongSettings
=== CONT  TestAccSiteRecoveryReplicationPolicyV2A_noSnapshots
--- PASS: TestAccSiteRecoveryReplicationPolicyV2A_wrongSettings (14.40s)
--- PASS: TestAccSiteRecoveryReplicationPolicyV2A_noSnapshots (443.06s)
--- PASS: TestAccSiteRecoveryReplicationPolicyV2A_basic (623.56s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/recoveryservices      623.630s

```

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@ziyeqf the Classic resources are likely to be removed in the future - since #20881 is adding support for the non-Classic version, what's the use-case for supporting the Classic version?

**Comment by ziyeqf** [comment]
> @ziyeqf the Classic resources are likely to be removed in the future - since #20881 is adding support for the non-Classic version, what's the use-case for supporting the Classic version?

AFAIK, there is no deprecate plan (in public) for the classic version and users could also use it for now.  And the applications used to connected VMWare to vault are different, the classic one has been released for more time (maybe more stable?) so there may be users want to use the classic version I think.

**Comment by tombuildsstuff** [comment]
@grayzu is reaching out to the Service Team about this one

**Comment by tombuildsstuff** [comment]
hey @ziyeqf 

As discussed offline, since we're not planing to support the `classic` version of this resource, whilst I'd like to thank you for this PR @ziyeqf I'm going to close this PR for the moment.

Thanks!

**Comment by grayzu** [comment]
@tombuildsstuff actually this PR is in support of new functionality. The `classic` name might be misleading here but this should not fall into the same bucket as other `classic` resources. Reopening and will discuss further offline if necessary.

**Comment by ziyeqf** [comment]
Sorry for the forth and back, discussed offline we decided to close this PR

**Pull request closed without merging**
