### PR TITLE
`dependencies`: Update `recoveryservices` to 2021-12-01/backup

### PR DESCRIPTION
**Pull request by myc2h6o**
- Prepare for https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-enhanced-policy
- `ResourceStorageConfigsClient` has been deprecated and replaced with `ResourceStorageConfigsNonCRRClient`. Have confirmed with service team. Also for these two clients, the generated API request, function parameter and return type are same.

### CODE REVIEW

**Comment by myc2h6o** [comment]
Test result:
image

**Review by katbyte — CHANGES_REQUESTED** [review]
we have 2 failing tests:

image

we may need to add an additional wait on delete for the first failure, but try merging main first as that check should be turned off on main

**Comment by myc2h6o** [comment]
Hi @katbyte `TestAccBackupProtectedVm_separateResourceGroups` is being fixed by #16552 `TestAccRecoveryServicesVault_switchEncryptionKeyVaultKey` is being fixed by #16545 I'll rerun the test for this change after those two are merged

**Review by katbyte — APPROVED** [review]
Thanks @myc2h6o - LGTM 🌿

**Pull request merged**
