### PR TITLE
azurerm_application_gateway - ordered zones

### PR DESCRIPTION
**Pull request by hbuckle**
We've just been through a support case with Microsoft following a failed configuration update and they told us that the ordering of the zones for application gateway matters

### CODE REVIEW

**Comment by hbuckle** [comment]
Just noticed the zones stuff is in a package - should I update go-azure-helpers or just add the TypeList schema to the application_gateway_resource directly?

**Comment by hbuckle** [comment]
@tombuildsstuff - any chance of getting this one in? I believe there's a risk of configuration updates failing on any app gateway with zones enabled at the moment.

**Comment by hbuckle** [comment]
@tombuildsstuff - bump

**Comment by hbuckle** [comment]
@katbyte @tombuildsstuff - any progress here? Thanks

**Comment by hbuckle** [comment]
Just to update, I can definitely see this in action

If I create a new app gateway with the following config

```hcl
resource "azurerm_application_gateway" "app_gateway" {
  name                = "myAppGateway"
  resource_group_name = azurerm_resource_group.app_gateway.name
  location            = azurerm_resource_group.app_gateway.location
  zones               = [1, 2, 3, ]
```

And then inspect the request sent to the API, the JSON body has

```json
"zones": [
  "2",
  "3",
  "1"
]
```

Which is then reflected in the Azure Portal:

image

**Comment by tombuildsstuff** [comment]
@hbuckle apologies for the delayed response on this one, I thought I'd replied previously - we've been running this down with MS internally.

The Service Team have patched the Update API to account for this but it's not yet been rolled out, whilst I don't have a timeframe for that we'll post an update here when there's an update from the Service Team.

**Comment by tombuildsstuff** [comment]
@hbuckle we've heard back from the Service Team that this API bug has been fixed, meaning that the ordering should be ignored for this resource during updates (removing this issue) - would you be able to take a look and see if that's now fixed for you?

**Comment by hbuckle** [comment]
Sorry for the delay, I was away. I've tested with powershell and it appears to be working now

```powershell
$appgw = Get-AzApplicationGateway -Name cbuk-core-hbtest-appgatewayshared-uksouth -ResourceGroupName cbuk-core-hbtest-appgatewayshared-uksouth
$appgw.Zones
3
2
1
$appgw.Zones = @(1,2,3)
Set-AzApplicationGateway -ApplicationGateway $appgw # Previously this errored
```

**Comment by katbyte** [comment]
Sounds like this has been fixed so going to close it out, let us know if its still an issue @hbuckle

**Pull request closed without merging**
