### PR TITLE
Support for DigitalTwinChangeEvents in route sources (fixes #12036)

### LINKED ISSUE #12036: Support for DigitalTwinChangeEvents in route sources in azurerm_iothub_route and azurerm_iothub
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

IoT Hub now support new source of events in routes definition called DigitalTwinChangeEvents. Would be nice that azurerm provider also would support this.

### New or Affected Resource(s)

* azurerm_iothub_route
* azurerm_iothub

### Potential Terraform Configuration

```hcl
resource "azurerm_iothub_route" "DigitalTwinChangeEvents" {
       resource_group_name = azurerm_resource_group.iothub-rg.name
       iothub_name         = azurerm_iothub.iothub.name
       condition           = "true"
       enabled             = true
       endpoint_names      = [
         "events",
       ]
       name                = "DeviceUpdate.DigitalTwinChanges"
       source              = "DigitalTwinChangeEvents"
}
```

### References

Here you can find some reference in MS documentation:
* https://docs.microsoft.com/en-us/azure/digital-twins/concepts-route-events

### PR DESCRIPTION
**Pull request by stawii**

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thank for this @stawii, would you mind updating the docs with this value too?

**Comment by stawii** [comment]
The const is defined in most SDK (ie. https://github.com/Azure/azure-sdk-for-net/blob/0e4684948c75c0e716e98c2a54ba76297c0f41b6/sdk/iothub/Microsoft.Azure.Management.IotHub/src/Generated/Models/RoutingSource.cs#L24) but missing from go-lang.

**Comment by stephybun** [comment]
@stawii, this value is available in a [newer version of the API spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/iothub/resource-manager/Microsoft.Devices/preview/2022-04-30-preview/iothub.json#L3305), the correct way to go about this will be to upgrade the SDK for IoTHub instead of hardcoding the strings into the resource. 

In order to do this we will need to generate the go SDK for the new version using https://github.com/hashicorp/pandora. I can take look into this next week to see if this is feasible.

**Comment by stawii** [comment]
@stephybun You mean update it here https://github.com/Azure/azure-sdk-for-go/blob/069418f89e8a2a790382e221f998882f64fc6ce0/services/iothub/mgmt/2021-07-02/devices/enums.go#L391-L407 ? It seems to be generated and I'm not sure how. There is no newer version I could try, and changing this to Pandora seems like beyond my skills.

**Comment by stephybun** [comment]
@stawi the `azure-sdk-for-go` can't be updated directly since, as you pointed out, it is generated. The swagger spec that I linked in my comment, is the source data from which `azure-sdk-for-go` is generated from. 

Unfortunately I run into errors when I try to generate the go SDK with Pandora using the latest version `2022-04-30-preview` of the swagger, we do have an alternative means of generating another `azure-sdk-for-go` though. Once https://github.com/tombuildsstuff/kermit/pull/18 is merged we should be able to upgrade the SDK.

**Comment by stephybun** [comment]
The SDK swap and upgrade for IoTHub is over in #19070. I hope you don't mind I also took the opportunity to add `DigitalTwinChangeEvents` to all the relevant properties over there so I'm going to close this PR in favour of #19070.

Thanks for your effort and this PR though!

**Pull request closed without merging**
