### PR TITLE
API of iothub/mgmt upgraded to 2021-03-31

### PR DESCRIPTION
**Pull request by ramondeklein**
This PR upgrades the IOT-hub management API to 2021-03-03-preview to allow the creation of `DeviceConnectionStateEvents` routes (#12477 and #12985). No new features have been added that might have be added in this API, but the creation of `DeviceConnectionStateEvents` routes now works fine.

Some remarks about this PR:

- The module `github.com/Azure/azure-sdk-for-go/services/iothub/mgmt/2020-03-01/devices` has been upgraded to `github.com/Azure/azure-sdk-for-go/services/preview/iothub/mgmt/2021-03-03-preview/devices` (therefore a lot of changes in the `vendor` folder).
- The API now uses prefixes for some enumerations, so this has been updated in other parts of the source where these enumerations were referenced.
- The `IotHubResourceClient.CreateEventHubConsumerGroup()` now requires a `devices.EventHubConsumerGroupBodyDescription` structure containing a `Name` property. However, this isn't documented at all ([link](https://docs.microsoft.com/en-us/azure/templates/microsoft.devices/2021-03-03-preview/iothubs/eventhubendpoints/consumergroups?tabs=json#eventhubconsumergroupname)) and it property is optional, so we won't use it.
- `internal/services/iothub/iothub_route_resource.go` contained the hard-coded string `"DeviceConnectionStateEvents"`, which can now be replaced with the proper enumeration `devices.RoutingSourceDeviceConnectionStateEvents`.

### CODE REVIEW

**Comment by stephybun** [comment]
Thanks for this PR @ramondeklein, but it looks like there are some test failures, specifically the ones for the iothub consumer group resource
```
TF_ACC=1 go test -v ./internal/services/iothub -run=TestAccIotHub -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccIotHubConsumerGroup_events
=== PAUSE TestAccIotHubConsumerGroup_events
=== RUN   TestAccIotHubConsumerGroup_requiresImport
=== PAUSE TestAccIotHubConsumerGroup_requiresImport
=== RUN   TestAccIotHubConsumerGroup_operationsMonitoringEvents
=== PAUSE TestAccIotHubConsumerGroup_operationsMonitoringEvents
=== RUN   TestAccIotHubConsumerGroup_withSharedAccessPolicy
=== PAUSE TestAccIotHubConsumerGroup_withSharedAccessPolicy
=== RUN   TestAccIotHubDPSCertificate_basic
=== PAUSE TestAccIotHubDPSCertificate_basic
=== RUN   TestAccIotHubDPSCertificate_requiresImport
=== PAUSE TestAccIotHubDPSCertificate_requiresImport
=== RUN   TestAccIotHubDPSCertificate_update
=== PAUSE TestAccIotHubDPSCertificate_update
=== RUN   TestAccIotHubDPS_basic
=== PAUSE TestAccIotHubDPS_basic
=== RUN   TestAccIotHubDPS_requiresImport
=== PAUSE TestAccIotHubDPS_requiresImport
=== RUN   TestAccIotHubDPS_update
=== PAUSE TestAccIotHubDPS_update
=== RUN   TestAccIotHubDPS_linkedHubs
=== PAUSE TestAccIotHubDPS_linkedHubs
=== RUN   TestAccIotHubDpsSharedAccessPolicy_basic
=== PAUSE TestAccIotHubDpsSharedAccessPolicy_basic
=== RUN   TestAccIotHubDpsSharedAccessPolicy_writeWithoutRead
=== PAUSE TestAccIotHubDpsSharedAccessPolicy_writeWithoutRead
=== RUN   TestAccIotHubDpsSharedAccessPolicy_enrollmentReadWithoutRegistration
=== PAUSE TestAccIotHubDpsSharedAccessPolicy_enrollmentReadWithoutRegistration
=== RUN   TestAccIotHubDpsSharedAccessPolicy_enrollmentWriteWithoutOthers
=== PAUSE TestAccIotHubDpsSharedAccessPolicy_enrollmentWriteWithoutOthers
=== RUN   TestAccIotHubEndpointEventHub_basic
=== PAUSE TestAccIotHubEndpointEventHub_basic
=== RUN   TestAccIotHubEndpointEventHub_requiresImport
=== PAUSE TestAccIotHubEndpointEventHub_requiresImport
=== RUN   TestAccIotHubEndpointServiceBusQueue_basic
=== PAUSE TestAccIotHubEndpointServiceBusQueue_basic
=== RUN   TestAccIotHubEndpointServiceBusQueue_requiresImport
=== PAUSE TestAccIotHubEndpointServiceBusQueue_requiresImport
=== RUN   TestAccIotHubEndpointServiceBusTopic_basic
=== PAUSE TestAccIotHubEndpointServiceBusTopic_basic
=== RUN   TestAccIotHubEndpointServiceBusTopic_requiresImport
=== PAUSE TestAccIotHubEndpointServiceBusTopic_requiresImport
=== RUN   TestAccIotHubEndpointStorageContainer_basic
=== PAUSE TestAccIotHubEndpointStorageContainer_basic
=== RUN   TestAccIotHubEndpointStorageContainer_requiresImport
=== PAUSE TestAccIotHubEndpointStorageContainer_requiresImport
=== RUN   TestAccIotHubEnrichment_basic
=== PAUSE TestAccIotHubEnrichment_basic
=== RUN   TestAccIotHubEnrichment_requiresImport
=== PAUSE TestAccIotHubEnrichment_requiresImport
=== RUN   TestAccIotHubEnrichment_update
=== PAUSE TestAccIotHubEnrichment_update
=== RUN   TestAccIotHubFallbackRoute_basic
=== PAUSE TestAccIotHubFallbackRoute_basic
=== RUN   TestAccIotHubFallbackRoute_update
=== PAUSE TestAccIotHubFallbackRoute_update
=== RUN   TestAccIotHub_basic
=== PAUSE TestAccIotHub_basic
=== RUN   TestAccIotHub_ipFilterRules
=== PAUSE TestAccIotHub_ipFilterRules
=== RUN   TestAccIotHub_requiresImport
=== PAUSE TestAccIotHub_requiresImport
=== RUN   TestAccIotHub_standard
=== PAUSE TestAccIotHub_standard
=== RUN   TestAccIotHub_customRoutes
=== PAUSE TestAccIotHub_customRoutes
=== RUN   TestAccIotHub_enrichments
=== PAUSE TestAccIotHub_enrichments
=== RUN   TestAccIotHub_removeEndpointsAndRoutes
=== PAUSE TestAccIotHub_removeEndpointsAndRoutes
=== RUN   TestAccIotHub_fileUpload
=== PAUSE TestAccIotHub_fileUpload
=== RUN   TestAccIotHub_withDifferentEndpointResourceGroup
=== PAUSE TestAccIotHub_withDifferentEndpointResourceGroup
=== RUN   TestAccIotHub_fallbackRoute
=== PAUSE TestAccIotHub_fallbackRoute
=== RUN   TestAccIotHub_publicAccess
=== PAUSE TestAccIotHub_publicAccess
=== RUN   TestAccIotHub_minTLSVersion
=== PAUSE TestAccIotHub_minTLSVersion
=== RUN   TestAccIotHubRoute_basic
=== PAUSE TestAccIotHubRoute_basic
=== RUN   TestAccIotHubRoute_requiresImport
=== PAUSE TestAccIotHubRoute_requiresImport
=== RUN   TestAccIotHubRoute_update
=== PAUSE TestAccIotHubRoute_update
=== RUN   TestAccIotHubSharedAccessPolicy_basic
=== PAUSE TestAccIotHubSharedAccessPolicy_basic
=== RUN   TestAccIotHubSharedAccessPolicy_writeWithoutRead
=== PAUSE TestAccIotHubSharedAccessPolicy_writeWithoutRead
=== RUN   TestAccIotHubSharedAccessPolicy_requiresImport
=== PAUSE TestAccIotHubSharedAccessPolicy_requiresImport
=== CONT  TestAccIotHubConsumerGroup_events
=== CONT  TestAccIotHubEnrichment_requiresImport
=== CONT  TestAccIotHubDpsSharedAccessPolicy_writeWithoutRead
=== CONT  TestAccIotHubEnrichment_basic
=== CONT  TestAccIotHubEndpointStorageContainer_requiresImport
=== CONT  TestAccIotHubEndpointStorageContainer_basic
=== CONT  TestAccIotHubEndpointServiceBusTopic_requiresImport
=== CONT  TestAccIotHubEndpointServiceBusTopic_basic
=== CONT  TestAccIotHubEndpointServiceBusQueue_requiresImport
=== CONT  TestAccIotHubEndpointServiceBusQueue_basic
=== CONT  TestAccIotHubEndpointEventHub_requiresImport
=== CONT  TestAccIotHubEndpointEventHub_basic
=== CONT  TestAccIotHubDpsSharedAccessPolicy_enrollmentWriteWithoutOthers
=== CONT  TestAccIotHub_withDifferentEndpointResourceGroup
=== CONT  TestAccIotHubDpsSharedAccessPolicy_enrollmentReadWithoutRegistration
=== CONT  TestAccIotHub_requiresImport
--- PASS: TestAccIotHubDpsSharedAccessPolicy_writeWithoutRead (125.00s)
=== CONT  TestAccIotHub_fileUpload
--- PASS: TestAccIotHubDpsSharedAccessPolicy_enrollmentWriteWithoutOthers (196.44s)
=== CONT  TestAccIotHubSharedAccessPolicy_requiresImport
--- PASS: TestAccIotHubDpsSharedAccessPolicy_enrollmentReadWithoutRegistration (196.87s)
=== CONT  TestAccIotHub_removeEndpointsAndRoutes
=== CONT  TestAccIotHubConsumerGroup_events
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Consumer Group "test" (Endpoint "events" / IoTHub "acctestIoTHub-210913141009087652" / Resource Group "acctestRG-210913141009087652"): devices.IotHubResourceClient#CreateEventHubConsumerGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\"code\":400007,\"httpStatusCode\":\"BadRequest\",\"message\":\"Consumer group name in the request body should not be null or empty. If you contact a support representative please include this correlation identifier: fdf8d723-beea-4071-a8ff-99cf41e37438, timestamp: 2021-09-13 12:13:27Z, errorcode: IH400007.\"}" error: json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string
        
          with azurerm_iothub_consumer_group.test,
          on terraform_plugin_test.tf line 26, in resource "azurerm_iothub_consumer_group" "test":
          26: resource "azurerm_iothub_consumer_group" "test" {
        
--- FAIL: TestAccIotHubConsumerGroup_events (292.13s)
=== CONT  TestAccIotHubSharedAccessPolicy_writeWithoutRead
--- PASS: TestAccIotHubSharedAccessPolicy_writeWithoutRead (10.80s)
=== CONT  TestAccIotHub_enrichments
--- PASS: TestAccIotHub_requiresImport (314.03s)
=== CONT  TestAccIotHubSharedAccessPolicy_basic
--- PASS: TestAccIotHubEndpointStorageContainer_basic (358.16s)
=== CONT  TestAccIotHub_customRoutes
--- PASS: TestAccIotHub_fileUpload (293.16s)
=== CONT  TestAccIotHubRoute_update
--- PASS: TestAccIotHubEndpointServiceBusQueue_basic (437.04s)
=== CONT  TestAccIotHub_standard
--- PASS: TestAccIotHubEndpointStorageContainer_requiresImport (466.50s)
=== CONT  TestAccIotHub_publicAccess
--- PASS: TestAccIotHubEndpointEventHub_requiresImport (497.58s)
=== CONT  TestAccIotHubRoute_requiresImport
=== CONT  TestAccIotHub_fallbackRoute
--- PASS: TestAccIotHubEndpointEventHub_basic (497.77s)
--- PASS: TestAccIotHubEnrichment_requiresImport (502.51s)
=== CONT  TestAccIotHubRoute_basic
--- PASS: TestAccIotHubEnrichment_basic (515.06s)
=== CONT  TestAccIotHubConsumerGroup_withSharedAccessPolicy
--- PASS: TestAccIotHubEndpointServiceBusQueue_requiresImport (515.61s)
=== CONT  TestAccIotHubDPSCertificate_update
--- PASS: TestAccIotHub_withDifferentEndpointResourceGroup (530.10s)
=== CONT  TestAccIotHubDpsSharedAccessPolicy_basic
--- PASS: TestAccIotHubEndpointServiceBusTopic_requiresImport (606.55s)
=== CONT  TestAccIotHubDPS_linkedHubs
--- PASS: TestAccIotHubEndpointServiceBusTopic_basic (615.80s)
=== CONT  TestAccIotHubDPS_update
--- PASS: TestAccIotHubSharedAccessPolicy_requiresImport (436.43s)
=== CONT  TestAccIotHubDPS_requiresImport
--- PASS: TestAccIotHubSharedAccessPolicy_basic (399.67s)
=== CONT  TestAccIotHubDPS_basic
--- PASS: TestAccIotHub_removeEndpointsAndRoutes (532.27s)
=== CONT  TestAccIotHub_minTLSVersion
--- PASS: TestAccIotHub_enrichments (427.99s)
=== CONT  TestAccIotHubDPSCertificate_basic
=== CONT  TestAccIotHubConsumerGroup_withSharedAccessPolicy
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Consumer Group "test" (Endpoint "events" / IoTHub "acctestIoTHub-210913141009081140" / Resource Group "acctestRG-210913141009081140"): devices.IotHubResourceClient#CreateEventHubConsumerGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\"code\":400007,\"httpStatusCode\":\"BadRequest\",\"message\":\"Consumer group name in the request body should not be null or empty. If you contact a support representative please include this correlation identifier: 108543fd-dc8e-4f7d-948d-bd3b2194b1b5, timestamp: 2021-09-13 12:21:57Z, errorcode: IH400007.\"}" error: json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string
        
          with azurerm_iothub_consumer_group.test,
          on terraform_plugin_test.tf line 27, in resource "azurerm_iothub_consumer_group" "test":
          27: resource "azurerm_iothub_consumer_group" "test" {
        
--- PASS: TestAccIotHub_standard (313.69s)
=== CONT  TestAccIotHubConsumerGroup_operationsMonitoringEvents
--- PASS: TestAccIotHubDpsSharedAccessPolicy_basic (249.20s)
=== CONT  TestAccIotHubFallbackRoute_update
--- PASS: TestAccIotHub_fallbackRoute (286.26s)
=== CONT  TestAccIotHubDPSCertificate_requiresImport
--- PASS: TestAccIotHub_customRoutes (432.39s)
=== CONT  TestAccIotHub_ipFilterRules
--- PASS: TestAccIotHubDPSCertificate_update (278.86s)
=== CONT  TestAccIotHub_basic
--- PASS: TestAccIotHubDPS_requiresImport (202.78s)
=== CONT  TestAccIotHubFallbackRoute_basic
--- FAIL: TestAccIotHubConsumerGroup_withSharedAccessPolicy (352.07s)
=== CONT  TestAccIotHubEnrichment_update
--- PASS: TestAccIotHubDPS_update (268.99s)
=== CONT  TestAccIotHubConsumerGroup_requiresImport
--- PASS: TestAccIotHubDPS_linkedHubs (294.51s)
--- PASS: TestAccIotHubDPS_basic (188.67s)
--- PASS: TestAccIotHubRoute_requiresImport (411.55s)
=== CONT  TestAccIotHubConsumerGroup_operationsMonitoringEvents
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Consumer Group "test" (Endpoint "operationsMonitoringEvents" / IoTHub "acctestIoTHub-210913141009084763" / Resource Group "acctestRG-210913141009084763"): devices.IotHubResourceClient#CreateEventHubConsumerGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\"code\":400007,\"httpStatusCode\":\"BadRequest\",\"message\":\"Consumer group name in the request body should not be null or empty. If you contact a support representative please include this correlation identifier: 0538e748-57d9-4e5a-98c9-51eb310f98ab, timestamp: 2021-09-13 12:25:20Z, errorcode: IH400007.\"}" error: json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string
        
          with azurerm_iothub_consumer_group.test,
          on terraform_plugin_test.tf line 26, in resource "azurerm_iothub_consumer_group" "test":
          26: resource "azurerm_iothub_consumer_group" "test" {
        
--- PASS: TestAccIotHubDPSCertificate_basic (196.33s)
--- PASS: TestAccIotHubRoute_basic (468.72s)
--- PASS: TestAccIotHubDPSCertificate_requiresImport (213.23s)
--- PASS: TestAccIotHubRoute_update (581.20s)
--- FAIL: TestAccIotHubConsumerGroup_operationsMonitoringEvents (254.33s)
--- PASS: TestAccIotHub_minTLSVersion (294.29s)
--- PASS: TestAccIotHub_publicAccess (559.72s)
=== CONT  TestAccIotHubConsumerGroup_requiresImport
    testcase.go:88: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Consumer Group "test" (Endpoint "events" / IoTHub "acctestIoTHub-210913141009088159" / Resource Group "acctestRG-210913141009088159"): devices.IotHubResourceClient#CreateEventHubConsumerGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "{\"code\":400007,\"httpStatusCode\":\"BadRequest\",\"message\":\"Consumer group name in the request body should not be null or empty. If you contact a support representative please include this correlation identifier: e59b7af6-e325-4661-bf6c-494a775f9df9, timestamp: 2021-09-13 12:27:22Z, errorcode: IH400007.\"}" error: json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string
        
          with azurerm_iothub_consumer_group.test,
          on terraform_plugin_test.tf line 26, in resource "azurerm_iothub_consumer_group" "test":
          26: resource "azurerm_iothub_consumer_group" "test" {
        
--- PASS: TestAccIotHub_basic (307.55s)
--- FAIL: TestAccIotHubConsumerGroup_requiresImport (241.84s)
--- PASS: TestAccIotHub_ipFilterRules (395.29s)
--- PASS: TestAccIotHubFallbackRoute_basic (433.90s)
--- PASS: TestAccIotHubFallbackRoute_update (524.92s)
--- PASS: TestAccIotHubEnrichment_update (515.49s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/iothub        1383.928s
FAIL
make: *** [acctests] Error 1

```

**Comment by ramondeklein** [comment]
@stephybun This will have probably to do with the change in the name property. I'll take a look later this week and will push a fix when all test-cases work fine again. Thanks for pointing out...

**Comment by ramondeklein** [comment]
@katbyte I have updated this pull-request, so it now also sends the name. But there seems to be an issue in the 2021-03-03-preview API that prevents this call from succeeding. I have filed an issue with the Microsoft Azure SDK for Go team (https://github.com/Azure/azure-sdk-for-go/issues/15545) with details what's wrong. This needs to be fixed, before we can upgrade to this new API. I'll will monitor the SDK issue and comment when it has been fixed an this PR can continue.

**Comment by ramondeklein** [comment]
SDK will be fixed in the next release and we will need to upgrade to 2021-03-31 by then ([source](https://github.com/Azure/azure-sdk-for-go/issues/15545#issuecomment-921432471)).

**Comment by ramondeklein** [comment]
@katbyte The API has now been upgraded to the **non-preview** 2021-03-31 version to fix the SDK issue (https://github.com/Azure/azure-sdk-for-go/issues/15545). Everything compiles and all unit tests are passing.

**Review by katbyte — APPROVED** [review]
Thanks @ramondeklein - LGTM 🏗️

**Pull request merged**
