### PR TITLE
`azurerm_app_service_environment_v3` - update for SDK supported GA changes to service

### LINKED ISSUE #12251: Support for internal_load_balancing_mode on azurerm_app_service_environment_v3
### Terraform (and AzureRM Provider) Version

- Terraform 1.0.0
- AzureRM Provider 2.63.0

### Affected Resource(s)

azurerm_app_service_environment_v3

### Terraform Configuration Files

```hcl
data "azurerm_virtual_network" "vnet" {
  name                = "MyVNET"
  resource_group_name = "Group-VNET"
}

resource "azurerm_subnet" "inbound" {
  name                                           = "ase-in"
  resource_group_name                            = data.azurerm_virtual_network.vnet.resource_group_name
  virtual_network_name                           = data.azurerm_virtual_network.vnet.name
  address_prefixes                               = ["10.9.88.192/27"]
  enforce_private_link_endpoint_network_policies = false
}

resource "azurerm_subnet" "outbound" {
  name                 = "ase-out"
  resource_group_name  = data.azurerm_virtual_network.vnet.resource_group_name
  virtual_network_name = data.azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.9.88.224/27"]

  delegation {
    name = "delegation"
    service_delegation {
      name    = "Microsoft.Web/hostingEnvironments"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "ase-tf"
  location = "westeurope"
}

resource "azurerm_app_service_environment_v3" "ase" {
  name                = "myase"
  resource_group_name = azurerm_resource_group.rg.name
  subnet_id           = azurerm_subnet.outbound.id

  tags = {
    terraformed = "true"
  }
}
```

### Expected Behaviour

When creating an "App Service Environment (preview)" via the Azure Portal the ASE inbound IP is bound into a subnet of my vnet via a private endpoint. Same behaviour is expected when creating via Terraform provider.

### Actual Behaviour

The ASE created via Terraform provider created inbound connection to an external public IP address.

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #12450: Support for new attribute "inbound IP address" on azurerm_app_service_environment_v3
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To be able to create a **DNS A record** inside my private DNS zone for the app service environment internal load balancer the **inbound IP address** has to be extracted as new attribute on the resource and data-source of **azurerm_app_service_environment_v3**.

### New or Affected Resource(s)

* azurerm_app_service_environment_v3

### References

* #0000

### LINKED ISSUE #12577: Enable Zonal capability for App Service Enviroment V3
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Today the App Service Enviroment V3 povider does no support the ability to run this in a Zonal config. This service is now in GA.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3
I am told by the product team that the swagger is being updated but is avaiable(but not documented) in the current API spec..
https://docs.microsoft.com/en-us/rest/api/appservice/app-service-environments

"zoneRedundant": true/false

### New or Affected Resource(s)

Existing resource that is impacted.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3

azurerm_app_service_environment

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3
and
https://docs.microsoft.com/en-us/rest/api/appservice/app-service-environments

* #0000

### PR DESCRIPTION
**Pull request by jackofallops**
Closes #12251
Closes #12450
Closes #12577

### CODE REVIEW

**Review by manicminer — APPROVED** [review]
LGTM 👍

**Comment by hbuckle** [comment]
I don't see internalInboundIpAddresses being exposed here?

**Comment by jackofallops** [comment]
Hi @hbuckle - They are collectively exposed in `inbound_network_dependencies`, but on reflection I can see that the discrete values would be useful, so I'll take a look at adding them in whilst I need to also make another change for some functionality that the API does not yet support.

**Comment by hbuckle** [comment]
Ah ok. What a weirdly named property.

**Comment by jackofallops** [comment]
> Ah ok. What a weirdly named property.

Naming things is always a challenge, in this case it's a collection of addresses, ports and a brief description, but I agree "dependencies" is possibly misleading here.  In any case, I've added the internal and external inbound IP lists as separate items and I've kicked off the acceptance tests.  These take a while to run, but I think everything should be fine to have this in the release this week.

**Comment by jackofallops** [comment]
Tests look good.

**Pull request merged**
