### PR TITLE
fix: typo in Azure Orbital service delegation name

### PR DESCRIPTION
**Pull request by astraios**
We have a small typo with `Microsoft.Orbital/orbitalGateway`, a trailing `s` character seems to be missing

### CODE REVIEW

**Review by catriona-m — APPROVED** [review]
Thanks @astraios LGTM! 👩‍🚀

**Comment by catriona-m** [comment]
Just one minor comment - it would be nice if this option could be reflected in the subnet docs too?

**Comment by astraios** [comment]
@catriona-m I added the `Microsoft.Orbital/orbitalGateways` in the subnet documentation. Thanks for reviewing this change 🙏.

**Comment by catriona-m** [comment]
> @catriona-m I added the `Microsoft.Orbital/orbitalGateways` in the subnet documentation. Thanks for reviewing this change 🙏.

Thank you @astraios! 🚀

**Pull request merged**
