### PR TITLE
`azurerm_postgresql_flexible_server` - expose `storage_tier` field

### PR DESCRIPTION
**Pull request by WodansSon**

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
LGTM 
🚜

**Comment by WodansSon** [comment]
There is a wrinkle to this fix which I have discovered, while the code in the PR is sound, the implementation per the service team will break many users as the new `storage_tier` field has many limitations based on other field values in the resource. I am currently communicating with the service team to understand that matrix so we can implement this field correctly within the Terraform provider.

**Comment by WodansSon** [comment]
image

**Review by katbyte — APPROVED** [review]
LGTM round 2 🧯

**Comment by WodansSon** [comment]
image

**Comment by sergiupantiru-tomtom** [comment]
I think this change has introduced a bug in the restore mode of flexible postgres servers. The size and tier can be omitted when restoring a database but now, the default values are provided.

**Pull request merged**
