### PR TITLE
`azurerm_application_insights` - support for `custom_metrics_opted_in_type`

### LINKED ISSUE #6901: Support for enabling alerting on custom metric dimensions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
It is currently possible to enable alerting on custom metric dimensions via the GUI and also via ARM but not yet via Terraform.
I raised this question in the documentation repo and somebody answered that the field to look at is:
```
"CustomMetricsOptedInType": "WithDimensions"
```

### New or Affected Resource(s)

* `azurerm_application_insights`

### Potential Terraform Configuration

```hcl
resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
  custom_metrics_opted_in_type = "WithDimensions"
}
```

### References
* [The discussion](https://github.com/MicrosoftDocs/azure-docs/issues/54745) we had on the azure-docs repo
* The [actual feature](https://docs.microsoft.com/en-us/azure/azure-monitor/app/pre-aggregated-metrics-log-metrics#custom-metrics-dimensions-and-pre-aggregation) we're talking about

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:

### PR DESCRIPTION
**Pull request by gukoff**
`azurerm_application_insights` - support for `custom_metrics_opted_in_type`

Fixes #6901

### CODE REVIEW

**Comment by gukoff** [comment]
I used #4925 for inspiration.

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @gukoff - overall looks good but seems we have some test failures:
```
------- Stdout: -------
=== RUN   TestAccApplicationInsights_basicWeb
=== PAUSE TestAccApplicationInsights_basicWeb
=== CONT  TestAccApplicationInsights_basicWeb
    testcase.go:88: Step 1/2 error: Check failed: Check 3/3 error: azurerm_application_insights.test: Attribute 'custom_metrics_opted_in_type' found when not expected
--- FAIL: TestAccApplicationInsights_basicWeb (124.07s)
FAIL
```

**Comment by gukoff** [comment]
@katbyte thanks for the heads up. This looks looks simple to fix fix once I can run tests myself :)

There's a larger problem with this PR: I added a new parameter to Azure SDK code without realizing it's a vendored library (see the failing github action). 

Looks like we should wait for the Application Insights team to publish this parameter `custom_metrics_opted_in_type` in [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), let it propagate to the [vendored SDK library](https://github.com/Azure/azure-sdk-for-go), and re-vendor the updated libary here. Then this PR will work.

I'll try to get some clarity about `custom_metrics_opted_in_type` from the service team.

**Comment by katbyte** [comment]
ahh yes, we'll need to wait for that to hit the official SDK before we can merge this

**Comment by katbyte** [comment]
@gukoff - any update from the service team? or shall we close this till they update the SDK and reopen it at that point

**Comment by gukoff** [comment]
Yes - the feature stays in preview for now, and the team can't publish the API spec for it yet.

> or shall we close this till they update the SDK and reopen it at that point

Let's do so :)

**Pull request closed without merging**
