### PR TITLE
dependencies: upgrade eventhubs sdk from `2017-04-01`, `2018-01-01-preview` and `2021-01-01-preview` to `2021-11-01`

### PR DESCRIPTION
**Pull request by catriona-m**

### CODE REVIEW

**Review by katbyte — CHANGES_REQUESTED** [review]
looks like we have some fialing tests:
image

**Comment by catriona-m** [comment]
> looks like we have some fialing tests: image

Thanks @katbyte - I've made some changes now that have resolved the failures, apart from some that are also failing in main currently

**Comment by tombuildsstuff** [comment]
@catriona-m can you update this to use the new split-out SDK? https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/eventhub/2021-11-01

**Comment by tombuildsstuff** [comment]
Closing in favour of #17719

**Pull request closed without merging**
