### PR TITLE
`azurerm_route_table`: support `next_hop_in_ip_address` value as nil

### PR DESCRIPTION
**Pull request by wuxu92**
Fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20340

image

### CODE REVIEW

**Comment by karlparry** [comment]
Would be great if we could merge this, as plans are failing because of this issue now

**Review by katbyte — APPROVED** [review]
LGTM 🍬

**Review by katbyte — CHANGES_REQUESTED** [review]
TEst failures:
```
------- Stdout: -------
=== RUN   TestAccRouteTable_basicNilNextHopIPAddress
=== PAUSE TestAccRouteTable_basicNilNextHopIPAddress
=== CONT  TestAccRouteTable_basicNilNextHopIPAddress
    testcase.go:110: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating/updating Route Table: (Name "acctestrt230209222146314944" / Resource Group "acctestRG-230209222146314944"): network.RouteTablesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingNextHopIpAddress" Message="NextHopIpAddress cannot be Null or Empty in route route1 when NextHopType is VirtualAppliance." Details=[]
        
          with azurerm_route_table.test,
          on terraform_plugin_test.tf line 22, in resource "azurerm_route_table" "test":
          22: resource "azurerm_route_table" "test" {
        
--- FAIL: TestAccRouteTable_basicNilNextHopIPAddress (78.27s)
FAIL
```

**Comment by wuxu92** [comment]
acc test configu updated

```
--- PASS: TestAccRouteTable_basicNilNextHopIPAddress (175.40s)
PASS
```

**Review by katbyte — APPROVED** [review]
LGTM 💣

**Pull request merged**
