### PR TITLE
New Resource - azurerm_route_server_bgp_connection, azurerm_route_server

### PR DESCRIPTION
**Pull request by xiaxyi**
Adding new resource [Azure Route Server](https://docs.microsoft.com/en-us/azure/route-server/overview)

acc tests:
```
--- PASS: TestAccRouteServer_requiresImport (1455.63s)
--- PASS: TestAccRouteServer_basic (1527.78s)
--- PASS: TestAccRouteServer_complete (1648.24s)
--- PASS: TestAccRouteServerBgpConnection_basic (1659.84s)
--- PASS: TestAccRouteServerBgpConnection_requiresImport (1730.02s)
--- PASS: TestAccRouteServer_update (1779.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/network	1780.465s

```

### CODE REVIEW

**Review by tombuildsstuff — CHANGES_REQUESTED** [review]
hi @xiaxyi 

The Provider already supports Route Server (as `azurerm_virtual_hub`, which is what this is called in the API / before the marketing rebrand). Whilst this has been rebranded in Azure it's only the marketing name and not the resource name (within the API) which has changed - so I'm not sure we should be renaming this resource?

Thanks!

**Comment by xiaxyi** [comment]
Thanks @tombuildsstuff for the comment. It's two separate resources, they are using the same API. Virtual Hub is created when specifying the virtual_wan while route server is an independent resource.

just for your reference, PowerShell's practice:

virtual hub:https://docs.microsoft.com/en-us/powershell/module/az.network/new-azvirtualhub?view=azps-7.5.0
route server:https://docs.microsoft.com/en-us/azure/route-server/quickstart-configure-route-server-powershell

**Comment by katbyte** [comment]
compile failure:
image

**Comment by xiaxyi** [comment]
@katbyte Thanks for the comment, I updated the sdk and tests are passing now.

image

**Review by katbyte — APPROVED** [review]
LGTM 🦕

**Pull request merged**
