### PR TITLE
Update `azurerm_linux|windows_virtual_machine` - Support `extensions_time_budget`

### PR DESCRIPTION
**Pull request by ArcturusZhang**

### CODE REVIEW

**Review by katbyte — APPROVED** [review]
Thanks @ArcturusZhang - this LGTM 👍

**Comment by katbyte** [comment]
Once we fix the merge conflicts this should be good to merge

**Comment by ArcturusZhang** [comment]
Hi @katbyte I just did a merge, and the conflicts should be resolved, please have a look, thanks

**Comment by jackofallops** [comment]
tests looking good (failures unrelated)
image

**Pull request merged**
