### PR TITLE
Updated to v58 of Azure SDK for Go

### PR DESCRIPTION
**Pull request by dylanmorley**
V58 released - https://github.com/Azure/azure-sdk-for-go/releases/tag/v58.0.0

### CODE REVIEW

**Comment by aristosvo** [comment]
Use `go mod vendor` to install the right dependencies in de `/vendor` directory 👍🏽

**Comment by aristosvo** [comment]
@dylanmorley If you want some help, I've a bit of time on my hands and waiting on the same thing.

Let me know!

**Comment by dylanmorley** [comment]
Breaking changes in compute package needs fixing - will address first

**Comment by aristosvo** [comment]
@dylanmorley Are the constants changed or only the Golang Enum names? It seemed to me the latter was the case, in that case it is not breaking, right?

Do you have a specific breaking resource?

**Comment by dylanmorley** [comment]
@aristosvo yes, should have been clearer - just the constant changes  (I meant breaking as not a straight upgrade -> compile -> done, needed the changes done on your branch) 

Looks like you're pretty much there, so will leave a PR to you :)

**Pull request closed without merging**
