### PR TITLE
`r\backup_protected_vm` Add doc for destroy hanging

### PR DESCRIPTION
**Pull request by myc2h6o**
Adding doc for #4276

### CODE REVIEW

**Comment by myc2h6o** [comment]
Hi @katbyte the soft-delete feature is added to service and tf support is added by #5586. The backup item can be destroyed properly when setting `soft_delete_enabled` to `false` on its `azurerm_recovery_services_vault`. However, it seems to be a service design that, when soft-delete is enabled, the deleted backup vm still remains in the list as a soft-delete state, causing the Get API to not return 404 and the deletion to timeout

**Comment by katbyte** [comment]
@myc2h6o - i feel like that is an API bug that should be resolved?

**Comment by mbfrahry** [comment]
Closing this as it was superseded by #16939

**Comment by myc2h6o** [comment]
The workaround mentioned above is implemented by #16939, the doc update is not needed any more

**Pull request closed without merging**
