### PR TITLE
`azurerm_api_management_api` : fix service is unavailable while updating `azurerm_api_management_api` 

### LINKED ISSUE #22973: service unavailable while azurerm_api_management_api updates api definition
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.65.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.0.11"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.87.0"
    }
    null = {
      source  = "hashicorp/null"
      version = ">= 3.1.0"
    }
  }
}

locals {
  # openapi_value = var.openapi_value != "" ? var.openapi_value : (var.openapi_file != "" ? file(var.openapi_file) : null)
  openapi_content = var.openapi_file == null ? var.openapi_content : file(var.openapi_file)
}

resource "azurerm_api_management_api" "api" {

  api_management_name   = var.apim_name
  description           = var.description
  display_name          = var.api_name
  name                  = var.version_name == null ? var.api_name : "${var.api_name}-${var.version_name}"
  path                  = var.path
  protocols             = ["https"]
  resource_group_name   = var.apim_rg
  revision              = "1"
  service_url           = var.webservice_url
  subscription_required = var.subscription_required
  version_set_id        = var.version_set_id
  version               = var.version_name

  # Convert import to dynamic import block to be able to exclude depending on configured json import.
  # see https://discuss.hashicorp.com/t/pattern-to-handle-optional-dynamic-blocks/2384
  dynamic "import" {
    for_each = local.openapi_content[*]
    content {
      content_format = var.content_format
      content_value  = import.value # TODO file or url depending on content-format
    }
  }

  # oauth link only if present, not for sandbox
  dynamic "oauth2_authorization" {
    for_each = var.authorization_server_name[*]
    content {
      authorization_server_name = var.authorization_server_name
    }
  }
}
```

### Debug Output/Panic Output

```shell
module.api_provider_registration.module.api.azurerm_api_management_api.api: Modifying... [id=/subscriptions/e5e059e9-92ef-4e3c-a352-00554175fc0f/resourceGroups/caz-preprod-rg/providers/Microsoft.ApiManagement/service/caz-preprod-apim/apis/glu-test-minimalist-service]

module.api_provider_registration.module.api.azurerm_api_management_api.api: Still modifying... [id=/subscriptions/e5e059e9-92ef-4e3c-a352-...-apim/apis/glu-test-minimalist-service, 10s elapsed]
module.services.kubernetes_deployment_v1.deployment: Still modifying... [id=glu-test-minimalist-service/glu-test-minimalist-service, 10s elapsed]

module.api_provider_registration.module.api.azurerm_api_management_api.api: Still modifying... [id=/subscriptions/e5e059e9-92ef-4e3c-a352-...-apim/apis/glu-test-minimalist-service, 20s elapsed]
module.services.kubernetes_deployment_v1.deployment: Still modifying... [id=glu-test-minimalist-service/glu-test-minimalist-service, 20s elapsed]
module.api_provider_registration.module.api.azurerm_api_management_api.api: Still modifying... [id=/subscriptions/e5e059e9-92ef-4e3c-a352-...-apim/apis/glu-test-minimalist-service, 30s elapsed]

module.api_provider_registration.module.api.azurerm_api_management_api.api: Modifications complete after 31s [id=/subscriptions/e5e059e9-92ef-4e3c-a352-005[541](https://gitlab.com/diemobiliar/it/glu/test/glu-test-minimalist-service/-/jobs/4876787810#L541)75fc0f/resourceGroups/caz-preprod-rg/providers/Microsoft.ApiManagement/service/caz-preprod-apim/apis/glu-test-minimalist-service]
```

### Expected Behaviour

The terraform apply should complete within seconds. No service interruption should be observed. 

### Actual Behaviour

As can be seen from the log extract (only relevant part, this is a deployment with other things happening), the execution takes 31 seconds. During this time, the service cannot be reached. Note that this happens only if the api definition (openapi description) is modified. Hence it is not related to the availability of backend pods. 

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by sinbai**
When updating resource `azurerm_api_management_api`, if `import` is set and `service_url` is set, the service will be unavailable for a short time.

This is because if the "import" property is set in configuration, TF sends the properties to the Azure API in two operations. First TF executes import and then updates other properties.

The current TF code does not set the `service_url` property when importing, which will cause `service_url` to be updated to the default value by API, and then TF sets `service_url` to correct value by updating other properties. This causes the service is unavailable while other properties are being updated.

So submit this PR to set `service_url` while importing to fix #22973.

Test result:
PASS: TestAccApiManagementApi_importSwaggerWithServiceUrl (471.20s)

### CODE REVIEW

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @sinbai - Thanks for this PR. Is it possible to include a test that shows this fix successfully resolves the issue?

Thanks

**Comment by sinbai** [comment]
> Hi @sinbai - Thanks for this PR. Is it possible to include a test that shows this fix successfully resolves the issue?
> 
> Thanks

Hi @jackofallops thanks for your feedback. Testcase has been added and passed. Could you please take another look?

**Comment by mrickly** [comment]
@sinbai , @jackofallops : What is the planned timeline for this change?

**Review by tombuildsstuff — APPROVED** [review]
LGTM 👍

**Comment by mrickly** [comment]
@sinbai : Sorry to bother you, but what is the process exactly? Is there any reason to not merge this? And how/when can I expect the fix to be released?

**Comment by sinbai** [comment]
> @sinbai : Sorry to bother you, but what is the process exactly? Is there any reason to not merge this? And how/when can I expect the fix to be released?

This PR has been merged. Normally, it would be released this week.

**Pull request merged**
