### PR TITLE
[Bug fix] Fix service bus subscription id case diff issue

### PR DESCRIPTION
**Pull request by xiaxyi**
Fix case diff of service bus subscription id.  

fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/16166

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
@xiaxyi as [per this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/16166#issuecomment-1088489989) we'll need to parse the ServiceBus Subscription ID where it's used within the ServiceBus package and call `.ID()` on it, rather than using a diff suppress func here

**Comment by xiaxyi** [comment]
@tombuildsstuff the sub_id was parsed in Read() function already 

```
d.Set("subscription_id", parse.NewSubscriptionID(id.SubscriptionId, id.ResourceGroup, id.NamespaceName, id.TopicName, id.SubscriptionName).ID())

```

**Comment by katbyte** [comment]
@xiaxyi - could you try using a state migration function?

**Comment by xiaxyi** [comment]
> @xiaxyi - could you try using a state migration function?

I'll try that, let me confirm with the affected user about the actual value in state file

**Comment by xiaxyi** [comment]
@tombuildsstuff  updated the state migration

**Review by katbyte — APPROVED** [review]
Thanks @xiaxyi - LGTM 🚜

**Pull request merged**
