### PR TITLE
`azurerm_container_app_custom_domain` - fix when `azurerm_container_app` has `secret` specified (#25196)

### LINKED ISSUE #25196: azurerm_container_app_custom_domain errors if container app has private registry (secret set)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_custom_domain

### Terraform Configuration Files

```hcl
resource "azurerm_container_app" "ingress" {
  name                         = "ingress"
  container_app_environment_id = azurerm_container_app_environment.container-app-environment.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Single"

  template {
    container {
      name   = "hub"
      image  = "ghcr.io/my-org/ingress:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }

  registry {
    server               = "ghcr.io"
    username             = "my-user"
    password_secret_name = "registry-secret"
  }

  secret {
    name  = "registry-secret"
    value = "my-password"
  }

  ingress {
    target_port      = 80
    external_enabled = true
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}

resource "azurerm_container_app_custom_domain" "root" {
  name                                     = azurerm_dns_a_record.root.fqdn
  container_app_id                         = azurerm_container_app.ingress.id
  container_app_environment_certificate_id = azurerm_container_app_environment_certificate.container-app-certificate.id
  certificate_binding_type                 = "SniEnabled"
}
```

### Debug Output/Panic Output

```shell
Resource Group Name: "***"
Container App Name: "ingress"
Custom Domain Name: "***"): performing CreateOrUpdate: unexpected status 400 with error: ContainerAppSecretInvalid: Invalid Request: Container app secret(s) with name(s) 'registry-secret' are invalid: value or keyVaultUrl and identity should be provided.

  with azurerm_container_app_custom_domain.root,
  on 02-ingress.tf line 37, in resource "azurerm_container_app_custom_domain" "root":
  37: resource "azurerm_container_app_custom_domain" "root" {
```

### Expected Behaviour

The `azurerm_container_app_custom_domain` should correctly add the custom domain.

### Actual Behaviour

The `azurerm_container_app_custom_domain` fails to create. The logs seem to indicate it is because the registry secret is not resolved, presumably because the `azurerm_container_app_custom_domain` is getting the container app in order to update it with the custom domain, but isn't retrieving the secret and then when updating isn't sending the secret back.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by AButler**
## Community Note

* Please vote on this PR by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original PR to help the community and maintainers prioritize for review
* Please do not leave "+1" or "me too" comments, they generate extra noise for PR followers and do not help prioritize for review

## PR Checklist

- [ ] I have followed the guidelines in our [Contributing Documentation](../blob/main/contributing/README.md).
- [x] I have checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change.
- [x] I have checked if my changes close any open issues. If so please include appropriate [closing keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) below.
- [x] I have used a meaningful PR title to help maintainers and other users understand this change and help prevent duplicate work. 
For example: “`resource_name_here` - description of change e.g. adding property `new_property_name_here`”

## Changes to existing Resource / Data Source

- [ ] I have added an explanation of what my changes do and why I'd like you to include them (This may be covered by linking to an issue above, but may benefit from additional explanation).
- [ ] I have written new tests for my resource or datasource changes.
- [ ] I have successfully run tests with my changes locally. If not, please provide details on testing challenges that prevented you running the tests.

## Documentation Changes

- [ ] Documentation is written in a helpful and kind way to assist users that may be unfamiliar with the resource / data source.

## Description

Secrets were not being resolved when updating the container app. 

## Related Issue(s)
Fixes #25196. 

## Change Log
Below please provide what should go into the changelog (if anything) conforming to the [Changelog Format documented here](../blob/main/contributing/topics/maintainer-changelog.md).

* `azurerm_container_app_custom_domain` - fix when container app has secrets [GH-25196]

This is a (please select all that apply):

- [x] Bug Fix
- [ ] New Feature (ie adding a service, resource, or data source)
- [ ] Enhancement
- [ ] Breaking Change

> [!NOTE] 
> If this PR changes meaningfully during the course of review please update the title and description as required.

### CODE REVIEW

**Review by mbfrahry — APPROVED** [review]
LGTM! Thanks for this @AButler

**Review by mbfrahry — CHANGES_REQUESTED** [review]
@AButler, apologies for the premature approval. Looks like this will need some fixes to get around linting

**Comment by AButler** [comment]
@mbfrahry Sorry about that - was missing some imports. Have pushed the changes.

**Comment by AButler** [comment]
@mbfrahry I'm unsure why this one check is failing as it appears to be unrelated to the changes I made

**Review by katbyte — APPROVED** [review]
Thanks @AButler - LGTM 🚒

**Pull request merged**
