### PR TITLE
`azurerm_kubernetes_cluster` - gate `node_os_channel_upgrade` check since it's a preview feature

### PR DESCRIPTION
**Pull request by stephybun**
Due to the nature of the feature we had to add in some fairly stringent validation to prevent users from ending up with config that diverged from state.

But the validation currently also prevents clusters from being created even if the preview feature isn't enabled. This rearranges the validation to not interfere with users not wishing to use the preview feature.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@stephybun according to the last [AKS release notes](https://github.com/Azure/AKS/releases/tag/2023-06-18) it's only the `SecurityPatch` node upgrade channel which is behind the preview flag.

**Comment by stephybun** [comment]
@stevehipwell yes I saw this in the docs and unfortunately that behaviour is not what I observed for the version that we're currently on which is `2023-04-02-preview`. I got errors from the API that the preview feature isn't registered when trying to set `node_os_upgrade_channel` to `None` or `Unmanaged` as well.

From the release notes it looks like that behaviour applies from the versions `2023-06-01` and `2023-06-02-preview` onwards which I don't see in the Azure REST API repo yet. Once they're available in the repo we can look into upgrading the API version and confirming whether that behaviour is valid.

**Comment by stevehipwell** [comment]
@stephybun setting `NodeImage`, which is the default, seems fine without the feature gate set?

**Review by jackofallops — APPROVED** [review]
Thanks @stephybun - LGTM 👍

**Comment by stephybun** [comment]
@stevehipwell setting default values on fields is problematic in AKS since they aren't usually returned by the API until they've been explicitly set by the user. This is compounded by the fact that this is also a preview feature so the default value could change from version to version which would then constitute a breaking change in the provider. 

This feature is actually a great example of that since the [msft docs](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-image#using-node-os-auto-upgrade) currently states 

> By default, a cluster's node OS auto-upgrade channel is set to Unmanaged.

But the changelog says

> Default for [node os upgrade channel](https://learn.microsoft.com/azure/aks/auto-upgrade-node-image) updated to NodeImage in 2023-06-01 and 2023-06-02-preview APIs.

Since we cannot move to either of those versions yet, we believe this fix is the least disruptive way to expose it until we're able to upgrade the API version in the provider.

**Pull request merged**
