### PR TITLE
feat: role management policy resource

### PR DESCRIPTION
**Pull request by josh-barker**
This PR creates a new resource - role management policy, which allows you to manage the settings for PIM roles on Azure Resources.

Replaces #20496

### CODE REVIEW

**Comment by tombuildsstuff** [comment]
hey @josh-barker 

Chatting about this one internally / to give an update on this one - given that PIM spans both `azuread` and `azurerm` we're wanting to take a little time to evaluate this one more in-depth - @manicminer would be the person to look into that - but since this is waiting on design/thought I'm gonna add the `thinking` label to this one for the moment.

Thanks!

**Comment by josh-barker** [comment]
Hey @tombuildsstuff , no worries. I added it in here as target is Azure resources and that's where the APIs are defined, but also understand from a consumer point of view PIM is a bit awkward if the resources are defined in `azurerm` and `azuread`.

Thanks for letting me know where things are up to. :)

**Comment by drdamour** [comment]
i thinks this would fix #23458 & consequently #22766 

regardless of where this goes (azurerm azuread or a 3rd PIM specific provider) the community is anxiously awaiting this functionality as the https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/pim_eligible_role_assignment is effectively dead in the water for the most common use case of just in time PIM

**Comment by haflidif** [comment]
+1 Another bump here any ETA or further thoughts on this feature? @tombuildsstuff , @manicminer

**Comment by manicminer** [comment]
Hi @josh-barker, thanks for working on this and apologies for the delay in getting to this PR. I've looked through this and #25900 which duplicates this, and whilst I would normally defer to the earlier PR, #25900 is a bit more developed and also contains a matching data source. Therefore whilst I greatly appreciate your work on this, I'm going to close this for now in favor of #25900. Thank you again for your efforts on this PR.

**Comment by josh-barker** [comment]
Hey @manicminer , no worries! Thanks for your explanation and it totally makes sense. Glad to see the feature get in!

**Pull request closed without merging**
