### PR TITLE
Support customer managed keys for azurerm_batch_account

### PR DESCRIPTION
**Pull request by AdamMachera**
Adding support for customer managed keys for azure batch account
[#13542 ] (https://github.com/hashicorp/terraform-provider-azurerm/issues/13542)

### CODE REVIEW

**Comment by katbyte** [comment]
we'll need to fix the linting here:
```
Error: S1009: should omit nil check; len() for nil slices is defined as zero (gosimple)
```

**Comment by AdamMachera** [comment]
Can you point me into direction what is wrong now:
Error: golangci-lint exit with code 137
I checked that sometimes it is due to out of memory issue

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @AdamMachera - linting seems to be fixed now. All that is left is updating the docs and adding a test with the new block

**Comment by AdamMachera** [comment]
Hi, I have added tests and updated documentation. I cannot figure out why the triage fails.
Can you please help.

Error: YAMLException: duplicated mapping key (199:1)

 196 | service/monitor:
 19[7](https://github.com/hashicorp/terraform-provider-azurerm/runs/5050060167?check_suite_focus=true#step:3:7) |   - internal/services/monitor/**/*
 19[8](https://github.com/hashicorp/terraform-provider-azurerm/runs/5050060167?check_suite_focus=true#step:3:8) | 
 1[9](https://github.com/hashicorp/terraform-provider-azurerm/runs/5050060167?check_suite_focus=true#step:3:9)9 | service/authorization:
-------^
 200 |   - internal/services/msi/**/*
 201 | 
Error: duplicated mapping key ([19](https://github.com/hashicorp/terraform-provider-azurerm/runs/5050060167?check_suite_focus=true#step:3:19)9:1)

 196 | service/monitor:
 197 |   - internal/services/monitor/**/*
 198 | 
 199 | service/authorization:
-------^
 [20](https://github.com/hashicorp/terraform-provider-azurerm/runs/5050060167?check_suite_focus=true#step:3:20)0 |   - internal/services/msi/**/*
 201 |

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks @AdamMachera & @catriona-m - running tests and it appears we may need to grant some permissions 
```
------- Stdout: -------
=== RUN   TestAccBatchAccountDataSource_cmk
=== PAUSE TestAccBatchAccountDataSource_cmk
=== CONT  TestAccBatchAccountDataSource_cmk
    testcase.go:110: Step 1/1 error: Error running apply: exit status 1
        
        Error: checking for presence of existing Key "enckey220210182759567467" (Key Vault "https://batchkvih621.vault.azure.net/"): keyvault.BaseClient#GetKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=*******;oid=3aa04c8c-5a75-4e5e-9117-1b7cf6f33e21;numgroups=10;iss=https://sts.windows.net/*******/' does not have keys get permission on key vault 'batchkvih621;location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
        
          with azurerm_key_vault_key.test,
          on terraform_plugin_test.tf line 85, in resource "azurerm_key_vault_key" "test":
          85: resource "azurerm_key_vault_key" "test" {
        
--- FAIL: TestAccBatchAccountDataSource_cmk (233.53s)
FAIL
```

**Comment by AdamMachera** [comment]
I have added permissions for keys create operation to data.azurerm_client_config.current.object_id

**Comment by katbyte** [comment]
looks like we still have some failing tests 
image

**Comment by AdamMachera** [comment]
When I added Delete permission for identity that is running the test (data.azurerm_client_config.current.object_id)- 
`make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccountDataSource_cmk' TESTTIMEOUT='30m'`

I'm getting exception
`make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccountDataSource_cmk' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccountDataSource_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccBatchAccountDataSource_cmk
=== PAUSE TestAccBatchAccountDataSource_cmk
=== CONT  TestAccBatchAccountDataSource_cmk
    testcase.go:110: Step 1/1 error: Check failed: Check 1/2 error: Not found: data.azurerm_batch_account.test in [root]
    testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1

        Error: purging of Key "enckey220216084857736022" (Key Vault "https://batchkv6su07.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: batchkv6su07;location=westeurope"

--- FAIL: TestAccBatchAccountDataSource_cmk (223.71s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 224.458s
FAIL
make: *** [GNUmakefile:100: acctests] Error 1
`

Key vault is created with purge protection enabled because it is requirement of the CMK.

Also I have tested it using terraform destroy and it failed:

`azurerm_batch_account.test: Destroying... [id=/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccrg-batch-adam16/providers/Microsoft.Batch/batchAccounts/testaccbatchadam16]
azurerm_key_vault_access_policy.test: Destroying... [id=/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccRG-batch-adam16/providers/Microsoft.KeyVault/vaults/batchkvadam16/objectId/bd31378e-8426-4e90-b466-567caa52f5e1]
azurerm_key_vault_access_policy.test: Still destroying... [id=/subscriptions/1c6bdc0f-f6e9-475c-824c-...d/bd31378e-8426-4e90-b466-567caa52f5e1, 10s elapsed]
azurerm_batch_account.test: Still destroying... [id=/subscriptions/1c6bdc0f-f6e9-475c-824c-...Batch/batchAccounts/testaccbatchadam16, 10s elapsed]
azurerm_key_vault_access_policy.test: Destruction complete after 10s
azurerm_batch_account.test: Destruction complete after 16s
azurerm_user_assigned_identity.test: Destroying... [id=/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccRG-batch-adam16/providers/Microsoft.ManagedIdentity/userAssignedIdentities/acctestadam16]
azurerm_key_vault_key.test: Destroying... [id=https://batchkvadam16.vault.azure.net/keys/enckeyadam16/67f46a9819994be38c3073931afde804]
azurerm_storage_account.test: Destroying... [id=/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccRG-batch-adam16/providers/Microsoft.Storage/storageAccounts/testaccsaadam16]
azurerm_user_assigned_identity.test: Destruction complete after 4s
azurerm_storage_account.test: Destruction complete after 5s
azurerm_key_vault_key.test: Still destroying... [id=https://batchkvadam16.vault.azure.net/k...dam16/67f46a9819994be38c3073931afde804, 10s elapsed]
╷
│ Error: purging of Key "enckeyadam16" (Key Vault "https://batchkvadam16.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: batchkvadam16;location=westeurope"
│`

Should I remove these two new integration tests (because we cannot disable purge protection for keyvault that is serving encryption keys)?

**Comment by katbyte** [comment]
hey @AdamMachera - I think you should be able to disable and purge on destroy via the features block - that functionality was enabled by 5344 so you can see how we handle it in tests there

**Comment by AdamMachera** [comment]
Thanks @katbyte, I have added set purge_soft_delete_on_destroy = false.

However when I'm running these two tests locally I'm getting this weird exception:
```
 make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccount_cmk' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccount_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccBatchAccount_cmk
=== PAUSE TestAccBatchAccount_cmk
=== CONT  TestAccBatchAccount_cmk
    testcase.go:110: Step 1/1 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # azurerm_key_vault.test will be updated in-place
          ~ resource "azurerm_key_vault" "test" {
              ~ access_policy                   = [
                    {
                        application_id          = ""
                        certificate_permissions = []
                        key_permissions         = [
                            "Get",
                            "Create",
                            "Delete",
                            "WrapKey",
                            "UnwrapKey",
                        ]
                        object_id               = "1bb76f86-cb40-4fc8-b153-bfbd44f60531"
                        secret_permissions      = []
                        storage_permissions     = []
                        tenant_id               = "72f988bf-86f1-41af-91ab-2d7cd011db47"
                    },
                  - {
                      - application_id          = ""
                      - certificate_permissions = []
                      - key_permissions         = [
                          - "Get",
                          - "WrapKey",
                          - "UnwrapKey",
                        ]
                      - object_id               = "949f7fba-ca4f-4523-bb50-f356da152e6c"
                      - secret_permissions      = []
                      - storage_permissions     = []
                      - tenant_id               = "72f988bf-86f1-41af-91ab-2d7cd011db47"
                    },
                ]
                id                              = "/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccRG-batch-220216212700681868/providers/Microsoft.KeyVault/vaults/batchkvxcds2"
                name                            = "batchkvxcds2"
                tags                            = {}
                # (12 unchanged attributes hidden)

                # (1 unchanged block hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccBatchAccount_cmk (263.17s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 263.744s
FAIL
make: *** [GNUmakefile:100: acctests] Error 1



$ make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccountDataSource_cmk' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccountDataSource_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccBatchAccountDataSource_cmk
=== PAUSE TestAccBatchAccountDataSource_cmk
=== CONT  TestAccBatchAccountDataSource_cmk
    testcase.go:110: Step 1/1 error: Check failed: Check 1/2 error: Not found: data.azurerm_batch_account.test in [root]
--- FAIL: TestAccBatchAccountDataSource_cmk (238.41s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 239.055s
FAIL
make: *** [GNUmakefile:100: acctests] Error 1

```

When I was running the terraform plan and apply using modified provider, I have checked that state is getting updated:

` {
      "mode": "managed",
      "type": "azurerm_batch_account",
      "name": "test",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "account_endpoint": "testaccbatchadam21.westeurope.batch.azure.com",
            "encryption": [
              {
                "key_vault_key_id": "https://batchkvadam21.vault.azure.net/keys/enckeyadam21/2c3d4e80c5a246af8521a08295b47c97"
              }
            ],
            "id": "/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccrg-batch-adam21/providers/Microsoft.Batch/batchAccounts/testaccbatchadam21",`

Any idea what I'm doing wrong?

**Comment by catriona-m** [comment]
> Thanks @katbyte, I have added set purge_soft_delete_on_destroy = false.
> 
> However when I'm running these two tests locally I'm getting this weird exception:
> 
> ```
>  make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccount_cmk' TESTTIMEOUT='30m'
> ==> Checking that code complies with gofmt requirements...
> ==> Checking that Custom Timeouts are used...
> ==> Checking that acceptance test packages are used...
> TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccount_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
> === RUN   TestAccBatchAccount_cmk
> === PAUSE TestAccBatchAccount_cmk
> === CONT  TestAccBatchAccount_cmk
>     testcase.go:110: Step 1/1 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
>         stdout
> 
> 
>         Terraform used the selected providers to generate the following execution
>         plan. Resource actions are indicated with the following symbols:
>           ~ update in-place
> 
>         Terraform will perform the following actions:
> 
>           # azurerm_key_vault.test will be updated in-place
>           ~ resource "azurerm_key_vault" "test" {
>               ~ access_policy                   = [
>                     {
>                         application_id          = ""
>                         certificate_permissions = []
>                         key_permissions         = [
>                             "Get",
>                             "Create",
>                             "Delete",
>                             "WrapKey",
>                             "UnwrapKey",
>                         ]
>                         object_id               = "1bb76f86-cb40-4fc8-b153-bfbd44f60531"
>                         secret_permissions      = []
>                         storage_permissions     = []
>                         tenant_id               = "72f988bf-86f1-41af-91ab-2d7cd011db47"
>                     },
>                   - {
>                       - application_id          = ""
>                       - certificate_permissions = []
>                       - key_permissions         = [
>                           - "Get",
>                           - "WrapKey",
>                           - "UnwrapKey",
>                         ]
>                       - object_id               = "949f7fba-ca4f-4523-bb50-f356da152e6c"
>                       - secret_permissions      = []
>                       - storage_permissions     = []
>                       - tenant_id               = "72f988bf-86f1-41af-91ab-2d7cd011db47"
>                     },
>                 ]
>                 id                              = "/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccRG-batch-220216212700681868/providers/Microsoft.KeyVault/vaults/batchkvxcds2"
>                 name                            = "batchkvxcds2"
>                 tags                            = {}
>                 # (12 unchanged attributes hidden)
> 
>                 # (1 unchanged block hidden)
>             }
> 
>         Plan: 0 to add, 1 to change, 0 to destroy.
> --- FAIL: TestAccBatchAccount_cmk (263.17s)
> FAIL
> FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 263.744s
> FAIL
> make: *** [GNUmakefile:100: acctests] Error 1
> 
> 
> 
> $ make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccountDataSource_cmk' TESTTIMEOUT='30m'
> ==> Checking that code complies with gofmt requirements...
> ==> Checking that Custom Timeouts are used...
> ==> Checking that acceptance test packages are used...
> TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccountDataSource_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
> === RUN   TestAccBatchAccountDataSource_cmk
> === PAUSE TestAccBatchAccountDataSource_cmk
> === CONT  TestAccBatchAccountDataSource_cmk
>     testcase.go:110: Step 1/1 error: Check failed: Check 1/2 error: Not found: data.azurerm_batch_account.test in [root]
> --- FAIL: TestAccBatchAccountDataSource_cmk (238.41s)
> FAIL
> FAIL    github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 239.055s
> FAIL
> make: *** [GNUmakefile:100: acctests] Error 1
> ```
> 
> When I was running the terraform plan and apply using modified provider, I have checked that state is getting updated:
> 
> ` { "mode": "managed", "type": "azurerm_batch_account", "name": "test", "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]", "instances": [ { "schema_version": 0, "attributes": { "account_endpoint": "testaccbatchadam21.westeurope.batch.azure.com", "encryption": [ { "key_vault_key_id": "https://batchkvadam21.vault.azure.net/keys/enckeyadam21/2c3d4e80c5a246af8521a08295b47c97" } ], "id": "/subscriptions/1c6bdc0f-f6e9-475c-824c-83ad0989ce48/resourceGroups/testaccrg-batch-adam21/providers/Microsoft.Batch/batchAccounts/testaccbatchadam21",`
> 
> Any idea what I'm doing wrong?

Hi @AdamMachera. It looks like you are specifying the access policy twice in your test with different permissions in each which is causing an update-in-place. To fix this you could try removing `azurerm_key_vault_access_policy` or removing the `access_policy` block from the `azurerm_key_vault` resource.

**Comment by catriona-m** [comment]
After running the tests again it looks like there are still a couple of failures:

```
------- Stdout: -------
=== RUN   TestAccBatchAccount_cmk
=== PAUSE TestAccBatchAccount_cmk
=== CONT  TestAccBatchAccount_cmk
testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
Error: purging of Key "enckey220302194204684309" (Key Vault "https://batchkvweuk7.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: batchkvweuk7;location=westeurope"
--- FAIL: TestAccBatchAccount_cmk (289.83s)
FAIL

------- Stdout: -------
=== RUN   TestAccBatchAccountDataSource_cmk
=== PAUSE TestAccBatchAccountDataSource_cmk
=== CONT  TestAccBatchAccountDataSource_cmk
testing_new.go:70: Error running post-test destroy, there may be dangling resources: exit status 1
Error: purging of Key "enckey220302194204762905" (Key Vault "https://batchkv4a4ay.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: batchkv4a4ay;location=westeurope"
--- FAIL: TestAccBatchAccountDataSource_cmk (293.73s)
FAIL

------- Stdout: -------
=== RUN   TestAccBatchAccountDataSource_userSubscription
=== PAUSE TestAccBatchAccountDataSource_userSubscription
=== CONT  TestAccBatchAccountDataSource_userSubscription
testcase.go:110: Step 1/1 error: Error running apply: exit status 1
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."
with azurerm_role_assignment.contribrole,
on terraform_plugin_test.tf line 43, in resource "azurerm_role_assignment" "contribrole":
43: resource "azurerm_role_assignment" "contribrole" {
--- FAIL: TestAccBatchAccountDataSource_userSubscription (323.43s)
FAIL
```

**Comment by AdamMachera** [comment]
When I run it locally:

```
make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccountDataSource_cmk' TESTTIMEOUT='30m'

==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccountDataSource_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccBatchAccountDataSource_cmk
=== PAUSE TestAccBatchAccountDataSource_cmk
=== CONT  TestAccBatchAccountDataSource_cmk
--- PASS: TestAccBatchAccountDataSource_cmk (338.70s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 339.761s

make acctests SERVICE='batch' TESTARGS='-run=TestAccBatchAccount_cmk' TESTTIMEOUT='30m'
==> Checking that code complies with gofmt requirements...
==> Checking that Custom Timeouts are used...
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/batch -run=TestAccBatchAccount_cmk -timeout 30m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccBatchAccount_cmk
=== PAUSE TestAccBatchAccount_cmk
=== CONT  TestAccBatchAccount_cmk
--- PASS: TestAccBatchAccount_cmk (275.47s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/batch 276.257s


```

tests are passing.

This test is failing not due my changes (at least this is what I think)

```
------- Stdout: -------
=== RUN   TestAccBatchAccountDataSource_userSubscription
=== PAUSE TestAccBatchAccountDataSource_userSubscription
=== CONT  TestAccBatchAccountDataSource_userSubscription
testcase.go:110: Step 1/1 error: Error running apply: exit status 1
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."
with azurerm_role_assignment.contribrole,
on terraform_plugin_test.tf line 43, in resource "azurerm_role_assignment" "contribrole":
43: resource "azurerm_role_assignment" "contribrole" {
--- FAIL: TestAccBatchAccountDataSource_userSubscription (323.43s)
FAIL
```

Probably from some previous run, you have this assignment enabled:
```
resource "azurerm_role_assignment" "contribrole" {
  scope                = "/subscriptions/%s"
  role_definition_name = "Contributor"
  principal_id         = "${data.azuread_service_principal.test.object_id}"
}
```
this is why it throw 409

**Pull request merged**
