### PR TITLE
`azurerm_windows_web_app`, `azurerm_windows_web_app_slot`, `azurerm_linux_web_app`, `azurerm_linux_web_app_slot` - fix `win32_status` and `sub_status` not being set issue

### PR DESCRIPTION
**Pull request by xiaxyi**
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/17862
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/21823

For status code trigger, the `win32_status` and `sub_status` is not being correctly set as they were not included in the PUT request and in flatten function neither.

--- PASS: TestAccWindowsWebApp_withAutoHealRulesStatusCodeRange (279.55s)
--- PASS: TestAccWindowsWebApp_withAutoHealRulesStatusCode (288.62s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    289.343s
--- PASS: TestAccLinuxWebApp_withAutoHealRulesStatusCodeRange (274.33s)
--- PASS: TestAccLinuxWebApp_withAutoHealRulesStatusCode (275.71s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    276.493s

remodel the status code trigger block to:
```
status_code {
  status_code = "503"
  interval          = "00:01:30"
  count             = 20
  path = "./terraformteststatusrange.aspx"
  win32_status = "30"
  sub_status = 202
}

status_code_range {        
  status_code_range = "400-500"
  interval          = "00:01:30"
  count             = 20
}
````

### CODE REVIEW

**Comment by pietersap** [comment]
We're all looking forward to the merge here! Thanks already

**Comment by xiaxyi** [comment]
The linter error seems not relate to the PR itself

**Comment by pietersap** [comment]
@jackofallops  any update on this?

**Comment by peruzzof** [comment]
As the #22003 was merged I am assuming that this can be closed, right?

**Comment by jackofallops** [comment]
This PR has been superseded by 22003, as such I'm closing this one out.

**Pull request closed without merging**
