### PR TITLE
internal/services/cognitive: add kind = "OpenAI"

### PR DESCRIPTION
**Pull request by davecheney**
Azure Cognitive Services supports models of kind = "OpenAI". Add this
kind to the validation list to permit the provider to create and manage
cog services resources of this kind.

### CODE REVIEW

**Comment by davecheney** [comment]
@katbyte @tombuildsstuff gentle ping 🙏

**Review by katbyte — APPROVED** [review]
thanks @davecheney - LGTM 🤖

**Comment by davecheney** [comment]
Woo hoo, thanks so much for the super fast turn around @katbyte

**Comment by trastvolt** [comment]
davecheney:davecheney-cognitive-services-add-kind-openai

**Pull request merged**
