### PR TITLE
`azurerm_windows_web_app`, `azurerm_linux_web_app` - fix auto heal issue, support `path` in `slow_reuqest_trigger` block

### PR DESCRIPTION
**Pull request by xiaxyi**
Fix https://github.com/hashicorp/terraform-provider-azurerm/issues/17862
fix https://github.com/hashicorp/terraform-provider-azurerm/issues/19256

acc tests:
```
--- PASS: TestAccWindowsWebApp_withAutoHealRulesSlowRequestWithPath (387.40s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    388.175s
--- PASS: TestAccLinuxWebApp_withAutoHealRulesSlowRequestWithPath (471.79s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/appservice    472.729s


```

### CODE REVIEW

**Review by jackofallops — CHANGES_REQUESTED** [review]
Hi @xiaxyi - Thanks for this PR.
I think two changes have been conflated here and are making this difficult to review correctly.  The change to the schema for `path` looks unrelated to the issue being addressed, and as far as I can tell is not necessary at all? Am I missing something?

**Comment by xiaxyi** [comment]
Thanks @jackofallops for the comments, as you can tell from the code, this pr is trying to address two issues:
1. fix the status code not being set issue as mentioned in https://github.com/hashicorp/terraform-provider-azurerm/issues/17862
2. add support for auto heal rule for user to be able to set the slow request path in the auto heal trigger rule. There are two properties in the api: `SlowRequestsBasedTrigger` and `SlowRequestsBasedTrigger`. We only provided the first option.

**Comment by xiaxyi** [comment]
@jackofallops this is the api response by setting the trigger with & without path:
```
  "slowRequests": {
                    "timeTaken": "00:00:10",
                    "path": null,
                    "count": 10,
                    "timeInterval": "00:10:00"
                },
                "slowRequestsWithPath": [
                    {
                        "timeTaken": "00:00:11",
                        "path": "/xiaxintest1",
                        "count": 11,
                        "timeInterval": "00:11:00"
                    },
                    {
                        "timeTaken": "00:00:12",
                        "path": "/xiaxintest2",
                        "count": 12,
                        "timeInterval": "00:12:00"
                    }
                ],
```

just for your reference, you can try below config to have more information:
```
resource "azurerm_windows_web_app" "dotnet" {
  name                = "xiaxintestWA-autoheal"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  service_plan_id     = azurerm_service_plan.test.id

  site_config {
    application_stack {
      dotnet_version = "core3.1"
      current_stack  = "dotnetcore"
    }
    auto_heal_enabled = true

    auto_heal_setting {
      trigger {
        slow_request {
          count      = "10"
          interval   = "00:10:00"
          time_taken = "00:00:10"
          path       = null
        }
        slow_request_with_path {
          count      = "11"
          interval   = "00:11:00"
          time_taken = "00:00:11"
          path       = "/xiaxintest1"
        }
        slow_request_with_path {
          count      = "12"
          interval   = "00:12:00"
          time_taken = "00:00:12"
          path       = "/xiaxintest2"
        }
        status_code {
          status_code_range = "400"
          interval          = "00:01:00"
          count             = 10
          win32_status = "202"
        }
      }

      action {
        action_type                    = "Recycle"
        minimum_process_execution_time = "00:05:00"
      }
  }
  }
}
```

**Comment by jackofallops** [comment]
Closing as superseded by 19685.

**Pull request closed without merging**
