### PR TITLE
`azurerm_container_app` - Support for both system and user assigned identities at the same time

### PR DESCRIPTION
**Pull request by Joey40**
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/21148
fixes https://github.com/hashicorp/terraform-provider-azurerm/issues/20437

### CODE REVIEW

**Comment by Joey40** [comment]
@jackofallops any update on this?

**Comment by jtatum** [comment]
Also fixes #20437

**Comment by Joey40** [comment]
@tombuildsstuff this has gone almost two months without an update.  Is it possible to assign a new reviewer?  This is a fairly small change.

**Comment by eugene-prout** [comment]
@jackofallops @tombuildsstuff Could this be reviewed please? It's causing me issues too and it looks ready to be merged. If not, could you suggest a workaround?

**Review by jackofallops — APPROVED** [review]
Hi @Joey40, Thanks for this PR and apologies for the delay in getting to it.

This LGTM 👍 

Thanks again!

**Comment by jackofallops** [comment]
tests look good (failure was a transient service issue)

image

**Pull request merged**
