### PR TITLE
Stop recreating a new instance when changing a tag

### PR DESCRIPTION
**Pull request by larsmaes**
Changing tags forces replacement. This is unwanted

### CODE REVIEW

**Comment by larsmaes** [comment]
#13265

**Comment by larsmaes** [comment]
#13256

**Review by katbyte — CHANGES_REQUESTED** [review]
Thanks for the PR @larsmaes, could we update docs and add a test to ensure this works/continues to work? thanks!

**Comment by larsmaes** [comment]
I am not sure i understand the request. I think this is the needed change for this resource to stop it from being replaced when a tag is changes.

**Comment by katbyte** [comment]
the docs will most likely (or should at least!) stat "changing this property will force a new resources" - as for adding it to a test its adding the tag to the update test so we can ensure it still works without re-creating the resource & if the API changes in the future to catch that service change

**Comment by catriona-m** [comment]
Hi @larsmaes, thanks for this PR! I tried updating an acceptance test to cover this case but unfortunately I could not get the test to pass:

```
=== RUN   TestAccAppServiceEnvironmentV3_completeUpdate
=== PAUSE TestAccAppServiceEnvironmentV3_completeUpdate
=== CONT  TestAccAppServiceEnvironmentV3_completeUpdate
    testcase.go:88: Step 3/4 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # azurerm_app_service_environment_v3.test will be updated in-place
          ~ resource "azurerm_app_service_environment_v3" "test" {
                id                                     = "/subscriptions/xxxxx/resourceGroups/acctestRG2-ase-210922102017011484/providers/Microsoft.Web/hostingEnvironments/acctest-ase-210922102017011484"
                name                                   = "acctest-ase-210922102017011484"
              ~ tags                                   = {
                  + "newTag"  = "Tag"
                    # (2 unchanged elements hidden)
                }
                # (15 unchanged attributes hidden)
        
                # (3 unchanged blocks hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccAppServiceEnvironmentV3_completeUpdate (10128.41s)
```

The reason is that in order to update the tags we would need to add the updated tags here too: https://github.com/hashicorp/terraform-provider-azurerm/blob/d841e691719b1a65de1000ea5d8826314fd9bd9b/internal/services/web/app_service_environment_v3_resource.go#L443 

At the minute, it is not possible to do this as it is not currently supported by the Azure API - there is no option to add Tags to AppServiceEnvironmentPatchResource:
 ```
// AppServiceEnvironmentPatchResource ARM resource for a app service environment.
type AppServiceEnvironmentPatchResource struct {
	// AppServiceEnvironment - Core resource properties
	*AppServiceEnvironment `json:"properties,omitempty"`
	// ID - READ-ONLY; Resource Id.
	ID *string `json:"id,omitempty"`
	// Name - READ-ONLY; Resource Name.
	Name *string `json:"name,omitempty"`
	// Kind - Kind of resource.
	Kind *string `json:"kind,omitempty"`
	// Type - READ-ONLY; Resource type.
	Type *string `json:"type,omitempty"`
}
```

 Unfortunately, this change may have to be put on hold until this part of the API is updated first.

**Comment by tombuildsstuff** [comment]
hi @larsmaes 

Unfortunately as @catriona-m [has mentioned above](https://github.com/hashicorp/terraform-provider-azurerm/pull/13251#issuecomment-926568771) it's not possible to update the tags on an App Service Environment through the API at this time - as such Terraform's behaviour is correct (if not ideal) here based on the behaviour of the API at this point in time.

Whilst we'd like to make Tags updatable on an App Service Environment at some point in time - since the API / SDK doesn't support this at this point in time, I'd suggest [opening an issue on the Swagger repository](https://github.com/Azure/azure-rest-api-specs) where someone from the App Service team should be able to take a look into supporting that. Once support for this exists in the API / SDK then we can take a look into supporting this functionality in Terraform (and removing the `ForceNew` here).

However since this behaviour is unfortunately correct at this point in time - [as per this comment]((https://github.com/hashicorp/terraform-provider-azurerm/pull/13251#issuecomment-926568771) - whilst I'd like to thank you for this contribution I'm going to close this PR for the moment.

Thanks!

**Pull request closed without merging**
