### PR TITLE
Added windows Example

### LINKED ISSUE #11962: Update for virtual_machine_extension documentation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.60.0

### Affected Resource(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

Current examples are not working with Windows devices and it would be good to add also Windows example to [azurerm_virtual_machine_extension](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension)

Working example for Windows devices

```hcl
resource "azurerm_virtual_machine_extension" "hello_world" {
  name                 = "ansible_windows_winrm"
  virtual_machine_id   = azurerm_windows_virtual_machine.example.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.9"
  tags = {
    environment = "Production"
  }

  settings = <<SETTINGS
    {
        "fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],
        "commandToExecute": "powershell -ExecutionPolicy Unrestricted -file ConfigureRemotingForAnsible.ps1 -EnableCredSSP -DisableBasicAuth"
    }
SETTINGS
}
```

* #0000

### PR DESCRIPTION
**Pull request by Sheetalsingh23**
Fixed #11962  Added a windows example in virtual_machine_extension.html.markdown.

### CODE REVIEW

**Comment by Sheetalsingh23** [comment]
@jvekka @katbyte  Could you please review this issue?

**Review by Jvekka — APPROVED** [review]
Looks good.
I can't test the code with the newest version currently, so I hope someone else can confirm this also.

**Review by aristosvo — COMMENTED** [review]
Hi @Sheetalsingh23! This looks great for the extension! 

I think it would be better to split for the different OSes, as the Windows extension is now applied on a Linux Virtual Machine. Could you split the example up in a complete example for Linux and a complete example for Windows?

**Comment by tombuildsstuff** [comment]
hey @Sheetalsingh23 

Thanks for this PR.

We try and keep the Example Usages in the docs simplified as much as we can (creating just the basic resource where possible) - as such whilst this looks like a good addition, rather than adding to the Example Usage here, could we instead [add an Example of using a Windows VM with an Extension to the Examples folder](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/virtual-machines/windows) instead?

Thanks!

**Comment by Sheetalsingh23** [comment]
Hi @tombuildsstuff,
Sure, I can do that. So, can you please tell, where exactly in Examples folder do I need to add the Example Usage?

**Pull request merged**
