### PR TITLE
Add IoT Hub example templates

### PR DESCRIPTION
**Pull request by bramvdklinkenberg**
This PR adds three example templates:

1. IoT Hub
2. IoT Hub Device Provisioning Service
3. IoT Hub Certificate

### CODE REVIEW

**Review by stephybun — CHANGES_REQUESTED** [review]
Thanks so much for these @bramvdklinkenberg.

The validation on the examples failed, would you mind following these instructions to fix it:
```
The directories listed below failed to validate using 'terraform validate'
Please fix the validation errors for these, these can be found by running
'terraform init' and then 'terraform validate':
- ./examples/iot/iot-hub
```

**Comment by bramvdklinkenberg** [comment]
Hi @stephybun, I made a small adjustment and validate passed locally.

**Comment by bramvdklinkenberg** [comment]
Also ran `terraform fmt` on all three directories and pushed format changes

**Review by stephybun — APPROVED** [review]
Thanks @bramvdklinkenberg LGTM 🌻

**Pull request merged**
